composer.lock

The composer.lock in develop got messed up in a git merge. I ran composer update to generate a new one.

Did a composer update.

---

composer.json
composer.lock
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_healthcare_html.yml

Run composer install, then uninstall/reinstall VA.gov Migrate module for changes to take effect.

Vagov 557 replace react content

---

docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_healthcare.yml
docroot/modules/custom/va_gov_migrate/src/EventSubscriber/VaPostRowSave.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/CollapsiblePanel.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/CollapsiblePanelItem.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/StarredHr.php
docroot/modules/custom/va_gov_migrate/src/ParagraphMigrator.php
docroot/modules/custom/va_gov_migrate/src/ParagraphType.php
docroot/modules/custom/va_gov_migrate/va_gov_migrate.services.yml

Migrates content into paragraphs (currently only starred hr and wysiwyg)

Vagov 641 paragraph migrate poc

---

config/sync/core.entity_form_display.paragraph.alert.default.yml
config/sync/core.entity_view_display.paragraph.alert.default.yml
config/sync/field.field.paragraph.alert.field_alert_trigger_text.yml
config/sync/field.storage.paragraph.field_alert_trigger_text.yml
docroot/modules/custom/va_gov_backend/js/script.js
docroot/modules/custom/va_gov_backend/va_gov_backend.info.yml
docroot/modules/custom/va_gov_backend/va_gov_backend.libraries.yml
docroot/modules/custom/va_gov_backend/va_gov_backend.module
docroot/modules/custom/va_gov_migrate/src/EventSubscriber/VaPostRowSave.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/Alert.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/CollapsiblePanelItem.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/ExpandableText.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/LinksListItem.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/SubwayMap.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/SubwayStop.php

Adds migrations for
- Alert
- Expandable Text
- SubwayMap
- SubwayStop
Adds VA.gov Backend module to hold form_alter function and js to handle hiding/showing trigger text on Alert.

Vagov000 migrate more paragraphs

---

config/sync/core.entity_form_display.node.page.default.yml
config/sync/core.entity_view_display.node.page.default.yml
config/sync/field.field.node.page.field_plainlanguage_date.yml
config/sync/field.storage.node.field_plainlanguage_date.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_healthcare.yml
docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/source/MetalsmithSource.php

This may have merge conflicts with my previous pr.

Vagov806 migrate plainlanguage

---

.gitignore
README.md
scripts/sync-db-var-config-example
scripts/sync-db.sh

This is an interim solution until we have a systemd timer (cron)
automate backups to a central location where we can sanitize and pull
from.

VAGOV-885 Add script to download STG DB and sync into Lando.

---

Dockerfile-appserver
Dockerfile-database
docker/config/engine/scripts/lando-entrypoint-app.sh
docker/config/engine/scripts/wait-for-it.sh

adding ability to wait for a service to start before running post deploy hooks

VAGOV-1074 Add Post Deploy Hooks

---

composer.json
composer.lock
config/sync/migration_tools.settings.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_hub.yml
docroot/modules/custom/va_gov_migrate/src/EventSubscriber/PostRowSave.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/LinksList.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/LinksListItem.php
docroot/modules/custom/va_gov_migrate/src/ParagraphMigrator.php

Branch relies on 3 commits from Beth's VAGOV-934 - I squashed them into one commit prior to mine.
Testing steps: 
- `lando drush pmu va_gov_migrate; lando drush en va_gov_migrate; lando drush mim va_hub`
- Visually verify that 14 hub pages are migrated
- Visit VA Health Care edit page
- Visually verify 3 spoke paragraphs with all fields populated
- Visually verify 1 related links paragraph with all fields populated

VAGOV-1170

---

docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_work_areas.yml
docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/source/WorkAreas.php

Steps to test:
1. Uninstall/reinstall va_gov_migrate.
2. Run 'Create work areas' (va_work_areas) migration.
3. Verify that 4 administration taxonomy terms were created (http://vagovcms.lndo.site/admin/structure/taxonomy/manage/administration/overview).
4. Verify that 'Veterans Health Administration' term exists and its Contact Info/Connect With Us section corresponds to contents of 'Connect with Us' block in right rail of https://www.va.gov/health-care/
5. Verify that social media links work (From VHA term edit page, click  'Veterans Health Administration' breadcrumb, then click social media links).

VAGOV-959 Migrate administrations (aka work areas)

---

docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_hub.yml

Testing:
1. Run Hub migration.
2. Verify that 9 hub pages were created/updated, corresponding to this list:

VAGOV-1338 Migrate only selected Hub Pages.

---

config/sync/migrate_plus.migration.va_alert_block.yml
config/sync/migrate_plus.migration.va_hub.yml
config/sync/migrate_plus.migration.va_support_service.yml
config/sync/migrate_plus.migration.va_work_areas.yml
config/sync/migrate_plus.migration_group.va_gov.yml

To test:
1. Run drush cim
2. Verify that 5 migrations appear when you run drush ms or go to http://vagovcms.lndo.site/admin/structure/migrate/manage/va_gov/migrations

VAGOV-000: Updated config for migrations.

---

README.md

Mostly a test to demo CD automation to DEV.

VAGOV-1282: Automate CD to DEV

---

README.md

For demo to show Jenkins trigger of DEV deploy.

VAGOV-1282: Automate CD to DEV environment

---

config/sync/core.entity_form_display.node.landing_page.default.yml
config/sync/core.entity_view_display.node.landing_page.default.yml
config/sync/field.field.node.landing_page.field_support_services.yml
config/sync/field.storage.node.field_support_services.yml
config/sync/migrate_plus.migration.va_alert_block.yml
config/sync/migrate_plus.migration.va_healthcare.yml
config/sync/migrate_plus.migration.va_hub.yml
config/sync/migrate_plus.migration.va_promo.yml
config/sync/migrate_plus.migration.va_promo_images.yml
config/sync/migrate_plus.migration.va_promo_media.yml
config/sync/migrate_plus.migration.va_support_service.yml
config/sync/migrate_plus.migration.va_work_areas.yml
config/sync/migrate_plus.migration_group.va_gov.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_healthcare.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_hub.yml
docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/source/AlertBlockSource.php

To test:
1. If on local, run drush config sync
2. Run 'Import hub pages and paragraphs from va.gov' with 'Update' checked.
3. Verify that 'VA Health Care' and 'VA Housing Assistance' hub pages have the "How do I get help if I'm homeless or at risk of becoming homeless?" alert box.

VAGOV-1314 add alerts to hubs

---

config/sync/core.entity_form_display.node.landing_page.default.yml
config/sync/core.entity_view_display.node.landing_page.default.yml
config/sync/field.field.node.landing_page.field_support_services.yml
config/sync/field.storage.node.field_support_services.yml
config/sync/migrate_plus.migration.va_alert_block.yml
config/sync/migrate_plus.migration.va_healthcare.yml
config/sync/migrate_plus.migration.va_hub.yml
config/sync/migrate_plus.migration.va_promo.yml
config/sync/migrate_plus.migration.va_promo_images.yml
config/sync/migrate_plus.migration.va_promo_media.yml
config/sync/migrate_plus.migration.va_support_service.yml
config/sync/migrate_plus.migration.va_work_areas.yml
config/sync/migrate_plus.migration_group.va_gov.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_alert_block.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_healthcare.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_hub.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_promo.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_support_service.yml
docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/source/AlertBlockSource.php

Steps to test:
1. Run config sync, if on local
2. Migrate "Import hub pages and paragraphs from va.gov" and "Import basic pages and paragraphs from va.gov"
3. Go to Content page and verify that Moderation State for all nodes is "published".

Vagov 1310 migrate as published

---

config/sync/core.entity_form_display.paragraph.q_a_section.default.yml
config/sync/core.entity_view_display.paragraph.q_a_section.default.yml
config/sync/field.field.paragraph.q_a_section.field_accordion_display.yml
config/sync/field.field.paragraph.q_a_section.field_section_intro.yml
config/sync/field.storage.paragraph.field_accordion_display.yml
config/sync/field.storage.paragraph.field_section_intro.yml
docroot/modules/custom/va_gov_migrate/src/Paragraph/Base/QABase.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/CollapsiblePanel.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/LinksList.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/QAAccordion.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/QASchema.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/QAUnstructured.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/QaSection.php
docroot/modules/custom/va_gov_migrate/src/ParagraphMigrator.php
docroot/modules/custom/va_gov_migrate/src/ParagraphType.php

After syncing, Q&A Sections should have a checkbox to display as accordion and a textarea for intro text. 
After doing a Basic Page migration, most basic pages should have Q&A sections. Some pages (e.g. "VA Nursing Homes, Assisted Living, And Home Health Care") will have Q&A instead of wysiwyg in the Feature field.

Vagov 1312 migrate qa

---

docroot/modules/custom/va_gov_migrate/src/Paragraph/NumberCallout.php

See https://www.va.gov/health-care/how-to-apply/ near bottom of main section for example of number callout ("Less than 1 week")

VAGOV-1545: Migrate Number callout paragraphs.

---

config/sync/migrate_plus.migration.va_alert_block.yml
config/sync/migrate_plus.migration.va_healthcare.yml
config/sync/migrate_plus.migration.va_hub.yml
config/sync/migrate_plus.migration.va_outreach.yml
config/sync/migrate_plus.migration.va_outreach_doc_media.yml
config/sync/migrate_plus.migration.va_outreach_embedded_images.yml
config/sync/migrate_plus.migration.va_outreach_files.yml
config/sync/migrate_plus.migration.va_outreach_image_media.yml
config/sync/migrate_plus.migration.va_outreach_video.yml
config/sync/migrate_plus.migration.va_promo.yml
config/sync/migrate_plus.migration.va_promo_images.yml
config/sync/migrate_plus.migration.va_promo_media.yml
config/sync/migrate_plus.migration.va_support_service.yml
config/sync/migrate_plus.migration.va_work_areas.yml
config/sync/migrate_plus.migration_group.va_gov.yml
config/sync/migrate_plus.migration_group.va_outreach.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_healthcare.yml
docroot/modules/custom/va_gov_migrate/src/EventSubscriber/PostRowSave.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/LinksList.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/LinksListItem.php
docroot/modules/custom/va_gov_migrate/src/ParagraphMigrator.php

After running va_healthcare migration, Veterans Health Issues Related To Service History and Veterans Programs For Health And Wellness should have list teasers in Main Content field.

VAGOV-1318: Migrate link teasers that are outside of the article tag.

---

config/sync/migrate_plus.migration.va_alert_block.yml
config/sync/migrate_plus.migration.va_healthcare.yml
config/sync/migrate_plus.migration.va_hub.yml
config/sync/migrate_plus.migration.va_outreach.yml
config/sync/migrate_plus.migration.va_outreach_doc_media.yml
config/sync/migrate_plus.migration.va_outreach_embedded_images.yml
config/sync/migrate_plus.migration.va_outreach_files.yml
config/sync/migrate_plus.migration.va_outreach_image_media.yml
config/sync/migrate_plus.migration.va_outreach_video.yml
config/sync/migrate_plus.migration.va_promo.yml
config/sync/migrate_plus.migration.va_promo_images.yml
config/sync/migrate_plus.migration.va_promo_media.yml
config/sync/migrate_plus.migration.va_support_service.yml
config/sync/migrate_plus.migration.va_work_areas.yml
config/sync/migrate_plus.migration_group.va_gov.yml
config/sync/migrate_plus.migration_group.va_outreach.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_healthcare.yml
docroot/modules/custom/va_gov_migrate/src/Paragraph/ReactWidget.php

There should be a react widget with "Call To Action Widget" checked and only Widget Type of 'rx' on 'VA Prescription Refill and Tracking'.
There should be a react widget with "Call To Action Widget" unchecked and all other fields populated on "How to Apply for VA Health Care".

VAGOV-1513: Migrate React Widget paragraphs.

---

config/sync/core.entity_view_display.node.health_care_region_page.default.yml
config/sync/core.entity_view_display.node.health_care_region_page.teaser.yml
config/sync/core.entity_view_display.node.news_story.default.yml
config/sync/core.entity_view_display.node.news_story.teaser.yml
config/sync/core.entity_view_display.node.press_release.teaser.yml
config/sync/core.entity_view_display.node.regional_health_care_service_des.teaser.yml

I thought this was needed to fix my last PR fail, but apparently not.

VAGOV-000: Entity view display config.

---

.composer-cache/README.md
Dockerfile-appserver

There is a parallel PR in devops repo for this here https://github.com/department-of-veterans-affairs/va.gov-cms-devops/pull/29

VAGOV-839 Support for composer caching

---

config/sync/core.extension.yml
config/sync/lightning_core.versions.yml
docroot/modules/custom/va_gov_backend/js/script.js

@andyhawks this turns on the module controlling the email help popup, and fixes the subject line.

Vagov 000 adhoc email fixes

---

composer.json
composer.lock

VAGOV-1641 Apply GraphQL Patch "Fix broken entity reference query filter".

---

docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.module

This should be done with settings.php and ENV variables etc. but we need
to get this working right away (yesterday) and this works for now.
https://vetsgov-pr-9681.herokuapp.com/preview?nodeId=123 works back to test1, this PR gets us from origin to preview.

VAGOV-1739 Add test1 preview env, temporary.

---

docker/config/engine/scripts/lando-entrypoint-app.sh

VAGOV-1757 Set Dockerfile-appserver to copy settings.lando.php to new path.

---

.lando.yml

Recent changes to addressing conflicts with running the preview server on the same machine. These changes resolve the conflict and allow local devs to run the preview server locally without conflict.

VAGOV-000 Update node ports to resolve conflict with local preview

---

composer.lock

Ran 'composer update' to update composer.lock

VAGOV-000: Update composer.lock

---

config/sync/core.entity_form_display.node.health_care_region_detail_page.default.yml
config/sync/core.entity_view_display.node.health_care_region_detail_page.default.yml
config/sync/field.field.node.health_care_region_detail_page.field_intro_text.yml

Adds field_intro_text to health_care_region_detail_page. Paired with this vets-website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/9741

VAGOV-1658: Add intro text to health care detail page content type

---

docroot/sites/default/settings/settings.dev.php
docroot/sites/default/settings/settings.prod.php
docroot/sites/default/settings/settings.stg.php
docroot/sites/default/settings/settings.test.php

Currently failing on new VAEC ELB PR CNAMEs, this fixes it.

VAGOV-320 Fix ELB hostname regex.

---

docroot/sites/default/settings/settings.fast_404.php
docroot/sites/default/settings/settings.local.php

Follow up to https://github.com/department-of-veterans-affairs/va.gov-cms/pull/227

VAGOV-320 Fix fast404 include path.

---

config/sync/field.field.node.health_care_local_facility.field_nickname_for_this_facility.yml
config/sync/metatag.metatag_defaults.node__event.yml
config/sync/metatag.metatag_defaults.node__health_care_local_facility.yml
config/sync/metatag.metatag_defaults.node__health_care_region_detail_page.yml
config/sync/metatag.metatag_defaults.node__news_story.yml
config/sync/metatag.metatag_defaults.node__person_profile.yml
config/sync/system.site.yml

Config updates including:
1. Changed site name to Veterans Affairs
2. Updated meta tag titles for facility pages to include the name of the facility
3. Updated local facility meta tag titles to use facility nickname instead of title
4. Made facility nickname field required.
To test:
View pages in drupal. Inspect or view page source to check meta tags and title tag.

Vagov 1902 metatag updates

---

.lando.yml
README.md
scripts/sync-db.sh

Also made the naming a bit better, didn't have enough time to spend
making the command accept an argument e.g. lando sync --db --files
To test:
```
hub pr checkout 232
lando sync-db
lando sync-files
```

VAGOV-320 Update lando sync commands for VAEC.

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/lightning_core.versions.yml
config/sync/node_revisions_autoclean.settings.yml

Set config to limit revisions to 50 for all content types except 'page' which is 100.

VAGOV-000: Add node_revisions_cleanup module.

---

config/sync/core.entity_form_display.node.landing_page.default.yml
config/sync/core.entity_form_display.node.page.default.yml
config/sync/field.storage.node.field_alert.yml
docroot/modules/custom/va_gov_migrate/src/Paragraph/ExpandableText.php

There are still issues with migrating the new alert and multiple alerts. I'll circle back to them later.

Vagov 1948 multiple alerts

---

config/sync/migrate_plus.migration.va_alert_block.yml
config/sync/migrate_plus.migration.va_benefits_menu.yml
config/sync/migrate_plus.migration.va_healthcare.yml
config/sync/migrate_plus.migration.va_hub.yml
config/sync/migrate_plus.migration.va_main_menu.yml
config/sync/migrate_plus.migration.va_outreach.yml
config/sync/migrate_plus.migration.va_outreach_doc_media.yml
config/sync/migrate_plus.migration.va_outreach_embedded_images.yml
config/sync/migrate_plus.migration.va_outreach_files.yml
config/sync/migrate_plus.migration.va_outreach_image_media.yml
config/sync/migrate_plus.migration.va_outreach_video.yml
config/sync/migrate_plus.migration.va_promo.yml
config/sync/migrate_plus.migration.va_promo_images.yml
config/sync/migrate_plus.migration.va_promo_media.yml
config/sync/migrate_plus.migration.va_support_service.yml
config/sync/migrate_plus.migration.va_work_areas.yml
config/sync/migrate_plus.migration_group.va_gov.yml
config/sync/migrate_plus.migration_group.va_outreach.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_healthcare.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_hub.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_outreach.yml

To test. Run migrations for healthcare pages, hub and outreach. They should all have administration fields filled in.

VAGOV-1948: Added administration field to hub, detail, and assets.

---

docroot/modules/custom/va_gov_migrate/src/ParagraphMigrator.php
docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/source/AlertBlockSource.php

This doesn't actually fix anything, but it reports to dblog when removing bad spans results in a loss of text.
Other than that, there should be no change to the migration.
There's no particular rush to deploy this. We'll want it for making edits post-migration.

VAGOV-2041: Create error message when unwrapping spans loses text.

---

config/sync/core.extension.yml
config/sync/lightning_core.versions.yml
docroot/modules/custom/va_gov_login/va_gov_login.info.yml
docroot/modules/custom/va_gov_login/va_gov_login.module

Updated the help test on the login form and removed the request new password tab.

VAGOV-2160: Updated the user login form and menu.

---

composer.lock

This also changes the composer URLs to the new gitlab home.

VAGOV-2353: Fix fatal error with React Widget paragraph.

---

tests/phpunit/CreateTaxonomyTermTest.php

PhpUnit test to confirm ability to create taxonomy term and compare performance against benchmark time.
https://va-gov.atlassian.net/browse/VAGOV-2209

VAGOV-2209: Create PHPUnit test for taxonomy.

---

composer.json
composer.lock
config/sync/core.entity_form_display.node.health_care_region_detail_page.default.yml
config/sync/core.extension.yml
config/sync/field.field.block_content.alert.field_node_reference.yml
config/sync/field.field.node.event.field_facility_location.yml
config/sync/field.field.node.event.field_office.yml
config/sync/field.field.node.health_care_local_facility.field_region_page.yml
config/sync/field.field.node.health_care_region_detail_page.field_office.yml
config/sync/field.field.node.health_care_region_page.field_clinical_health_services.yml
config/sync/field.field.node.health_care_region_page.field_leadership.yml
config/sync/field.field.node.landing_page.field_support_services.yml
config/sync/field.field.node.news_story.field_author.yml
config/sync/field.field.node.news_story.field_office.yml
config/sync/field.field.node.person_profile.field_office.yml
config/sync/field.field.node.press_release.field_office.yml
config/sync/field.field.node.press_release.field_press_release_contact.yml
config/sync/field.field.node.regional_health_care_service_des.field_region_page.yml
config/sync/field.field.node.support_service.field_office.yml
config/sync/lightning_core.versions.yml

See QA steps in https://va-gov.atlassian.net/browse/VAGOV-2458

VAGOV-2458: Entity reference unpublished module and config.

---

tests/phpunit/CreateMediaTest.php

PHPUnit test  to confirm the ability to create file media and to verify that the operation is performant.
https://va-gov.atlassian.net/browse/VAGOV-2208

VAGOV-2209: Create PHPUnit test for media

---

docroot/modules/custom/va_gov_backend/js/script.js

@andyhawks per Jeff Brauer, this is a hotfix situation.

VAGOV-000: Change help email address.

---

composer.json
composer.lock
config/sync/better_field_descriptions.settings.yml
config/sync/core.extension.yml

Installs and enables better field descriptions to module to allow site builders to put help text above or below a field.

VAGOV-1884: More flexible field help text

---

.gitignore
.lando.yml
Dockerfile-database
docker/config/engine/scripts/lando-entrypoint-app.sh
tests/phpunit/MigrationCountTest.php

VAGOV-3079 fix backup public private s3 bucket master

---

config/sync/paragraphs.paragraphs_type.alert.yml
config/sync/paragraphs_browser.paragraphs_browser_type.content.yml

QA https://va-gov.atlassian.net/browse/VAGOV-2865

VAGOV-2865: Provide help text in paragraphs browser.

---

composer.json
composer.lock
config/sync/core.entity_form_display.node.event.default.yml
config/sync/core.entity_form_display.node.health_care_region_detail_page.default.yml
config/sync/core.entity_form_display.node.health_care_region_page.default.yml
config/sync/core.entity_form_display.node.landing_page.default.yml
config/sync/core.entity_form_display.node.news_story.default.yml
config/sync/core.entity_form_display.node.page.default.yml
config/sync/core.entity_form_display.node.person_profile.default.yml
config/sync/core.entity_form_display.node.press_release.default.yml
config/sync/core.entity_form_display.paragraph.alert.default.yml
config/sync/core.entity_form_display.paragraph.collapsible_panel_item.default.yml
config/sync/core.entity_form_display.paragraph.expandable_text.default.yml
config/sync/core.entity_form_display.paragraph.health_care_local_facility_servi.default.yml
config/sync/core.entity_form_display.paragraph.link_teaser.default.yml
config/sync/core.entity_form_display.paragraph.number_callout.default.yml
config/sync/core.entity_form_display.paragraph.q_a.default.yml
config/sync/core.entity_form_display.paragraph.spanish_translation_summary.default.yml
config/sync/core.entity_form_display.paragraph.wysiwyg.default.yml
config/sync/core.extension.yml
config/sync/lightning_core.versions.yml
config/sync/views.view.content.yml

Installs and enables textfield_counter module for fields that should have character limits.
Ticket: https://va-gov.atlassian.net/browse/VAGOV-1897

VAGOV-1897: Textfield Counter Module

---

config/sync/editor.editor.rich_text.yml
config/sync/filter.format.rich_text.yml

See QA steps at 
https://va-gov.atlassian.net/browse/VAGOV-3249
https://va-gov.atlassian.net/browse/VAGOV-3197

VAGOV-3249: Fix primary button in rich text format and VAGOV-3197: Remove img and drupal-entity

---

scripts/sync-db.sh
scripts/sync-files.sh

Forgot that backticks in shell code are same as $(command).

VAGOV-3461 Fix sync-db/files.sh invoking socks proxy.

---

config/sync/auto_entitylabel.settings.node.health_care_local_health_service.yml
config/sync/cer.corresponding_reference.local_health_service_to_facility.yml
config/sync/cer.corresponding_reference.local_health_service_to_regions_health_service.yml
config/sync/core.base_field_override.node.health_care_local_facility.title.yml
config/sync/core.entity_form_display.node.health_care_local_health_service.default.yml
config/sync/core.entity_form_display.node.health_care_region_page.default.yml
config/sync/core.entity_form_display.node.regional_health_care_service_des.default.yml
config/sync/core.entity_view_display.node.health_care_local_health_service.default.yml
config/sync/core.entity_view_display.node.regional_health_care_service_des.default.yml
config/sync/field.field.node.health_care_local_facility.field_local_health_care_service_.yml
config/sync/field.field.node.health_care_local_health_service.field_clinical_health_services.yml
config/sync/field.field.node.health_care_local_health_service.field_facility_location.yml
config/sync/field.field.node.health_care_local_health_service.field_regional_health_service.yml
config/sync/field.field.node.health_care_region_page.field_clinical_health_services.yml
config/sync/field.field.node.regional_health_care_service_des.field_local_health_care_service_.yml
config/sync/field.storage.node.field_regional_health_service.yml
config/sync/node.type.health_care_local_facility.yml
config/sync/node.type.health_care_local_health_service.yml
config/sync/node.type.health_care_region_page.yml
config/sync/node.type.regional_health_care_service_des.yml
config/sync/views.view.health_service_offerings.yml

QA: https://va-gov.atlassian.net/browse/VAGOV-3468

VAGOV-3448: Health service relationships

---

config/sync/field.field.paragraph.q_a_section.field_questions.yml

QA instructions are here: https://va-gov.atlassian.net/browse/VAGOV-3505

VAGOV-3474: Allow react widget as a question type.

---

config/sync/core.entity_form_display.node.health_care_region_page.default.yml
config/sync/core.entity_view_display.node.health_care_region_page.default.yml
config/sync/field.field.node.health_care_region_page.field_other_va_locations.yml
config/sync/field.storage.node.field_other_va_locations.yml

QA instructions: https://va-gov.atlassian.net/browse/VAGOV-3506

VAGOV-3457: Other VA locations field on Our Locations page.

---

config/sync/core.entity_form_display.node.landing_page.default.yml
config/sync/field.storage.node.field_title_icon.yml

QA steps are in  https://va-gov.atlassian.net/browse/VAGOV-3517

VAGOV-3517: Add more icons as options for hub landing pages, and improve form AX

---

config/sync/field.field.node.health_care_local_facility.field_media.yml

This mr changes the help text on Health Care facility image field. Incorrect crop style of 7:2 was indicated.
There is no qa associated with this mr.

VAGOV-2270: Updating image field to indicate 3:2 crop style.

---

README.md

I've updated README to include the SOCKS proxy command, and improve formatting.

VAGOV-3559: Updating readability of README.md, including SOCKS proxy command.

---

composer.json

`composer va:proxy:start` or `composer v:p:s`
Also:
`composer va:config:export` and `composer va:config:import`
This way, developers don't have to remember how to run the SOCKS or even know where "documentation is located.

VAGOV-000: Add fun commands to allow easily connecting to the proxy

---

docroot/modules/custom/va_gov_migrate/README.md
docroot/modules/custom/va_gov_migrate/src/Obtainer/ObtainAndTestBody.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/CollapsiblePanelItem.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/Table.php
docroot/modules/custom/va_gov_migrate/src/ParagraphType.php

Mostly various fixes for table paragraph migration.

Vagov 000 migration updates

---

tests/phpunit/MigrationCountTest.php

Update phpunit counts in migration count test.

VAGOV-000 Update counts in migration count test.

---

config/sync/migrate_plus.migration.va_alert_block.yml
config/sync/migrate_plus.migration.va_benefits_menu.yml
config/sync/migrate_plus.migration.va_benefits_pension.yml
config/sync/migrate_plus.migration.va_benefits_pension_menu.yml
config/sync/migrate_plus.migration.va_benefits_records.yml
config/sync/migrate_plus.migration.va_benefits_records_menu.yml
config/sync/migrate_plus.migration.va_hub.yml
config/sync/migrate_plus.migration.va_main_menu.yml
config/sync/migrate_plus.migration.va_new_hubs.yml
config/sync/migrate_plus.migration.va_new_landing_pages.yml
config/sync/migrate_plus.migration.va_new_pages.yml
config/sync/migrate_plus.migration.va_outreach.yml
config/sync/migrate_plus.migration.va_outreach_doc_media.yml
config/sync/migrate_plus.migration.va_outreach_embedded_images.yml
config/sync/migrate_plus.migration.va_outreach_files.yml
config/sync/migrate_plus.migration.va_outreach_image_media.yml
config/sync/migrate_plus.migration.va_outreach_video.yml
config/sync/migrate_plus.migration.va_promo.yml
config/sync/migrate_plus.migration.va_promo_images.yml
config/sync/migrate_plus.migration.va_promo_media.yml
config/sync/migrate_plus.migration.va_support_service.yml
config/sync/migrate_plus.migration_group.va_gov.yml
config/sync/migrate_plus.migration_group.va_new_benefits.yml
config/sync/migrate_plus.migration_group.va_outreach.yml
config/sync/migrate_plus.migration_group.va_tests.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_new_pages.yml
docroot/modules/custom/va_gov_migrate/src/Paragraph/QaSection.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/Table.php
docroot/modules/custom/va_gov_migrate/src/ParagraphMigrator.php

Not much to test here, since this mostly just fixes tests.

VAGOV-3483 migration similarity test

---

docroot/modules/custom/va_gov_migrate/src/Paragraph/QAUnstructured.php

If you want to test,
1. Go to /admin/structure/migrate/manage/va_tests/migrations/va_new_hubs/execute
2. Run the migration (it will take a long time).
3. Go to /disability/after-you-file-claim and edit it.
4. Open the last question on the page, "What should I do if I received an other than honorable, bad conduct, or dishonorable discharge?"
5. You should see a "List of link teasers" paragraph at the bottom of the "Main Content" section.
There's no rush on this one.

VAGOV-3957: End answer when links list is hit during migration.

---

docker/config/engine/scripts/lando-entrypoint-app.sh
docker/templates/ssmtp.revaliases.tpl

https://github.com/department-of-veterans-affairs/va.gov-cms-devops/pull/75

VAGOV-3157-SMTP-INTEGRATION

---

config/sync/migrate_plus.migration.va_alert_block.yml
config/sync/migrate_plus.migration.va_benefits_menu.yml
config/sync/migrate_plus.migration.va_benefits_pension.yml
config/sync/migrate_plus.migration.va_benefits_pension_menu.yml
config/sync/migrate_plus.migration.va_hub.yml
config/sync/migrate_plus.migration.va_main_menu.yml
config/sync/migrate_plus.migration.va_new_hubs.yml
config/sync/migrate_plus.migration.va_new_landing_pages.yml
config/sync/migrate_plus.migration.va_new_pages.yml
config/sync/migrate_plus.migration.va_promo.yml
config/sync/migrate_plus.migration.va_promo_images.yml
config/sync/migrate_plus.migration.va_promo_media.yml
config/sync/migrate_plus.migration.va_root_pages.yml
config/sync/migrate_plus.migration.va_support_service.yml
config/sync/migrate_plus.migration_group.va_gov.yml
config/sync/migrate_plus.migration_group.va_new_benefits.yml
config/sync/migrate_plus.migration_group.va_tests.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_root_pages.yml
docroot/modules/custom/va_gov_migrate/src/Paragraph/QAUnstructured.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/QaSection.php

To test:
1. Go to /admin/structure/migrate/manage/va_new_benefits/migrations/va_root_pages/execute and execute migration
2. Go to /admin/content/benefits?title=&moderation_state=All&type_1=All&order=changed&sort=asc and confirm that there are 9 pages with Owner: 'Root Pages'.

VAGOV-2282 migrate root pages

---

config/sync/core.entity_view_display.media.document.default.yml
config/sync/core.entity_view_display.media.image.default.yml
config/sync/core.entity_view_display.media.video.default.yml
config/sync/core.entity_view_display.node.documentation_page.default.yml
config/sync/core.entity_view_display.node.event.default.yml
config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
config/sync/core.entity_view_display.node.health_care_region_detail_page.default.yml
config/sync/core.entity_view_display.node.health_care_region_page.default.yml
config/sync/core.entity_view_display.node.landing_page.default.yml
config/sync/core.entity_view_display.node.news_story.default.yml
config/sync/core.entity_view_display.node.page.default.yml
config/sync/core.entity_view_display.node.person_profile.default.yml
config/sync/core.entity_view_display.node.press_release.default.yml
config/sync/core.entity_view_display.node.support_service.default.yml
config/sync/core.entity_view_display.paragraph.collapsible_panel_item.default.yml
config/sync/core.entity_view_display.paragraph.q_a.default.yml
config/sync/core.entity_view_display.paragraph.q_a_section.default.yml
config/sync/core.entity_view_display.paragraph.react_widget.default.yml
config/sync/core.entity_view_display.taxonomy_term.administration.default.yml
config/sync/diff.settings.yml

QA notes: https://va-gov.atlassian.net/browse/VAGOV-4214

VAGOV-4214: Content revision UI and entity display improvements.

---

config/sync/field.field.node.landing_page.field_intro_text.yml
config/sync/field.field.node.page.field_intro_text.yml
config/sync/filter.format.plain_text.yml

QA: https://va-gov.atlassian.net/browse/VAGOV-4263

VAGOV-4263: plain text tags.

---

config/sync/core.entity_form_display.node.outreach_asset.default.yml
config/sync/core.entity_view_display.node.outreach_asset.default.yml
config/sync/core.entity_view_display.node.outreach_asset.teaser.yml
config/sync/field.field.node.outreach_asset.field_benefits.yml
config/sync/field.storage.node.field_benefits.yml

This pr only changes field_benefits from unlimited to 1 (Andy Lewandowski request).
The majority of the work for this task will be in the vets-website repo.
No QA for this.

VAGOV-3442

---

composer.json
composer.lock
config/sync/content_lock.settings.yml
config/sync/content_lock_timeout.settings.yml
config/sync/core.extension.yml
config/sync/lightning_core.versions.yml
config/sync/system.action.block_content_break_lock_action.yml
config/sync/system.action.media_break_lock_action.yml
config/sync/system.action.node_break_lock_action.yml
config/sync/system.action.taxonomy_term_break_lock_action.yml
config/sync/views.view.locked_content.yml

QA notes: https://va-gov.atlassian.net/browse/VAGOV-2753

VAGOV-2753: Content locking

---

config/sync/pathauto.pattern.menu_based.yml
config/sync/pathauto.settings.yml

QA notes: https://va-gov.atlassian.net/browse/VAGOV-3982

VAGOV-3982: Fix menu link alias.

---

config/sync/cer.corresponding_reference.local_health_service_to_facility.yml
config/sync/cer.corresponding_reference.local_health_service_to_regions_health_service.yml
config/sync/cer.corresponding_reference.region_to_regional_health_service_offering.yml

QA notes: https://va-gov.atlassian.net/browse/VAGOV-4333

 VAGOV-4333: Create CER between Health System and Regional Health Service.

---

config/sync/user.role.content_publisher.yml
tests/phpunit/SecurityRolesPermissionsTest.php

QA: https://va-gov.atlassian.net/browse/VAGOV-3983

VAGOV-3983: Allow content_publisher to create URL aliases.

---

docroot/modules/custom/va_gov_migrate/src/Obtainer/ObtainAndTestPlainTextWithNewLines.php

To test (in PR environment):
1. Go to /admin/structure/migrate/manage/va_new_benefits/migrations/va_benefits_careers/execute and run migration
2. Go to /careers-employment/vocational-rehabilitation/programs/reemployment and confirm that Intro Text has paragraph tags

VAGOV-4368: Modify plain text migration to allow <a><em><strong><p><br>

---

docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/source/AlertBlockSource.php
docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/source/MetalsmithSource.php

It's not possible to test this yet. No migration scripts have been merged that use the new functionality. 

VAGOV-4117: Add optional config var to set server (defaults to va.gov)

---

docroot/modules/custom/va_gov_migrate/src/EventSubscriber/MessageLogger.php
docroot/modules/custom/va_gov_migrate/src/Obtainer/ObtainAndTestBody.php
docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/source/MetalsmithSource.php

No changes to migration functionality, just adding to and updating tests.

VAGOV-000: migration anomaly tests

---

config/sync/core.entity_form_display.media.document.default.yml
config/sync/core.entity_form_display.media.document.media_browser.yml
config/sync/core.entity_form_display.media.image.default.yml
config/sync/core.entity_form_display.media.image.media_browser.yml
config/sync/core.entity_form_display.media.video.default.yml
config/sync/core.entity_form_display.media.video.media_browser.yml

QA: https://va-gov.atlassian.net/browse/VAGOV-4400

VAGOV-4579: Remove published checkbox and other fields from media entity forms.

---

config/sync/core.entity_form_display.node.event_listing.default.yml
config/sync/core.entity_form_display.node.publication_listing.default.yml
config/sync/core.entity_view_display.node.event_listing.teaser.yml
config/sync/core.entity_view_display.node.publication_listing.teaser.yml
config/sync/field.field.node.event_listing.field_administration.yml
config/sync/field.field.node.event_listing.field_description.yml
config/sync/field.field.node.event_listing.field_intro_text.yml
config/sync/field.field.node.event_listing.field_office.yml
config/sync/field.field.node.publication_listing.field_description.yml
config/sync/field.field.node.publication_listing.field_intro_text.yml
config/sync/field.field.node.publication_listing.field_office.yml
config/sync/node.type.publication_listing.yml
config/sync/pathauto.pattern.events.yml

QA notes: https://va-gov.atlassian.net/browse/VAGOV-4732

VAGOV-4732: Outreach events. 

---

config/sync/menu_breadcrumb.settings.yml
config/sync/node.type.page.yml
config/sync/system.menu.burials-and-memorials-benef.yml
config/sync/system.menu.careers-employment-benefits.yml
config/sync/system.menu.decision-reviews-benefits-h.yml
config/sync/system.menu.disability-benefits-hub.yml
config/sync/system.menu.education-benefits-hub.yml
config/sync/system.menu.pension-benefits-hub.yml
config/sync/system.menu.root-benefits-hub.yml

QA: https://va-gov.atlassian.net/browse/VAGOV-4779

VAGOV-4779: Configure menus for remaining benefits hub.

---

config/sync/core.entity_form_display.node.health_care_region_page.default.yml
config/sync/core.entity_view_display.node.event.teaser.yml
config/sync/core.entity_view_display.node.health_care_region_page.default.yml
config/sync/core.entity_view_display.node.outreach_asset.teaser.yml
config/sync/field.field.node.health_care_region_page.field_operating_status.yml
config/sync/field.storage.node.field_operating_status.yml
config/sync/field.storage.node.field_title_icon.yml

QA: 
* Edit node 318
* There should be an "operating status" link field near the Social Media and Email links.

VAGOV-4688: Add operating status field to health care system.

---

docroot/modules/custom/va_gov_backend/va_gov_backend.install

This pr creates menu items for outreach, and outreach office node, a publication listing node, and events listing node. Also associates all benefit assets with outreach type.

VAGOV-4732: Updating update hook to account for new outreach config.

---

config/sync/core.entity_form_display.node.health_care_region_detail_page.default.yml
config/sync/core.entity_view_display.node.health_care_region_detail_page.default.yml
config/sync/field.field.node.health_care_region_detail_page.field_table_of_contents_boolean.yml
config/sync/field.storage.node.field_table_of_contents_boolean.yml

QA: 
* Go to http://localhost:32789/node/add/health_care_region_detail_page
* You should see a Table of contents fieldset containing a boolean, between the Featured content and the Main content.

VAGOV-4005: Table of contents boolean for detail pages.

---

config/sync/pathauto.pattern.events.yml

We need to update from `{HUB-NAME}/event-title` to `{HUB-NAME}/events/event-title` - that's what this mr does.

VAGOV-000: Updating events path to include events landing page.

---

config/sync/field.storage.node.field_title_icon.yml
config/sync/migrate_plus.migration.va_alert_block.yml
config/sync/migrate_plus.migration.va_benefits_disability.yml
config/sync/migrate_plus.migration.va_benefits_disability_menu.yml
config/sync/migrate_plus.migration.va_benefits_housing.yml
config/sync/migrate_plus.migration.va_benefits_housing_extra.yml
config/sync/migrate_plus.migration.va_benefits_housing_menu.yml
config/sync/migrate_plus.migration.va_benefits_life_insurance.yml
config/sync/migrate_plus.migration.va_benefits_life_insurance_menu.yml
config/sync/migrate_plus.migration.va_benefits_menu.yml
config/sync/migrate_plus.migration.va_hub.yml
config/sync/migrate_plus.migration.va_main_menu.yml
config/sync/migrate_plus.migration.va_new_hubs.yml
config/sync/migrate_plus.migration.va_new_landing_pages.yml
config/sync/migrate_plus.migration.va_new_pages.yml
config/sync/migrate_plus.migration.va_promo.yml
config/sync/migrate_plus.migration.va_promo_images.yml
config/sync/migrate_plus.migration.va_promo_media.yml
config/sync/migrate_plus.migration.va_root_pages.yml
config/sync/migrate_plus.migration.va_support_service.yml
config/sync/migrate_plus.migration_group.va_gov.yml
config/sync/migrate_plus.migration_group.va_new_benefits.yml
config/sync/migrate_plus.migration_group.va_tests.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_hub.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_new_landing_pages.yml

To test:
1. Go to
2. Execute the migration.
3. There should be 10 new benefits landing pages in Draft (this migration will creates dupes of existing ones that are either Published or Archived). They should all have hub icons selected.

VAGOV-5066 update hub icons

---

config/sync/pathauto.pattern.person_profile.yml

Updates Person profile  to [node:field_office:entity:url:path]/staff-profiles/[node:title] pattern
Go to /admin/config/search/path/patterns and visually verify that Person profile pattern appears like: [node:field_office:entity:url:path]/staff-profiles/[node:title]

VAGOV-4351: Updating profile alias pattern.

---

config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
config/sync/field.field.node.health_care_local_facility.field_operating_status_facility.yml
config/sync/field.storage.node.field_operating_status_facility.yml

**Description**
- Adds Operating status field to facility content type
**QA**
- Go to admin/structure/types/manage/health_care_local_facility/fields
- Visually verify that Operating status field appears

VAGOV-4852: Adding operation status to facility type.

---

docroot/modules/custom/va_gov_migrate/src/Paragraph/Base/QABase.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/QaSection.php
docroot/modules/custom/va_gov_migrate/src/ParagraphType.php

To test (from PR environment, http://internal-test-vagovcms-3106-2085586314.us-gov-west-1.elb.amazonaws.com/):
1. Go to /admin/structure/migrate/manage/va_new_benefits/migrations/va_benefits_disability/execute and execute the migration.
2. Go to /disability/file-an-appeal and confirm that the first section intro has an html link ('<a href="/disability/get-help-filing-claim/">Get help filing your appeal</a>').
3. Go to /disability/va-claim-exam and edit the page. Confirm that the last question, "What if I have more questions about my exam?", is in its own Q&A Section

VAGOV-4638: disability migration fixes

---

config/sync/core.entity_form_display.node.person_profile.default.yml
config/sync/core.entity_view_display.node.person_profile.default.yml
config/sync/crop.type.1_1_5.yml
config/sync/field.field.node.person_profile.field_complete_biography.yml
config/sync/field.storage.node.field_complete_biography.yml

**ABOUT**
Relates to https://va-gov.atlassian.net/browse/VAGOV-5022
I thought I could fake the bio by grabbing text and generating pdf with js library. Decided too many unknowns. This approach allows for a user to upload a pdf to drupal file system, which we can path to on frontend with graphql.

VAGOV-000: Adding file download field to staff profile content type.

---

docroot/modules/custom/va_gov_build_trigger/src/Form/BuildTriggerForm.php

VAGOV-5135 Update build trigger to not use SOCKS proxy anymore. (update)

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/lightning_core.versions.yml
config/sync/views.view.content.yml
config/sync/views.view.media.yml

To QA:
[ ] As admin, go to Manage > Content 
[ ] You should see a Bulk Edit Content tab. click on it. 
[ ] You should be able to select several nodes and update a specific field's content by clicking "Modify field values"
[ ] Go to Manage > Content > Media Library > Media bulk edit in the toolbar
[ ] You should be able to select several media items and bulk update a specific field's content by clicking "Modify field values"
[ ] As louis.scavnicky, you should not be able to access either the media or the node bulk edit screens. (/admin/content/bulk and /admin/content/media/bulk-edit)

VAGOV-5357: Configure Views bulk edit for media and nodes.

---

config/sync/migrate_plus.migration.va_benefits_burials.yml~VAGOV-5287: Updated migration config.
config/sync/migrate_plus.migration.va_support_service.yml
config/sync/migrate_plus.migration_group.va_gov.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_benefits_burials.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_support_service.yml
docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/source/MetalsmithSource.php

To test:
1. Go to /admin/structure/migrate/manage/va_tests/migrations/va_benefits_burials/execute and execute migration.
2. Go to /section/burials-and-memorials-benefits-hub. There should be 12 nodes corresponding to Burials & Memorials detail pages.

VAGOV-5287: migrate from PR

---

composer.json
composer.lock
tests/behat/features/content.feature

Previously new composer installs just installed latest SHA.

VAGOV-2937 Pin exact SHA of Unity branch for vets-website.

---

config/sync/core.extension.yml
config/sync/lightning_core.versions.yml

QA
* as admin, go to /admin/content/bulk
* From the Action dropdown, you should see Modify field values.

VAGOV-5472: Reenable views bulk edit.

---

config/sync/menu_breadcrumb.settings.yml

QA. 
Compare [menu breadcrumbs on the prod site](http://prod.cms.va.gov/admin/config/user-interface/menu-breadcrumb), which were configured on prod to the a menu breadcrumbs, to the same config page in the PR environment. They should be the same.

VAGOV-5415: Reorder breadcrumb menus.

---

config/sync/menu_export.export_data.yml
config/sync/menu_export.settings.yml

To test:
1. Go to /admin/config/development/menu_export/import. "Menus to Import" should list "Main navigation" only.
2. Click "Import Menu Links". Menu should import successfully.
3. Go to main navigation menu (/admin/structure/menu/manage/main) and make sure the menu structure matches the megamenu on va.gov.

VAGOV-2287: Menu export config and data for main nav

---

config/sync/core.entity_form_display.node.health_care_region_page.default.yml
config/sync/core.entity_form_display.node.news_story.default.yml
config/sync/core.entity_form_display.node.page.default.yml
config/sync/core.entity_form_display.node.press_release.default.yml
tests/behat/drupal-spec-tool/content_model.feature

See QA at https://va-gov.atlassian.net/browse/VAGOV-5834

VAGOV-5834: Remove inline entity form widgets.

---

config/sync/core.entity_form_display.menu_link_content.footer-bottom-rail.default.yml
config/sync/core.entity_view_display.menu_link_content.footer-bottom-rail.default.yml
config/sync/field.field.block_content.alert.field_node_reference.yml
config/sync/field.field.menu_link_content.footer-bottom-rail.field_open_link_in_new_tab.yml
config/sync/system.menu.footer-bottom-rail.yml
tests/behat/drupal-spec-tool/menus.feature

• Adds bottom rail footer menu.
• Adds an existing menu field to that menu ("Open link in new tab?").
• Adds workbench menu access permission to that menu.

VAGOV-5865: Bottom Rail Footer Config

---

config/sync/editor.editor.rich_text.yml
config/sync/embed.button.file.yml
config/sync/embed.button.media_browser.yml
config/sync/entity_browser.browser.downloadable_file_browser.yml
config/sync/entity_browser.browser.image_browser.yml
config/sync/entity_browser.browser.media_browser.yml
config/sync/field.field.block_content.alert.field_node_reference.yml
config/sync/filter.format.rich_text.yml

- Adds entity embed via autocomplete entity reference to wysiwygs (only allows for file download link)
- Visit any node that has a wysiwyg (or allows for one to be added)
- Click the `E` icon, and start typing to add a file
- Save the node, and visit the corresponding front end page
- Visually verify the linked entity appears, and clicking the link displays the file (requires pr https://github.com/department-of-veterans-affairs/vets-website/pull/10702)

VAGOV-5857: Adding embedded asset functionality to wysiwyg.

---

composer.json
composer.lock

Latest version of said module has check that prevents log pollution.

VAGOV-5809: Updating tablefield to prevent log notices.

---

composer.json

VAGOV-5835 Update vets-website to latest.

---

READMES/workflow.md
composer.json
composer.lock
patches/nullFormIDFixInRedirect.patch

VAGOV-6028: Update headless_lightning

---

Jenkinsfile.cd

This job is being pushed to really large nodes, but doesn't need to be as it's just a meta job that's calling others. Move this to any so it can be executed on master or swarm nodes.

change jenkins agent to any

---

config/sync/redirect.settings.yml

https://va-gov.atlassian.net/browse/VAGOV-6061

VAGOV-6061: Automatically create redirects when URL aliases are changed.

---

tests/behat/features/decoupled.feature

This reverts commit be31b71175f4d980fb07b10fcc5ff5a2bee3e933 in #605.

Revert "VAGOV-6064: Remove check for /static/ URL in decoupled.feature."

---

READMES/testing.md
composer.json
composer.lock
config/sync/core.entity_form_display.taxonomy_term.health_care_service_taxonomy.default.yml
config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml
config/sync/core.extension.yml
config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vha_healthservice_stopcode.yml
config/sync/field.storage.taxonomy_term.field_vha_healthservice_stopcode.yml
config/sync/lightning_core.versions.yml
config/sync/paragraphs.paragraphs_type.address.yml
config/sync/views.view.vha_health_service_taxonomy.yml
tests/behat/drupal-spec-tool/content_model.feature
tests/behat/drupal-spec-tool/views.feature

VAGOV-5952: Stopcode and health service export.

---

Jenkinsfile.cd

VAGOV-000 Fix Jenkins stage.

---

composer.json

Unfortunately this can only be tested fully on dev, staging, and prod.

VAGOV-6123: Add ability to change PW if SSO used to login.

---

config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
config/sync/field.field.node.health_care_local_facility.field_address.yml
config/sync/field.field.node.health_care_local_facility.field_facility_hours.yml
config/sync/field.field.node.health_care_local_facility.field_mental_health_phone.yml
config/sync/field.field.node.health_care_local_facility.field_phone_number.yml
config/sync/field.storage.node.field_facility_hours.yml
config/sync/field.storage.node.field_mental_health_phone.yml
docroot/modules/custom/va_gov_backend/va_gov_backend.module
docroot/modules/custom/va_gov_consumers/src/FacilityConsumer.php
docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
tests/behat/drupal-spec-tool/content_model.feature

Sucks in these fields (and disables user editing) on facility nodes in a presave hook:
- Title
- Address
- Hours
- Phone
Migration to update facilities on daily(ish) interval

VAGOV-5333: Add fields and logic for facility API sourced data.

---

composer.json

Remove static assets before building them again to prevent straggler html

---

config/sync/views.view.content_served_from_drupal.yml
tests/behat/drupal-spec-tool/views.feature

VAGOV-5853: List of content served from Drupal.

---

config/sync/core.extension.yml
config/sync/xmlsitemap_engines.settings.yml

PR: https://va-gov.atlassian.net/browse/VAGOV-3950

VAGOV-3950: Disable XML sitemap engines module.

---

config/sync/block.block.burialsandmemorialsbenefitshub.yml
config/sync/block.block.careersemploymentbenefitshub.yml
config/sync/block.block.disabilitybenefitshub.yml
config/sync/block.block.educationbenefitshub.yml
config/sync/block.block.healthcarebenefitshub.yml
config/sync/block.block.housingassistancebenefitshub.yml
config/sync/block.block.lifeinsurancebenefitshub.yml
config/sync/block.block.outreachandevents.yml
config/sync/block.block.pensionbenefitshub.yml
config/sync/block.block.recordsbenefitshub.yml
config/sync/block.block.vaaltoonahealthcare.yml
config/sync/block.block.vabutlerhealthcare.yml
config/sync/block.block.vacoatesvillehealthcare.yml
config/sync/block.block.vagovadmin_content.yml
config/sync/block.block.vagovadmin_local_actions.yml
config/sync/block.block.vagovadmin_login.yml
config/sync/block.block.valebanon.yml
config/sync/block.block.vaphiladelphiahealthcare.yml
config/sync/block.block.vapittsburghhealthcare.yml
config/sync/block.block.vawilkesbarrehealthcare.yml
config/sync/block.block.vawilmingtonhealthcare.yml
config/sync/views.view.right_sidebar_latest_revision.yml

QA: 
https://va-gov.atlassian.net/browse/VAGOV-6234

VAGOV-6234: Display revision author not node creator.

---

tests.yml

Reverts department-of-veterans-affairs/va.gov-cms#685
This is passing but isn't actually working it appears.

Revert "VAGOV-000 Test config:import imports cleanly."

---

config/sync/field.field.node.full_width_banner_alert.field_alert_inheritance_subpages.yml
tests/behat/drupal-spec-tool/content_model.feature

Changing field label and help text.

VAGOV-000: Changing banner field help text and label.

---

config/sync/menu_breadcrumb.settings.yml

This reverts commit fc0adaf2bd22c537b4e1ed24eabc4ee14203ccf2.

Revert "VAGOV-6296: Don't add Home link to breadcrumb. (#725)"

---

config/sync/block.block.va.govcmsdocumentation.yml
config/sync/core.base_field_override.node.documentation_page.status.yml
config/sync/core.entity_form_display.node.documentation_page.default.yml
config/sync/core.entity_view_display.node.documentation_page.default.yml
config/sync/field.field.node.documentation_page.field_administration.yml
config/sync/node.type.documentation_page.yml
config/sync/pathauto.pattern.documentation.yml
tests/behat/drupal-spec-tool/content_model.feature

See https://va-gov.atlassian.net/browse/VAGOV-6314
QA: Create a new documentation page node

VAGOV-6314: Documentation improvement

---

config/sync/user.role.admnistrator_users.yml
config/sync/views.view.user_admin_people.yml
tests/behat/drupal-spec-tool/access_control.feature

User story: https://va-gov.atlassian.net/browse/VAGOV-6313

VAGOV-6313: Change user admin role name and improve user admin view.

---

config/sync/user.role.content_admin.yml
tests/phpunit/SecurityRolesPermissionsTest.php

VAGOV-5974: Allow content_admin to import csv to tablefields.

---

config/sync/core.entity_form_display.node.full_width_banner_alert.default.yml
config/sync/core.entity_form_display.node.full_width_banner_alert.inline_entity_form.yml
config/sync/core.entity_view_display.node.full_width_banner_alert.ief_table.yml
config/sync/field.field.node.full_width_banner_alert.field_banner_alert_situationinfo.yml
config/sync/field.field.node.full_width_banner_alert.field_banner_alert_vamcs.yml
config/sync/node.type.full_width_banner_alert.yml
tests/behat/drupal-spec-tool/content_model.feature

https://va-gov.atlassian.net/browse/VAGOV-6321

VAGOV-6361: Improve VAMC banner alert form.

---

config/sync/core.menu.static_menu_link_overrides.yml

https://va-gov.atlassian.net/browse/VAGOV-6315

VAGOV-6315: Sort menus.

---

docroot/modules/custom/va_gov_govdelivery/src/Routing/RouteSubscriber.php
docroot/modules/custom/va_gov_govdelivery/va_gov_govdelivery.info.yml
docroot/modules/custom/va_gov_govdelivery/va_gov_govdelivery.services.yml

VAGOV-6350 Add basic auth to govdelivery queue endpoint.

---

.dependabot/config.yml

VAGOV-6347
https://dependabot.com/docs/config-file/
* Security updates
* va.gov/web (vets-website) update, automerged if status checks pass
* Daily

VAGOV-6347 Add dependabot config.yml for auto-updates to vets-website daily w/auto merge

---

config/sync/metatag.metatag_defaults.node__event.yml

Changing metatag pattern for events to default to have last argument default to ` | Veterans Affairs`

VAGOV-6402: Updating last paramter in events metas.

---

Jenkinsfile.cd

We don't need to run tests on this one. It won't do anything right now.

VAGOV-000 Update deploy notify # to #cms-team in Jenkinsfile.

---

config/sync/metatag.metatag_defaults.global.yml
config/sync/metatag.metatag_defaults.node.yml
config/sync/metatag.metatag_defaults.node__event.yml
config/sync/metatag.metatag_defaults.node__news_story.yml
config/sync/metatag.metatag_defaults.node__person_profile.yml
config/sync/metatag.metatag_defaults.node__press_release.yml
tests/behat/features/user.feature

See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/834

VACMS-834: Replace all instances of [site:name] with Veterans Affairs in content metatags.

---

config/sync/core.extension.yml
docroot/modules/custom/va_gov_db/va_gov_db.install

This leads the way to removing headless_lightning.

VAGOV-5244 Uninstall json_content module.

---

docroot/modules/custom/va_gov_build_trigger/src/Form/BuildTriggerForm.php
docroot/modules/custom/va_gov_build_trigger/src/Service/BuildFrontend.php
docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.info.yml
docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.module
docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.services.yml
scripts/composer/EnvironmentHandler.php

**Dev**
As a content editor
**Banner alerts**
**Local Facility page**
**Hand trigger**
After submitting the form there should be a status message saying that a deploy it in process.
**CI**
As a content editor
After submitting the form there should be a status message saying that a deploy it in process.

VAGOV-6412 Add trigger FE build on alert and status update.

---

config/sync/core.entity_form_display.node.event.default.yml
config/sync/core.entity_form_display.node.event_listing.default.yml
config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
config/sync/core.entity_form_display.node.health_care_region_detail_page.default.yml
config/sync/core.entity_form_display.node.health_care_region_page.default.yml
config/sync/core.entity_form_display.node.health_services_listing.default.yml
config/sync/core.entity_form_display.node.landing_page.default.yml
config/sync/core.entity_form_display.node.locations_listing.default.yml
config/sync/core.entity_form_display.node.office.default.yml
config/sync/core.entity_form_display.node.outreach_asset.default.yml
config/sync/core.entity_form_display.node.page.default.yml
config/sync/core.entity_form_display.node.person_profile.default.yml
config/sync/core.entity_form_display.node.story_listing.default.yml
config/sync/field.field.node.event.field_description.yml
config/sync/field.field.node.health_care_local_facility.field_description.yml
config/sync/field.field.node.health_care_region_detail_page.field_description.yml
config/sync/field.field.node.health_care_region_page.field_description.yml
config/sync/field.field.node.landing_page.field_description.yml
config/sync/field.field.node.office.field_description.yml
config/sync/field.field.node.outreach_asset.field_description.yml
config/sync/field.field.node.page.field_description.yml
config/sync/field.field.node.person_profile.field_description.yml
tests/behat/drupal-spec-tool/content_model.feature

- Changes Description field label to Meta Description
- Adds meta tag fieldset to nodeforms, and moves meta title and meta description fields into said fieldset

VAGOV-6370: Adding meta fieldsets to node forms.

---

composer.json

- Allows for table drag sorting on node forms
- Go to `/node/589/edit`
- In Main Content section, open up a table field.
- Change sort order
- Save, confirm new order has been preserved.

VAGOV-6374: Adding draggable table functionality.

---

config/sync/workflows.workflow.editorial.yml

- Remove `Staged` state from workflow, per #901

VAGOV-901: Remove staged state from workflow.

---

tests/behat/drupal-spec-tool/workflow.feature

Attn: @jonpugh @swirtSJW @ElijahLynn

VAGOV-000: Fix failing workflow model test.

---

docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.module

Adds the preview button back to the person_profile content type node view.

VAGOV-1738: Adding preview back to person_profile.

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/lightning_core.versions.yml

- Adds a new tab to perms place for better ui filtering / experieince
- Go to `admin/people/pfm-permissions`
- Click on the PFM permissions tab
- Spot check filtering by various modules and roles

VAGOV-911: Adding better perm ui experience.

---

config/sync/core.base_field_override.node.leadership_listing.promote.yml
config/sync/core.base_field_override.node.leadership_listing.status.yml
config/sync/core.base_field_override.node.leadership_listing.title.yml
config/sync/core.entity_form_display.node.leadership_listing.default.yml
config/sync/core.entity_view_display.node.leadership_listing.default.yml
config/sync/core.entity_view_display.node.leadership_listing.teaser.yml
config/sync/field.field.node.leadership_listing.field_administration.yml
config/sync/field.field.node.leadership_listing.field_description.yml
config/sync/field.field.node.leadership_listing.field_intro_text.yml
config/sync/field.field.node.leadership_listing.field_meta_tags.yml
config/sync/field.field.node.leadership_listing.field_meta_title.yml
config/sync/field.field.node.leadership_listing.field_office.yml
config/sync/menu_breadcrumb.settings.yml
config/sync/node.type.leadership_listing.yml
config/sync/node_revisions_autoclean.settings.yml
config/sync/pathauto.pattern.leadership_listing.yml
config/sync/search_api.index.content.yml
config/sync/user.role.content_admin.yml
config/sync/views.view.search.yml
tests/behat/drupal-spec-tool/content_model.feature
tests/phpunit/SecurityRolesPermissionsTest.php

See #921 
Visual
N/A
As and admin:
- Go to `admin/structure/types/manage/leadership_listing` visually verify that new content type has been created

VACMS-921: Adding leadership_listing content type.

---

config/sync/node_revisions_autoclean.settings.yml
config/sync/workflows.workflow.editorial.yml

Missed adding new listing type to main site workflow. This is an addendum to #923 
Visual

VACMS: Adding new listing type to main workflow.

---

config/sync/core.entity_form_display.node.leadership_listing.default.yml
config/sync/core.entity_view_display.node.leadership_listing.default.yml
config/sync/field.field.node.leadership_listing.field_leadership.yml
tests/behat/drupal-spec-tool/content_model.feature

Adds an entity ref field to listing type - relates to #921 
Visual

VACMS-921: Adding missed field to new listing type.

---

composer.json
composer.lock

See #1001 . 
As user _uid_ with content editor role
1. Go to /pittsburgh-health-care/events/university-drive-september-2020-town-hall
1. Click the edit tab Make no changes, but save the page
1.  Click the edit tab and change the title to "University Drive September ZZZ" and save the page.

VACMS-1001 Update pathauto.

---

config/sync/views.view.user_email_csv.yml

- Adds a view to show all user emails in csv format
- Visual

VACMS-000: Adding user email csv view.

---

tests/behat/drupal-spec-tool/views.feature

Behat spec tool tests pass. 
1. Do this
1. Then that

VACMS Add behat Spec test item for email list view.

---

composer.json
composer.lock

See #1082 
1login as yourself
1. go to /user   ( it will redirect to include your user id.)
1. CLick the edit tab and validate the page does not whitescreen.

VACMS-1082 Patch prevent hide_revision_field from whitescreen user edit

---

composer.json

VAGOV-1176 Fix "Cannot find profiles directory ./profiles".

---

scripts/sync-files.sh

I have errors when trying to sync files locally, this fixes theme
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/1251)

Fix issues with sync-files script on mac and zsh

---

READMES/environments.md

VACMS-000 Add CI ssh directions.

---

config/sync/migrate_plus.migration.va_node_facility_nca.yml
config/sync/migrate_plus.migration.va_node_facility_vba.yml
config/sync/migrate_plus.migration.va_node_facility_vet_centers.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_nca.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vba.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers.yml
docroot/sites/default/settings.php

Login as an admin user
1. Visit http://pr1400.ci.cms.va.gov/admin/structure/migrate/manage/facility/migrations
**VBA**
1. `drush mim va_node_facility_vba`  On CI and BRD this will have to be done in the UI by going here http://pr1400.ci.cms.va.gov/admin/structure/migrate/manage/facility/migrations and click the "execute" button for "va_node_facility_vba"
Batch process should run (less than 5 min) 
**472 were migrated**, but no failures - going to assume this is a pass, @swirtSJW 
2. Go to  content and edit a vba_facility node and validate that
**NCA**
1. `drush mim va_node_facility_vca`  On CI and BRD this will have to be done in the UI by going here http://pr1400.ci.cms.va.gov/admin/structure/migrate/manage/facility/migrations and click the "execute" button for …

VACMS-1368 alt facilities migration

---

composer.lock

See #1428 
`lando test` did not pass locally but CI passed here so...

composer update va-gov/web

---

docroot/sites/default/settings.php

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1431
1. Do this
1. Then that

Use CMS_VAGOV_API_URL/KEY ENV variable in settings.php.

---

config/sync/system.menu.decision-reviews-benefits-h.yml
tests/behat/drupal-spec-tool/menus.feature

VACMS-1436: Rename Decision Reviews menu.

---

docroot/modules/custom/va_gov_db/va_gov_db.install

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/1445)

Remove # from standbox drush update

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/lightning_core.versions.yml
docroot/modules/custom/va_gov_post_api/src/EventSubscriber/QueueProcessedEventSubscriber.php
docroot/modules/custom/va_gov_post_api/va_gov_post_api.info.yml
docroot/modules/custom/va_gov_post_api/va_gov_post_api.module
docroot/modules/custom/va_gov_post_api/va_gov_post_api.services.yml
docroot/sites/default/settings.php

See #1389 . 
Visual + CR of this PR and https://git.drupalcode.org/project/post_api/tree/8.x-1.x
Queue UI - /admin/config/post-api/queue
As user 1
1. Update settings.php file w/ facility endpoint url and apikey in order to test locally https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1446/files#diff-2737999ec8b2368b193b40b46c5679c2R154
1.  Edit or update any facility node
1. confirm your updated data is posted by performing a curl GET request for the facility ID you edited 
`curl -v -H "apikey: <APIKEY>" https://<HOST>/services/va_facilities/v0/facilities/<FACILITY_ID>`
1. run Cron - confirm facility queue is processed by running curl against edited/added facility ID again
1. test queue failure and Slack notification: 
1. enter bogus apikey in settings.php
1. update …

VACMS-1389: post api

---

config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
config/sync/migrate_plus.migration_group.facility_status.yml
docroot/modules/custom/va_gov_migrate/composer.json
docroot/modules/custom/va_gov_migrate/composer.lock
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml
docroot/modules/custom/va_gov_migrate/src/Plugin/migrate_plus/data_parser/Csv.php

See #1390. 
Pull locally, or ssh into devshop
1. Check the status of the migration 
`drush migrate-status va_node_health_care_local_facility_status`  
```
Group: facility_status (facility_status)   Status  Total  Imported  Unprocessed  Last imported       
va_node_health_care_local_facility_status  Idle    1009   0         1009            
```
The exact number may fluctuate slightly depending on the source asp paages.
2. Run the migration as an update migration 
`drush migrate-import va_node_health_care_local_facility_status --update`
3. The migration may take a while, but after it is completed check the status:
`drush migrate-status va_node_health_care_local_facility_status`  
```
Group: facility_status (facility_status)   Status  Total  Imported  Unprocessed  Last imported …
```

VACMS-1390 facility status migration

---

tasks-background.yml

VACMS-1054 Add migration yaml tasks

---

composer.lock

See #1501  
Manual 
Successfully processed some items
Successfully processed all items
Run `lando composer install`
Update settings.php file w/ facility endpoint url and apikey in order to test locally https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1446/files#diff-2737999ec8b2368b193b40b46c5679c2R154
**Test successful processing or ALL queued items**
1. Add or update two or more facility nodes
1. visit /admin/config/post-api/queue and process queue by pressing "Process queue" button
**Test successful processing or SOME queued items**
1. Add or update two or more facility nodes. Modify the endpoint path for one of the queued items in db table `queue` by editing item data blob
1. visit /admin/config/post-api/queue and process queue by pressing "Process queue" button

VACMS-1501: Watchdog summary record for post api queue success.

---

docroot/modules/custom/va_gov_post_api/va_gov_post_api.module

VACMS-000: Add NID to queue item.

---

docroot/modules/custom/va_gov_post_api/va_gov_post_api.module

VACMS-0: Adjust logging for empty facility ids.

---

config/sync/migrate_plus.migration.va_node_facility_nca.yml
config/sync/migrate_plus.migration.va_node_facility_vba.yml
config/sync/migrate_plus.migration.va_node_facility_vet_centers.yml
config/sync/migrate_plus.migration.va_node_health_care_local_facility.yml
config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_nca.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vba.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml

The data this was meant to protect against is now gone.  So there is nothing to test, but we should get it in since the data source is kind of unstable and may lead to html reappearing and being to long.
1. Do this
1. Then that

VACMS-1530 add strip_tags to migration

---

docroot/sites/default/settings.php

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/1560)

Add mysql init commands for read commits

---

docroot/sites/default/settings.php

This is a reversal of https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1560

Remove DB init settings.

---

docroot/modules/custom/va_gov_post_api/va_gov_post_api.install

VACMS-1586 Trigger another force push of facility status to lighthouse.

---

docroot/modules/custom/va_gov_backend/va_gov_backend.libraries.yml
docroot/modules/custom/va_gov_backend/va_gov_backend.module

VACMS-1588 Add site_alert styles back in.

---

docroot/modules/custom/va_gov_backend/src/Service/UserPermsService.php

VACMS-1548: Fixed permission issue for field_listing.

---

.gitignore

VACMS-000 add DS_Store to gitignore.

---

Jenkinsfile.cd

For https://github.com/department-of-veterans-affairs/devops/pull/6767

Parameterize the Jenkinsfile.cd file to work with cms or cms-test.

---

config/sync/migrate_plus.migration.regional_health_care_service.yml
config/sync/migrate_plus.migration_group.default.yml
config/sync/migrate_plus.migration_group.vamc.yml
docroot/modules/custom/va_gov_migrate/data/regional-health-care-service.csv

This is in replacement to https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1621
1. Do this
1. Then that

VAMC-6571 Initialize health service migration.

---

composer.lock

See #1701. 
1. Do this
1. Then that

VACMS-1701 Security update to drupal/webform.

---

composer.lock
config/sync/webform.webform.request_cms_user.yml

VACMS-1753 Webform Drupal SA-2020-018

---

composer.json
composer.lock

See #1797  
As admin
1. Login and visit /admin/reports/status
2. Bounce around on the site to several content pages then visit /admin/reports/dblog
3. Edit a node with a WYSWIG: visit /node/2450/edit
4.  Edit one of the WYSIWYG paragraphs in the main content section. then save the node.
5 Validate that the change worked.
6. Edit a node with draggable paragrapsh: visit /node/2450/edit
7. Drag the the bottom paragraph in the main content section to the top of the section and save the node.  
9. Create a site_alert here /admin/config/system/site-alerts and set an expiry time a minute or two in the future
10. Visit a node edit page /node/716/edit

VACMS-1797 Security update SA-CORE-2020-002

---

tests/behat/drupal-spec-tool/content_model_bundles.feature
tests/behat/drupal-spec-tool/content_model_fields.feature

See #1902. 
None. This just sorts the code. 
Visit the [Bundles](https://docs.google.com/spreadsheets/d/1vL8rqLqcEVfESnJJK_GWQ7nf3BPe4SSevYYblisBTOI/edit#gid=858986005) and [Fields](https://docs.google.com/spreadsheets/d/1vL8rqLqcEVfESnJJK_GWQ7nf3BPe4SSevYYblisBTOI/edit#gid=943298572) tabs and verify that they are sorted by 
1. Entity type
2. Entity bundle
3. Field machine name (for the fields tab)

VACMS-1902: Sort drupal spec tool behat output intelligently.

---

.github/ISSUE_TEMPLATE/cms-discovery.md

See #1863 . 
review template updates

VACMS-1863: Iteration on CMS discovery template.

---

composer.json
tests.yml

See #1519 
See #1519
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/1913)

VACMS-1519: Have composer fail instead of yaml-tests when patches to not apply correctly

---

.lando.yml
scale.php
tests/phpunit/ScalabilityCreateNodeTest.php

See #1890
Total number of runs: 
* Operation took 4.00 and completed 3 iterations.
* Operation took 4.13 and completed 3 iterations.
Output from running script in lando:
```
❯ lando test_performance
0: Waiting on start time
1: Waiting on start time
2: Waiting on start time
3: Waiting on start time
Waiting on 7777
4: Waiting on start time
1: Staring test
4: Staring test
0: Staring test
3: Staring test
2: Staring test
Unable to execute the following command /app/bin/phpunit --debug --exclude-group disabled --verbose --colors=always tests/phpunit/ScalabilityCreateNodeTest.php {output: }3######################
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.1.33
Configuration: /app/phpunit.xml
Testing tests\phpunit\ScalabilityCreateNodeTest
Test …
```

VACMS-1890 Add scalability test script

---

composer.lock

Current build is about a month old.
1. Do this
1. Then that

`composer update va-gov/web`

---

composer.json
composer.lock

The modules UI_patterns and cshs are unused and have never been installed, so needs no uninstalls run.

VACMS-000  Remove unused  ui patterns, and cshs.

---

composer.json
composer.lock

Unable to update composer lock file.
1. Do this
1. Then that

VACMS-000 Fix composer lock issue with fast_404.

---

config/sync/core.entity_form_display.node.landing_page.default.yml
config/sync/core.entity_form_display.node.va_form.default.yml
config/sync/core.entity_view_display.node.va_form.default.yml
config/sync/core.entity_view_display.node.va_form.external_content.yml
config/sync/core.entity_view_display.node.va_form.teaser.yml
config/sync/field.field.node.va_form.field_alert.yml
hooks/git/pre-commit
tests/behat/drupal-spec-tool/content_model_fields.feature

https://github.com/department-of-veterans-affairs/va.gov-team/issues/9189
As an admin or content admin
1.Navigate to an existing va_form /find-forms/about-form-10-10143g
2. Click the edit tab.
3. Choose an alert block and save the node.   
4. Return to the  node edit tab.

VAGOV-TEAM-9189 VA Forms alert

---

.lando.yml

Add a rebuild check to lando
See https://github.com/AaronFeledy/lando-examples/tree/master/landofile-changed-alert for the origin/idea.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/2162)

Add a rebuild check to lando

---

composer.json
composer.lock

See #910
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/2151)

Update composer file for vets website

---

READMES/cms-export.md

Update cms export doc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/2200)

Update cms export doc

---

composer.json
composer.lock

See #2215
As an admin:
1. Go to `/node/5977/edit`
2. In the Meta Description field paste in which contains 320 chars.
```
I am a sentence that has 100 characters in my space and happily take up and will do no more or less. I am a sentence that has 100 characters in my space and happily take up and will do no more or less. I am a sentence that has 100 characters in my space and happily take up and will do no more or less. I have 20 chars!?
```
3. Save the node. 
4. Edit the node

VACMS-2215 update metatag  for string length

---

config/sync/field.field.node.health_care_local_health_service.field_online_scheduling_availabl.yml
config/sync/field.field.node.health_care_local_health_service.field_referral_required.yml
config/sync/field.field.node.health_care_local_health_service.field_walk_ins_accepted.yml
tests/behat/drupal-spec-tool/content_model_fields.feature

See #2228  
Visual
- Go to `node/481/edit`
- Visually verify that the 3 appointment fields are not required.

VACMS-2228: Change appt fields to not required.

---

composer.lock

Updating to use the latests va-gov/web
Test pass

VACMS-000 Update va-gov/web

---

config/sync/linkit.linkit_profile.default.yml

See _issueid_. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2079
As user with permission to update content

VACMS-2079: Updated config for linkit bundles

---

docroot/modules/custom/va_gov_migrate/va_gov_migrate.drush.inc

See #2229 and #2277
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/2283)

Add drush job to clear out old revisions

---

composer.json
composer.lock

See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/910
This will pull the latest tag from composer and use the git repo for the build to work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/2322)

Update vets website version

---

READMES/ewa-rules-of-engagement.md
composer.json
composer.lock

See #2096  
* minimal structure for `workflow_assignments` module to support collaboration
* `READMES/ewa-rules-of-engagement.md` provides the outline of EWA contribution process
* `docroot/module/contrib/workflow_assignments` included in phpcs checks. PHPCS will review this directory on every commit. This directive will eventually go away once we fully move to DO.

VACMS-2096: EWA contrib module collaboration setup & rules of engagement

---

docroot/modules/custom/va_gov_backend/js/gtm_tag_push.js
docroot/modules/custom/va_gov_backend/va_gov_backend.module

We changed the env from 5 to 2, but didn't update the auth token. This pr corrects with environment specific token.

VACMS-000: Changing gtm auth token to env-2 requirement.

---

config/sync/core.entity_form_display.node.va_form.default.yml
config/sync/core.entity_view_display.node.va_form.default.yml
config/sync/core.entity_view_display.node.va_form.external_content.yml
config/sync/core.entity_view_display.node.va_form.teaser.yml
config/sync/field.field.node.va_form.field_va_form_deleted.yml
config/sync/field.field.node.va_form.field_va_form_deleted_date.yml
config/sync/field.storage.node.field_va_form_deleted.yml
config/sync/field.storage.node.field_va_form_deleted_date.yml
config/sync/menu_breadcrumb.settings.yml
config/sync/migrate_plus.migration.va_node_facility_vet_centers_status.yml
config/sync/migrate_plus.migration.va_node_form.yml
config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
config/sync/migrate_plus.migration.va_support_service.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.regional_health_care_service.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_nca.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers_status.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_form.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_support_service.yml
docroot/modules/custom/va_gov_migrate/va_gov_migrate.module
tests/behat/drupal-spec-tool/content_model_fields.feature

See #2359 . 
1. As an admin go to /node/5709/edit  
2. Click on the View tab and 
3. Go to /node/5955/edit   (this is a form that has been deleted in the DB)

VACMS-2359 new va form fields

---

docroot/modules/custom/va_gov_content_export/src/AddBreadcrumbToEntity.php

This is a follow up of #2358 to fix issues with the breadcrumb export
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/2373)

VACMS-11288 Follow up breadcrumb fixes on CMS export

---

config/sync/migrate_plus.migration.va_node_form.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_form.yml

See #2379. 
1. Do this
1. Then that

VACMS-2379 Update va_form migration to not overwrite names.

---

config/sync/migrate_plus.migration.va_node_form.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_form.yml

VACMS-2389 Change va_form migration to not overwrite field_va_form_type

---

config/sync/core.entity_form_display.paragraph.button.default.yml
config/sync/core.entity_view_display.paragraph.button.default.yml
config/sync/field.field.paragraph.button.field_button_label.yml
config/sync/field.field.paragraph.button.field_button_link.yml
config/sync/field.storage.paragraph.field_button_label.yml
config/sync/field.storage.paragraph.field_button_link.yml
config/sync/paragraphs.paragraphs_type.button.yml
tests/behat/drupal-spec-tool/content_model_bundles.feature
tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature

See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/2303
As user admin
1.Login

VACMS-2303 Add CTA Component Build

---

config/sync/block.block.views_block__services_block_1.yml
config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
config/sync/core.entity_view_display.paragraph.health_care_local_facility_servi.default.yml
config/sync/field.field.node.health_care_local_facility.field_local_health_care_service_.yml
config/sync/node.type.health_care_local_facility.yml
config/sync/views.view.services.yml
tests/behat/drupal-spec-tool/content_model_content_type_fields.feature
tests/behat/drupal-spec-tool/views.feature

See #2503. 
Manual, some behat spec tool 
1. Go to admin/content
1. Filter by VAMC facility content type and VISN 4
1. Visit a random sample of VAMC facilities 
1. Check the health services data is filtered correctly (you can edit a couple to make sure it's tied to the right facility)

VACMS-2503: Health services dashboard on facility page

---

config/sync/core.entity_form_display.node.health_care_local_health_service.default.yml
config/sync/field.field.node.health_care_local_health_service.field_phone_numbers_paragraph.yml
tests/behat/drupal-spec-tool/content_model_content_type_fields.feature

See #2512 
Visual, behat
As an administrator, go to `/admin/structure/types/manage/health_care_local_health_service/form-display` and visually verify that it looks like the above screenshot.

VACMS-2512: Update facility service config to obscure fields on node form

---

config/sync/core.menu.static_menu_link_overrides.yml
config/sync/menu_breadcrumb.settings.yml
config/sync/node.type.event.yml
config/sync/node.type.event_listing.yml
config/sync/node.type.health_care_local_facility.yml
config/sync/node.type.health_care_region_detail_page.yml
config/sync/node.type.health_care_region_page.yml
config/sync/node.type.health_services_listing.yml
config/sync/node.type.leadership_listing.yml
config/sync/node.type.locations_listing.yml
config/sync/node.type.news_story.yml
config/sync/node.type.person_profile.yml
config/sync/node.type.press_release.yml
config/sync/node.type.press_releases_listing.yml
config/sync/node.type.publication_listing.yml
config/sync/node.type.story_listing.yml
config/sync/node.type.vamc_operating_status_and_alerts.yml
config/sync/system.menu.va-black-hills-health-care.yml
config/sync/system.menu.va-central-iowa-health-care.yml
config/sync/system.menu.va-fargo-health-care.yml
config/sync/system.menu.va-fargo-health-cares.yml
config/sync/system.menu.va-iowa-city-health-care.yml
config/sync/system.menu.va-minneapolis-health-care.yml
config/sync/system.menu.va-nebraska-western-iowa-health-.yml
config/sync/system.menu.va-sioux-falls-health-care.yml
config/sync/system.menu.va-southern-nevada-health-care.yml
config/sync/system.menu.va-st-cloud-health-care.yml
tests/behat/drupal-spec-tool/menus.feature

Map out and Create Admin and Editorial Menus for VISN 23 Systems.
As admin
Visit the following
and validate that the content types have new Menu items (VISN 23 systems) selected as enabled (check box) to match this.

VAMC-11521: VISN 23 systems menus.

---

.github/dependabot.yml

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2560
https://github.com/dependabot/dependabot-core/issues/2416
This is the test. 
1. Do this
1. Then that

Remove indirect dependencies to avoid dependabot 30 minute timeout

---

config/sync/core.entity_form_display.paragraph.button.default.yml

See #2548 
Visual
As an administrator, go to `/admin/structure/paragraphs_type/button/form-display`, open the button label fieldset, and visually verify settings match screenshot.

VACMS-2548: Increase button char limit.

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/editor.editor.rich_text_limited.yml
config/sync/field.field.node.checklist.field_intro_text_limited_html.yml
config/sync/field.field.node.faq_multiple_q_a.field_intro_text_limited_html.yml
config/sync/field.field.node.page.field_intro_text_limited_html.yml
config/sync/field.field.node.step_by_step.field_intro_text_limited_html.yml
config/sync/filter.format.rich_text_limited.yml
config/sync/lightning_core.versions.yml

See #2370 #2392 #2539 
This pr:
- Adds the allowed_formats project. Said project adds text format options on a per field basis, which have been used to limit the text format option to Rich text limited for all instances of the field_intro_text_limited_html (Benefits detail page, Step-by-Step, FAQ - multiple Q&As, Checklist)
- Augments the Rich text limited wysiwyg with additional buttons
Visual
As an administrator, go to `/node/add/checklist` and visually verify that Page introduction field wysiwyg looks like screenshot.

VACMS-2370_2392_2539 Rich text limited formatting

---

tests/behat/Drupal/FeatureContext.php
tests/behat/features/save_and_continue.feature

VACMS-2352: Adding save and continue behat testing.

---

config/sync/field.field.node.event.field_additional_information_abo.yml
config/sync/field.field.node.event.field_address.yml
config/sync/field.field.node.event.field_administration.yml
config/sync/field.field.node.event.field_date.yml
config/sync/field.field.node.event.field_description.yml
config/sync/field.field.node.event.field_event_cost.yml
config/sync/field.field.node.event.field_event_cta.yml
config/sync/field.field.node.event.field_facility_location.yml
config/sync/field.field.node.event.field_link.yml
config/sync/field.field.node.event.field_listing.yml
config/sync/field.field.node.event.field_location_humanreadable.yml
config/sync/field.field.node.event.field_media.yml
config/sync/field.field.node.event.field_url_of_an_online_event.yml
tests/behat/drupal-spec-tool/content_model_content_type_fields.feature

See #2618 
Grabbing prod config for event content type updates made on prod by @rachel-kauff - this is the first update of several.
Behat
N/A

VACMS-2618: Update event node type fields with prod config.

---

config/sync/core.base_field_override.node.news_story.title.yml
config/sync/core.entity_form_display.node.news_story.default.yml
config/sync/field.field.node.event_listing.field_office.yml
config/sync/field.field.node.news_story.field_administration.yml
config/sync/field.field.node.news_story.field_author.yml
config/sync/field.field.node.news_story.field_featured.yml
config/sync/field.field.node.news_story.field_full_story.yml
config/sync/field.field.node.news_story.field_image_caption.yml
config/sync/field.field.node.news_story.field_intro_text.yml
config/sync/field.field.node.news_story.field_listing.yml
config/sync/field.field.node.story_listing.field_administration.yml
config/sync/field.field.node.story_listing.field_description.yml
config/sync/field.field.node.story_listing.field_intro_text.yml
config/sync/field.field.node.story_listing.field_meta_title.yml
config/sync/field.field.node.story_listing.field_office.yml
config/sync/node.type.news_story.yml
config/sync/node.type.story_listing.yml
tests/behat/drupal-spec-tool/content_model_content_type_fields.feature

See #2642 
Continued exporting of field label updates made by @rachel-kauff on prod
Behat

VACMS-2642: Updating field labels and test from prod for three types.

---

docroot/modules/custom/va_gov_content_export/src/ListDataCompiler.php

VACMS-2637 & 2636 modify reverse entity reference export.

---

config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
config/sync/core.entity_form_display.node.health_care_local_health_service.default.yml
config/sync/field.field.node.health_care_local_facility.field_administration.yml
config/sync/field.field.node.health_care_local_facility.field_description.yml
config/sync/field.field.node.health_care_local_facility.field_intro_text.yml
config/sync/field.field.node.health_care_local_facility.field_location_services.yml
config/sync/field.field.node.health_care_local_facility.field_main_location.yml
config/sync/field.field.node.health_care_local_facility.field_media.yml
config/sync/field.field.node.health_care_local_facility.field_meta_title.yml
config/sync/field.field.node.health_care_local_facility.field_operating_status_facility.yml
config/sync/field.field.node.health_care_local_facility.field_operating_status_more_info.yml
config/sync/field.field.node.health_care_local_facility.field_region_page.yml
tests/behat/drupal-spec-tool/content_model_content_type_fields.feature

See #2656 
Exporting @rachel-kauff changes prod changes to config.
Behat

VACMS-2656: Export content model changes from prod.

---

READMES/unity.md

Just minor edits that the grammarian in me can't help proposing :-)

Update for grammar/clarity

---

docroot/themes/custom/vagovadmin/vagovadmin.theme

See #2714 . 
As content_admin
1. Go to /node/591/revisions
2. Revert to an earlier revision

VACMS-2714: Remove theme suggestion that is breaking node reverts.

---

config/sync/workbench_access.access_scheme.section.yml
tests/behat/features/perms.feature

See #2393 
** Also adding taxonomy to config b/c screenshot provided in description indicates it should be checked.
Visual
As an admin, go to `admin/config/workflow/workbench_access/access_scheme/section/edit` and visually verify that all items are checked.

VACMS-2393: Adding governance to all types.

---

Jenkinsfile.cd

See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1019

Remove cleanWs() from JenkinsFile.cd.

---

config/sync/core.entity_form_display.media.image.default.yml
config/sync/core.entity_form_display.media.image.media_browser.yml
config/sync/core.entity_form_display.media.image.media_library.yml
config/sync/core.entity_form_display.paragraph.media_list_images.default.yml
config/sync/core.entity_view_display.media.image.default.yml
config/sync/core.entity_view_display.media.image.download_link.yml
config/sync/core.entity_view_display.media.image.embedded.yml
config/sync/core.entity_view_display.media.image.media_library.yml
config/sync/core.entity_view_display.media.image.thumbnail.yml
config/sync/core.entity_view_display.paragraph.media_list_images.default.yml
config/sync/field.field.media.image.field_description.yml
config/sync/field.field.paragraph.media_list_images.field_images.yml
config/sync/field.field.paragraph.media_list_images.field_section_header.yml
config/sync/field.storage.media.field_description.yml
config/sync/field.storage.paragraph.field_images.yml
config/sync/paragraphs.paragraphs_type.media_list_images.yml
tests/behat/drupal-spec-tool/content_model_bundles.feature
tests/behat/drupal-spec-tool/content_model_media_fields.feature
tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature

See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/board?assignees=kaise-lafrai&filterLogic=any&repos=154174777
As an editor:
Login
1. Navigate here: admin/structure/media/manage/image/fields
2. Navigate to Paragraph page:
3. [x] Spec tool tests updated

VACMS-2453 media list images component

---

config/sync/core.entity_form_display.node.vamc_operating_status_and_alerts.default.yml
config/sync/field.field.node.vamc_operating_status_and_alerts.field_banner_alert.yml
config/sync/field.field.node.vamc_operating_status_and_alerts.field_facility_operating_status.yml
config/sync/field.field.node.vamc_operating_status_and_alerts.field_links.yml
config/sync/field.field.node.vamc_operating_status_and_alerts.field_operating_status_emerg_inf.yml
config/sync/node.type.vamc_operating_status_and_alerts.yml
tests/behat/drupal-spec-tool/content_model_content_type_fields.feature
tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature

VACMS-2771: Export prod config to code.

---

config/sync/field.field.node.full_width_banner_alert.field_alert_inheritance_subpages.yml
config/sync/field.field.node.full_width_banner_alert.field_banner_alert_vamcs.yml
config/sync/field.field.node.full_width_banner_alert.field_operating_status_sendemail.yml
config/sync/field.field.node.health_care_local_facility.field_operating_status_facility.yml
tests/behat/drupal-spec-tool/content_model_content_type_fields.feature

VACMS-2783: Adding prod config to code.

---

docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/UniqueTitle.php
docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/UniqueTitleValidator.php
docroot/modules/custom/va_gov_backend/va_gov_backend.module

See #2471 
Visual / form submit
- As an admin, go to `node/add/q_a` and fill in required fields. In title field, enter `How do I get these benefits?` (already existing Q&A node title)
- Verify error appears with link to existing node.

VACMS-2471: Adding q_a title constraint.

---

config/sync/menu_breadcrumb.settings.yml

Fix broken breadcrumb paths caused by menu_breadcrumb update which had an update hook setting new config AND a new option added that was a breaking change.  
@ElijahLynn @indytechcook @swirtSJW

VACMS-000: Fix broken menu_breadcrumb config.

---

config/sync/views.view.content.yml
tests/behat/drupal-spec-tool/views.feature

See #2843. 
* log in as `Randi.Hecht@va.gov` (content admin). Confirm you see a view that includes only Learning Center content types at `/admin/content/learning-center` and you are able to bulk publish content in the view
* log in as `tracey.testuser@va.gov` (content editor, reviewer, publisher). Confirm you do not have access to this view `/admin/content/learning-center`
NOTE: this view is temporary and will be removed once LC MVP1.0 is launched

VACMS-2843: Temp content admin view for LC content.

---

docroot/modules/custom/va_gov_content_export/src/Normalizer/LinkItemNormalizer.php
docroot/sites/default/settings.php

Fix issue with running drush during deploy mode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/2887)

Fix issue with running drush during deploy mode

---

config/sync/taxonomy.vocabulary.products.yml
tests/behat/drupal-spec-tool/content_model_bundles.feature

See #2889 . 
Creates "Products taxonomy vocab.

VACMS-2889: Products vocabulary.

---

composer.json
composer.lock

VACMS-2931 sa-core-2020-007 thru 011 Update drupal core.

---

config/sync/field.storage.node.field_related_links.yml
tests/behat/drupal-spec-tool/content_model_content_type_fields.feature

VACMS-2945: Set field cardinality to 1.

---

config/sync/core.entity_form_display.node.checklist.default.yml
config/sync/core.entity_form_display.node.faq_multiple_q_a.default.yml
config/sync/core.entity_form_display.node.media_list_images.default.yml
config/sync/core.entity_form_display.node.media_list_videos.default.yml
config/sync/core.entity_form_display.node.q_a.default.yml
config/sync/core.entity_form_display.node.step_by_step.default.yml
config/sync/core.entity_form_display.paragraph.checklist.default.yml
config/sync/core.entity_form_display.paragraph.checklist_item.default.yml
config/sync/core.entity_form_display.paragraph.media_list_images.default.yml
config/sync/core.entity_form_display.paragraph.media_list_videos.default.yml
config/sync/core.entity_form_display.paragraph.q_a_group.default.yml
config/sync/core.entity_form_display.paragraph.step_by_step.default.yml
tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature

See #2463 
Replacement of #2942 
Visual / Behat
Manual by @oksana-c
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/2953)

VACMS-2463: Add lc field character limits. 

---

config/sync/core.entity_form_display.node.checklist.default.yml
config/sync/core.entity_form_display.node.faq_multiple_q_a.default.yml
config/sync/core.entity_form_display.node.media_list_images.default.yml
config/sync/core.entity_form_display.node.media_list_videos.default.yml
config/sync/core.entity_form_display.node.q_a.default.yml
config/sync/core.entity_form_display.node.step_by_step.default.yml
config/sync/core.entity_form_display.node.support_resources_detail_page.default.yml
config/sync/field.storage.node.field_other_categories.yml
tests/behat/drupal-spec-tool/content_model_content_type_fields.feature

See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3022
As an editor
- Navigate to the following content types to confirm the cardinality of an existing field called machine name: field_other_categories Label: Additional categories (optional).
- Select **Edit** under the Operations column for the **Additional categories (optional)** field:
- Select **Field Settings** tab and confirm the following:
- Navigate back to the **Manage Fields** tab and select the **Manage form display** tab.
- Select Gear icon associated with the **Other categories where people may look for this article** field and confirm the following:
- Select **Edit** under the Operations column for the **Additional categories (optional)** …

VACMS-3022: Field Other Categories Cardinality

---

composer.lock

https://github.com/zaporylie/composer-drupal-optimizations/pull/22 lando composer update zaporylie/composer-drupal-optimizations --no-plugins && lando composer update --lock

VACMS-000: Fix blocking issue described here:

---

docroot/modules/custom/va_gov_build_trigger/src/Service/BuildFrontend.php

VACMS-3122: Fix slack channel in content release error message.

---

composer.lock

VACMS-000 Bump va-gov/web

---

config/sync/auto_entitylabel.settings.node.health_care_local_health_service.yml
config/sync/core.entity_view_mode.node.external_content.yml
config/sync/core.entity_view_mode.paragraph.preview.yml
config/sync/core.entity_view_mode.paragraph.user_guides.yml
config/sync/field.field.node.step_by_step.field_tags.yml
config/sync/field.field.node.support_resources_detail_page.field_tags.yml
config/sync/field.storage.node.field_online_scheduling_availabl.yml
config/sync/field.storage.node.field_referral_required.yml
config/sync/field.storage.node.field_walk_ins_accepted.yml
config/sync/paragraphs.paragraphs_type.collapsible_panel.yml
config/sync/paragraphs.paragraphs_type.q_a_section.yml
config/sync/paragraphs.paragraphs_type.wysiwyg.yml
config/sync/toolbar_menu.toolbar_menu_element.cms_help_center.yml
config/sync/user.role.administrator.yml

Db config code drift occurs organically over time. This pr remedies by bringing in differences
between prod db and config. This commit adds innocuous changes like quotes around strings, etc.
Syncing db with code is necessary to prevent developers from having to filter through code noise
when exporting config for commit.
Attn: @swirtSJW @kevwalsh @kaise-lafrai ^^^^^^^^^

VACMS-000: Sync config with prod db.

---

composer.json
composer.lock
package-lock.json
package.json
tests/accessibility/aXeAccessibilityCheck.js

See #1298
See also included [patch to paragraphs](https://www.drupal.org/project/paragraphs/issues/3176946).
NB: this PR also introduces updates to the axe testing packages.
Ran accessibility tests, manually verified that paragraph creation functions correctly on /node/add/page
Before:
After:
Validate that:

VACMS-1298 fix duplicate id accessibility test failure

---

config/sync/field.field.node.faq_multiple_q_a.field_related_benefit_hubs.yml
config/sync/field.field.paragraph.contact_information.field_benefit_hub_contacts.yml
config/sync/field.field.paragraph.contact_information.field_contact_default.yml
config/sync/field.field.paragraph.q_a_group.field_q_as.yml

…o allow the selection of unpublished entity reference nodes
See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3205
- username: Laura.Walsh1@va.gov
- password: drupal8
- Edit existing FAQ - Multiple Q&As
- Navigate here: `/node/8222/edit`
- Scroll down to the **Q&A GROUPS** section
- Select the **Place Q&As** button
- Select a node that has a status of **Draft**
- Scroll down to the **VA BENEFIT HUBS** section
- Select 2 additional hubs and confirm your selection
- Scroll down to the **CONTACT INFORMATION** section
- Select **Benefit Hub Contacts** radio button
- Select **Add Benefit Hub Contacts** button
- Select any node and confirm your selection
- Complete remainder of the form
- username: …

VACMS-3205:Updated entity reference fields used for Learning Center

---

tests/behat/features/content_editing.feature

See #3208 
Ran behat test locally and verified that terms are created and cleaned up.

VACMS-3208: ensure that created terms are cleaned up after test is complete

---

composer.lock

VACMS-000 Bump vetswebsite.

---

config/sync/filter.format.rich_text_limited.yml

See #3260 
Visual
- Go to `node/8420/edit`
- Edit the source of the Answer rich text field, and paste in this link <a href="tel:+18008271000" aria-label="8 0 0. 8 2 7. 1 0 0 0.">800-827-1000</a>
- Uncheck "Source"
- Check source again, aria-label should be visible

VACMS-3260: Update rich text a attribute handling.

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module
scripts/content/VACMS-3197-bulk_update_lc_path_aliases-2020-10.php

Just adding a missing content type.
1. Do this
1. Then that

VACMS-3197 Add support_resource_detail_page to locked aliases.

---

config/sync/views.view.content.yml

…rning center details page type and a filter
See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/2706
- Login as Admin
- Navigate here: `/admin/content/resources-and-support`
- Confirm the following:
- Confirm results appear when filtering for each content type:

VACMS-3346: Updated Resources and Support Dashboard

---

composer.json
composer.lock

See #3439 . 
https://www.drupal.org/project/govdelivery_bulletins/releases/8.x-1.3
Upstream module bump.
- [/] No announcement is needed for this code change. 
- [/] Merge & carry on unburdened by announcements

VACMS-3439 Update drupal/govdelivery_bulletins.

---

composer.json
composer.lock

Update vets-website to lastest tag.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/3600)

Update vets-website to v0.1.1173 & update composer nodejs from 10 to 14.

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module

See #3616 
1. Do this
1. Then that

VACMS-3616: Prevent format on plain text table cells.

---

config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
config/sync/core.entity_form_display.paragraph.link_teaser_with_image.default.yml
config/sync/core.entity_view_display.node.campaign_landing_page.default.yml
config/sync/core.entity_view_display.node.campaign_landing_page.teaser.yml
config/sync/core.entity_view_display.paragraph.link_teaser_with_image.default.yml
config/sync/field.field.node.campaign_landing_page.field_clp_stories_cta.yml
config/sync/field.field.node.campaign_landing_page.field_clp_stories_header.yml
config/sync/field.field.node.campaign_landing_page.field_clp_stories_intro.yml
config/sync/field.field.node.campaign_landing_page.field_clp_stories_panel.yml
config/sync/field.field.node.campaign_landing_page.field_clp_stories_teasers.yml
config/sync/field.field.paragraph.link_teaser_with_image.field_link_teaser.yml
config/sync/field.field.paragraph.link_teaser_with_image.field_media.yml
config/sync/field.storage.node.field_clp_stories_cta.yml
config/sync/field.storage.node.field_clp_stories_header.yml
config/sync/field.storage.node.field_clp_stories_intro.yml
config/sync/field.storage.node.field_clp_stories_panel.yml
config/sync/field.storage.node.field_clp_stories_teasers.yml
config/sync/field.storage.paragraph.field_link_teaser.yml
config/sync/paragraphs.paragraphs_type.link_teaser_with_image.yml
tests/behat/drupal-spec-tool/content_model_bundles.feature
tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature

See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/2260
Coming soon...

VACMS-2260-CLP-Stories-Panel

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module

We missed adding the edit page - only covered the clp add page

VACMS-000: Add clp edit page to toggle logic.

---

docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php

Follow up on #3677 with a fix for BRD plugin

Use the correct method to the the message

---

.tugboat/config.yml

Change Tugboat online step to not report status to github outside of PRs

Change Tugboat online step to not report status to github outside of PRs

---

composer.json
composer.lock

cc #3487
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/3771)

Update vets-website to v0.1.1191

---

docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Lando.php
docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Tugboat.php

Add a message after a content release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/3831)

Add a message after a content release

---

config/sync/core.entity_form_display.paragraph.button.default.yml
config/sync/core.entity_view_display.paragraph.button.default.yml

…en Label for both the form and the display
See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3766
- Create a 'checklist' content item here: /node/add/checklist
- Fill out all required fields
- Save successfully

VACMS-3766: CTA Paragraph Text URL Order

---

composer.lock

See #3826. 
Reviewed [changelog](https://www.drupal.org/project/drupal/releases/8.9.11) (I didn't see any messages that indicated changes to or conflicts with our setup), observed output while updating to ensure core and contrib patches were applied, and checked for database updates (none present).  Opening PR to see results of automated tests.
As any developer
1. Validate Acceptance Criteria from #3826:

VACMS-3826: Updates Drupal Core 8.9.10 -> 8.9.11.

---

composer.lock

Update vetswebsite version to v0.1.1214
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/3953)

Update vetswebsite version to v0.1.1214

---

composer.lock

See #3960 . 
1. Do this
1. Then that

VACMS 3960: Updates va-gov/web to v0.1.1217

---

config/sync/core.entity_form_display.taxonomy_term.health_care_service_taxonomy.default.yml
config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml
config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_service_type_of_care.yml
config/sync/field.storage.taxonomy_term.field_service_type_of_care.yml
config/sync/views.view.vha_health_service_taxonomy.yml
tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature

See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3915
- Login to preview environment and navigate here: /vha-health-services
- Select Edit on any row

VACMS-3915: Type Of Care

---

config/sync/migrate_plus.migration.facility_health_care_service_covid.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.facility_health_care_service_covid.yml
docroot/modules/custom/va_gov_migrate/data/facility_health_care_service_covid.csv

VACMS-3824 Update covid vaccine facility service data.

---

config/sync/core.entity_form_display.media.document_external.default.yml
config/sync/core.entity_form_display.menu_link_content.footer-bottom-rail.default.yml
config/sync/core.entity_form_display.menu_link_content.footer.default.yml
config/sync/core.entity_form_display.menu_link_content.header-megamenu.default.yml
config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
config/sync/core.entity_form_display.node.event.default.yml
config/sync/core.entity_form_display.node.health_care_region_page.default.yml
config/sync/core.entity_form_display.node.support_service.default.yml
config/sync/core.entity_form_display.node.va_form.default.yml
config/sync/core.entity_form_display.node.vamc_operating_status_and_alerts.default.yml
config/sync/linkit.linkit_profile.default.yml
tests.yml
tests/behat/drupal-spec-tool/content_model_benefits_hubs_content_type_fields.feature
tests/behat/drupal-spec-tool/content_model_campaign_landing_page_content_type_fields.feature
tests/behat/drupal-spec-tool/content_model_media_fields.feature
tests/behat/drupal-spec-tool/content_model_va_forms_content_type_fields.feature
tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
tests/scripts/check-linkit-logs.sh

See #3917 
Visual / behat / shell
N/A
As an admin, create a new clp, and a new VA form.
Visually verify that all link field instances use linkit widget.

VACMS-3917 linkit widget updates

---

.tugboat/.env.j2
.tugboat/config.yml
config/sync/block.block.whatsnewinthecms.yml
docroot/modules/custom/va_gov_backend/js/script.es6.js
docroot/modules/custom/va_gov_backend/js/script.js
docroot/modules/custom/va_gov_backend/va_gov_backend.libraries.yml
scripts/tests/cypress-axe.sh

VACMS-4022: Fix accessibility test failure

---

composer.lock

Update vets-website to v0.1.1234
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/4042)

Update vets-website to v0.1.1234

---

.tugboat/config.yml

See #4058 
1. Do this
1. Then that

VACMS-4058: Use xargs instead of -exec for files directory permission updates

---

READMES/tugboat.md

See #3978.
WIP for Demo preview environment launch on Tugboat. Everyone is encouraged to push commits to this PR or make edits etc.

[docs] Prepare for Demo preview environment launch on Tugboat

---

.lando/zzz-lando-my-custom.ini
.tugboat/config.yml

See #4102.  Update tugboat and lando php/memory settings to allow for larger GraphQL requests. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/4123)

VACMS-4102 tugboat php settings

---

config/sync/views.view.content_release_logs.yml

Disable caching on content release logs view

---

composer.lock

`Updating va-gov/web (v0.1.1266 => v0.1.1291):  Checking out 0c1e29c807`
1. Do this
1. Then that

Updates web.

---

config/sync/core.entity_form_display.media.video.default.yml
config/sync/core.entity_form_display.media.video.media_browser.yml
config/sync/core.entity_form_display.media.video.media_library.yml
config/sync/core.entity_view_display.media.video.default.yml
config/sync/core.entity_view_display.media.video.embedded.yml
config/sync/core.entity_view_display.media.video.thumbnail.yml
config/sync/core.entity_view_display.media.video.user_guides.yml
config/sync/field.field.media.video.field_publication_date.yml
config/sync/field.storage.media.field_publication_date.yml
tests/behat/drupal-spec-tool/content_model_media_fields.feature

See #4156 
Visual / Behat
- As an administrator, go to `/media/add/video` and fill in all fields.
- As an administrator, go to `/node/15068/edit` and open the video panel.
- Remove the current video, and select the video you just uploaded in the media browser.
- Visually verify that the publication date appears.

VACMS-4156: Add pub date to video.

---

docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php

See #4222. 
Forthcoming.
Forthcoming.
Forthcoming.

VACMS-4222: Better testing for the BRD environment.

---

config/sync/field.field.node.health_care_local_health_service.field_facility_location.yml
config/sync/views.view.local_facilities_entity_reference_view.yml

See #4236 
manual testing
As a user with the content admin role:
1. Edit a VAMC facility health service node

VACMS-4236: Show VAMC system on HC facility entity reference

---

composer.lock

Updates va-gov/web to v0.1.1303

---

config/sync/field.field.node.page.field_intro_text_limited_html.yml

See #4234 
Visual / Behat
As an administrator, go to `/node/add/page` and visually verify that the intro text field help text reads `Add an introduction that helps visitors understand if information on the page is relevant to them.`

VACMS-4234: Update intro page help text.

---

composer.json
composer.lock

VACMS-4286: Upgrade module to d9 compatibility.

---

composer.json
composer.lock
config/sync/migrate_plus.migration.va_node_form.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_form.yml
docroot/modules/custom/va_gov_migrate/va_gov_migrate.module

See #4307
1. Do this
1. Then that

VACMS-4307 Unarchive unflagged VA forms.

---

docroot/modules/custom/va_gov_backend/src/Controller/ContentReleaseStatusController.php

This is an interim fix only! Trying to get this out before today's release.
See #4319 
1. Do this
1. Then that

VACMS-4319: Change hard-coded URL for interim fix

---

docroot/modules/custom/va_gov_migrate/va_gov_migrate.module

VACMS-4307 restrict va form archiving to cms migrator. 2

---

composer.lock

The upgrade!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/4343)

FASTER VETS-WEBSITE (va-gov/web from 0.1.1303 to 0.1.1320)!!!!

---

composer.json
composer.lock

See #4313 
Manual testing.
Attempt to login with a valid username and incorrect password more than 5 times in a row. You should see a message that the account has been temporarily blocked. Then, review the [new documentation](https://github.com/acrollet/va.gov-cms/blob/VACMS-2824-2825-flood_control/READMES/user_management.md) and log in as a user with the `Administrator` role:

VACMS-4313: Use manually created patch for flood control

---

composer.json
composer.lock
config/sync/admin_toolbar_tools.settings.yml
docroot/modules/custom/va_gov_backend/va_gov_backend.module
tests.yml
tests/behat/features/hms.feature
tests/scripts/check-cer.sh

See #4260 #4264 #4265 #4266 #4267 #4276 #4277 #4278
Build, log checks, behat, phpunit, spot checks
N/A
- Spot check multiple pages and review logs for issues.

VACMS-4260 4264 4265 4266 4267 4276 4277 4278 D9 upgrades

---

composer.json
composer.lock
config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml
docroot/modules/custom/va_gov_migrate/src/Plugin/migrate_plus/data_parser/Csv.php

VAMS-4305 Migration url csv fetcher hardening

---

READMES/scalability.md
scripts/clone.php

See #4215 . 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/4470)

Add clone and scalability readme

---

config/sync/core.entity_form_display.node.vet_center_locations_list.default.yml
config/sync/core.entity_view_display.node.vet_center_locations_list.default.yml
config/sync/core.entity_view_display.node.vet_center_locations_list.teaser.yml
config/sync/field.field.node.vet_center_locations_list.field_administration.yml
config/sync/field.field.node.vet_center_locations_list.field_intro_text.yml
config/sync/field.field.node.vet_center_locations_list.field_nearby_vet_centers.yml
config/sync/field.storage.node.field_nearby_vet_centers.yml
tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature

https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/4428
https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/4419
Coming soon...

VACMS-4428: Vet Center Location List Updates

---

config/sync/core.entity_form_display.node.vet_center.default.yml
config/sync/core.entity_form_display.paragraph.basic_accordion.default.yml
config/sync/core.entity_view_display.node.vet_center.default.yml
config/sync/core.entity_view_display.node.vet_center.teaser.yml
config/sync/core.entity_view_display.paragraph.basic_accordion.default.yml
config/sync/field.field.node.vet_center.field_prepare_for_visit.yml
config/sync/field.field.paragraph.basic_accordion.field_header.yml
config/sync/field.field.paragraph.basic_accordion.field_rich_wysiwyg.yml
config/sync/field.storage.node.field_prepare_for_visit.yml
config/sync/field.storage.paragraph.field_header.yml
config/sync/field.storage.paragraph.field_rich_wysiwyg.yml
config/sync/paragraphs.paragraphs_type.basic_accordion.yml
tests/behat/drupal-spec-tool/content_model_bundles.feature
tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature
tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature

See #4442 
Visual / behat
- As an administrator, go to `node/add/vet_center` and visually verify that `Prepare for your visit` field appears as in screenshots.

VACMS-4442: Add new vc Prepare for your visit field and paragraph.

---

config/sync/core.entity_form_display.media.document_external.default.yml
config/sync/core.entity_view_display.node.campaign_landing_page.default.yml
config/sync/field.field.node.campaign_landing_page.field_hero_image.yml
config/sync/workbench_access.access_scheme.section.yml
tests/behat/drupal-spec-tool/content_model_campaign_landing_page_content_type_fields.feature

See #4368 #4389 #4390 #4393
Visual / Behat
**As an administrator:**
1. - go to `admin/config/workflow/workbench_access/access_scheme/section/edit` and visually verify that document external is checked.
2. - go to `/node/add/campaign_landing_page` and visually verify hero image is required.
3. - go to `/node/15068` and visually verify that you do not see the moderation widget
4. - go to `admin/structure/media/manage/document_external/form-display`, and visually verify name message is set to `<span class="remaining_count">@remaining_count</span> characters remaining.`

VACMS-4368_4389_4390_4393: Add quick clp config related updates.

---

docroot/modules/custom/va_gov_user/src/Plugin/Block/UserSections.php

See #4499.
1. Do this
1. Then that

VACMS-4499: Fix count() warning in UserSections block.

---

composer.lock

1. Do this
1. Then that
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/4524)

Update vets-website v0.1.1345 => v0.1.1363

---

READMES/getting-started.md

[docs] document lando version requirement for mariadb 10.5

---

docroot/modules/custom/va_gov_db/va_gov_db.install

See #4262. 
1. Do this
1. Then that
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/4544)

VACMS-4262 Uninstall cms export modules

---

composer.lock

1. Do this
1. Then that
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/4579)

Upgrade va-gov/web (v0.1.1363 => v0.1.1376)

---

docroot/modules/custom/va_gov_db/va_gov_db.install

See #4262 . 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/4600)

VACMS-4262 Uninstall tome_static and tome_base

---

config/sync/system.menu.va-oklahoma-health-care.yml
tests/behat/drupal-spec-tool/menus.feature

See #4597. 
As admin
1. Navigate to admin/structure/menu/manage/va-oklahoma-health-care?destination=/admin/structure/menu%3Fpage%3D2
2.  automated tests pass

VACMS-4597 Add City to Oklahoma City health care menu.

---

.lando.yml
.tugboat/config.yml
composer.json
composer.lock

See #1004. 
1. Do this
1. Then that

VACMS-1004: Update Composer, Lando, Tugboat to PHP 7.3

---

docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.facility_health_care_service.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.facility_health_care_service_2.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.facility_health_care_service_covid.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.health_care_region_page.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.regional_health_care_service.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.regional_health_care_service_covid.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.regional_health_care_service_region_keyed.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_nca.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vba.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers_status.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_form.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml
docroot/modules/custom/va_gov_migrate/va_gov_migrate.module

See #4609. 
1. Do this
1. Then that

VACMS-4609 Replace migration calls to time() with custom callable.

---

config/sync/migrate_plus.migration.facility_health_care_service.yml
config/sync/migrate_plus.migration.facility_health_care_service_2.yml
config/sync/migrate_plus.migration.facility_health_care_service_covid.yml
config/sync/migrate_plus.migration.health_care_region_page.yml
config/sync/migrate_plus.migration.regional_health_care_service.yml
config/sync/migrate_plus.migration.regional_health_care_service_covid.yml
config/sync/migrate_plus.migration.regional_health_care_service_region_keyed.yml
config/sync/migrate_plus.migration.va_node_facility_nca.yml
config/sync/migrate_plus.migration.va_node_facility_vba.yml
config/sync/migrate_plus.migration.va_node_facility_vet_centers.yml
config/sync/migrate_plus.migration.va_node_facility_vet_centers_status.yml
config/sync/migrate_plus.migration.va_node_form.yml
config/sync/migrate_plus.migration.va_node_health_care_local_facility.yml
config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml

VACMS-4609 Update config/sync migrations

---

composer.lock

Update vets-website
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/4605)

Updating va-gov/web (v0.1.1376 => v0.1.1385)

---

.devcontainer/post-create.sh

Remove paths from post-create script

---

docroot/modules/custom/va_gov_db/va_gov_db.install

See #4262 . 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/4635)

VACMS-4262: Try uninstalling tome again

---

config/sync/core.extension.yml
docroot/modules/custom/va_gov_db/va_gov_db.install

See #4262 . 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/4640)

VACMS-4262 why no uninstall tome

---

composer.json
composer.lock
patches/yaml-tasks-pending.patch

See #4653 
1. Do this
1. Then that

VACMS-4653: patch yaml tasks

---

READMES/Codespaces.md
READMES/codespaces.md

[docs] add documentation on codespaces

---

config/sync/core.entity_form_display.node.vet_center.default.yml
config/sync/core.entity_view_display.node.vet_center.default.yml
config/sync/core.entity_view_display.node.vet_center.teaser.yml
config/sync/field.field.node.vet_center.field_cc_non_traditional_hours.yml
config/sync/field.field.node.vet_center.field_cc_vet_center_call_center.yml
config/sync/field.field.node.vet_center.field_cc_vet_center_faqs.yml
config/sync/field.storage.node.field_cc_non_traditional_hours.yml
config/sync/field.storage.node.field_cc_vet_center_call_center.yml
config/sync/field.storage.node.field_cc_vet_center_faqs.yml
tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature

See #4613 #4615
Visual / behat
As an administrator, go to `admin/structure/types/manage/vet_center/fields/node.vet_center.field_cc_vet_center_faqs` and visually verify that page settings match screenshot 3.
As an administrator, go to `/admin/structure/types/manage/vet_center/fields` and visually verify you see fields named `field_cc_non_traditional_hours` and `field_cc_vet_center_call_center` 

VACMS-4613 4615 VC config items

---

config/sync/user.role.content_admin.yml
tests/phpunit/Security/RolesPermissionsTest.php

VACMS-4728: Restore url perm.

---

tests/behavioral/cypress/integration/image_crop.feature

Image Crop tests might be causing intermittent failures in testing PRs.  Ignoring them should help.  I'll try and get the tests to pass 100% of the time when I'm back from my staycation.
1. Do this
1. Then that

VACMS-0000: Ignore Image Crop tests.

---

config/sync/core.entity_form_display.node.regional_health_care_service_des.default.yml

See #4758
Visual / behat
As an administrator, go to `node/7380/edit` and visually verify that you can see the moderation workflow widget.

VACMS-4758: Enable workflow field on node form.

---

config/sync/user.role.office_content_creator.yml
tests/behat/drupal-spec-tool/access_control.feature

See #4588
Visual / behat / phpunit
- As an administrator, go to `admin/people/roles` and visually verify that you see `Content creator - Outreach Hub`

VACMS-4588: Rename cc office role.

---

composer.json
config/sync/field.field.node.health_care_region_page.field_media.yml
tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature

See #4614 
Visual / behat
As an administrator, go to `/node/add/health_care_region_page` and visually verify that field_media is required.

VACMS-4614: Require image field on system nodes.

---

config/sync/views.view.facility_governance.yml

See #4825. 
As an admin visit
https://pr4825-0dje4yxibaxe8egxwotpsj2dbjk9nac7.ci.cms.va.gov/admin/content/facility-status?Title=escanaba&field_facility_locator_api_id_value=&field_operating_status_facility_value=All&field_operating_status_more_info_value=&taxonomy_entity_index_tid_depth%5B%5D=190&moderation_state=All
visit https://pr4825-0dje4yxibaxe8egxwotpsj2dbjk9nac7.ci.cms.va.gov/admin/content/facility-status?Title=&field_facility_locator_api_id_value=&field_operating_status_facility_value=All&field_operating_status_more_info_value=&taxonomy_entity_index_tid_depth%5B%5D=190&moderation_state=All 
1. Do this
1. Then that

VACMS-4820 Add VC outstations and CAPs to status View.

---

config/sync/migrate_plus.migration.va_node_facility_vet_centers.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers.yml

VACMS-4823 Update vet center migration to lookup parent by id.

---

docroot/modules/custom/va_gov_notifications/va_gov_notifications.info.yml

See #4831.  This one slipped through our net, presumably because of the timing in which different things were merged. 
Re-checked with Upgrade Status module, no issues found.
1. Do this
1. Then that

VACMS-4831: Makes va_gov_notifications D9-compatible.

---

docroot/modules/custom/va_gov_post_api/va_gov_post_api.module

VACMS-000 Removing trailing character.

---

config/sync/views.view.content.yml

See #4844 
Visual
As an administrator, go to `/admin/config/system/taxonomy-entity-index/reindex` and reindex content
Once complete, visit `/admin/content/events` and verify view is working as expected.

VACMS-4844: Fix broken events view.

---

config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
config/sync/core.entity_form_display.node.health_care_local_facility.inline_entity_form.yml
config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
config/sync/core.entity_view_display.node.health_care_local_facility.ief_table.yml
config/sync/core.entity_view_display.node.health_care_local_facility.teaser.yml
config/sync/field.field.node.health_care_local_facility.field_mobile.yml
config/sync/field.storage.node.field_mobile.yml
docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature

See _issueid_. #4744 
- Login to PR environment
- Navigate here: `node/add/health_care_local_facility`
- Confirm a new boolean field called `Mobile` is visible, is not checked and is not editable.
- Confirm on save of the node that it displays `Mobile: FALSE`

VACMS-4744: Mobile-Flag-VAMC

---

config/sync/core.entity_form_display.node.vet_center_cap.default.yml
config/sync/core.entity_form_display.node.vet_center_cap.inline_entity_form.yml
config/sync/core.entity_form_display.node.vet_center_locations_list.default.yml
config/sync/core.entity_view_display.node.vet_center_cap.default.yml
config/sync/core.entity_view_display.node.vet_center_cap.external_content.yml
config/sync/core.entity_view_display.node.vet_center_cap.ief_table.yml
config/sync/core.entity_view_display.node.vet_center_cap.teaser.yml
config/sync/core.entity_view_display.node.vet_center_locations_list.default.yml
config/sync/core.entity_view_display.node.vet_center_locations_list.teaser.yml
config/sync/entity_browser.browser.mobile_vet_centers.yml
config/sync/field.field.node.vet_center_cap.field_operating_status_facility.yml
config/sync/field.field.node.vet_center_cap.field_operating_status_more_info.yml
config/sync/field.field.node.vet_center_cap.field_table_of_contents.yml
config/sync/field.field.node.vet_center_locations_list.field_nearby_mobile_vet_centers.yml
config/sync/field.field.node.vet_center_locations_list.field_nearby_vet_centers.yml
config/sync/field.storage.node.field_nearby_mobile_vet_centers.yml
config/sync/user.role.authenticated.yml
config/sync/views.view.vet_centers.yml
tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature
tests/behat/drupal-spec-tool/views.feature
tests/phpunit/Security/RolesPermissionsTest.php

See _issueid_. #4933 #4934 
- Login as Vet Center editor here: https://pr4948-ialkjr84zhqljf9d5htvganh1kuspz6h.ci.cms.va.gov
- Navigate here: https://pr4948-ialkjr84zhqljf9d5htvganh1kuspz6h.ci.cms.va.gov/node/16626/edit
- Navigate here: https://pr4948-ialkjr84zhqljf9d5htvganh1kuspz6h.ci.cms.va.gov/node/16478/edit

VACMS-4933: CAP-VC-Location -Updates

---

config/sync/migrate_plus.migration.va_node_facility_vet_centers.yml
config/sync/migrate_plus.migration.va_node_health_care_local_facility.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.facility_health_care_service.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.facility_health_care_service_2.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.facility_health_care_service_covid.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.health_care_region_page.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.regional_health_care_service.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.regional_health_care_service_covid.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.regional_health_care_service_region_keyed.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility.yml

See _issueid_. #4745 
- Navigate here: `/admin/structure/migrate/manage/facility/migrations/va_node_health_care_local_facility/execute`
- Be sure to select the UPDATE checkbox before starting the migration:
- 
- Select Execute

VACMS-4745: Update VAMC facilities "mobile" status from migraiton.

---

composer.json
composer.lock

1. Go to https://pr4984-tx33nf8f48ochoo6kad1e0jlqsashwbu.ci.cms.va.gov/graphql/explorer
2. enter the following in the query window
```
query {
nodeById(id: "16141") {
uuid,
entityType,
entityBundle,
entityLabel,
title,
status,
entityMetatags {
key
value
}
... on NodeVamcSystemPoliciesPage {
fieldCcBottomOfPageContent{
targetType,
targetId,
targetField,
fetchedBundle
fetched,
}
fieldCcTopOfPageContent {
targetType,
targetId,
targetField,
fetchedBundle
fetched,
}
}
}
}
```

VACMS-4822 Update drupal entity_fetch_field module.

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module
docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.module

Reverts department-of-veterans-affairs/va.gov-cms#4907
The results of this PR ended up being cached and bleeding over to other content types.

Revert "VACMS-4541: Prevent non admin user from editing administration."

---

composer.json

See #4966. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/5013)

Add `force-content-build` flag to full web build

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/memcache_admin.settings.yml

See #4460.  This is just preparatory work, doesn't actually _use_ memcache.
None, didn't (shouldn't) change anything.
1. Do this
1. Then that

VACMS-4460: Install and enable Memcache (part 1).

---

config/sync/core.entity_form_display.node.event.default.yml

See #5062
Visual
Go to `admin/structure/types/manage/event/form-display` click on the Date and Time cog, and visually verify that the Hide the end date field is unchecked.

VACMS-5062: Fix date end field display bug.

---

tests.yml

VACMS-0000: Rename variable in va/tests/phplint task.

---

tests.yml

IDK why, exactly, but the named pipe stuff in this particular test is just not playing well with Jenkins, so I'm removing it (the useful information is posted as a comment to GitHub when relevant anyway).
1. Do this
1. Then that

VACMS-0000: Strip named pipe from phplint.

---

tasks-periodic.yml

One task was duplicated in the taskfile and (obv) did not need to be.
Also, `va/background/daily/migrate_copy/va_forms_csv_source` was being executed in two separate shells and consequently downloading the file to the wrong destination, so the migration wasn't being updated properly.
1. Do this
1. Then that

VACMS-0000: Fix a couple of issues in the periodic tasks.

---

docroot/modules/custom/va_gov_build_trigger/src/GraphQLEntityQuery.php
docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.module

See #5351. 
Ran a count query of graphql cache results with `node_list` and saw several hundred.  After the code is there I ran the same API request there were 0 results.
1. Do this
1. Then that
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/5145)

VACMS-5131: Do not have graphql add node_list cache tag.

---

docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.module

Back out #5124
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/5155)

Back out #5124 to add back node_list cache tag.

---

composer.json
composer.lock

See #4292 and #4805.  This was supposed to be removed previously but for some reason it didn't stick 🤔 
1. Do this
1. Then that

VACMS-0000: Remove Schemata module.

---

config/sync/views.view.taxonomy_term.yml

VACMS-5169 Restore filters on section View.

---

composer.json
composer.lock

See #4954.  Maybe third time's a charm?
This should be good to merge iff tests pass. 
1. Do this
1. Then that

VACMS-4954: Updates acquia/drupal-spec-tool to ^3.0.

---

config/sync/views.view.taxonomy_term.yml

See #5195. 
As user admin
1. go here https://pr5197-lyltuliy9z0volodlvgvkhp0fn0o4pwc.ci.cms.va.gov/section/veterans-health-administration/visn-19

VACMS-5195 Add -any- to taxonomy term View.

---

composer.json
composer.lock

An issue we've been patching in composer.json has been fixed in a recent release of this module.  (Wouldn't've noticed except it popped up while evaluating the core patches.)
1. Do this
1. Then that

VACMS-0000: Updates drupal/entity_clone to 1.0b6.

---

composer.json
composer.lock
docroot/modules/custom/va_gov_backend/src/Markdown.php
docroot/modules/custom/va_gov_build_trigger/src/Plugin/AdvancedQueue/JobType/WebBuildJobType.php

See #5204. 
Ran content release and looked at output.

VACMS-5204 Add logging for Broken links

---

composer.lock

See #5159  and #5160. 
As admin :
1. login and go here https://pr5233-fuyomo9jggwkxql2vctoagaxmifkkbnz.ci.cms.va.gov/graphql/explorer
2. Paste the following in to the explorer window on the left
```
query {
nodeById(id: "3756") {
title,
status,
type {
targetId
},
... on NodeVetCenter {
fieldCcVetCenterFaqs {
fetched
fetchedBundle
targetType
targetField
targetId
}
fieldCcNonTraditionalHours{
fetched
fetchedBundle
targetType
targetField
targetId
}
fieldCcVetCenterFeaturedCon{
fetched
fetchedBundle
targetType
targetField
targetId
}
}
}
}
```
3. Press the play button.

VACMS-5159 Update entity_field_fetch

---

.tugboat/config.yml
composer.json
composer.lock
docroot/modules/custom/va_gov_build_trigger/src/Controller/FrontEndBranchAutocompleteController.php
docroot/modules/custom/va_gov_build_trigger/src/WebBuildCommandBuilder.php
docroot/sites/default/settings/settings.dev.php
docroot/sites/default/settings/settings.prod.php
docroot/sites/default/settings/settings.staging.php
docroot/static
tests/phpunit/FrontendBuild/WebBuildCommandBuilderTest.php
web

See #5193. 
Automated tests and manual tests

VACMS-5193 Content Build Separation work

---

composer.json
composer.lock

This update resolves [an issue](https://www.drupal.org/project/path_redirect_import/issues/2995543) for which we are maintaining a Composer-level patch.
1. Do this
1. Then that

VACMS-0000: Updates drupal/path_redirect_import to 1.0.0-beta4.

---

composer.json
composer.lock

Supplants #5223 and #5224.  These two modules had associated patches maintained in composer.json but no longer need them.  Tests have passed for both individually.
1. Do this
1. Then that

VACMS-5224: Update drupal/metatag and drupal/inline_entity_form.

---

composer.json
composer.lock
docroot/modules/custom/va_gov_build_trigger/src/Plugin/AdvancedQueue/JobType/WebBuildJobType.php
docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Tugboat.php
docroot/modules/custom/va_gov_build_trigger/src/WebBuildBrokenLinkChecker.php
docroot/modules/custom/va_gov_build_trigger/src/WebBuildCommandBuilder.php
docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.services.yml
tests/phpunit/FrontendBuild/WebBuildCommandBuilderTest.php

Content build log clean up.
Build finished successfully
Broken links always showing first
1. Do this
1. Then that

Content build log clean up

---

tests/behat/drupal-spec-tool/menus.feature

Cures failing menu spec tool test introduced in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5293
Behat

VACMS-000: Update menu spec test.

---

composer.json
composer.lock

update content-build repo to use dev-master

---

config/sync/field.field.node.leadership_listing.field_leadership.yml

See #5334
Visual
As an administrator, go to `admin/structure/types/manage/leadership_listing/fields/node.leadership_listing.field_leadership` and verify that the `Create referenced entities if they don't already exist` checkbox is unchecked

VACMS-5334: Update staff profile config.

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module

See #5367.  
This function is deprecated and [replaced with a call to `$this->createFileUrl()`](https://www.drupal.org/node/3019830).
1. Do this
1. Then that

VACMS-5367: Replaces call to File::url() with File::createFileUrl().

---

config/sync/field.storage.taxonomy_term.field_vet_center_type_of_care.yml

See #4893
Visual
**1. Create a PR that adds the new key** - current pr
2. Release it to prod
3. Edit the content on prod
4. Create a PR that removes the old key
5. Release to prod

VACMS-4893: Fix spelling typo in word counseling.

---

config/sync/core.entity_form_display.node.vet_center_locations_list.default.yml

See #5045. 
Manual/visual
1. As admin go to https://pr5389-9ubprhr1zqauc8jlodsyuveld2vlkusy.ci.cms.va.gov/node/16478/edit 
2. Look ma, no Edit buttons! Just remove buttons (which are broken but #5390 will address).
3. This also removes the (already hidden) Published checkbox and the URL redirects, to keep standard with other content types. 

VACMS-5045: Remove edit links on Nearby Vet Center field.

---

composer.lock

https://www.drupal.org/sa-core-2021-003
1. Do this
1. Then that

VACMS-0000: Updates to Drupal 8.9.16

---

config/sync/linkit.linkit_profile.default.yml

See #5478
Visual
1. Go to any rich text editor
2. Add a link
3. Try to link to a VAMC System Policies Page
4. Confirm VAMC System Policies pages are listed in the Linkit tool

VACMS-5478: Update linkit config to include additional content type.

---

composer.lock
config/sync/node_link_report.settings.yml

closes #5442
As any editorial or admin user
1. visit https://pr5512-b3jrurc7jpoyeeybbbewzjnzrzmmkf5r.ci.cms.va.gov//northern-california-health-care/locations/sacramento-va-medical-center
2.  Edit this node https://pr5512-b3jrurc7jpoyeeybbbewzjnzrzmmkf5r.ci.cms.va.gov/node/20543/edit and make a link in the rich text editor to https://google.com with the link text `- - +` and save the node
1. Then that

VACMS-5442 Expand link error handling and 508.

---

config/sync/node.type.locations_listing.yml

closes #5517
As an admin
1. Go to https://pr5518-pgcvfazniava6lgr732usge9npdilblv.ci.cms.va.gov/node/20504/edit

VACMS-5517 Add saginaw menu to VAMC Locations page.

---

config/sync/views.view.health_care_service_names_and_descriptions.yml

See #4768. 
Manual
1. Go to https://pr5565-i6vykqtquk22bef0lbj4bp5eqqkksxak.ci.cms.va.gov/node/add/regional_health_care_service_des
2. You should see all services listed at https://pr5565-i6vykqtquk22bef0lbj4bp5eqqkksxak.ci.cms.va.gov/admin/structure/views/view/health_care_service_names_and_descriptions/edit/entity_reference_vamc_services
3. There should be no Parent dependency in the above view 

VACMS-4768: Remove parent dependency on health service entity references.

---

composer.lock

Closes #5536
As admin
1. Visit https://pr5588-1egqf9x8fyrdzabnxptihl15ozbhnqzq.ci.cms.va.gov/node/20709/edit

VACMS-5536 Bump node_link_report.

---

READMES/migrations-facility.md

[DOCS] VACMS-000 Add documentation for system service migrations.

---

composer.lock

closes #5613
As an admin
1. Go to https://cms-7abv2v8n3nqxwhoxpf61zzi7n2jswev1.ci.cms.va.gov/graphql_explorer
2. Paste in this query
```
fragment policiesPageFragment on NodeVamcSystemPoliciesPage {
title
status
changed
entityBundle
entityUrl {
path
}
fieldCcIntroText {
fetched
fetchedBundle
}
fieldCcTopOfPageContent {
fetched
fetchedBundle
}
fieldVamcVisitationPolicy {
processed
}
fieldVamcOtherPolicies {
processed
}
fieldCcGenVisitationPolicy {
fetched
fetchedBundle
}
fieldCcBottomOfPageContent {
fetched
fetchedBundle
}
fieldOffice {
entity {
... on NodeHealthCareRegionPage {
entityLabel
title
}
}
}
}
{
nodeQuery(limit: 500, filter: {conditions: [{field: "type", value: ["vamc_system_policies_page"]}]}) {
entities {
...policiesPageFragment
}
}
}
```
3. Press the Play button to run the …

VACMS-5613 Bump Entity Field Fetch.

---

config/sync/views.view.taxonomy_term.yml

See #5320. 
Behat
- As an administrator, go to `section/veterans-health-administration` & `section/vamc-facilities` & visually verify absence of vbo.

VACMS-5320: Remove vbo from section views.

---

config/sync/image_style_warmer.settings.yml

See #5694
Visual
- As an administrator, go to `admin/config/development/performance/image-style-warmer` and confirm the highlighted styles are checked.

VACMS-5694: Add style to image cache warmer.

---

config/sync/feature_toggle.features.yml

See #5671
Visual
- As an administrator, go to `admin/config/system/feature_toggle` and visually verify the presence of FEATURE_CHANGE_LEADERSHIP_LINK

VACMS-5671: Add leadership flag.

---

config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml

This should be held until the four sites go Full in the CMS and have their Teamsite sites shut down.
Ideally this should go to prod the day before the teamsite pages get shut down.   Otherwise the failure of Altoona may prevent all other status from being run.
1. ~VA Butler health care~
2. VA Wilkes-Barre health care 
3. VA Wilmington health care 
4. VA Altoona health care 
1. Do this
1. Then that

[Merge EOD June 28] VACMS-5634 Remove endpoints for 3 VAMC sites.

---

config/sync/views.view.taxonomy_term.yml

See #5761. 
Visual
Before 
After 
Go to /section/veterans-health-administration/vamc-facilities/va-black-hills-health-care
Check that it's sorted by Last updated

VACMS-5761: Fix sort order on Section listings.

---

config/sync/views.view.content.yml
config/sync/views.view.taxonomy_term.yml

VACMS-1875: Add last revision user to Updated column on content listings.

---

READMES/vamc-facilities.md

[DOCS] Fix link to facility migration goc.

---

docroot/modules/custom/va_gov_login/va_gov_login.module

Update deprecated entity manager service reference

---

config/sync/va_gov_menu_access.settings.yml

Closes #5884 
1. Do this
1. Then that

VACMS-5884 Add menu root to allowed menu access.

---

docroot/themes/custom/vagovadmin/templates/layout/page--help--search.html.twig

Closes #5947. 
Visual
As any user
1. Go to /help/search
2. "Remove sidebars, at least for now." should not appear at the bottom of the page. 

VACMS-5947: Remove code comment from KB search page.

---

SECURITY.md

[docs] Create SECURITY.md

---

docroot/modules/custom/va_gov_db/va_gov_db.install

Closes #5917
Visual
- Go to `/admin/content?title=&type=vet_center_locations_list&moderation_state=All&owner=All` and visually verify all items are draft, the creator is `CMS migrator` and the count is 300.

VACMS-5917: Create remaining vc location listings.

---

tests.yml

Missed a variable.
```
☁  va.gov-cms [VACMS-0000-Fix-exit-code-for-status-error] lando task --taskfile=./tests.yml va/tests/status-error
...
task: Failed to run task "va/tests/status-error": exit status 1
```
```
☁  va.gov-cms [VACMS-0000-Fix-exit-code-for-status-error] lando drush $DRUSH_ALIAS core-requirements --severity=2 
+------------------+----------+-------------+
| Title            | Severity | Summary     |
+------------------+----------+-------------+
| Database updates | Error    | Out of date |
|                  |          |             |
+------------------+----------+-------------+
```
[after updates]
```
☁  va.gov-cms [VACMS-0000-Fix-exit-code-for-status-error] lando task --taskfile=./tests.yml va/tests/status-error                         
[exit code 0]
☁  va.gov-cms …
```

Fixes exit code for va/tests/status-error.

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module

Make sure the logic to get the commit is correct

---

docroot/modules/custom/va_gov_backend/src/Controller/VaGovBackendController.php
phpstan-baseline.neon

Closes #_issueid_. 
1. Do this
1. Then that

Fix static analysis errors in VaGovBackendController

---

config/sync/node.type.event.yml
config/sync/node.type.event_listing.yml
config/sync/node.type.health_care_local_facility.yml
config/sync/node.type.health_care_region_detail_page.yml
config/sync/node.type.health_care_region_page.yml
config/sync/node.type.health_services_listing.yml
config/sync/node.type.leadership_listing.yml
config/sync/node.type.locations_listing.yml
config/sync/node.type.news_story.yml
config/sync/node.type.person_profile.yml
config/sync/node.type.press_release.yml
config/sync/node.type.press_releases_listing.yml
config/sync/node.type.publication_listing.yml
config/sync/node.type.story_listing.yml
config/sync/node.type.vamc_operating_status_and_alerts.yml
config/sync/node.type.vamc_system_policies_page.yml

Closes #5931
1. Do this
1. Then that

VACMS-5931 Add walla walla menu to content types.

---

docroot/modules/custom/va_gov_user/va_gov_user.module

Save the session before rediect in hook_user_login.
See https://www.drupal.org/node/3006306 and https://www.drupal.org/node/2023537
1. Do this
1. Then that

Save the session before redirecting in hook_user_login

---

config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml

4 more down, 112 left to go.
1. Do this
1. Then that

VACMS-000 Remove 4 status endpoints.

---

.lando.yml
.tugboat/config.yml

Fixes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5578.

VACMS-5578: tugboat memcache memory limit

---

READMES/development-best-practices.md

link to doc and specify integration type

---

tests/phpunit/Content/NodeLinkEnforcementFilterTest.php

VACMS-0000: Adds tests for NodeLinkEnforcementFilter.

---

config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml

Closes #6125 
1. Do this
1. Then that

VACMS-6125 Remove hudson valley endpoint.

---

docroot/sites/default/settings.php

Update http timeout to 60 seconds

---

.github/workflows/s3-backup-retention.yml

IDK if anyone else is having this problem.  This might fix it, though.  Or it might make things worse, IDK.
1. Do this
1. Then that

Run backup-retention action only on main repo.

---

config/sync/core.entity_form_display.node.health_care_local_facility.inline_entity_form.yml

Relates to #6159
Behat
- As an administrator go to `admin/structure/types/manage/health_care_local_facility/form-display/inline_entity_form` and visually verify `Details` matches screenshot

VACMS-6159: Update ief to use char count on vamc facility form.

---

config/sync/user.role.admnistrator_users.yml
tests/behat/drupal-spec-tool/access_control.feature

Closes to #6152 
Visual / behat
As an administrator, go to `admin/people/roles` and visually verify `User admin` does not appear, but `CMS account admin` does.

VACMS-6152: Update role label.

---

config/sync/core.entity_form_display.paragraph.featured_content.default.yml

Closes #6186
Visual / behat
- As an administrator, go to `/node/3813/edit` and add some characters to the second paragraph.
- On save, visually verify length errors are thrown on the wysiwyg.

VACMS-6186: Enforce wysiwyg char limit.

---

config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml

Finger Lakes went into full CMS mode on Aug 11th.   
https://dsva.slack.com/archives/CPQFCQKEH/p1628715649071900
I believe this was missed due to the original name being fingerlakes (no space) and the new one being finger-lakes.
1. Do this
1. Then that

VACMS-000 Removed fingerlakes endpoint.

---

config/sync/search_api.index.knowledge_base_search.yml

Relates to #6311. 
None so far, not totally sure how to reproduce except with a drush command. 
1. Do this
1. Then that

VACMS-6311: Index field_products not field_product.

---

.devcontainer/post-create.sh
READMES/codespaces.md

[docs] Update codespaces welcome message and README

---

composer.lock
docroot/sites/default/default.services.yml

Relates to #6407. 
https://www.drupal.org/project/drupal/releases/9.2.6
https://www.drupal.org/sa-core-2021-006
https://www.drupal.org/sa-core-2021-007
https://www.drupal.org/sa-core-2021-008
https://www.drupal.org/sa-core-2021-009
https://www.drupal.org/sa-core-2021-010
>No other fixes are included.
So less to test.  But we were on 9.2.4, so:
https://www.drupal.org/project/drupal/releases/9.2.5
- Issue #3228634 by Spokje, xjm, paulocs, tim.plunkett, Lendude: Move tests for integrations between QuickEdit and other modules into QuickEdit so that it can more easily be moved into contrib
- Revert "Issue #3228634 by Spokje, xjm, paulocs, tim.plunkett, Lendude: Move tests for integrations between QuickEdit and other modules into QuickEdit so that it can more easily be moved into contrib"
- …

VACMS-6470: Updates Drupal to 9.2.6

---

config/sync/core.entity_form_display.node.vet_center.default.yml
config/sync/core.entity_view_display.node.vet_center.default.yml
config/sync/core.entity_view_display.node.vet_center.external_content.yml
config/sync/core.entity_view_display.node.vet_center.ief_table.yml
config/sync/core.entity_view_display.node.vet_center.teaser.yml
config/sync/field.field.node.vet_center.field_official_name.yml
config/sync/field.storage.node.field_official_name.yml
tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature

VACMS-6448: Add new name field to vc.

---

config/sync/core.entity_form_display.node.vamc_system_billing_insurance.default.yml
config/sync/core.entity_form_display.node.vamc_system_medical_records_offi.default.yml
config/sync/core.entity_form_display.node.vamc_system_register_for_care.default.yml
config/sync/core.entity_view_display.node.vamc_system_billing_insurance.default.yml
config/sync/core.entity_view_display.node.vamc_system_medical_records_offi.default.yml
config/sync/core.entity_view_display.node.vamc_system_register_for_care.default.yml
config/sync/field.field.node.vamc_system_billing_insurance.field_cc_bottom_of_page_content.yml
config/sync/field.field.node.vamc_system_billing_insurance.field_cc_related_links.yml
config/sync/field.field.node.vamc_system_billing_insurance.field_cc_top_of_page_content.yml
config/sync/field.field.node.vamc_system_medical_records_offi.field_cc_faqs.yml
config/sync/field.field.node.vamc_system_medical_records_offi.field_cc_get_records_in_person.yml
config/sync/field.field.node.vamc_system_medical_records_offi.field_cc_get_records_mail_or_fax.yml
config/sync/field.field.node.vamc_system_medical_records_offi.field_cc_how_we_share_records.yml
config/sync/field.field.node.vamc_system_medical_records_offi.field_cc_react_widget.yml
config/sync/field.field.node.vamc_system_medical_records_offi.field_cc_related_links.yml
config/sync/field.field.node.vamc_system_medical_records_offi.field_cc_top_of_page_content.yml
config/sync/field.field.node.vamc_system_register_for_care.field_cc_bottom_of_page_content.yml
config/sync/field.field.node.vamc_system_register_for_care.field_cc_related_links.yml
config/sync/field.field.node.vamc_system_register_for_care.field_cc_top_of_page_content.yml
config/sync/field.storage.node.field_cc_faqs.yml
config/sync/field.storage.node.field_cc_get_records_in_person.yml
config/sync/field.storage.node.field_cc_get_records_mail_or_fax.yml
config/sync/field.storage.node.field_cc_how_we_share_records.yml
config/sync/field.storage.node.field_cc_react_widget.yml
config/sync/field.storage.node.field_cc_related_links.yml
tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature

VACMS-6396: Add EFF fields to 3 top task pages.

---

composer.json
composer.lock

Update content-build version v0.0.1337 => v0.0.1372

---

composer.lock

https://www.drupal.org/project/linkit/releases/6.0.0-beta3
https://www.drupal.org/sa-contrib-2021-042
This should be merged as soon as all tests pass.
1. Do this
1. Then that

VACMS-0000: Updates Linkit (Security Update)

---

composer.json
composer.lock
config/sync/core.extension.yml

Closes #6561 
At the moment this is just a test environment so the FE team can see if it does what they need.
As admin
1. go to https://pr6568-evjtc4b1rljtu67clslvtg444yrbfygw.ci.cms.va.govadmin/modules
2. go to https://pr6568-evjtc4b1rljtu67clslvtg444yrbfygw.ci.cms.va.gov/graphql/explorer
3. execute the following query
```
{
menuByName(name: "va-alexandria-health-care") {
description
name
links {
...MenuItem
links {
...MenuItem
links {
...MenuItem
}
}
}
}
}
fragment MenuItem on MenuLink {
expanded
description
label
url {
path
}
entity {
... on MenuLinkContent {
linkedEntity(language_fallback: true, bypass_access_check: true) {
... on Node {
entityPublished
moderationState
}
}
}
}
}
```

VACMS-6561 Add and enable drupal graphql_menu module.

---

READMES/migrations-facility.md

Updated facility migrations documentation to include details for the required settings.local.php file.

[docs] Facility migrations documentation to include settings.local.php

---

config/sync/core.entity_form_display.taxonomy_term.health_care_service_taxonomy.default.yml
config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml
config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vet_center_required_servic.yml
config/sync/field.storage.taxonomy_term.field_vet_center_required_servic.yml
tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature

VACMS-6638: Add new bool to service vocab fields.

---

tests/phpunit/Deploy/Plugins/HealthCheckTest.php

VACMS-0000: Fixes health check test.

---

tests/phpunit/Deploy/Plugins/HealthCheckTest.php

Relates to #6201.
1. Do this
1. Then that

VACMS-0000 Fix Health Check Test by Adding Test for Datadog

---

config/sync/field.storage.taxonomy_term.field_service_type_of_care.yml

Relates to #6341
**Quick config update for merge**
Behat

VACMS-6341: Update service type of care.

---

docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRDGHA.php
docroot/modules/custom/va_gov_consumers/src/Git/GithubAdapter.php

https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6740
1. Do this
1. Then that

Followups from debugging on staging

---

config/sync/field.field.node.regional_health_care_service_des.field_body.yml

Relates to #6536
Visual / behat

VACMS-6536: Update VAMC health service body help text.

---

READMES/vamc-facilities.md

Relates to #4595 but does not close it.
1. Do this
1. Then that

[DOCS] Add GovDelivery documentation.

---

scripts/tests/cypress.sh

Relates to @msbtterswrth 's continuing troubles..
1. Do this
1. Then that

VACMS-0000: Installs Cypress before running tests.

---

config/sync/field.field.node.event.field_facility_location.yml
config/sync/views.view.content_entity_reference_source.yml
tests/behat/drupal-spec-tool/views.feature

closes #6938
- Configuration changes:
- Created "Entity Reference: Systems" display in "Content Entity Reference Source" view and configured it.
- Assigned the new "Entity Reference: Systems" view display to the "Event" content type "field_facility_location" field.
- Updated views.feature behat test and added the new display for "Content Entity Reference Source" view.
As an editor
1. Go to `/node/add/event` 
3. visit an existing event and set a facility location.  Save the node.
-[x]  Re-edit the node and validate that the value saved.

VACMS-6938: Clarify duplicate place names listed on facility location drop-down menu when creating VA Events

---

config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml

Relates to #6958 
As a github user

VACMS-6958C: remove endpoints for VAMCs going to prod week of Nov 15 2021

---

config/sync/feature_toggle.features.yml

- Added new FEATURE_RECURRING_EVENTS flag in features.
closes #7020 
1. [x] Verify and confirm that the new `FEATURE_RECURRING_EVENTS` flag has been added to `/admin/config/system/feature_toggle`

VACMS-7020: Create recurring events feature flag

---

docroot/sites/default/settings/settings.dev.php
docroot/sites/default/settings/settings.prod.php
docroot/sites/default/settings/settings.staging.php

This changes the front end build type to use jenkins.

Change the Drupal triggered content release to use Jenkins

---

README.md
READMES/broken-links.md

[DOCS] Add broken link documentation.

---

docroot/sites/default/settings/settings.dev.php
docroot/sites/default/settings/settings.prod.php
docroot/sites/default/settings/settings.staging.php

Rename Github Actions.
Previous PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7061

Change the manual content release to use GitHub Actions

---

config/sync/views.view.content.yml
config/sync/views.view.detail_page_url_audit_and_bulk_udpate.yml

closes #7154
As admin
1. Visit https://pr7155-qajgjssxdhvojjnkgk8kd71dnlgpsijt.ci.cms.va.gov/admin/content/audit   
2. Filter section to VISN 1.
3. Filter section to "VA bedford health care"
4. Scroll to the bottom of the page and click the  orange "CSV button"
5. The batch should run and then return this status message 
6.  Clicking that link may not work.  If not copy and past the url for that link into a new tab.  It should kick off the download
7. Save the file and import it into a spreadsheet.
1  Visit https://pr7155-qajgjssxdhvojjnkgk8kd71dnlgpsijt.ci.cms.va.gov/admin/content/audit/vamc-detail-pages

VACMS-7154 Expand url audit view.

---

README.md
READMES/cms-editor-notifications.md

[docs] Add documentation for user notifications system.

---

config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml

Vacms 7246 remove final 4 facility status endpoints

---

config/sync/core.entity_form_display.node.health_care_local_facility.default.yml

VACMS-7230: Fix faulty facility help link.

---

config/sync/menu_breadcrumb.settings.yml
config/sync/node.type.event.yml
config/sync/node.type.event_listing.yml
config/sync/node.type.health_care_local_facility.yml
config/sync/node.type.health_care_region_detail_page.yml
config/sync/node.type.health_care_region_page.yml
config/sync/node.type.health_services_listing.yml
config/sync/node.type.leadership_listing.yml
config/sync/node.type.locations_listing.yml
config/sync/node.type.news_story.yml
config/sync/node.type.person_profile.yml
config/sync/node.type.press_release.yml
config/sync/node.type.press_releases_listing.yml
config/sync/node.type.publication_listing.yml
config/sync/node.type.story_listing.yml
config/sync/node.type.vamc_operating_status_and_alerts.yml
config/sync/node.type.vamc_system_billing_insurance.yml
config/sync/node.type.vamc_system_medical_records_offi.yml
config/sync/node.type.vamc_system_policies_page.yml
config/sync/node.type.vamc_system_register_for_care.yml
config/sync/system.menu.lovell-federal-health-care.yml
tests/behat/drupal-spec-tool/menus.feature

- Created Lovell Federal health care (lovell-federal-health-care) menu in CMS.
- Enabled Lovell Federal health care menu in menu breadcrumbs config through the UI.
- Enabled the "Lovell Federal health care" menu in these content types: Event, Events List, Health Services List, Leadership List, News Release, News Releases List, Publication Listing Page, Staff Profile, Stories List, Story, VAMC Detail Page, VAMC Facility, VAMC System Billing and Insurance, VAMC System Locations List, VAMC System Medical Records Office, VAMC System Operating Status, VAMC System Policies Page, VAMC System Register for Care.
- Added Lovell Federal health care menu to workbench menu access referencing "VA Lovell federal health care".
relates to #7163  but does not close
Passes all tests. …

VACMS-7163: Add new lovell menu.

---

.vscode/launch.json

I found these adjustments necessary for ddev's xdebug support to communicate with vscode. Recommendations per ddev docs: 
https://ddev.readthedocs.io/en/stable/users/step-debugging/#vscode
https://ddev.readthedocs.io/en/stable/users/snippets/launch.json

VACMS-000: updated vscode config for ddev.

---

READMES/getting-started.md
READMES/workflow.md

[DOCS] Add config steps to git setup.

---

composer.json
composer.lock

Remove workflow_assigments

---

composer.json
composer.lock

Replaces https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7395

Update migreate_plus and remove patch

---

README.md
READMES/cms-content-workflow.md

[docs] Add documentation of the preview button.

---

config/sync/core.entity_view_display.taxonomy_term.administration.default.yml
config/sync/node_link_report.settings.yml
docroot/themes/custom/vagovadmin/templates/taxonomy-term.html.twig
docroot/themes/custom/vagovclaro/templates/layout/taxonomy-term.html.twig

Closes #7162 .
Viewed section dashboard and confirmed only one title was visible. Viewed section facilities dashboard and confirmed no products appeared under the view table.
Only one title appears:
No products appear:
As cms editor I can
1. Visit a section (`/section/vha/vamc-facilities/va-bedford-health-care`) and see the title (section name) appears only once.
2. Visit a facility section )`/section/vamc-facilities`) and see that there are no products listed at the bottom.

VACMS-7162: Update section dashboard layout to remove extra titles and products

---

package-lock.json
package.json

To address [this security vulnerability](https://github.com/department-of-veterans-affairs/va.gov-cms/security/dependabot/package-lock.json/json-schema/open).
1. Do this
2. Then that

VACMS-0000: Updates json-schema to 0.4.0

---

config/sync/system.menu.va-north-florida-health-care.yml

Relates to #6920
Visual testing
This change captures the menu label in config to match the changes manually applied for ticket 6920

VACMS-6920: update label for north florida/south georgia menu

---

tests/behat/drupal-spec-tool/menus.feature

Update Menu label for VA North Florida/South Georgia health care
Original PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7613

Update Menu label for VA North Florida/South Georgia health care

---

config/sync/node.type.banner.yml
config/sync/node.type.campaign_landing_page.yml
config/sync/node.type.centralized_content.yml
config/sync/node.type.faq_multiple_q_a.yml
config/sync/node.type.full_width_banner_alert.yml
config/sync/node.type.health_care_local_health_service.yml
config/sync/node.type.outreach_asset.yml
config/sync/node.type.press_release.yml
config/sync/node.type.promo_banner.yml
config/sync/node.type.step_by_step.yml
config/sync/node.type.va_form.yml
config/sync/node.type.vamc_operating_status_and_alerts.yml
config/sync/node.type.vamc_system_billing_insurance.yml
config/sync/node.type.vamc_system_medical_records_offi.yml
config/sync/node.type.vamc_system_policies_page.yml
config/sync/node.type.vamc_system_register_for_care.yml
config/sync/node.type.vet_center_cap.yml
config/sync/node.type.vet_center_facility_health_servi.yml
config/sync/node.type.vet_center_locations_list.yml
config/sync/node.type.vet_center_mobile_vet_center.yml
config/sync/node.type.vet_center_outstation.yml

~Relates to~ #7578.
Closes #7578
Checked that drupal preview was removed from the following content types: 
- banner
- clp
- centralized content
- faq
- full width banner
- health care local health service
- outreach asset
- press release
- promo banner
- step by step
- va form
- vamc operated status
- vamc system billing insurance
- vamc medical records
- vacms system policies page
- vamc register for care
- vet center cap
- vet center facility health service
- vet center locations list
- vet center mobile vet center
- vet center outstation
As cms editor
1. I can edit any node type (/node/17664/edit) 
2. and see there is no longer a drupal preview button 

VACMS-7578: Remove preview option from all content types.

---

config/sync/feature_toggle.features.yml

Relates to #7658 .
Viewed feature toggle list and verified new feature toggle was there.
As a cms admin
1. visit `/admin/config/system/feature_toggle`

VACMS-7658: Add feature flag for care we provide.

---

config/sync/field.storage.node.field_vamc_ehr_system.yml

VACMS-7809: Update values in EHR system field to support Cerner in Staging.

---

composer.json

To stop breaking things locally

Add in phpcode sniffer allowed plugin

---

READMES/migrations-facility.md

Relates to #6522.
1. Do this
2. Then that

[docs] VACMS-6522 Update facility migration readme for nightly removal scan.

---

config/sync/core.entity_form_display.node.vamc_system_billing_insurance.default.yml
config/sync/core.entity_form_display.node.vamc_system_medical_records_offi.default.yml
config/sync/core.entity_form_display.node.vamc_system_policies_page.default.yml
config/sync/core.entity_form_display.node.vamc_system_register_for_care.default.yml
config/sync/core.entity_view_display.node.vamc_system_billing_insurance.default.yml
config/sync/core.entity_view_display.node.vamc_system_medical_records_offi.default.yml
config/sync/core.entity_view_display.node.vamc_system_policies_page.default.yml
config/sync/core.entity_view_display.node.vamc_system_register_for_care.default.yml

VACMS-7957: Update top task tooltip text.

---

config/sync/views.view.facility_services.yml
tests/behat/drupal-spec-tool/views.feature

Closes #7500
Visual testing
As an authenticated user

VACMS-7500: config - add facility services audit view

---

READMES/workflow.md

[docs] Add module removal process.

---

docroot/modules/custom/va_gov_events/js/recurringDates.es6.js
docroot/modules/custom/va_gov_events/js/recurringDates.js
docroot/themes/custom/vagovclaro/assets/scss/components/_recurring_events.scss

VACMS-7941: Adjust recur box theme in claro.

---

config/sync/search_api.index.knowledge_base_search.yml

Relates to #7012 .
**Improvements from changing weighting and removing html preprocesses on title field**
1. log in help is now first and many irrelevant results have been removed.
2. relevant pages are now at the top of the list 
3. relevant pages are now at the top of the list, this can further be improved by adding another sort to the view (title ASC).
**Improvements from content updates**
4. expected article did not contain the keyword 'pdf', so that was added to the introduction.
5. the keyword 'broken link' was added to the title which brought this result to the top
As CMS editor I want to
1. find articles about log in help
2. search for “system health service” and find the relevant page about how to create a system health service
3. work on the 5 required VAMC trainings and search …

VACMS-7012: KB SAPI improvements.

---

composer.json

Modify `va:web:build` script to handle coming changes to the content-build. One extra step checks for a content-build defaults file and sets it up if it exists, then performs the build normally.
Relates to #7965
1. Do this
2. Then that

VACMS-0000: Modify va:web:build Script

---

config/sync/filter.format.rich_text.yml

- Disabled Entity Embed module in Rich Text editor.
Relates to #7995 but does not close.
**Disabled Entity Embed in Rich Text editor:**
**No Entity Embed related HTML in "Allowed HTML tags":**
1. Go to `/admin/config/content/formats` and:

VACMS-7995: Disable Entity Embed module in Rich Text editor

---

.ddev/commands/web/behat

Closes #8151
As user dev
1. Go to your terminal
2.  `ddev behat --tags=views`

VACMS-8151 Make ddev run behat.

---

.github/ISSUE_TEMPLATE/runbook-facility-closed.md
.github/ISSUE_TEMPLATE/runbook-facility-name-change.md
.github/ISSUE_TEMPLATE/runbook-facility-new.md
.github/ISSUE_TEMPLATE/runbook-vamc-system-name-change.md

[docs] Runbooks for facility flags.

---

config/sync/views.view.user_admin_people.yml
tests/behat/drupal-spec-tool/views.feature

- Created the new CSV display and configure it:
- Removed "section" filter
- Adjusted permission to be by role authenticated user
- Updated the CSV display path to /admin/people/vacms-all-users-export.csv
- Added the footer to the people main display (which later remove because the CSV icon was showing twice)
- Updated the Drupal spec tool and then updated the behat test.
closes #8048 
As any authenticated user, content creator, content editor, content reviewer, content publisher, content admin and administrator

VACMS-8048: Allow authenticated users to export CSV of users

---

composer.lock

https://www.drupal.org/project/drupal/releases/9.3.8

VACMS-0000: Updates Drupal to 9.3.8.

---

config/sync/views.view.content.yml

- Removed access to the "Content audit tools" view to the "Content editor", "Content reviewer", "Content publisher" and "Redirect admin" roles.
closes #8268 
1. Go to `/admin/structure/views/view/content/edit/content_audit_page`
2. Then as a "Content admin", "CMS account admin" and "Administrator" roles
3. Then as any other roles (not "Content admin", "CMS account admin" and/or "Administrator") 

VACMS-8268: Non-content admins should not be able to access Content Audit Tools view

---

docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php

Closes #8495
As samuel.house2@va.gov , 
- Go to https://pr8503-3yr77xidr7cbiyrlqdpebgbcxqnrgkvr.ci.cms.va.gov/node/add/event
- Go to https://pr8503-3yr77xidr7cbiyrlqdpebgbcxqnrgkvr.ci.cms.va.gov/node/42066/edit

VACMS-8495 Resolve failing file upload from office_hours logic.

---

config/sync/user.role.authenticated.yml
tests/phpunit/Security/RolesPermissionsTest.php

VACMS-8495 Adjust dropzone perms

---

config/sync/node.type.checklist.yml
config/sync/node.type.faq_multiple_q_a.yml
config/sync/node.type.media_list_images.yml
config/sync/node.type.media_list_videos.yml
config/sync/node.type.q_a.yml
config/sync/node.type.step_by_step.yml
config/sync/node.type.support_resources_detail_page.yml
tests/behat/drupal-spec-tool/content_model_bundles.feature
tests/behat/drupal-spec-tool/content_model_lc_content_type_fields.feature

- Updated "Resources and support Detail Page" content type description.
- Updated "Checklist" content type description.
- Updated "FAQ page" content type name and description.
- Updated "Image list" content type name and description.
- Updated "Video list" content type name and description.
- Updated "Q&A - single" content type name and description.
- Updated "Step-by-Step" content type description.
- Updated content_model_bundles.feature.
- Updated content_model_lc_content_type_fields.feature.
closes #8569 
Visual and Behat
1. Go to `/admin/content-models/content` to

VACMS-8569: Update various content types name and description

---

.storybook/403-error-document.j2.html
.tugboat/config.yml

Follow up to https://github.com/department-of-veterans-affairs/va.gov-cms/pull/8482 to get it working. 
Tested command on a clone and it works. 
1. Do this
2. Then 

Fix Storybook Tugboat Alias

---

.ddev/docker-compose.m1.yaml

Needed by M1 macs to work; ignored by non-M1 macs.

Add file for m1 macs.

---

simplesamlphp-config-metadata/config/config.php

When SAML errors are encountered on the Drupal login page when using a PIV, an error report page appears. It directs users on the page to submit a response describing their actions that led up to the error.  When pressing submit the error page is sending e-mails to a locked VA org distribution group that is not active `VACMSsupport@va.gov`. Update this to the currently monitored `support@va-gov.atlassian.net`
1. Do this
2. Then

VACMS-0000: Update SAML Login Error Report Page Email Address 

---

.github/workflows/phpcs.yml
.github/workflows/stylelint-modules.yml
.github/workflows/stylelint-themes.yml

Closes #8741.
1. Do this
2. Then

VACMS-8741: Adds Git "safe directory" for project to allow GitHub Actions to run.

---

composer.json
composer.lock

Bump content build to 0.0.2990

---

composer.lock

Closes #8790.
1. Do this
2. Then

VACMS-8790: Upgrades Drupal to 9.3.11.

---

composer.lock

Closes #8823.
1. Do this
2. Then

VACMS-8823: Updates Drupal to 9.3.12

---

.github/dependabot.yml

Dependabot doesn't do the necessary updb and config operations, so we end up closing all their PRs anyway.
1. Do this
2. Then

VACMS-0000: Prevents Dependabot from attempting Drupal core updates.

---

tests/behavioral/cypress/integration/common/i_create_a_node.js
tests/behavioral/cypress/integration/common/i_should_see.js
tests/behavioral/cypress/integration/file_upload.feature

Closes #8519.
1. Do this
2. Then

VACMS-8519: Adds test coverage for file upload.

---

config/sync/views.view.facility_services.yml
tests/behat/drupal-spec-tool/views.feature

closes #8808
This View is only temporary.  (see [issue for details](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8808#issuecomment-1104213211).)
As an admin
1. Visit https://pr8831-7yer0heuengchbrhca5uzcyzhlb0cfmv.ci.cms.va.gov/admin/content/facilities/urls
- api locator id
- a va.gov based url to the related facility.

VCMS-8808 Add vha  facility url export.

---

composer.json
composer.lock

This is just an ordinary bump of content-build 0.0.2993 but needed the removal of @cweagans patch, since the patch is part of 0.0.2993

Bump content-build and remove patch.

---

.ddev/commands/web/phpcbf
.ddev/commands/web/phpcs
.ddev/config.yaml
.ddev/homeadditions/bashrc.d/certs.sh
.ddev/homeadditions/bashrc.d/path.sh
.ddev/mutagen/mutagen.yml
.vscode/launch.json

Misc changes to ddev:
* Updates .ddev/config.yaml with the most recent version of ddev
* Update xdebug port
* Make sure that our project `bin/` dir comes first in `$PATH`
* Update mutagen.yml with the latest ddev
* Add phpcbf and phpcs helper commands to ddev
1. Do this
2. Then

Misc ddev updates

---

composer.json
config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
config/sync/core.entity_view_display.taxonomy_term.facility_supplemental_status.name_with_term.yml
config/sync/core.entity_view_mode.taxonomy_term.name_with_term.yml
config/sync/field.field.node.health_care_local_facility.field_operating_status_facility.yml
config/sync/field.field.node.health_care_local_facility.field_operating_status_more_info.yml
config/sync/field.field.node.health_care_local_facility.field_supplemental_status.yml
config/sync/views.view.health_care_service_names_and_descriptions.yml
docroot/themes/custom/vagovclaro/templates/taxonomy/taxonomy-term--name-with-term.html.twig

Closes #9043 
1. Do this
2. Then

VACMS-9043 update facility supplemental status

---

config/sync/views.view.facility_services.yml

manual, automatic
1. Do this
2. Then

VACMS-000: Fix facility status export duplication.

---

composer.json
config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
config/sync/core.entity_form_display.node.health_care_local_facility.inline_entity_form.yml
config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
config/sync/core.entity_view_display.node.health_care_local_facility.external_content.yml
config/sync/core.entity_view_display.node.health_care_local_facility.ief_table.yml
config/sync/core.entity_view_display.node.health_care_local_facility.teaser.yml
config/sync/core.entity_view_display.taxonomy_term.facility_supplemental_status.name_with_term.yml
config/sync/core.entity_view_mode.taxonomy_term.name_with_term.yml
config/sync/field.field.node.health_care_local_facility.field_operating_status_facility.yml
config/sync/field.field.node.health_care_local_facility.field_operating_status_more_info.yml
config/sync/field.field.node.health_care_local_facility.field_supplemental_status.yml
config/sync/field.storage.node.field_supplemental_status.yml
config/sync/views.view.facility_services.yml
config/sync/views.view.health_care_service_names_and_descriptions.yml
docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php
docroot/themes/custom/vagovclaro/templates/taxonomy/taxonomy-term--name-with-term.html.twig
tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
tests/behat/drupal-spec-tool/views.feature
tests/phpunit/Content/FacilityStatusQueueTest.php

Full QA performed in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9028 already.  This is just the one to merge so we don't lose that environment.

Integration covid status not for human QA

---

docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.info.yml
docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.routing.yml

Relates to #9008
1. Do this
2. Then

Enable basic auth for placeholder routes

---

docroot/modules/custom/va_gov_migrate/src/EventSubscriber/MessageLogger.php

DO NOT MERGE UNTIL DEFAULT BRANCH OF VAGOV-CONTENT IS MAIN
1. Do this
2. Then

update reference to default branch of vagov-content

---

config/sync/field.storage.node.field_hours_for_copay_inquiries_.yml

closes #9326
Visual / behat
- `admin/structure/types/manage/vamc_system_billing_insurance/fields/node.vamc_system_billing_insurance.field_hours_for_copay_inquiries_/storage`
- `admin/structure/types/manage/vet_center_outstation/fields/node.vet_center_outstation.field_office_hours/storage`
- `admin/structure/types/manage/vet_center_mobile_vet_center/fields/node.vet_center_mobile_vet_center.field_office_hours/storage`
- `admin/structure/types/manage/vet_center/fields/node.vet_center.field_office_hours/storage`
- `admin/structure/types/manage/vet_center_cap/fields/node.vet_center_cap.field_office_hours/storage`
- `admin/structure/types/manage/health_care_local_facility/fields/node.health_care_local_facility.field_office_hours/storage`
- …

VACMS-9326: Change billing and insurance hours field from select to html5 picker.

---

config/sync/views.view.media.yml

Closes #9375 
manual, automatic
[images-export(5).csv](https://github.com/department-of-veterans-affairs/va.gov-cms/files/8864437/images-export.5.csv)
As CMS user
1. View the Images audit page (`/admin/content/media/images`)
2. Then click the download CSV link

VACMS-9375: Update media export to include alt and image link.

---

READMES/interfaces.md
READMES/migrations-facility.md

Just adding some additional details related to migrations to connect them up with the appropriate runbooks.
1. Do this
2. Then

DOCS Update facility migration documentation.

---

config/sync/core.entity_view_display.message.va_facility_new_facility.default.yml
config/sync/core.entity_view_display.message.va_facility_new_facility.mail_body.yml
config/sync/core.entity_view_display.message.va_facility_new_facility.mail_subject.yml
config/sync/field.field.message.va_facility_new_facility.field_target_entity.yml
config/sync/field.field.message.va_facility_new_facility.field_target_node_title.yml
config/sync/message.template.va_facility_new_facility.yml
docroot/modules/custom/va_gov_backend/va_gov_backend.module
docroot/modules/custom/va_gov_notifications/src/Service/NotificationsManager.php
docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
tests/behat/Drupal/FeatureContext.php

This PR restores the original code of https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9345   
That was reverted due to an odd situation where tests running individually were passing fine, but running them in parallel was causing a theme error discussed in slack [here](https://dsva.slack.com/archives/CT4GZBM8F/p1654630565447059) and [here](https://dsva.slack.com/archives/CT4GZBM8F/p1654885840468949) 
As admin:
1. Go here https://pr9412-ttzpvof2dv07rv7no5htef6mx9yzuwcb.ci.cms.va.gov/user/4050/edit and  add bogus email adress to the user help@desk.com
2. Save the user  (this is …

VACMS-9097 Add new facility notification.

---

.devcontainer/devcontainer.json
.devcontainer/on-create.sh
.devcontainer/post-start.sh
.devcontainer/update-content.sh

devcontainer updates

---

docroot/modules/custom/va_gov_build_trigger/src/Controller/ContentReleaseNotificationController.php
tasks-periodic.yml

Queues need to be processed + do not fail content build if out of sync

---

READMES/workflow.md

Updates to documentation
N/A
N/A

[DOCS] Drupal spec tool edits

---

composer.json
composer.lock
tests/cypress/integration/behavioral/content_release.feature

Closes #9574.
1. Do this
2. Then

VACMS-9574: Update Drupal to 9.3.17. [SECURITY]

---

composer.json
composer.lock

This is just a version bump and removes the patch for [this issue](https://www.drupal.org/project/entity_browser/issues/3123876).

Bump entity_browser and remove patch.

---

config/sync/views.view.facility_services.yml
tests/behat/drupal-spec-tool/views.feature

Closes #9615 
Manual testing
As  a developer with the admin role
1. Navigate to https://pr9660-f7oae9lmjnt6qplu811frhcgaohoggze.ci.cms.va.gov/admin/content/facilities/addresses
2. Then
3. Then 

VACMS-9615 Addresses and addresses.csv in audit view

---

composer.json
composer.lock

~Relates to~ Closes #9700
Before:
After:
Steps to reproduce the behavior:
Go to /node/add/event
Create a recurring event starting at 9am, repeating weekly, for 1 year, and set time zone to Phoenix.
See that your event starts at 9am when DST is active in Eastern time zone
1. Modify your user profile and set your timezone to 'New York' if not already set in /user/[uid]/edit.
2. Go to /node/add/event and fill out a new test event.
3. Ensure the start date is November 5, 2022 @ 9:00AM
4. Set the timezone to Phoenix
5. Set daily recurrences until November 7, 2022.
6. Save the node
7. Then
8. Edit your user profile and change your timezone to 'Los Angeles'
9. Edit the node created earlier, make no changes, and re-save
10. Then

VACMS-9700: Patch smart_date for recurrence bug identified in d.o issue #3294350

---

config/sync/views.view.rich_text_field_audit.yml
tests/behat/drupal-spec-tool/views.feature

Relates to #9696. 
manual, behat
As CMS admin
1. Visit the new phone audit `admin/content/audit/phone-numbers`

VACMS-9696: Create phone number audit.

---

composer.lock

VACMS-9872: core 9.3.19 update.

---

composer.json

Closes #10066 
Site builds.
As an admin visit https://pr10069-yyp3rgsqamzyjmn9vjbvooayjl0ygvnm.ci.cms.va.gov/node/add/banner

VACMS-10066 Swap floating patch for file patch.

---

composer.json
config/sync/geocoder.geocoder_provider.mapbox.yml

Closes #10055
https://www.drupal.org/project/geocoder/issues/3301383
Manually
As an admin
1. Make sure the build is successful
2. Then visit /admin/config/system/geocoder/geocoder-provider/manage/mapbox
3. Then change the "Geocoding mode" to "mapbox.places-permanent"

Adds endpoint config patch from Geocoder module

---

config/sync/prometheus_exporter.settings.yml
docroot/modules/custom/va_gov_build_trigger/src/Plugin/MetricsCollector/BaseContentReleaseMetricsCollector.php
docroot/modules/custom/va_gov_build_trigger/src/Plugin/MetricsCollector/TimeSinceLastContentRelease.php
tests/phpunit/FrontendBuild/BuildMetricsTest.php

Relates to #10019.
1. Do this
2. Then

Add business hours calculation to all duration metrics

---

composer.json
composer.lock
config/sync/core.extension.yml

Add jsonapi_menu_items and patch.

---

docroot/modules/custom/va_gov_graphql/assets/explorer/package-lock.json

Incidental work done as part of #10249.  Upgraded two packages with security vulnerabilities.

VACMS-10249: Upgrade graphql explorer packages (undici and dset).

---

config/sync/system.site.yml

VACMS-10247: Update System email address.

---

READMES/workflow.md

1. Scan for readability - does it makes sense
2. Scan for typos

[DOCS] Add contribution info to workflow.

---

composer.json
composer.lock
config/sync/entityqueue.entity_queue.staged_content.yml

Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10374
1. Verify "staged_content " entityqueue exists at admin/structure/entityqueue

VACMS-10374: Add staged_content entityqueue

---

config/sync/views.view.facility_services.yml

VACMS-10277: enhance facility services reports with additional fields

---

README.md
READMES/facilities-lovell.md
docroot/modules/custom/va_gov_lovell/va_gov_lovell.module

VACMS-10165: Add lovell documentation.

---

composer.json
composer.lock

Reverts department-of-veterans-affairs/va.gov-cms#10362

Revert "Bump drupal/smart_date from 3.5.1 to 3.6.0"

---

config/sync/feature_toggle.features.yml
config/sync/node_link_report.settings.yml

Relates to #10342
Syncing these up to mimic prod.
There is nothing to test as these are synching changes that were already applied to prod.

VACMS-10342 Remove old feature flags.

---

.github/workflows/composer-validate.yml

Closes #10502.
If this and current tests pass, this should be safe to merge.

VACMS-10502: Adds `composer validate` GitHub Action.

---

composer.json
composer.lock
tests/behat/behat.yml

Closes #9992.
Ran `ddev composer why-not php 8.1.0`
Result was `There is no installed package depending on "php" in versions not matching 8.1.0`.
Verify code changes.

VACMS-9992: removed behat-seo-contexts package, updated password_strength module

---

composer.json
composer.lock

Closes #10000.
Changes are almost all cosmetic.  I'll annotate.

VACMS-10000: Audit composer patches.

---

.tugboat/config.yml

VACMS-10890: Fix issues with GD support for JPEG and FreeType on Tugboat.

---

.github/actions/post-checkout/action.yml
.github/workflows/continuous_integration.yml
phpunit.xml
tests/phpunit/Content/PreventAbsoluteCmsLinksValidatorTest.php
tests/phpunit/Content/PreventLocalFileLinksValidatorTest.php

Closes #10555.
More work will be done in further issues.
If the PHPUnit GHA task passes, this is safe to merge.  It should have no risk.

VACMS-10555: Add a code coverage report to PHPUnit GitHub Action.

---

composer.lock
docroot/sites/default/default.services.yml

Closes #10950.
Tested on local ddev.

Drupal Core Critical update SA-CORE-2022-016 

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module

Closes #11041
Manually
As an admin, go to https://pr11046-spoo1g2htfgcgn3bkx7wcio1tyhqr35t.ci.cms.va.gov/node/43991/edit
1. Edit the Campaign Landing Page
2. [x] Validate that the page renders (and does not present a "white screen of death")
As an admin, go to https://pr11046-spoo1g2htfgcgn3bkx7wcio1tyhqr35t.ci.cms.va.gov/node/49755/edit
1. [x] Validate that the facility hours are still showing
As an admin, go to https://pr11046-spoo1g2htfgcgn3bkx7wcio1tyhqr35t.ci.cms.va.gov/node/13094/edit
1. [x] Validate that no hours are specified
As an admin, go to https://pr11046-spoo1g2htfgcgn3bkx7wcio1tyhqr35t.ci.cms.va.gov/node/34664/edit
1. [x] Validate that specific hours for this service are shown
As an admin, go to https://pr11046-spoo1g2htfgcgn3bkx7wcio1tyhqr35t.ci.cms.va.gov/node/49834/edit …

VACMS-110401 Fixes missed function name change

---

config/sync/search_api.index.content.yml

Closes #10455.  Aimed at preventing this sort of noise:
I opened and saved the field settings as per instructions, so lessee if it works.

VACMS-10455: Fix search_api complaints.

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/google_analytics.settings.yml
config/sync/user.role.authenticated.yml
tests/phpunit/Security/RolesPermissionsTest.php

Closes #11064.
None, can only be tested on prod. 
This can only be tested on prod by check GA dashboard to see if it is connecting.

VACMS-11064: install ga module, initial config for ga4

---

composer.lock

https://www.drupal.org/sa-contrib-2022-054

Update next module to 1.3.

---

config/sync/core.entity_view_display.menu_link_content.lovell-federal-health-care.default.yml
docroot/modules/custom/va_gov_backend/src/Plugin/Block/SidebarMenusBlock.php
docroot/modules/custom/va_gov_lovell/src/Event/BreadcrumbPreprocessEvent.php
docroot/modules/custom/va_gov_lovell/src/EventSubscriber/LovellEventSubscriber.php
docroot/modules/custom/va_gov_lovell/src/Factory/BreadcrumbPreprocessEventFactory.php
docroot/modules/custom/va_gov_lovell/src/LovellMenuLinkTreeManipulators.php
docroot/modules/custom/va_gov_lovell/src/LovellOps.php
docroot/modules/custom/va_gov_lovell/src/Variables/BreadcrumbEventVariables.php
docroot/modules/custom/va_gov_lovell/va_gov_lovell.info.yml
docroot/modules/custom/va_gov_lovell/va_gov_lovell.services.yml
docroot/modules/custom/va_gov_workflow_assignments/src/Plugin/Block/EntityMetaDisplay.php
docroot/modules/custom/va_gov_workflow_assignments/va_gov_workflow_assignments.info.yml

[Integration CMS](https://pr10491-hzzyr3vbc9omqj1j2ed4adipwdqu36xt.ci.cms.va.gov/)
[Integration web build from integration CMS
](https://web-hzzyr3vbc9omqj1j2ed4adipwdqu36xt.ci.cms.va.gov/)
1. Do this
2. Then

VACMS-9656: Integration-Lovell

---

composer.lock

Creating this in place of the Dependabot-created PR (https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11239)

Updating drupal/next.

---

config/sync/core.entity_form_display.node.vba_facility.default.yml
config/sync/core.entity_view_display.node.vba_facility.default.yml
config/sync/core.entity_view_display.node.vba_facility.external_content.yml
config/sync/core.entity_view_display.node.vba_facility.ief_table.yml
config/sync/core.entity_view_display.node.vba_facility.teaser.yml
config/sync/field.field.node.vba_facility.field_intro_text.yml
config/sync/field.field.node.vba_facility.field_media.yml
config/sync/field.field.node.vba_facility.field_non_va_location_url.yml
config/sync/field.field.node.vba_facility.field_non_va_official_name.yml
config/sync/field.field.node.vba_facility.field_office.yml
config/sync/field.field.node.vba_facility.field_shared_vha_location.yml
config/sync/field.storage.node.field_non_va_location_url.yml
config/sync/field.storage.node.field_non_va_official_name.yml
config/sync/field.storage.node.field_shared_vha_location.yml
tests/behat/drupal-spec-tool/content_model_vba_facility_content_type_fields.feature

Closes #10911 
Manually
1. As an admin user, go to [Edit VBA Facility Cleveland VA Regional Benefit Office](https://pr11202-lc28iiardbtw6x7wk5hhgppbgtnl9j2g.ci.cms.va.gov/node/4105/edit).
2. Add information from the [VBA Facilities July 2022 - Content Model](https://docs.google.com/spreadsheets/d/1rqP4d163TtYULKL3H-CcNJinaDmHg22T/edit#gid=393504393) to the appropriate fields
3. Change the hours on Monday to close at 4:29 pm.
4. Add a page introduction and facility photo
5. Save the node.
1. As an admin, in the terminal run `ddev drush migrate:import va_node_facility_vba --update --idlist=vba_325`
2. Refresh the [VBA Facility Cleveland VA Regional Benefit Office](https://pr11202-lc28iiardbtw6x7wk5hhgppbgtnl9j2g.ci.cms.va.gov/node/4105) page.
1. As an admin, edit the page introduction on …

VACMS-10911: Additional VBA fields

---

docroot/robots.txt

#10755 
Syntax/structure autotests.
See if the note on the robots.txt file here (internal only) makes sense to add. This is not the file that is used on va.gov and I thought it would be prudent to mention that as part of the robots.txt file update.

VACMS-10755 Add note about which robots.txt is used

---

docroot/modules/custom/va_gov_build_trigger/src/Service/ReleaseStateManager.php

See discussion [here](https://dsva.slack.com/archives/C02HX4AQZ33/p1666274722161189) and [here](https://dsva.slack.com/archives/CJT90C0UT/p1662040948350839).

VACMS-0000: Increase stale threshold a tad.

---

.ddev/php/zzz-va-overrides.ini
.tugboat/config.yml
composer.json
composer.lock

Fixes #11191 which is part of epic #10870.
Tested by building a new base preview, which runs the build stage in the Tugboat config file. I had to manually test out some PHP INI changes to get JIT working and am rebuilding the base now here https://tugboat.vfs.va.gov/6346dd33f976ab9f0a7b8c44, BUT I cloned it here https://tugboat.vfs.va.gov/634e75db7886eee909e2f293 before I did that so we would have a working 8.1 env in case it failed. 
The rebuild should very likely succeed and all status checks pass now. 
I think we could do some light perf testing too. 
Check /admin/reports/status/php to verify PHP version and PHP JIT settings
Check error logs at /admin/reports/dblog …

VACMS-10870: Upgrade Tugboat and Composer from PHP 7.4 to 8.1.

---

config/sync/core.extension.yml

Relates to #10793.
Enables the module before #11387 is merged.

VACMS-10793: enable views event dispatcher module

---

.github/workflows/config/advice/_github_workflows.md
scripts/create-bad-test-files.sh
scripts/delete-bad-test-files.sh

Closes #10722.
This PR includes two files:
- a script generates a couple of files that commit various sins that should be picked up by linters.
- a script that cleans up files generated by the above script.
This is to make it easier to test changes to GitHub Actions, etc that perform linting operations.

VACMS-10722: Create script to populate repo with bad files for tests.

---

config/sync/block_content.type.benefit_promo.yml
config/sync/block_content.type.news_promo.yml
config/sync/core.entity_form_display.block_content.benefit_promo.default.yml
config/sync/core.entity_form_display.block_content.news_promo.default.yml
config/sync/core.entity_view_display.block_content.benefit_promo.default.yml
config/sync/core.entity_view_display.block_content.news_promo.default.yml
config/sync/entityqueue.entity_queue.home_page_hero.yml
config/sync/entityqueue.entity_queue.home_page_news_spotlight.yml
config/sync/feature_toggle.features.yml
config/sync/field.field.block_content.benefit_promo.field_administration.yml
config/sync/field.field.block_content.benefit_promo.field_promo_cta.yml
config/sync/field.field.block_content.benefit_promo.field_promo_headline.yml
config/sync/field.field.block_content.benefit_promo.field_promo_text.yml
config/sync/field.field.block_content.news_promo.field_administration.yml
config/sync/field.field.block_content.news_promo.field_image.yml
config/sync/field.field.block_content.news_promo.field_link.yml
config/sync/field.field.block_content.news_promo.field_link_label.yml
config/sync/field.field.block_content.news_promo.field_promo_headline.yml
config/sync/field.field.block_content.news_promo.field_promo_text.yml
config/sync/field.storage.block_content.field_administration.yml
config/sync/field.storage.block_content.field_link.yml
config/sync/field.storage.block_content.field_link_label.yml
config/sync/field.storage.block_content.field_promo_cta.yml
config/sync/field.storage.block_content.field_promo_headline.yml
config/sync/field.storage.block_content.field_promo_text.yml
config/sync/system.menu.other-search-tools.yml
config/sync/system.menu.popular-on-va-gov.yml
tests/behat/drupal-spec-tool/content_model_bundles.feature
tests/behat/drupal-spec-tool/content_model_custom_block_fields.feature
tests/behat/drupal-spec-tool/menus.feature

This is the integration PR for work being done on the home page.
1. Do this
2. Then

[INTEGRATION] Drupalize homepage 

---

.ddev/php/zzz-va-overrides.ini
composer.json
composer.lock
docroot/modules/custom/va_gov_migrate/src/EventSubscriber/PrepareRow.php
patches/temporary_fix_for_htmlspecialchars_deprecation.patch
tests/behat/Drupal/FeatureContext.php
tests/behat/behat.yml

php8.1 testing

---

config/sync/views.view.va_forms.yml
docroot/themes/custom/vagovclaro/assets/scss/components/_elements.scss

~Closes 11246~  (no magic)
Closes #11246  (magic)
See QA steps.
- - [ ] title
- - [ ] updated
- - [ ] moderation state
- - [ ] section
- - [ ] form name
- - [ ] form administration
- - [ ] issue date
- - [ ] revision date

VACMS-11246: Update VA Forms audit View.

---

.github/actions/post-checkout/action.yml
.tugboat/config.yml
composer.json
composer.lock
docroot/modules/custom/va_gov_workflow/src/Service/Flagger.php
docroot/themes/custom/vagovclaro/vagovclaro.theme

Relates to . (or closes?)
1. Do this
2. Then

VACMS-10870: php testing

---

READMES/migrations-facility.md

[DOCS] Adds VBA DB migration instructions

---

composer.json
composer.lock

Dependabot was sllow.  Need this in for sprnt goal https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11418
1. Do this
2. Then

Bump va-gov/content-build 0.0.3143

---

config/sync/system.menu.footer-megamenu.yml
config/sync/system.menu.va-gov-footer.yml
tests/behat/drupal-spec-tool/menus.feature

VACMS-11438: Create a CMS-driven VA.gov footer menu

---

.tugboat/config.yml
docroot/modules/custom/va_gov_build_trigger/src/Plugin/AdvancedQueue/JobType/ReleaseRequest.php

Reverts department-of-veterans-affairs/va.gov-cms#11694

Revert "VACMS-11413: disable continuous content release on Tugboat."

---

config/sync/block_content.type.benefit_promo.yml
config/sync/core.entity_form_display.block_content.benefit_promo.default.yml
config/sync/core.entity_form_display.block_content.news_promo.default.yml
config/sync/field.field.block_content.benefit_promo.field_promo_headline.yml
config/sync/field.field.block_content.benefit_promo.field_promo_text.yml
config/sync/field.field.block_content.news_promo.field_link_label.yml
config/sync/field.field.block_content.news_promo.field_promo_headline.yml
config/sync/field.field.block_content.news_promo.field_promo_text.yml

Closes #11119
As a content admin or administrator or (the new 'homepage manager' role is not implemented yet and thus is not available as a test persona)
1. Visit the [add benefit promo block page](https://pr11615-ovk2ohlyw304z9op8jljps5bhk0nvtk9.ci.cms.va.gov/block/add/benefit_promo)
2. Visit the [add news promo block page](https://pr11615-ovk2ohlyw304z9op8jljps5bhk0nvtk9.ci.cms.va.gov/block/add/news_promo)

VACMS-11119: Adds V2 Homepage help text guidance.

---

tests.yml

Closes #11639.
This is unfortunately difficult to test interactively; this whole file is a mess and needs to be completely rewritten (see #5087).

VACMS-11639: Fix status-error processing.

---

config/sync/block.block.vagovclaro_knowledge_base_search_form.yml

Closes #11072.
Manually
As user with an admin role
1. Go to [General CMS questions](https://pr11763-d5xaeheecm2ulkkfbdasvwh5ye3xu71j.ci.cms.va.gov/help/cms-basics/general-cms-questions)

VACMS-11072: Disables search block

---

.github/workflows/continuous_integration.yml
.github/workflows/set-tugboat-tests-pending.yml
tests.yml

Closes #11811.
Fixed an issue with the arguments to `find` not being grouped correctly and consequently only testing `*.install` files 😩
```
No syntax errors detected in docroot/modules/custom/va_gov_workflow/va_gov_workflow.module
No syntax errors detected in docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
No syntax errors detected in docroot/modules/custom/va_gov_workflow/src/Service/Flagger.php
No syntax errors detected in docroot/modules/custom/va_gov_workflow/src/Service/WorkflowContentControl.php
No syntax errors detected in docroot/modules/custom/va_gov_flags/va_gov_flags.module
No syntax errors detected in docroot/modules/custom/va_gov_flags/src/FeatureFlagDataBuilderInterface.php
No syntax errors detected in …
```

VACMS-11811: Shifts PHP lint into GitHub Action.

---

.composer-cache/README.md

The .composer-cache directory was used when we were using ECS and Dockerfiles in this repo etc. Not needed anymore. See notes in deleted README. 
1. Do this
2. Then

VACMS-000: Delete .composer-cache directory

---

composer.json
composer.lock
config/sync/views.view.content.yml
docroot/modules/custom/va_gov_backend/va_gov_backend.module
tests/behat/drupal-spec-tool/views.feature

This reverts commit 3da852ba4d14a5b0a1e70e8129a7c508170b1d84.
closes #11924
As admin
1. visit https://pr11926-mwg37zdwtjkzkxqqgui6vlw5gpdc6jtz.ci.cms.va.gov/admin/content
2. Visit a sub level view like https://pr11926-mwg37zdwtjkzkxqqgui6vlw5gpdc6jtz.ci.cms.va.gov/admin/content/facilities

Revert "VACMS-11506: updated outdated content report (#11899)"

---

hooks/git/pre-commit

Closes #10586.
**TL;DR**: This is so we don't have to type `--no-verify` to commit when we're working on a Dependabot or revert PR locally.
I think there are only a few branch name patterns we wanna support, so this is probably a reasonable approach.
I'll write a test script to show what branch names are approved and which are rejected.
```bash
#!/bin/bash
function check_branch_name() {
case $1 in 
VAGOV-TEAM-[0-9]* | VACMS-[0-9]* | dependabot/* | revert-*) return 0;;
*) return 1;;
esac
}
branch_names=(
VACMS-0000-Use-ProphecyTrait
VACMS-10586-Improve-precommit-branch-name-check
VACMS-10870-upgrade-to-php81_rebased
VACMS-11049-Fix-attributes-error
VACMS-11082-Investigate-gathering-line-count-metrics
VACMS-11497-Set-last-touched-by-a-human-field-on-all-published-nodes …
```

VACMS-10586: Improve pre-commit branch name check.

---

composer.json
composer.lock
patches/drupal-core-claro_preprocess_input.patch

Closes #12054.
1. Do this
2. Then

VACMS-12054: Don't throw error on undefined array key :weary:

---

scripts/precommit.sh

Closes #10807.
As  a developer
1. Pull this code locally.
2. Make a change to the services.staging.yml and save it
3. Attempt to commit the change

VACMS-10807: Confirms that prod and staging services.yml files are identical.

---

composer.json
composer.lock
tests/cypress/integration/behavioral/password_policy.feature
tests/cypress/integration/behavioral/password_policy/i_disable_the_password_policy.js
tests/cypress/integration/behavioral/password_policy/i_enable_the_password_policy.js

Closes #11834.
Rather than scripting the UI interactions, I just changed this to Drush config settings.
If this passes all tests, it should be safe to merge.

VACMS-11834: Improve password_policy test.

---

.tugboat/config.yml

`jq` is needed for one of the tests.  `nano` is just useful for people who don't use Vim.

Install `jq` and `nano` on Tugboat.

---

.eslintrc.json
package-lock.json
package.json
tests/cypress/fixtures/documents/minimal.csv
tests/cypress/integration/behavioral/common/i_create_a_media.js
tests/cypress/integration/behavioral/common/i_create_a_node.js
tests/cypress/integration/behavioral/media.feature

Closes #11631.
This also closes #10401.  Not to smush multiple concerns together, but I got sick of the red underlines trying to work with the tests.
The tests.
If tests pass and seem reasonable, this should be good to merge.

VACMS-11631: Create and save media entities in functional tests.

---

docroot/modules/custom/va_gov_lovell/js/limit_lovell.es6.js
docroot/modules/custom/va_gov_lovell/js/limit_lovell.js
tests/cypress/integration/behavioral/content_editing_vamc_system_service.feature

Closes #12433
Manually
Using Cypress

VACMS-12433: Adds Lovell check for exact string to hide systems

---

tests/phpunit/Content/TrimNodeTitleWhitespaceTest.php

Relates to #11964.
See [here](https://dsva.slack.com/archives/CJT90C0UT/p1675872725255869).

Disable `TrimNodeTitleWhitespaceTest::testTitleTrimRestrictedToNodes`

---

.ddev/providers/platform.yaml

Just commits a change DDEV keeps making to this provider file.

Commit automatic platform.yaml changes.

---

composer.lock
config/sync/content_model_documentation.settings.yml
config/sync/views.view.content_model_documents.yml
docroot/modules/custom/va_gov_db/va_gov_db.install
tests/behat/drupal-spec-tool/views.feature

closes #12287
Code written in the upstream module for this issue https://git.drupalcode.org/project/content_model_documentation/-/compare/1.0.0-alpha3...1.0.0-alpha4?from_project_id=101712&straight=true
https://pr12432-i5lewscwe0rfmaekkrclnpbumnlficso.ci.cms.va.gov/
As an admin
(these function, but will be tested on a separate issue so not testing here)
- The list will likely be empty unless someone else created documents.
- Click on the name of the document in the list

VACMS-12287 Add content model documentation entity.

---

composer.json
composer.lock
patches/smart_date_missing_route.patch

Adds missing entity.smart_date_override.canonical.
Relates to  #12529
Successful edit and save of an event series override.
Prior to change, the following is visible in the console log when trying to save an event series override:
As content admin
1. Visit this node: /node/51553/edit
2. Under 'Date and time' fieldset, click the 'Edit event series' button
3. Click the 'edit' button next to any event date/time.
4. Change the time to a later hour
5. Click save
6. Save the node
7. Perform steps 2-3

VACMS-12529: Adds missing entity.smart_date_override.route definition.

---

scripts/tasks/VACMS-10735-Forms-CSV-migration-validation.php
tasks-periodic.yml

Relates to #10735
Locally xdebug, automated tests.
n/a
Recommend pulling and running locally.

VACMS-10735: Daily Form Migration CSV validation checks

---

package-lock.json
package.json

See https://dsva.slack.com/archives/CT4GZBM8F/p1676552855223089

VACMS-0000: Updates eslint-plugin-import for great committing success.

---

config/sync/core.entity_form_display.consumer.consumer.default.yml
config/sync/core.entity_form_display.node.office.default.yml
config/sync/core.entity_view_display.menu_link_content.header-megamenu.default.yml
config/sync/core.entity_view_display.node.outreach_asset.default.yml
config/sync/core.entity_view_display.paragraph.address.default.yml
config/sync/core.entity_view_display.paragraph.collapsible_panel.default.yml
config/sync/core.entity_view_display.paragraph.collapsible_panel_item.default.yml
config/sync/core.entity_view_display.paragraph.expandable_text.default.yml
config/sync/core.entity_view_display.paragraph.number_callout.default.yml
config/sync/core.entity_view_display.paragraph.process.default.yml
config/sync/core.entity_view_display.paragraph.staff_profile.default.yml
config/sync/core.entity_view_display.paragraph.wysiwyg.default.yml
config/sync/core.entity_view_display.taxonomy_term.products.default.yml
config/sync/core.extension.yml
config/sync/editor.editor.rich_text.yml
config/sync/node_link_report.settings.yml
config/sync/password_policy.password_policy.va_gov_cms.yml

This is just config drift that has occurred from contrib module updates and other things that altered minor stuff like config export sorting.
Passing tests should suffice.

VACMS-000 Sync config drift.

---

.github/ISSUE_TEMPLATE/enhancement.md
.github/ISSUE_TEMPLATE/knowledge-base-article.md
.github/ISSUE_TEMPLATE/pw-issue.md
README.md
READMES/content-models.md

[DOCS] Update documentation related to content model documentation.

---

.github/workflows/cypress.yml

For working with Sorry-Cypress.  This is not executed as a part of normal CI/CD at this time and in fact has to be manually invoked, so it should pose little risk.

Create Cypress GHA workflow.

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module
docroot/modules/custom/va_gov_db/va_gov_db.install
docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
docroot/modules/custom/va_gov_workflow/va_gov_workflow.module
docroot/modules/custom/va_gov_workflow/va_gov_workflow.services.yml
tests/behat/features/content_editing.feature
tests/behat/features/personal_content_flags.feature
tests/cypress/integration/common/i_create_a_node.js
tests/cypress/integration/common/i_publish_the_node.js
tests/cypress/integration/content_editing.feature
tests/cypress/integration/entity_reference_validation.feature
tests/cypress/integration/google_tag_manager.feature
tests/cypress/integration/media.feature
tests/cypress/integration/text_validation.feature

Closes #12449
**For each of the content types listed**, validate:
- that you can not save without a revision message 
- and that the checkbox to create a new revision does not exist
- VAMC System [ ] https://pr12658-0teghkcmacbmefzbt1y1dfgmp2gl5kal.ci.cms.va.gov/node/14992/edit

VACMS-12449 Make revision_log message required on all node content types.

---

config/sync/views.view.content_model_documents.yml

closes #12730
All the new additions to this View
As an admin (only admins can see this)
1. go to https://pr12850-dllggbyjr3y2btuld28m3eucxcueqmzf.ci.cms.va.gov/admin/structure/cm_document
2. Filters

VACMS-12730 Add custom fields to cm_document View.

---

composer.json
composer.lock

Removes as it seems to be un-needed. We use a script to removed those directories. 

VACMS-00000: remove topfloor/composer-cleanup-vcs-dirs

---

docroot/modules/custom/va_gov_vamc/src/Plugin/Validation/Constraint/SectionMatcher.php
docroot/modules/custom/va_gov_vamc/src/Plugin/Validation/Constraint/SectionMatcherValidator.php
docroot/modules/custom/va_gov_vamc/va_gov_vamc.module

VACMS-12619: Add field validation facility health services

---

composer.json
composer.lock
docroot/design-system/components/alert/alert.twig

closes #10164
This is a test of the patch from this core issue  https://www.drupal.org/project/drupal/issues/2942404
It breaks our styling but I want to be sure if solves the problem before chasing the CSS issues.
As any loggged in user
1. go to here https://pr12929-ld5t601kxvpuxhhfie02xzscb3knvyzj.ci.cms.va.gov/minneapolis-health-care/programs/neuromuscular-disorders
```
role="region" aria-label="Status message"
```

VACMS-10164 Fix core content landmark issue 2942404

---

.github/ISSUE_TEMPLATE/cms-team-and-sitewide-crew-member-onboarding.md

link now directs to Platform Website, not directly to gh ticket, so if changes are made to template labels, etc., new tickets have correct labels, etc.
1. Do this
2. Then

updated Platform Orientation link

---

tests/phpunit/Security/RolesPermissionsTest.php

Reverts department-of-veterans-affairs/va.gov-cms#13055

Revert "VACMS-0000: Sort permissions arrays before comparison."

---

.github/ISSUE_TEMPLATE/runbook-vet-center-outstation-to-vet-center.md

Closes #12898 
As a help desk manager

VACMS-12898: Updates runbook Outstation becomes Vet Center

---

.github/ISSUE_TEMPLATE/runbook-vamc-facility-duplicate-or-section-change.md

I noticed that the work done in for #12972 did not fully remap the migration.
N/A
Test when a performing the step in the runbook.
N/A

[DOCS] Updates VAMC facility duplicate db script

---

config/sync/content_model_documentation.settings.yml
config/sync/node_link_report.settings.yml

closes #13218
As an admin
1. Go to https://pr13219-nioxw47w7huwhxq1incy2daszuyj30fl.ci.cms.va.gov/admin/structure/cm_document/add
2. IN the select list "Documentation for:"  scroll down until you get to the module section of the list.  (alphabetical, in the "m")
3. Then choose a module and create a tests document

VACMS-13218 Enable module documentation.

---

.github/ISSUE_TEMPLATE/redirect-request-facility-url.md
.github/ISSUE_TEMPLATE/runbook-facility-url-change.md
.github/ISSUE_TEMPLATE/runbook-vamc-facility-duplicate-or-section-change.md
.github/ISSUE_TEMPLATE/runbook-vamc-facility-name-change.md
.github/ISSUE_TEMPLATE/runbook-vamc-facility-new.md
.github/ISSUE_TEMPLATE/runbook-vamc-system-name-change.md
.github/ISSUE_TEMPLATE/runbook-vet-center-cap-to-outstation.md
.github/ISSUE_TEMPLATE/runbook-vet-center-name-change.md
.github/ISSUE_TEMPLATE/runbook-vet-center-new.md
.github/ISSUE_TEMPLATE/runbook-vet-center-outstation-to-vet-center.md

Relates to #13109.
N/A
N/A
Review documentation for accuracy.

[DOCS] VACMS-13109: Adds new runbook and changes other runbooks.

---

docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php

Closes #13120 
Manually
1. Edit [Richland VA Clinic](https://pr13287-vm1qqyifxta8wjri7dsntyutaxmsg9n0.ci.cms.va.gov/node/2257/edit).
2. Set the operating status to Facility Notice
3. Add the following to the Details, which should be counted as 297 characters, showing "3 characters remaining":
```
The Department of Veterans Affairs (VA) is a federal agency that provides healthcare, education and other benefits to Veterans.
The VA has over 370,000 employees and is the second largest federal employer. The VA has been has been praised for its high-quality care and its commitment to veterans.
```
4. Save the facility as Published
5. Check the [Post API Queue](https://pr13287-vm1qqyifxta8wjri7dsntyutaxmsg9n0.ci.cms.va.gov/admin/config/post-api/queue)
6. [ ] Validate that the character count of …

VACMS-13120: Add check and cleanup string to status moreinfo push.

---

composer.lock
docroot/sites/default/default.settings.php

Closes #13366.
If this passes testing it should be good. 

VACMS-13366: sa-core-2023-005  update drupal core

---

.github/ISSUE_TEMPLATE/cms-design-system-update-or-addition.md
.github/ISSUE_TEMPLATE/cms-notification-trigger.md
.github/ISSUE_TEMPLATE/knowledge-base-article.md
.github/ISSUE_TEMPLATE/pw-issue.md
.github/ISSUE_TEMPLATE/qa-incidental.md
.github/ISSUE_TEMPLATE/runbook-facility-url-change.md
.github/ISSUE_TEMPLATE/runbook-vamc-facility-closed.md
.github/ISSUE_TEMPLATE/runbook-vamc-facility-duplicate-or-section-change.md
.github/ISSUE_TEMPLATE/runbook-vamc-facility-name-change.md
.github/ISSUE_TEMPLATE/runbook-vamc-facility-new.md
.github/ISSUE_TEMPLATE/runbook-vamc-system-name-change.md
.github/ISSUE_TEMPLATE/runbook-vba-facility-closed.md
.github/ISSUE_TEMPLATE/runbook-vba-facility-name-change.md
.github/ISSUE_TEMPLATE/runbook-vba-facility-new.md
.github/ISSUE_TEMPLATE/runbook-vet-center-cap-to-outstation.md
.github/ISSUE_TEMPLATE/runbook-vet-center-closed.md
.github/ISSUE_TEMPLATE/runbook-vet-center-name-change.md
.github/ISSUE_TEMPLATE/runbook-vet-center-outstation-to-vet-center.md

Originally here: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/13361, new branch rebased on Main after bigger runbook PR changes merged.
Relates to #10845

DaveP runbook alpha labels, typo fixes

---

scripts/web-build.sh
scripts/web-install.sh

Closes #13494.
Tested locally ran `va:web:install` and `va:web:build` with no errors
1. Check the build logs

VACMS-13494: added nvm commands to web:build and web:install

---

tests/loadtest/Cargo.lock
tests/loadtest/Cargo.toml

Closes #13489.
1. Do this
2. Then

VACMS-13489: Address `loadtest` vulnerability alerts.

---

docroot/modules/custom/va_gov_lovell/src/LovellMenuLinkTreeManipulators.php
tests/cypress/integration/vamc_lovell.feature

Closes #13431
As an anon user
1. go here https://pr13562-xku3f71uyf1vcgobwdstsgk2glihmthc.ci.cms.va.gov/lovell-federal-health-care
1. go here https://pr13562-xku3f71uyf1vcgobwdstsgk2glihmthc.ci.cms.va.gov/lovell-federal-health-care-tricare
1. go here https://pr13562-xku3f71uyf1vcgobwdstsgk2glihmthc.ci.cms.va.gov/lovell-federal-health-care-va
1. go here https://pr13562-xku3f71uyf1vcgobwdstsgk2glihmthc.ci.cms.va.gov/lovell-federal-health-care-va/work-with-us

VACMS-13431 Restore Lovell menu

---

READMES/dependabot-alerts.md

Closes #13498. 
pls like, comment, and subscribe for more policy recommendations from ya boi nug doug

VACMS-13498: Dependabot Alerts Policy

---

.tugboat/config.yml

Closes #11884.
1. Do this
2. Then

VACMS-11884: Upgrade Tugboat Docker images to Bullseye.

---

composer.json
composer.lock
patches/3106205-length-menu-tree-too-short.patch

Closes #13278.
Tested locally, link saved correctly without error. 
1. Go to `/admin/structure/menu/item/934/edit?destination=/admin/structure/menu/manage/header-megamenu`
and paste the following url in the link field `https://department.va.gov/biographies/?_bio_position=assistant-secretary%2Cchairman%2Cdeputy-secretary%2Cgeneral-counsel%2Cinspector-general%2Cprincipal-executive-director%2Csecretary%2Cunder-secretary%2Cva-chief-of-staff%2F%3Fredirect%3D1%2Cva-chief-of-staff`
then click save

VACMS-13278: patch to address menu link being too short

---

READMES/migrations-facility.md

[docs] Replace ddev migrate-sync with ddev composer va:migrate:sync

---

config/sync/views.view.facility_services.yml

Closes #13672
Manually
- Go to the [System Banner Image Audit](https://pr13988-q2ffccwghsonebcvoca6yd1mc6tondim.ci.cms.va.gov/admin/content/audit/system-banner-image)

VACMS-13672: Adds system banner image

---

composer.json
composer.lock

Closes #13583.
1. Go to either of these two locations:
- generic View bulk operation `/admin/content/bulk?title=&type=vet_center&moderation_state=All&taxonomy_entity_index_tid_depth=1017&page=0`
- Facility specific bulk operation `/admin/content/facilities/facility-status?Title=&field_facility_locator_api_id_value=&field_operating_status_facility_value=All&field_operating_status_more_info_value=&field_supplemental_status_target_id_op=or&field_supplemental_status_target_id=All&type=vet_center&moderation_state=All&workbench_access_section__section=1017`
2. Select all the items in that filtered …

VACMS-13583: Unable to alter field values by Views Bulk Operation

---

composer.json
composer.lock

Closes #13956 
Manually
Axe
1. Go to [Corpus Christi VA Clinic](https://pr14058-1tlulcbwuoudjohdpwqgajezky8tv5yu.ci.cms.va.gov/node/2310/edit)

VACMS-13956: Updates office_hours module, removes patch

---

.github/pull_request_template.md

This PR fixes a benign typo in the github PR template.
n/a
Guidance on testing PR templates requested as part of the PR review.

VACMS-0000: PR template small typo

---

composer.json
composer.lock
config/sync/migrate_plus.migration.va_node_health_care_local_facility.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility.yml

Related to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13478.
This adds a new process plugin to use in a migration that was failing under d10.
As an admin
1. Run the [VAMC facility migration](https://pr14122-m3mvjvohosjazvepvhtrqhzmzdvklq7c.ci.cms.va.gov/admin/structure/migrate/manage/facility/migrations/va_node_health_care_local_facility/execute) as an update migration 
2. Visit a [non-mobile facility](https://pr14122-m3mvjvohosjazvepvhtrqhzmzdvklq7c.ci.cms.va.gov/node/1233/edit). 
3. Visit a mobile facility [/chillicothe-health-care/locations/chillicothe-va-mobile-cli …

VACMS-000 upgrade migration tools module

---

composer.json
composer.lock
patches/3290964-add-drush-commands-2.patch

VACMS-00000: fix for patch on sitewide_alert

---

composer.lock

VACMS-00000: update form simplesamlphp library

---

composer.json
composer.lock
patches/3368310-str-replace-throws-php-error.patch
patches/combined-patches-for-migrate-plus.patch

Closes #14148.
Manually ran VBAmigration on tugboat.
1. Do this
2. Then

VACMS-14148: fix for facilites migration, patch migrate_plus

---

config/sync/core.extension.yml

VACMS-00000: disable flysystem modules

---

docroot/modules/custom/va_gov_content_release/src/Exception/CouldNotDetermineStrategyException.php
docroot/modules/custom/va_gov_content_release/src/GitHub/GitHubRepositoryDispatch.php
docroot/modules/custom/va_gov_content_release/src/GitHub/GitHubRepositoryDispatchInterface.php
docroot/modules/custom/va_gov_content_release/src/LocalFilesystem/LocalFilesystemBuildFile.php
docroot/modules/custom/va_gov_content_release/src/LocalFilesystem/LocalFilesystemBuildFileInterface.php
docroot/modules/custom/va_gov_content_release/src/Plugin/Strategy/GitHubRepositoryDispatch.php
docroot/modules/custom/va_gov_content_release/src/Plugin/Strategy/LocalFilesystemBuildFile.php
docroot/modules/custom/va_gov_content_release/src/Strategy/Resolver/Resolver.php
docroot/modules/custom/va_gov_content_release/src/Strategy/Resolver/ResolverInterface.php
docroot/modules/custom/va_gov_content_release/va_gov_content_release.services.yml
docroot/modules/custom/va_gov_environment/src/Environment/Environment.php
docroot/modules/custom/va_gov_environment/src/Environment/EnvironmentInterface.php
docroot/modules/custom/va_gov_environment/src/Service/Discovery.php
docroot/modules/custom/va_gov_environment/src/Service/DiscoveryInterface.php
docroot/sites/default/settings/settings.local.php
tests/phpunit/va_gov_content_release/functional/GitHub/GitHubRepositoryDispatchTest.php
tests/phpunit/va_gov_content_release/functional/LocalFilesystem/LocalFilesystemBuildFileTest.php
tests/phpunit/va_gov_content_release/functional/Plugin/Strategy/StrategyPluginManagerTest.php
tests/phpunit/va_gov_content_release/functional/Reporter/ReporterTest.php
tests/phpunit/va_gov_content_release/functional/Strategy/Resolver/ResolverTest.php
tests/phpunit/va_gov_content_release/unit/GitHub/GitHubRepositoryDispatchTest.php
tests/phpunit/va_gov_content_release/unit/Plugin/Strategy/GitHubRepositoryDispatchTest.php
tests/phpunit/va_gov_content_release/unit/Plugin/Strategy/LocalFilesystemBuildFileTest.php
tests/phpunit/va_gov_content_release/unit/Reporter/ReporterTest.php
tests/phpunit/va_gov_content_release/unit/Resolver/ResolverTest.php
tests/phpunit/va_gov_environment/functional/Service/DiscoveryTest.php
tests/phpunit/va_gov_environment/unit/Environment/EnvironmentTest.php
tests/phpunit/va_gov_environment/unit/Service/DiscoveryTest.php

Closes #13848.
Also includes some random refactoring that came up in the course of doing this work and adding tests. I'll note that work in separate comments.

VACMS-13848: Creates strategyresolver service.

---

READMES/devops/deploy-oob.md

Fleshing out the minimal doc created earlier.

VACMS-0000: Enhancements to OOB deploy documentation.

---

docroot/design-system/package-lock.json
package-lock.json
scripts/cd_metrics/package-lock.json

VACMS-0000: Updates NPM packages to fix Dependabot alerts.

---

config/sync/core.entity_form_display.node.full_width_banner_alert.default.yml
config/sync/field.field.node.full_width_banner_alert.field_body.yml
docroot/modules/custom/va_gov_vamc/va_gov_vamc.install

Relates to #11039 #14117
Manually
As user Ryan S.
- Go to [Help Limit the Spread of COVID-19 and other Illnesses](https://pr14048-lmz03qdvoytvgfwvgpjzsx007s6j3yry.ci.cms.va.gov/node/6922/edit) edit screen
**Note: Unsure if this can be merged when approved.**

VACMS-11039: Updates form and adds hook_update_n

---

docroot/modules/custom/va_gov_content_release/src/EntityEvent/Strategy/Resolver/Resolver.php
docroot/modules/custom/va_gov_content_release/src/EntityEvent/Strategy/Resolver/ResolverInterface.php
docroot/modules/custom/va_gov_content_release/va_gov_content_release.services.yml
tests/phpunit/va_gov_content_release/functional/EntityEvent/Strategy/Resolver/ResolverTest.php
tests/phpunit/va_gov_content_release/unit/EntityEvent/Strategy/Resolver/ResolverTest.php

Closes #13855.
This still exists parallel to the current content release system and should not impact it at this time.

VACMS-13855: Creates EntityEvent Strategy Resolver service.

---

docroot/modules/custom/va_gov_content_release/src/Exception/RequestException.php
docroot/modules/custom/va_gov_content_release/src/Request/Request.php
docroot/modules/custom/va_gov_content_release/src/Request/RequestInterface.php
docroot/modules/custom/va_gov_content_release/va_gov_content_release.services.yml
tests/phpunit/va_gov_content_release/functional/Request/RequestTest.php
tests/phpunit/va_gov_content_release/unit/Request/RequestTest.php

Closes #14270.
This is one of two (I think) remaining tickets that does _not_ directly impact the content release system as currently implemented.
Risk is low, provided tests pass.

VACMS-14270: Creates Content Release Request service.

---

config/sync/feature_toggle.features.yml

Adds a new feature flag.
Relates to #13481 
1. Visit /admin/config/system/feature_toggle

VACMS-13481: Adds new feature toggle for mobile app promotion.

---

READMES/devops/acm-certificate-import.md

Add process diagram to ACM-certificate-import readme

---

config/sync/field.field.node.page.field_content_block.yml

Closes #10941 
Manual function testing
As a content admin, go to node/add/page.
1. Click on the "Add content block" button.
2. Search for "Q&A Group"
3. Expand Q&As and click "Place Q&As" (see screen shot)
4. Select any content and click "Select Q&As"
5. Satisfy other form requirements and save.
View the note you just created.
You should see a block like the following on the page.
4. Select any content and click "Select Q&As"
5. Satisfy other form requirements and save.
View the note you just created.
You should see a block like the following on the page.

VACMS-10941: Add reusable Q&A to benefit detail pages

---

tests/cypress/integration/common/i_check_the_checkbox.js

Relates to #14117 
1. Do this
2. Then

VACMS-14117: Adds missing closing braces and paranthesis

---

docroot/themes/custom/vagovclaro/webpack.config.js
scripts/cd_metrics/time_to_restore.lib.js
scripts/cd_metrics/time_to_restore.test.js
scripts/js/babel-es6-build.js
scripts/js/babel-es6-watch.js

Just some little things to fix CodeQL complaints.

Random CodeQL alerts.

---

docroot/modules/custom/va_gov_backend/src/Plugin/views/access/PdfAuditAccess.php

Closes #14462.
As user danielle.thierry@va.gov
1. navigate to `/admin/content/media/pdfs`

VACMS-14462: added POs to access list

---

docroot/modules/custom/va_gov_post_api/README.md
docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityService.php
docroot/modules/custom/va_gov_post_api/va_gov_post_api.module

VACMS-8017 vamc service data push logging

---

package-lock.json

Closes #14624.
Context: https://github.com/department-of-veterans-affairs/va.gov-cms/security/dependabot/156

VACMS-14624: Updates `@cypress/request`.

---

composer.json
composer.lock

This reverts commit 8e1bc4659b1132de14abbc19081f7e3a7b150622.
1. Do this
2. Then

Revert "Bump va-gov/content-build from 0.0.3317 to 0.0.3318 (#14650)"

---

docroot/modules/custom/va_gov_backend/va_gov_backend.install
docroot/modules/custom/va_gov_magichead/va_gov_magichead.info.yml

VACMS-0000: Removes magichead update hook.

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module
docroot/modules/custom/va_gov_banner/va_gov_banner.info.yml
docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.info.yml
docroot/modules/custom/va_gov_bulk/va_gov_bulk.info.yml
docroot/modules/custom/va_gov_clone/va_gov_clone.info.yml
docroot/modules/custom/va_gov_clp/va_gov_clp.info.yml
docroot/modules/custom/va_gov_consumers/va_gov_consumers.info.yml
docroot/modules/custom/va_gov_dashboards/va_gov_dashboards.info.yml
docroot/modules/custom/va_gov_flags/va_gov_flags.info.yml
docroot/modules/custom/va_gov_govdelivery/va_gov_govdelivery.info.yml
docroot/modules/custom/va_gov_graphql/va_gov_graphql.info.yml
docroot/modules/custom/va_gov_help_center/va_gov_help_center.info.yml
docroot/modules/custom/va_gov_lovell/va_gov_lovell.info.yml
docroot/modules/custom/va_gov_media/va_gov_media.info.yml
docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.info.yml
docroot/modules/custom/va_gov_preview/va_gov_preview.info.yml
docroot/modules/custom/va_gov_user/va_gov_user.info.yml
docroot/modules/custom/va_gov_workflow/va_gov_workflow.info.yml
docroot/modules/custom/va_gov_workflow_assignments/va_gov_workflow_assignments.info.yml
scripts/content/script-library.php
tests/phpunit/Support/Classes/VaGovExistingSiteBase.php
tests/phpunit/Support/Entity/Storage.php

Closes #14792.
Closes #11000.
These are all work that @edmund-dunn did; I'm just cherry-picking individual files back into a PR to reduce the size of that D10 PR.

VACMS-14792: cherry pick d10 branch

---

docroot/modules/custom/va_gov_post_api/src/Form/VaGovFacilityForceQueueForm.php
docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityService.php
docroot/modules/custom/va_gov_post_api/va_gov_post_api.services.yml

Closes #8017 
Also:
Closes #8019
Closes #8042
Closes #10454
Data is validated by publishing  facility health care service and checking the entry in the [Post API queue](https://pr13464-bmyolh5b302vesdtyzpkbz3sbmtpklu0.ci.cms.va.gov/admin/config/post-api/queue).

VACMS-8017 Update Facility Service push data.

---

docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php

Makes revision log message required on block content forms.
Relates to #14800
Tested locally in UI.
1. Visit /block/236?destination=/admin/structure/block/block-content

VACMS-14800: Makes revision log message required on block content forms.

---

docroot/modules/custom/va_gov_post_api/src/Form/VaGovFacilityForceQueueForm.php
docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityService.php
docroot/modules/custom/va_gov_post_api/va_gov_post_api.module

Relates to #14857
Manually
N/A
[Force push facility services](https://pr14867-l2rkuuo23uyrcjlbkqge8wyapdnzp50f.ci.cms.va.gov/admin/config/va-gov-post-api/facility-force-queue).
- Validate that the file is where the it should be, according to the [Recent logs](https://pr14867-l2rkuuo23uyrcjlbkqge8wyapdnzp50f.ci.cms.va.gov/admin/reports/dblog). (Personally, I like to go to the [Terminal](https://tugboat.vfs.va.gov/tush/64e34ea62d3036648d5843f3) and run `drush watchdog:show --count=300 | grep "VA.gov Post API: A log file was created at"`
- Clear the queue (`drush queue:delete post_api_queue`)
[Update a system health service](https://pr14867-l2rkuuo23uyrcjlbkqge8wyapdnzp50f.ci.cms.va.gov/central-iowa-health-care/health-services/nutrition-food-and-dietary-care-at-va-central-iowa-health-care). …

VACMS-14857: Adds force push argument upstream. Moves log file creation.

---

config/sync/views.view.content_entity_reference_source.yml
config/sync/views.view.local_facilities_entity_reference_view.yml

VACMS-13980: Excludes archived facilities from 2 views

---

config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
docroot/modules/custom/va_gov_vamc/src/EventSubscriber/VAMCEntityEventSubscriber.php
scripts/content/VACMS-13679-wipe-out-covid-status-data.php
scripts/content/script-library.php
tests/cypress/integration/features/content_type/health_care_local_facility.feature

Relates to #13679
Manually
As an admin, do the following:

VACMS-13679: Sunset COVID health status in Drupal

---

tests/cypress/integration/features/content_type/campaign_landing_page/downloadable_resources.feature
tests/cypress/integration/features/content_type/campaign_landing_page/video.feature

Relates to #14442 
Fixes failing video cypress test and adjusts some when/then language. Should immediately follow related merged branch.
Local cypress
n/a
Ensure changes make readable sense and that automatic tests pass.

VACMS-14442: fix failing video test

---

docroot/modules/custom/va_gov_graphql/assets/explorer/package-lock.json

VACMS-15031: Updates Webpack for GraphQL Explorer.

---

composer.json
composer.lock

Update to lock simplesamlphp to 1.19
1. Do this
2. Then

VACMS-00000: update simplsamlphp to 1.19

---

config/sync/core.extension.yml
docroot/modules/custom/va_gov_live_field_migration/drush.services.yml
docroot/modules/custom/va_gov_live_field_migration/src/Commands/Commands.php
docroot/modules/custom/va_gov_live_field_migration/va_gov_live_field_migration.info.yml
docroot/modules/custom/va_gov_live_field_migration/va_gov_live_field_migration.module

Closes #14997.
This code is not invoked normally, and is just some stub drush commands in a custom module for work I'll do in #13699.

VACMS-14997: module shell for live migration module

---

config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
config/sync/core.entity_form_display.node.checklist.default.yml
config/sync/core.entity_form_display.node.media_list_images.default.yml
config/sync/core.entity_form_display.node.media_list_videos.default.yml
config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
config/sync/node_link_report.settings.yml
config/sync/views.view.date_fields.yml
config/sync/views.view.detail_page_url_audit_and_bulk_udpate.yml
config/sync/views.view.flagged_content_va_forms.yml
config/sync/views.view.image_style_warmer_warmup_files.yml
config/sync/views.view.knowledge_base_article_administration.yml
config/sync/views.view.media.yml
config/sync/views.view.section_export.yml

No ticket.
This PR resyncs some straggling database changes back to code. Most of them appear to just be weight changes/re-order of fields and data elements.
Some in-browser functional testing.
n/a
Take a look at the code syncs and make sure nothing seems amiss. No functionality of the site should have changed.

VACMS-0000: Resync stray config changes to code

---

.tugboat/config.yml

VACMS-15183 - Update Script so it doesn't say its outdated

---

scripts/compile-theme.sh

Closes #15298
Tested theme compile locally. 
1. Navigate to a node edit screen
2. Then

VACMS-15298: fix theme not compiling

---

composer.json
composer.lock

Closes #15332.
Verified version change in status report locally. 
1. Login and navigate to status report

VACMS-15332: upgrade drupal core

---

.github/ISSUE_TEMPLATE/ap-defect.md

Update to remove crlf.

---

docroot/modules/custom/va_gov_backend/src/Service/VaGovUrl.php

VACMS-15482: Adjust VaGovUrl request timeouts.

---

LICENSE.txt
docroot/design-system/package.json
docroot/themes/custom/vagovclaro/package.json
package.json

15471 Implement Snyk security scanning

---

config/sync/system.action.user_add_role_action.next_js.yml
config/sync/system.action.user_remove_role_action.next_js.yml
config/sync/user.role.next_js.yml

Next Drupal expects a user with certain permissions to be available to enable access to protected content (i.e. drafts & archives). Creates a role with the required permissions that will be assigned to the next api user.
Confirmed creation of role and assignment of permissions after importing configurations.
Confirmed role exists
Confirm that role is assigned the following permissions
- Bypass content access control
- Issue subrequests
- View user information

VACMS-15245: Set up user and role for Next/Drupal CMS Preview.

---

composer.json
composer.lock

Upgrades limited_field_widget module to latest version that is compatible with D10 (alpha state).
PR is in draft for further testing, not ready to merge.
Relates to #15337
functionally, locally and in tugboat according to QA steps below + logs
As administrator:
- Go to the CLP content type manage form display /admin/structure/types/manage/campaign_landing_page/form-display:
- Go to the Event content type manage form display: /admin/structure/types/manage/event/form-display
- Go to the VAMC Facility Health Service manage form display: /admin/structure/types/manage/health_care_local_health_service/form-display
As content_admin:

VACMS-15337: Upgrade limited_field_widget

---

config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
config/sync/core.entity_view_display.node.health_care_local_facility.external_content.yml
config/sync/field.field.node.health_care_local_facility.field_mental_health_phone.yml
config/sync/field.field.node.health_care_local_facility.field_phone_number.yml
config/sync/migrate_plus.migration.va_node_health_care_local_facility.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility.yml

Relates to #14213
As the user "QA Content Editor"
1. Go to [Viera VA clinic](https://pr15468-q3rkc1fdumq46rmvo8ezyblbmt61pbwo.ci.cms.va.gov/orlando-health-care/locations/viera-va-clinic)
2. Click the edit tab
4.  Change the value for the phone number  and save (this user can't publish).
-  [x] validate the data saved.
5. Log out and log back in as admin
6. Go to the [VAMC facility migration](https://pr15468-q3rkc1fdumq46rmvo8ezyblbmt61pbwo.ci.cms.va.gov/admin/structure/migrate/manage/facility/migrations/va_node_health_care_local_facility/execute)
7. Under "Additional execution options"  select …

VACMS-14213 Make CMS the source of truth for VAMC mental health phone number

---

composer.json
composer.lock

VACMS-14293: Removes Blazy.

---

config/sync/feature_toggle.features.yml

Relates to #15079
Functional
As an administrator, check the following:
- Go to[ Config > System > Feature Toggle](https://cms-suew0s7ulfusxfcvvzxzvfzwhxpdk90s.ci.cms.va.gov/admin/config/system/feature_toggle) (or click this link)

VACMS-15079: Removed mobile app promo feature flag

---

docroot/modules/custom/va_gov_notifications/README.md

[docs] Change Mailhog to Mailpit for notifications.

---

config/sync/views.view.content.yml

Relates to #15891 
Locally
Pasted from style guide:
https://prod.cms.va.gov/admin/structure/cm_document/note/124/views-style-guide
As a developer logged in as administrator, go to https://pr15896-p6xmcl1cuiwro2d1zvjakewau8sjznjv.ci.cms.va.gov/admin/structure/views/view/content/edit/page_qa
- ~~[ ] Is Locked (optional)~~

VACMS-15891: Update Q&A Content Report View to use Multiple Workflow Filter

---

config/sync/views.view.media.yml

Closes #16024.
Tested locally. Report successfully generated. 
1. Login and navigate to `/admin/content/media/images` and teh click on "Download CSV"

VACMS-16024: image export changed to batch for alt text audit

---

docroot/sites/default/settings/settings.prod.php

VACMS-00000: turned on gzip and aggregation

---

docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php

Relates to #14215 
This is part one to make sure the current MH phone we get from LH is what we push to LH.  It does not include the new field, but will automatically pick up the new field when it appears.
As an admin
1. Save a [VAMC facility](https://pr16274-0n8txzdyjfdhgc1gayhnymhc2yiww9og.ci.cms.va.gov/node/1652/edit) and publish it
2. Visit the [Post API Queue](https://pr16274-0n8txzdyjfdhgc1gayhnymhc2yiww9og.ci.cms.va.gov/admin/config/post-api/queue)
3. Process the Queue
---- 

VACMS-14215 Add editable mental health number to the VAMC Facility push

---

config/sync/core.entity_view_display.node.health_care_region_page.external_content.yml

Relates to #16396
As VAMC editor (Kaila.Bird)
1. Visit [VAMC System page](https://pr16398-oeqdqkonm4ltapylzisnfhgow2af49ep.ci.cms.va.gov/node/14989/edit)

VACMS-16396 Remove breadcrumbs on system external content.

---

READMES/jsonapi.md
composer.json
composer.lock
config/sync/core.extension.yml
docroot/modules/custom/va_gov_api/js/json-schemas-table-filter.js
docroot/modules/custom/va_gov_api/src/Plugin/openapi/OpenApiGenerator/VaGovOpenApiGenerator.php
docroot/modules/custom/va_gov_api/va_gov_api.libraries.yml
docroot/modules/custom/va_gov_api/va_gov_api.module
tests/phpunit/API/JsonApiExplorerUiTest.php

Closes #9135 by adding modules and config to view Swagger UI at "/admin/config/services/openapi/swagger/jsonapi".
I manually tested this and will look at the Tugboat once built. There is also a test included in this PR.
You can explore the JSON:API endpoints via a Swagger UI to see what's available and to test out requests and responses.
1. Login to the site as a user with an "administrator" or "content_api_consumer" role.
2. Make sure on "/admin/config/services/openapi" there is only one option called "VA.gov JSON:API".
3. Click to explore "VA.gov JSON:API" UI or go to "/admin/config/services/openapi/swagger/jsonapi".
4. Read a [Swagger UI tutorial](https://idratherbewriting.com/learnapidoc/pubapis_swagger.html) to familiarize yourself with the UI features, if you're not familiar …

VACMS-9135: json api UI e

---

config/sync/views.view.centralized_content_paragraphs.yml
config/sync/views.view.detail_page_url_audit_and_bulk_udpate.yml
config/sync/views.view.facility_services.yml
config/sync/views.view.section_export.yml
config/sync/views.view.vamc_top_task_page_revisions.yml

Relates to #16481
Note: I did a little clean-up along the way, making sure that all columns had a label, for instance, and making the buttons align to our style guide.
Manually
Go to the main audit page.

VACMS-16481: Moves audit views into the menu

---

READMES/tugboat.md

Related to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16561 and https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13834. Documenting design and technical details of the Tugboat GHA integration.
N/A
N/A
N/A

Add documentation for Tugboat GHA integration

---

config/sync/field.field.paragraph.audience_topics.field_markup.yml
config/sync/field.storage.paragraph.field_topics.yml
docroot/modules/custom/va_gov_backend/js/audience_topics.es6.js
docroot/modules/custom/va_gov_backend/js/audience_topics.js
docroot/modules/custom/va_gov_backend/va_gov_backend.module
tests/cypress/integration/features/content_type/support_resources_detail_page.feature

Closes #16574 . 
As a user that can edit _Resources and Support Detail Page_
1. Create a new page (/node/add/support_resources_detail_page)
2. Browse to the _Tags_ section

VACMS-16574: Remove tag topic restrictions.

---

composer.json
composer.lock

Closes #16898.
If it passes automated tests we should be good.

VACMS-16898: upgrade drupal core to 10.2.2

---

config/sync/feature_toggle.features.yml

Remove unused feature flag for single value link
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15758

VACMS-15758: Remove feature flag for single value link

---

.tugboat/vhost-next.conf

Relates to #15314. 
Next-build default port was updated here: https://github.com/department-of-veterans-affairs/next-build/pull/358
This PR updates the nginx config to use that port also.
1. Do this
2. Then

VACMS-15314 update next-build port

---

README.md

Testing https://github.com/department-of-veterans-affairs/va.gov-cms/pull/17007.

Test PR with documentation change

---

.github/CODEOWNERS

Relates to #14061 
n/a
n/a
n/a

VACMS-14061:  CODEOWNERS updates for Public Websites

---

composer.json
composer.lock

Closes #17289 
Tested locally
1. Navigate to `/node/7236/edit`

VACMS-17289: added patch to fix core bug fro Unable to update operating status

---

composer.json
composer.lock
docroot/modules/custom/va_gov_backend/src/Logger/Processor/DatadogApmProcessor.php

Relates to #17339 
tested on test.staging
1. Do this
2. Then

VACMS-17339: build and deploy breakdown revert monolog update

---

composer.lock
config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
config/sync/core.entity_view_display.node.health_care_local_facility.external_content.yml
config/sync/core.entity_view_display.node.nca_facility.default.yml
config/sync/core.entity_view_display.node.nca_facility.external_content.yml
config/sync/core.entity_view_display.node.vamc_system_billing_insurance.default.yml
config/sync/core.entity_view_display.node.vamc_system_billing_insurance.search_index.yml
config/sync/core.entity_view_display.node.vba_facility.default.yml
config/sync/core.entity_view_display.node.vba_facility.external_content.yml
config/sync/core.entity_view_display.node.vba_facility.ief_table.yml
config/sync/core.entity_view_display.node.vet_center.default.yml
config/sync/core.entity_view_display.node.vet_center.external_content.yml
config/sync/core.entity_view_display.node.vet_center_cap.default.yml
config/sync/core.entity_view_display.node.vet_center_mobile_vet_center.default.yml
config/sync/core.entity_view_display.node.vet_center_mobile_vet_center.external_content.yml
config/sync/core.entity_view_display.node.vet_center_outstation.external_content.yml
config/sync/core.entity_view_display.paragraph.service_location.default.yml
config/sync/views.view.non_clinical_services.yml

VACMS-17323: Updates module with fixes for button

---

composer.json
composer.lock

Revert hook event dispatcher update

---

docroot/themes/custom/vagovclaro/assets/scss/components/_textfield_counter.scss

Relates to #16732
Manually
_Note on implementation: I added the body class to the CSS selectors to increase the specificity of the definitions, so that the styles set by the module itself would not override them._

VACMS-16732: Removes border color related to text-counter

---

tests/cypress/integration/features/content_type/facilities/vamc/health_care_local_health_service.feature

Relates to #17524 .
Ran the cypress test locally

VACMS-17524: Removes scenario from VAMC Facililty Health Service cypress test

---

composer.json
composer.lock

Relates to #17073
Tested locally and verified that version is 3.0.0
1. Do this

VACMS-17073-upgrade-allowed-formats-module.

---

composer.json
composer.lock

Closes #17073
Confirmed removal of allowed_formats module
1. Do this

VACMS-17073: Removing allowed formats module from composer.

---

composer.json
composer.lock

Closes #17073
We still need this module for the hidden formats functionality. 
Tested locally
THis should be good if all automated tests pass and tugboat builds correctly. 

add allowed_formats back into composer

---

tests/cypress/integration/features/content_type/facilities/vba/vba_facility.feature

Relates to #17559
Cypress (2x)

VACMS-17559: Adds final steps to prevent Cypress failures

---

config/sync/views.view.non_clinical_services.yml
docroot/themes/custom/vagovclaro/assets/scss/components/_views.scss

Relates to #17381
Manually
If desired, check other sections as an admin, visiting other of the following pages:
- [Billing and Insurance](https://pr17721-0fgfioq95sm0vwnbjtb66620jxfv6us0.ci.cms.va.gov/admin/content?title=&type=vamc_system_billing_insurance&moderation_state=All&owner=All)
- [Medical records office](https://pr17721-0fgfioq95sm0vwnbjtb66620jxfv6us0.ci.cms.va.gov/admin/content?title=&type=vamc_system_medical_records_offi&moderation_state=All&owner=All)
- [Register for care](https://pr17721-0fgfioq95sm0vwnbjtb66620jxfv6us0.ci.cms.va.gov/admin/content?title=&type=vamc_system_register_for_care&moderation_state=All&owner=All)

VACMS-17381: Updates views configuration.

---

simplesamlphp-config-metadata/config/config.php

Relates to #17774
Tested on test infrastructure
Cannot be QAd on tugboat. If it passes all automated testing it should be good. 

17774 remove simplesamlphp salt and admin password from vagov cms and changes values

---

.ddev/config.yaml
.ddev/mutagen/mutagen.yml

Closes #17903.
Tested locally, ddev successfully started, restarted, and stopped. Pulled db and files. 
If this passes automated testing it should be good. 

VACMS-17903: ddev updates

---

config/sync/views.view.facility_services.yml

VACMS-7325: Adds number of services column and filter

---

composer.lock

Closes #17949.
If all automated testing passes this should be good. 

VACMS-17949: fix for composer.lock and drupal-test-traits

---

composer.lock
config/sync/field.storage.paragraph.field_office_visits.yml
config/sync/field.storage.paragraph.field_virtual_support.yml
docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityServiceVamc.php

VACMS-17843: change visit options virtual support

---

.ddev/config.yaml
.ddev/mutagen/mutagen.yml
.github/ISSUE_TEMPLATE/sitewide-crew-member-onboarding.md
.github/workflows/actions-metrics.yml
.github/workflows/contextual-advice.yml
.github/workflows/continuous_integration.yml
.github/workflows/cypress.yml
.github/workflows/default-branch-datadog-metrics.yml
.github/workflows/dependabot-auto-merge.yml
.github/workflows/pull-request-labels.yml
.github/workflows/set-tugboat-tests-pending.yml
composer.json
composer.lock
config/sync/views.view.facility_services.yml
docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityServiceVamc.php

Relates to #17956
_Note: also rebases integration branch from with `main` changes_
Manually

VACMS-17956: Add virtual support to VAMC health services push to Lighthouse

---

composer.json
composer.lock

Closes #17872
Added multiple content types in draft form. Signed in as super admin and content admin and tested if nodes were viewable in linkit.
What needs to be checked to prove this works? Add different content types and keep them in draft state (events, bios, etc). Go into another published or unpublished (draft) content type and try to add a link to one of the unpublished content types. 
What needs to be checked to prove it didn't break any related things? This was a patch specific to Linkit so there should not be any issues.
What variations of circumstances (users, actions, values) need to be checked? Super Admin and Content Admin
As user Super Admin and Content Admin
1. Do this
2. Then
Is an announcement needed to let editors know of …

VACMS-17872: Linkit fix for unpublished nodes.

---

READMES/upstream-dependencies.md
docroot/modules/custom/va_gov_backend/src/Plugin/views/access/PdfAuditAccess.php

Relates to #18094.
These changes are text changes only, no code, to use for the deployment of updates to the BRD deployment scripts. There is nothing to test. 

VACMS-18094: inconsequential changes for deployment

---

config/sync/views.view.content_entity_reference_source.yml

Relates to #10536
Tested using new Events while referencing NCA, VBA, Vet Center, and Vet Center Outstation facility types.
1. Visit /node/add/event

VACMS-10536: Updates entity reference source view for event->facility location

---

READMES/cms-collab-cycle/collab-cycle-qa.md
READMES/qa.md

Relates to #_18110_.
N/A
N/A
N/A

Adding/updating readme(s) for collab cycle and CMS testing

---

config/sync/system.menu.family-and-caregiver-benefits.yml

VACMS-18394: Adds menu config for Family and Caregiver Benefits

---

tests/phpunit/API/PostApiQueueTest.php

VACMS-18407: Updates path for Lighthouse v1 in PHPUnit test

---

docroot/sites/default/settings.php
docroot/sites/default/settings/settings.dev.php
docroot/sites/default/settings/settings.local.php
docroot/sites/default/settings/settings.prod.php
docroot/sites/default/settings/settings.staging.php
docroot/sites/default/settings/settings.tugboat.php

Relates to #18070 , and a follow-on to the work merged in this PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/18250
Next-Build will use our public file S3 buckets where Drupal's user files are available to the public via web. We do this by adding a request header when Next Build makes requests to Drupal; and then, on the Drupal side, to choose a different public file base URL if the request header is present. 
On the Next Build side, the change to add the header to the request to Drupal was done in this PR: https://github.com/department-of-veterans-affairs/next-build/pull/560
See QA steps; the same testing was done there. 
Noting for all this testing that the images not appearing for the staging domain dsva-vagov-staging-cms-files.s3.us-gov-west-1.amazonaws.com is a …

Rework of how the CMS responds to public file base header.

---

docroot/modules/custom/va_gov_vba_facility/src/EventSubscriber/VbaFacilitySubscriber.php

VACMS-17885 close link tag

---

config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
config/sync/field.field.node.health_care_local_facility.field_operating_status_more_info.yml

Relates to #15737
Tugboat verification
https://pr18495-jc2gb3a4aukubnpnwznjwcq6uyykpsap.ci.cms.va.gov/node/add/health_care_local_facility

VACMS-15737 Rework help text for operating status

---

config/sync/field.field.paragraph.phone_number.field_phone_extension.yml
config/sync/field.field.paragraph.phone_number.field_phone_label.yml
config/sync/field.field.paragraph.phone_number.field_phone_number.yml
config/sync/field.field.paragraph.phone_number.field_phone_number_type.yml

Updated help text based on Figma design comments

---

.github/dependabot.yml

Closes #18693 
This just effects dependabot opening PRs

VACMS-18693: removing package.json packages from dependabot

---

config/sync/feature_toggle.features.yml

Added CMS Feature Toggle in Support of DataDog RUM-BenefitsDecisionsReviewsTeam
Relates to #18409
Verify feature toggle exists in UI
As a Drupal Admin
1. Go to /admin/config/system/feature_toggle

VACMS-18409: Added CMS Feature Toggle in Support of DataDog RUM-BenefitsDecisionsReviewsTeam

---

composer.lock

Closes #18807 
If automated testing passes this should be good. 

VACMS-18807: updated geo modules

---

composer.json
composer.lock

Closes #19041 
Removing unused module

VACMS-19041: removing samlauth module

---

composer.json
composer.lock
patches/smart_date-undefined_value_in_validation-3260965-24-reroll.patch

Closes #18706 
- Module updated to 4.1.5 and patch applied without error
- Tested events content type to ensure error message still applied for recurring events that start before event date
As user _uid_ with  admin
1. Add a new event content type with a recurring date that starts before the event date.
2. Save new event

VACMS-18706:Update smart date, reroll patch and test.

---

config/sync/field.field.node.vet_center.field_mission_explainer.yml
config/sync/field.field.node.vet_center.field_vet_center_banner_image.yml

Relates to #19079
Manually
1. As an admin, go to the [Vet Center Mission Explainer field](https://pr19080-ouk9totqvprtelatpx7ozzuc8bbmxhhs.ci.cms.va.gov/admin/structure/types/manage/vet_center/fields/node.vet_center.field_mission_explainer)
2. Go to the [Vet Center banner image field](https://pr19080-ouk9totqvprtelatpx7ozzuc8bbmxhhs.ci.cms.va.gov/admin/structure/types/manage/vet_center/fields/node.vet_center.field_vet_center_banner_image)

VACMS-19079: Adds default value config

---

composer.lock

Closes #18995 
Module updated to V 2.0.2 without error. 
What needs to be checked to prove this works? Verify that patch is upgraded to V 2.0.2 and passes all checks

VACMS-18995: Update drupal metatag module.

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/s3fs.settings.yml

Install the s3fs module to preposition it for next week's deployment.
Relates to #18821
As long as this passes automated testing it should be good.

VACMS-18821: install s3fs module

---

composer.json
composer.lock
docroot/modules/custom/va_gov_backend/src/Logger/Processor/DatadogApmProcessor.php

Relates to #19113
1. Do this
2. Then

VACMS-19113: fixes for core update on staging

---

composer.json
composer.lock

Closes #18998 
Updated and applied new patch.

VACMS-18998: Update pathauto module.

---

tasks-periodic.yml

VACMS-19186: added pdf delete job to monthly cron

---

cypress.config.js
tests/cypress/integration/features/content_type/benefits_detail_page.feature
tests/cypress/integration/features/content_type/news_story.feature
tests/cypress/integration/features/content_type/press_release.feature
tests/cypress/integration/step_definitions/common/i_create_a_node.js
tests/cypress/support/accessibility.js

Closes #19002 
Run cypress tests locally and on tugboat.

VACMS-19002: comprehensive test plan identify and script e2e tests for additional content types

---

config/sync/core.entity_form_display.paragraph.digital_form_your_personal_info.default.yml
config/sync/core.entity_view_display.paragraph.digital_form_your_personal_info.default.yml
config/sync/field.field.node.digital_form.field_chapters.yml
config/sync/field.field.paragraph.digital_form_your_personal_info.field_identification_information.yml
config/sync/field.field.paragraph.digital_form_your_personal_info.field_name_and_date_of_birth.yml
config/sync/field.storage.paragraph.field_identification_information.yml
config/sync/field.storage.paragraph.field_name_and_date_of_birth.yml
config/sync/paragraphs.paragraphs_type.digital_form_your_personal_info.yml
config/sync/paragraphs_browser.paragraphs_browser_type.digital_forms.yml
scripts/content/digital-forms.php

Creates a new Paragraph type called "Your personal information" that contains the "Name and Date of Birth" and "Identification Information" Paragraph types within it. Removes "Name and Date of Birth" and "Identification Information" as selectable Steps. Updates the Digital Forms script to use the new Paragraph type.
- Closes department-of-veterans-affairs/va.gov-team#94366
- Manually created a Digital Form with a Step that included the "Your personal information" Paragraph type.
- Ran the updated script in my local environment and verified the creation of Digital Forms with the proper Steps.
The "Your personal information" Paragraph type inside of the Steps field:
1. Go to Manage > Content > Add content > Digital Form
2. In the "Steps" field, click "Add Step"
3. Click …

VATEAM-94366: Create "Your personal information" Paragraph type

---

config/sync/node.type.page.yml

Relates to #19481.
Manual in Tugboat
As user [4488](https://staging.cms.va.gov/user/4488) or a Content Admin 
1. [Login to the tugboat](https://pr19629-n55abtnmka82hdzehxwby3vswcrvznhq.ci.cms.va.gov/)
2. Then go to Content and [filter by Benefit Detail Pages](https://pr19629-n55abtnmka82hdzehxwby3vswcrvznhq.ci.cms.va.gov/admin/content?title=&type=page&moderation_state=All&owner=All)
3. Then go to Content > Add Content > [Benefit Detail Page](https://pr19629-n55abtnmka82hdzehxwby3vswcrvznhq.ci.cms.va.gov/node/add/page)

VACMS-19481: enable family member menu on Benefit detail pages

---

docroot/sites/default/maintenance.html

Change the deploy shield messaging.
Closes #19675 
If this passes testing, it should be good. There is no way to test on tugboat. 

VACMS-19675: updated deploy shield message

---

config/sync/next.next_entity_type_config.node.basic_landing_page.yml
config/sync/next.next_entity_type_config.node.campaign_landing_page.yml
config/sync/next.next_entity_type_config.node.checklist.yml
config/sync/next.next_entity_type_config.node.digital_form.yml
config/sync/next.next_entity_type_config.node.faq_multiple_q_a.yml
config/sync/next.next_entity_type_config.node.health_care_local_facility.yml
config/sync/next.next_entity_type_config.node.health_care_region_detail_page.yml
config/sync/next.next_entity_type_config.node.health_care_region_page.yml
config/sync/next.next_entity_type_config.node.health_services_listing.yml
config/sync/next.next_entity_type_config.node.landing_page.yml
config/sync/next.next_entity_type_config.node.leadership_listing.yml
config/sync/next.next_entity_type_config.node.locations_listing.yml
config/sync/next.next_entity_type_config.node.media_list_images.yml
config/sync/next.next_entity_type_config.node.media_list_videos.yml
config/sync/next.next_entity_type_config.node.office.yml
config/sync/next.next_entity_type_config.node.outreach_asset.yml
config/sync/next.next_entity_type_config.node.page.yml
config/sync/next.next_entity_type_config.node.person_profile.yml
config/sync/next.next_entity_type_config.node.publication_listing.yml
config/sync/next.next_entity_type_config.node.step_by_step.yml
config/sync/next.next_entity_type_config.node.support_resources_detail_page.yml
config/sync/next.next_entity_type_config.node.va_form.yml
config/sync/next.next_entity_type_config.node.vamc_operating_status_and_alerts.yml
config/sync/next.next_entity_type_config.node.vamc_system_billing_insurance.yml
config/sync/next.next_entity_type_config.node.vamc_system_medical_records_offi.yml
config/sync/next.next_entity_type_config.node.vamc_system_policies_page.yml
config/sync/next.next_entity_type_config.node.vamc_system_register_for_care.yml
config/sync/next.next_entity_type_config.node.vamc_system_va_police.yml
config/sync/next.next_entity_type_config.node.vba_facility.yml
config/sync/next.next_entity_type_config.node.vet_center_locations_list.yml

All content types added except those contained at https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/config/sync/va_gov_backend.exclusion_settings.yml
Closes #19644 
As long as automated tests pass this should be good. 

VACMS-19644: added entity types for nextjs

---

config/sync/content_sync.AdminSettings.yml
config/sync/core.extension.yml
content/sync/README.md

Reverts department-of-veterans-affairs/va.gov-cms#19832

VACMS-19496: Enable content sync with settings. REVERT

---

docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php

Relates to #19840 
Manually
1. [Log in](https://pr19845-ydff9q8ht9uxxqqd8agaf7yvtrzshc5z.ci.cms.va.gov/) as an admin
2. Assign the following sections to the QA Content Publisher
4. Assign the following roles to the QA Content Publisher:
1. Log in as QA Content Publisher
2. Edit the Manila VA Facility (`/node/1059/edit`)
- Change the operating status
- Save the node as published
3. Edit the [Kenosha VA Clinic] (`/node/1483/edit`)
- Change the operating status
- Save the node as published
1. Log in as an admin
2. Go to the Post API Queue (`/admin/config/post-api/queue`)

VACMS-19840: Updates Manila VA Clinic url

---

composer.json
composer.lock

Relates to #19921
1. Do this
2. Then

VACMS-19921: Updates content build version

---

composer.lock

Closes #19938 
If this passes automated testing, it should be good.

VACMS-19938: updating drupal core to v10.3.9

---

tests/cypress/integration/features/content_type/facilities/vamc/health_care_local_facility.feature
tests/cypress/integration/features/content_type/person_profile.feature

VACMS-19979: Updates cypress tests for phone number paragraph

---

config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
config/sync/core.entity_form_display.node.landing_page.default.yml
config/sync/core.entity_form_display.node.office.default.yml
config/sync/core.entity_view_display.node.campaign_landing_page.default.yml
config/sync/core.entity_view_display.node.landing_page.default.yml
config/sync/core.entity_view_display.node.office.connect_with_us.yml
config/sync/core.entity_view_display.node.office.default.yml
tests/cypress/integration/features/content_type/campaign_landing_page/clp_connect_with_us.feature

Relates to #19794
- Manual in Tugboat
- Cypress updated
Content | Prod | Tugboat
-- | -- | --
Office Edit | ![Screenshot 2024-11-27 at 11 05 02 AM](https://github.com/user-attachments/assets/dffacaae-6e95-41e8-b9c0-bb626999eaf3) | ![Screenshot 2024-11-27 at 10 57 04 AM](https://github.com/user-attachments/assets/086beb1c-a8ce-4b17-9ba0-ada745621ff8)
CLP Edit | ![Screenshot 2024-11-27 at 11 05 23 AM](https://github.com/user-attachments/assets/c91345eb-12ce-4639-80c7-fc314ec95d37) | ![Screenshot 2024-11-27 at 10 56 56 AM](https://github.com/user-attachments/assets/e0dafe72-40b7-4497-a894-fbfbc2389eba)
BHLP Edit | ![Screenshot 2024-11-27 at 11 05 48 AM](https://github.com/user-attachments/assets/1d1e75ba-8f96-4486-8692-a253c21c0ef5) | ![Screenshot 2024-11-27 at 10 56 …

VACMS-19794: Hiding Office-powered Connect With Us fields and updating Cypress Test

---

config/sync/field.field.media.document.field_document.yml

Updates the document upload help text.
Relates to #19912 
Local testing.

VACMS-19912: Updating document upload help text.

---

config/local/simplesamlphp_auth.settings.yml
config/prod/simplesamlphp_auth.settings.yml
config/stg/simplesamlphp_auth.settings.yml
config/tugboat/simplesamlphp_auth.settings.yml

Closes #20023 
Tested on test.prod.cms.va.gov
If this passes automated testing it should be good. 

VACMS-20023: update header_no_cache for simplesamlphp config

---

config/sync/metatag.metatag_defaults.node__event.yml

Relates to #19698
Changes the title for the event title tag in browsers to use the correct format
1. Do this
2. Then

VACMS-19698: Change title config for Events

---

docroot/modules/custom/va_gov_build_trigger/src/Traits/RunsDuringBusinessHours.php

This simply shifts Content Release to start an hour later, as approved by @EWashb .
#19883

Shift Content Release start time to 9 am.

---

READMES/getting-started.md

Updating guidance on pulling files down.

[DOCS] Update getting-started.md

---

.gitignore

Gitignore the core file that ddev sometimes generates.

Ignore core file that DDEV creates.

---

.ddev/config.yaml

remove comment

---

.github/actions/post-checkout/action.yml

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20394
Testing done in content-build repo.

Update actions/cache to latest version.

---

composer.json
composer.lock

Updates the config_split module due to moderate security alert: https://www.drupal.org/sa-contrib-2025-017
Relates to #20514 .
Build in tugboat
- Log into this tugboat
- navigate to `/admin/modules`
- filter on `config_split`
- verify that the version is `8.x-1.10`

update config_split module

---

.github/ISSUE_TEMPLATE/dark-launch.md

Accuracy for the Staging FE data > content release step

VAMCS-20516 Update dark-launch.md

---

composer.json
composer.lock

Relates to #20308 
As long as this passes automated testing it should be good.

VACMS-20308: update content-build and simplesamlphp dependencies

---

composer.lock

Closes to #20600
Pipeline tests
- Tugboat instance looks good
- Tests pass
- Basic Drupal functionality in tugboat instance

update drupal core

---

composer.json
composer.lock

Closes to #20599
Pipeline tests
- deployment works
- view tugboat for this PR

updated content-build

---

composer.json
composer.lock

Relates to #20599 
If this passes automated testing we should be good.

VACMS-20599: update va-gov/content-build

---

composer.json
composer.lock

VACMS-20750: updated content-build

---

.github/workflows/default-branch-datadog-metrics.yml
.github/workflows/s3-backup-retention.yml

Relates to #20694 
Upcoming Daylight Saving Time on Sunday, this aims to adjust GItHub Workflows that will run this Sunday, Monday etc
What needs to be checked to prove this works? A scheduled run
1. Do this
2. Then

VACMS-20694 adjust workflows for dst to est

---

tasks-periodic.yml

Closes #20844.
This pull request simplifies the `tasks-periodic.yml` file by removing the use of inline bash scripts and replacing them with direct task calls. This change improves readability and maintainability.
Key changes include:
* Simplified the `daily` task by replacing the inline bash script with direct task calls.
* Simplified the `daily_0800` task by replacing the inline bash script with direct task calls.
* Simplified the `periodic` task by replacing the inline bash script with direct task calls.
* Simplified the `every_minute` task by replacing the inline bash script with direct task calls.
Tested on prod. `every_minute` jobs run correctly. 
What variations of …

VACMS-20844: refactored cron jobs to address syntax changes

---

composer.json
composer.lock

Relates to #[20752](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20752)
Updates to latest version as per https://packagist.org/packages/va-gov/content-build
NA
NA
1. Do this
2. Then

VACMS-20752: Updating content-build to v0.0.3702

---

config/sync/eca.eca.workflow_vba_facility_as_draft.yml

Adds VBA Facility Service to the existing ECA workflow that sends email notifications for content moving into the draft workflow state.
Relates to #20698
This pull request includes changes to the `config/sync/eca.eca.workflow_vba_facility_as_draft.yml` file to update dependencies and events for a new workflow transition. The most important changes include adding a new node type to the dependencies and defining a new workflow transition event.
Updates to dependencies:
* Added `node.type.vba_facility_service` to the list of dependencies.
Updates to events:
* Added a new `workflow_transition_1` event with a state transition configuration for `node vba_facility_service` from an empty state to `draft`.
Manual and automated unit testing
<details><summary>Email body</summary>
<p>
Changes were …

VACMS-20698: Adds VBA Facility Service to VBA Facility Draft ECA Workflow

---

composer.json
composer.lock

Closes #20937 
This pull request includes a version update to the `composer.json` file. The `va-gov/content-build` dependency has been updated to version `^0.0.3708`.
Dependency update:
* [`composer.json`](diffhunk://#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34L233-R233): Updated `va-gov/content-build` from `0.0.3702` to `^0.0.3708`.
As long as automated testing passes this should be good.

VACMS-20937: update content-build

---

composer.lock

Drupal Core Update: Updated Drupal Core to version 10.3.14
Closes #20928
Ran the command **ddev drush status** with the following results
```
Drupal version   : 10.3.14                                            
Site URI         : http://default                                     
DB driver        : mysql                                              
DB hostname      : db                                                 
DB port          : 3306                                               
DB username      : db                                                 
DB name          : db                                                 
Database         : Connected                                          
Drupal bootstrap : …
```

VACMS-20928: Updated Drupal Core to version 10.3.14

---

composer.json
composer.lock
config/sync/core.entity_form_display.node.digital_form.default.yml
config/sync/core.entity_view_display.node.digital_form.default.yml
config/sync/core.entity_view_display.node.digital_form.external_content.yml
config/sync/core.entity_view_display.node.digital_form.teaser.yml
config/sync/field.field.node.digital_form.field_form_application_url.yml
config/sync/field.field.node.digital_form.field_plain_language_title.yml
config/sync/field.storage.node.field_form_application_url.yml
docroot/modules/custom/va_gov_form_builder/src/Controller/VaGovFormBuilderController.php
docroot/modules/custom/va_gov_form_builder/templates/page-content/base/single-column-with-buttons.html.twig
tests/cypress/integration/features/content_type/campaign_landing_page/clp_connect_with_us.feature
tests/cypress/integration/features/content_type/facilities/vamc/health_care_local_health_service.feature

Relates to https://github.com/department-of-veterans-affairs/va.gov-team/issues/100805
Adds new field to the Digital Form content type. Updates logic for previewing a Digital Form to use new field.
Verified button rendered (or didn't render) with these 5 cases of field values:
- `https://staging.va.gov/form-application-url`
- `staging.va.gov/form-application-url`
- `/form-application-url`
- `form-application-url`
- `empty field`
1. Do this
2. Then

VAGOV-TEAM-100805 digital form app url field & render logic

---

composer.lock
docroot/modules/custom/va_gov_content_types/src/Interfaces/ContentReleaseTriggerInterface.php
docroot/modules/custom/va_gov_content_types/src/Interfaces/GetOriginalInterface.php
docroot/modules/custom/va_gov_content_types/src/Traits/ContentModerationTransitionsTrait.php
docroot/modules/custom/va_gov_content_types/src/Traits/ContentReleaseTriggerTrait.php
docroot/modules/custom/va_gov_content_types/src/Traits/DidChangeOperatingStatusTrait.php
docroot/modules/custom/va_gov_content_types/src/Traits/GetOriginalTrait.php
docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityBase.php
tests/phpunit/va_gov_content_release/unit/EventSubscriber/EntityEventSubscriberTest.php
tests/phpunit/va_gov_content_types/functional/Traits/ContentModerationTransitionsTraitTest.php
tests/phpunit/va_gov_content_types/functional/Traits/GetOriginalTraitTest.php
tests/phpunit/va_gov_content_types/unit/Traits/ContentModerationTransitionsTraitTest.php
tests/phpunit/va_gov_content_types/unit/Traits/ContentReleaseTriggerTraitTest.php
tests/phpunit/va_gov_content_types/unit/Traits/DidChangeOperatingStatusTraitTest.php
tests/phpunit/va_gov_content_types/unit/Traits/GetOriginalTraitTest.php

21146 update eca module to v217 tcosgrove

---

composer.json
composer.lock

Version update for april 17
Relates to #[21172](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21172)
This pull request includes a minor version update for a dependency in the `composer.json` file.
* Updated the `va-gov/content-build` dependency from version `^0.0.3727` to `0.0.3730`, ensuring compatibility with the latest changes.
NA
MA
1. Do this
2. Then

17 April Composer updates

---

composer.json
composer.lock
config/sync/block_inactive_users.settings.yml
config/sync/block_inactive_users.settings_cancel_users.yml
config/sync/core.extension.yml

Installed Block Inactive Users module and set up an initial configuration
Closes #_20959_. (or closes?)
This pull request introduces the integration of the `block_inactive_users` module into the project. The changes include adding the module as a dependency, configuring its settings, and enabling it in the system. Below are the most important changes grouped by theme:
* Added the `block_inactive_users` module as a dependency in `composer.json` with version `^2.8`.
* Enabled the `block_inactive_users` module in the `core.extension.yml` configuration file.
* Added a new configuration file `block_inactive_users.settings.yml` with settings for email notifications, idle time, roles to exclude, and other module-specific options.
* Added a new configuration file …

VACMS-20959: Block-Inactive-Users

---

composer.json
composer.lock

Close #21174 
This pull request includes a minor update to the `composer.json` file, updating the version of the `va-gov/content-build` dependency from `^0.0.3731` to `^0.0.3733`.
As long as thispasses automated testing we should be good.

VACMS-21174: update content-build

---

composer.json
composer.lock

Closes #21175 
This pull request includes a version update for a dependency in the `composer.json` file.
* Updated the `va-gov/content-build` dependency from version `^0.0.3733` to `0.0.3736` to ensure compatibility or include the latest changes.
1. Do this
2. Then

Update content-build dependency

---

composer.json
composer.lock

#21271 
1. Go to the Dashboard for the Tugboat instance for this PR: https://tugboat.vfs.va.gov/6813b18809d190440ba7c14f
2. Open 'Terminal' for the PHP service.
3. `cd web`
4. `git log`: the top commit should be `6733e7aeb14ca017561068a7021d03340fa88b67`

Update content-build to 0.0.3738.

---

docroot/.htaccess

Relates to #21097
Accounts for the additional rewrite conditions that lock down added php files, causing them to return a 403.
This pull request includes a security-related update to the `.htaccess` file in the `docroot` directory. The change ensures that URI conditions for PHP file access are anchored at the start of the path, improving the specificity and reliability of the access control rules.
* Updated `RewriteCond` rules to anchor URI conditions at the start (`^`) for better security and to prevent potential bypasses. This change affects conditions for core PHP files, test-specific PHP files, and the Statistics module's custom front controller. (`[docroot/.htaccessL167-R174](diffhunk://#diff-97a20696a8f6a925104f5174167c8c6f73dd7606b1f7f263dea1f1d9e23969cbL167-R174)`)
Manually
Add …

VACMS-21097: More .htaccess file permissions

---

docroot/modules/custom/va_gov_form_builder/css/form-info.css
docroot/modules/custom/va_gov_form_builder/css/response-kind.css
docroot/modules/custom/va_gov_form_builder/css/step-style.css
docroot/modules/custom/va_gov_form_builder/src/Controller/VaGovFormBuilderController.php
docroot/modules/custom/va_gov_form_builder/src/Form/ChoiceType.php
docroot/modules/custom/va_gov_form_builder/src/Form/DateType.php
docroot/modules/custom/va_gov_form_builder/src/Form/ResponseKind.php
docroot/modules/custom/va_gov_form_builder/src/Form/TextType.php
docroot/modules/custom/va_gov_form_builder/templates/form/custom-single-question-date-range-response.html.twig
docroot/modules/custom/va_gov_form_builder/templates/form/custom-single-question-page-title.html.twig
docroot/modules/custom/va_gov_form_builder/templates/form/custom-single-question-single-date-response.html.twig
docroot/modules/custom/va_gov_form_builder/templates/form/custom-single-question-text-area-response.html.twig
docroot/modules/custom/va_gov_form_builder/templates/form/custom-single-question-text-input-response.html.twig
docroot/modules/custom/va_gov_form_builder/templates/form/form-info.html.twig
docroot/modules/custom/va_gov_form_builder/templates/page-content/identification-info.html.twig
docroot/modules/custom/va_gov_form_builder/templates/page-content/layout.html.twig
docroot/modules/custom/va_gov_form_builder/templates/page-content/step-style.html.twig
docroot/modules/custom/va_gov_form_builder/va_gov_form_builder.module
tests/phpunit/va_gov_form_builder/functional/Form/FormInfoTest.php
tests/phpunit/va_gov_form_builder/functional/content-pages/LayoutTest.php
tests/phpunit/va_gov_form_builder/unit/ModuleTest.php

Fixes for various issues raised in audit.
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/109099
- Very little testing required. Changes were almost entirely copy related. Not adjusting functionality.
Misc.
As a Form Builder user:
1. Load an existing for or create a new one.

VAGOV-TEAM-109099: Final changes

---

composer.json
composer.lock

Closes #21275 
This pull request includes a version update for the `va-gov/content-build` dependency in the `composer.json` file.
* [`composer.json`](diffhunk://#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34L234-R234): Updated the `va-gov/content-build` dependency from version `^0.0.3743` to `^0.0.3744`.

VACMS-21275: update content-build

---

tests/phpunit/va_gov_form_builder/functional/Form/IntroductionTest.php
tests/phpunit/va_gov_git/functional/Repository/RepositoryTest.php

remove group test

---

docroot/modules/custom/va_gov_form_builder/css/custom-single-question-response.css

Relates to https://github.com/department-of-veterans-affairs/va.gov-team/issues/109099
- Manual visual
As a Form Builder user
1. Go to checkbox or radio page.
2. Shrink screen width until the line in the screenshot wraps.

VAGOV-TEAM-109099: Small css change to adjust line spacing.

---

composer.json
composer.lock

Relates to #21406 
This pull request includes a minor update to the `composer.json` file. The change updates the version of the `va-gov/content-build` package from `^0.0.3763` to `^0.0.3766`.
1. Do this
2. Then

VACMS-21406: Updates content-build to 0.0.3766

---

tests/cypress/integration/features/api/event_listing.feature
tests/cypress/integration/step_definitions/facilities/event_listing_api_data_flow.js

Relates to #21322 
This pull request introduces enhancements to the event listing API tests, adding a new scenario and supporting step definitions to validate the API flow for specific paths. The changes improve test coverage and ensure the API behaves as expected when navigating event listings.
* **New scenario for event listing flow**: Added a test scenario in `tests/cypress/integration/features/api/event_listing.feature` to validate that JSON API consumers can follow the event listing flow for a given path.
* **Step definition for event listing API flow**: Implemented a step definition in `tests/cypress/integration/step_definitions/facilities/event_listing_api_data_flow.js` to support the new scenario. This includes:
- A helper function, `fetchAndCheckEventPage`, to fetch and validate …

VACMS-21322: Adds more detailed test for event listing

---

docroot/modules/custom/va_gov_content_release/src/Form/NextGitForm.php

Closes  to #[21610](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21610)
This pull request enhances the `NextGitForm` class by integrating environment-specific behavior and improving user experience based on the current environment. The changes introduce the `DiscoveryInterface` service to determine the environment and conditionally disable form elements in non-Tugboat and non-local environments.
* Added the `DiscoveryInterface` dependency to the `NextGitForm` class, including updates to the constructor, property definitions, and the `create` method to inject the service. (`docroot/modules/custom/va_gov_content_release/src/Form/NextGitForm.php`, [[1]](diffhunk://#diff-115eca002ef405fbc96ec954602bbc331c0cdcb8cbe1167e2425cdc62533a1bcR16) …

Disable form if in BRD env and add status.

---

docroot/modules/custom/va_gov_migrate/src/Service/VaGovMigrateService.php
docroot/modules/custom/va_gov_migrate/va_gov_migrate.services.yml
docroot/modules/custom/va_gov_scheduled_tasks/config/ultimate_cron.job.va_gov_scheduled_tasks_eight.yml
docroot/modules/custom/va_gov_scheduled_tasks/va_gov_scheduled_tasks.module

Vacms 21396 0800 cron

---

tests/cypress/integration/features/api/vamc_police.feature

Relates to #[20479](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20479)
This pull request introduces new Cypress test scenarios to verify API functionality related to `vamc_police` routes and nodes. These tests ensure proper responses are returned for specific API requests.
* [`tests/cypress/integration/features/api/vamc_police.feature`](diffhunk://#diff-bac1676545969ff9ed30b218ea7153be1ed0b5aa3c4535d1796beecd1a3fe107R1-R8): Added two scenarios to validate that an anonymous user receives a status code 200 when accessing the route translation and `vamc_police` nodes via the specified API endpoints.
Adding a test
What variations of circumstances (users, …

VACMS-20488: Post Launch Police Page

---

composer.lock

Closes #21830 
As long as this passes automated testing, it should be good. 

VACMS-21830: drupal module upgrades

---

.tugboat/config.yml
composer.json
scripts/compile-theme.sh

Relates to #21389.
Some additional design system components need to be taken out to prevent jenkins
1. Do this
2. Then

VACMS-21389: delete design system components

---

docker/apache/Dockerfile

Adding some config for apcu and opcahce to (hopefully) improve php performance
This pull request updates the PHP configuration in the `docker/apache/Dockerfile` to optimize performance and stability. The main changes involve significantly increasing opcache limits, adding recommended APCu settings, and clarifying configuration sections.
**PHP performance and configuration improvements:**
* Increased opcache limits and added new recommended opcache settings for better PHP performance, including raising `opcache.memory_consumption` to 1024, `opcache.interned_strings_buffer` to 16, `opcache.max_accelerated_files` to 42000, disabling timestamp validation, and enabling fast shutdown.
* Added recommended APCu settings, enabling APCu for CLI, increasing shared memory size, and enabling RFC1867 …

php perf tweaks

---

scripts/build-frontend.sh

#21789 
1. Visit the content-build Tugboat for this PR: https://web-k3muyquqm9wcegf73kez1fm50vcddshf.ci.cms.va.gov/
2. Check that fonts load. You should see fonts.

Always build vets-website when building the content-build frontend.

---

docker/apache/Dockerfile
docker/apache/docker-conf-files/install-va-certs.sh
docroot/sites/default/settings/settings.dev.php

Relates to #22188
This pull request makes several improvements to the Apache/PHP Docker setup and the Drupal development settings. The most significant changes enhance performance and reliability by tuning PHP-FPM and Apache configurations, improving certificate handling, and ensuring proper reverse proxy support in the development environment.
* Increased PHP-FPM resource limits for better concurrency: `pm.max_children` raised to 100, `pm.start_servers` to 20, `pm.min_spare_servers` to 15, `pm.max_spare_servers` to 50, and `pm.max_requests` to 1000 in `www.conf`.
* Enabled the `mpm_event` Apache module and added a new config to set `MaxRequestsPerChild`, `ThreadsPerChild`, and `MaxConnectionsPerChild` for improved Apache performance. …

VACMS -21855: update dockerfile for apache

---

.github/workflows/build-drupal-container.yml
Dockerfile
docker/apache/Dockerfile

Relates to #22188 
This pull request introduces several configuration changes to improve the scalability, reliability, and traceability of the Drupal container and Apache/PHP-FPM setup. The most significant updates include increasing resource limits for Apache and PHP-FPM to support higher concurrency, setting longer timeouts for proxies and connections, and adding build metadata for improved traceability.
**Resource and performance configuration:**
* Increased Apache MPM event module limits (`ServerLimit`, `MaxRequestWorkers`, `ThreadsPerChild`, etc.) to support higher concurrency, and enabled these settings via a new `mpm-event.conf` file.
* Raised PHP-FPM pool settings (`pm.max_children`, `pm.start_servers`, `pm.min_spare_servers`, and `pm.max_spare_servers`) to allow more simultaneous …

VACMS-22188: adjust apache config in apache Dockerfile

---

docker/apache/Dockerfile

Relates to #22188 
This pull request makes a minor change to the Apache Dockerfile, renaming the custom opcache configuration file to ensure it loads last.
* Renamed the opcache custom configuration file from `99-opcache-custom.ini` to `zz-opcache-custom.ini` in the `docker/apache/Dockerfile` to guarantee it is loaded after all other configurations.

VACMS-22188: rename opcache conf file so it loads in correct order

---

docker/apache/Dockerfile

Relates to #22188 
This pull request updates the PHP-FPM configuration in the `docker/apache/Dockerfile` to improve process management and adjust opcache settings.
**PHP-FPM process management changes:**
* Changed the `pm` (process manager) setting from `dynamic` to `static` in `www.conf`, which means PHP-FPM will now always maintain a fixed number of child processes instead of scaling dynamically.
* Increased `pm.max_children` from 5 to 250, `pm.start_servers` from 2 to 20, and `pm.min_spare_servers` from 1 to 5, allowing for greater concurrency and throughput.
**Opcache configuration adjustments:**
* Removed the explicit enabling of opcache (`php_admin_value[opcache.enable] = 1`) from the `kubernetes.conf` file, possibly relying on the default or another configuration for this setting. …

VACMS-22188: tweak fpm config

---

docker/apache/Dockerfile

Relates to #22188
This pull request makes two small but important changes to the `docker/apache/Dockerfile` to improve server resource limits and ensure proper installation paths for development tools.
Resource and performance configuration:
* Increased the Apache `ServerLimit` from 10 to 50, allowing the server to handle more concurrent processes and improve scalability.
Development tooling:
* Modified the Taskfile installation command to explicitly set the binary installation directory to `/usr/local/bin`, ensuring the tool is available in the expected location.
Is an announcement needed to let …

VACMS-22188: adjust settings for fpm

---

composer.json
composer.lock
docroot/modules/custom/va_gov_user/src/Form/VaGovUserMigrateSourceUiForm.php

Until further notice, the main branch of this repo is locked. Pull requests should be made against the [integration-202510](https://github.com/department-of-veterans-affairs/va.gov-cms/tree/integration-202510) branch. 
Merges to the main branch for critical bugs or security updates are allowed. Please contact CMS Team in the [#platform-cms-team](https://dsva.slack.com/archives/CT4GZBM8F) channel if you need assistance. 
| Module name | Version on main | Version in PR |
| ----------- | --------------- | ------------- |
| drupal/config_override_warn       | 1.4.0        | 1.5.0     |
| drupal/consumers                  | 1.20.0       | 1.21.0    |
| drupal/devel                      | 5.3.1        | 5.4.0     |
| drupal/entityqueue                | 1.9.0        | 1.10.0    |
| …

VACMS-22221: Drupal module updates
