config/sync/core.entity_view_display.node.landing_page.teaser.yml

This fixes a minor glitch that left config/sync/core.entity_view_display.node.landing_page.teaser.yml in an 'update' state even after it was successfully imported using drush cim. To see the problem, run drush cim. It will import successfully. But when you run drush cim again, core.entity_view_display.node.landing_page.teaser.yml still shows up as needing to update.
This patch shouldn't change the landing page teaser at all (not that that matters). It just makes cim recognize that it's in sync.

VAGOV-000: Re-exported landing page teaser display config.

---

composer.json
composer.lock
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_alert_block.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_healthcare.yml
docroot/modules/custom/va_gov_migrate/src/EventSubscriber/PostRowSave.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/ExpandableText.php
docroot/modules/custom/va_gov_migrate/src/ParagraphMigrator.php
docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/source/AlertBlockSource.php
docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/source/MetalsmithSource.php

To test:
1. Run composer install
2. Run drush cr 
2. Uninstall and reinstall va_gov_migrate module
3. From UI run 'Migrate alert blocks from va.gov'. Then run 'Import healthcare pages and paragraphs from va.gov'. OR From command line, run lando drush mim va_healthcare --update
4. That should generate 4 alert blocks and attach them to appropriate basic pages, e.g. 'Depression Treatment For Veterans', 'Order Hearing Aid Batteries And Prosthetic Socks From VA', 'Posttraumatic Stress Disorder (PTSD)', 'Get Your VA Medical Records Online'.
@andyhawks the latest composer update hosed drupal for me until I ran drush cr. When this gets merged, could you warn everyone about that if I forget to?

Vagov 934 migrate alert blocks

---

docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_support_service.yml
docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/source/SupportService.php

To test:
1. Uninstall and reinstall va_gov_migrate module.
2 Run migration, "Import support services from va.gov" (va_support_service).
3. Verify that 10 nodes of type, 'Support Service', were created. 
4. Verify that links in the "Ask Questions" block on the right rail of https://www.va.gov/health-care/ have corresponding Support Service nodes.

VAGOV-942: Added support services migration.

---

config/sync/core.entity_form_display.node.landing_page.default.yml
config/sync/core.entity_view_display.node.landing_page.default.yml
config/sync/field.field.node.landing_page.field_promo.yml
config/sync/field.storage.node.field_promo.yml
config/sync/migrate_plus.migration.va_alert_block.yml
config/sync/migrate_plus.migration.va_healthcare.yml
config/sync/migrate_plus.migration.va_hub.yml
config/sync/migrate_plus.migration.va_promo.yml
config/sync/migrate_plus.migration.va_promo_images.yml
config/sync/migrate_plus.migration.va_promo_media.yml
config/sync/migrate_plus.migration.va_support_service.yml
config/sync/migrate_plus.migration.va_work_areas.yml
config/sync/migrate_plus.migration_group.va_gov.yml
config/sync/views.view.va_blocks_admin.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_hub.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_promo.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_promo_images.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_promo_media.yml
docroot/modules/custom/va_gov_migrate/src/EventSubscriber/PostRowSave.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/LinksListItem.php

To test:
1. Import config (drush cim). 
2. Run hub migration ('Import hub pages and paragraphs from va.gov' from ui or 'drush mim va_hub --execute-dependencies --update' from command line).
3. Verify that there are now 9 promo blocks with images (/admin/content/promos).
4. Verify that hub pages now have links to promo blocks (near bottom of edit page, in 'Right Rail' section.
(Note that this pr also contains rebased branches VAGOV-1309-et and VAGOV-000-update-migrate-config)

Vagov 933 migrate promos

---

config/sync/core.entity_form_display.node.landing_page.default.yml
config/sync/core.entity_view_display.node.landing_page.default.yml
config/sync/field.field.node.landing_page.field_support_services.yml
config/sync/field.storage.node.field_support_services.yml
config/sync/migrate_plus.migration.va_alert_block.yml
config/sync/migrate_plus.migration.va_healthcare.yml
config/sync/migrate_plus.migration.va_hub.yml
config/sync/migrate_plus.migration.va_promo.yml
config/sync/migrate_plus.migration.va_promo_images.yml
config/sync/migrate_plus.migration.va_promo_media.yml
config/sync/migrate_plus.migration.va_support_service.yml
config/sync/migrate_plus.migration.va_work_areas.yml
config/sync/migrate_plus.migration_group.va_gov.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_hub.yml

To test:
1. Sync config (drush cim)
2. Run "Import hub pages and paragraphs from va.gov" migration with 'update' checked (drush mim --update --execute-dependencies
3. Verify that hub pages have a 'Support Services' field and it's populated.
Note:
I used Inline Entity Form for Support Services field. Not sure how that will or should affect editing permissions for Support Service nodes.

VAGOV-1313 add support services to hubs

---

.lando.yml

This matches what is in the lando-entrypoint-app.sh script now and
mirrors what happens on our deploys.

VAGOV-1558: Add cache:rebuild, updatedb & config:import to new pre-db-sync-stg event hook.

---

docroot/modules/custom/va_gov_migrate/src/Paragraph/ExpandableText.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/LinksListItem.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/NumberCallout.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/QaSection.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/ReactWidget.php
docroot/modules/custom/va_gov_migrate/src/ParagraphMigrator.php
docroot/modules/custom/va_gov_migrate/src/ParagraphType.php

This fixes the problem with internal urls on the site. They still won't link to anything yet, but they won't break the page now. Also fixed a couple of places where the text format wasn't set to rich text. It looked fine in drupal, but graphql was encoding the html.

VAGOV-000: Add scheme to internal uri's and format to rich text fields

---

config/sync/migrate_plus.migration.va_alert_block.yml
config/sync/migrate_plus.migration.va_benefits_menu.yml
config/sync/migrate_plus.migration.va_healthcare.yml
config/sync/migrate_plus.migration.va_hub.yml
config/sync/migrate_plus.migration.va_outreach.yml
config/sync/migrate_plus.migration.va_outreach_doc_media.yml
config/sync/migrate_plus.migration.va_outreach_embedded_images.yml
config/sync/migrate_plus.migration.va_outreach_files.yml
config/sync/migrate_plus.migration.va_outreach_image_media.yml
config/sync/migrate_plus.migration.va_outreach_video.yml
config/sync/migrate_plus.migration.va_promo.yml
config/sync/migrate_plus.migration.va_promo_images.yml
config/sync/migrate_plus.migration.va_promo_media.yml
config/sync/migrate_plus.migration.va_support_service.yml
config/sync/migrate_plus.migration.va_work_areas.yml
config/sync/migrate_plus.migration_group.va_gov.yml
config/sync/migrate_plus.migration_group.va_outreach.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_benefits_menu.yml
docroot/modules/custom/va_gov_migrate/data/sidebar.json
docroot/modules/custom/va_gov_migrate/src/EventSubscriber/PostRowSave.php
docroot/modules/custom/va_gov_migrate/src/Form/VaMenuTruncateForm.php
docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/source/AlertBlockSource.php
docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/source/MetalsmithSource.php
docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/source/VaBenefitsMenu.php
docroot/modules/custom/va_gov_migrate/va_gov_migrate.routing.yml

Before running menu migration ('Import menu links for health care benefits main menus'):
1. Create a menu with machine name 'health-care-benefits-hub'.
2. Run an update migration for benefits pages ('Import basic pages and paragraphs from va.gov'). This will give them all the same aliases they have on the current site, which the menu migration uses for generating menu link routes.
This migration only pulls in Health Care, but I've set it up so that other sections can be specified in the yaml.
I've also included a form to delete items from the main menu. No need to run it for this migration, but it'll be useful when we do the main menu migration. There's no menu link for it, but it's at /admin/config/structure/va_gov_migrate/truncate-menu.
Let me know when this is pushed and I'll do the …

Vagov 1568 migrate sidebar nav

---

config/sync/migrate_plus.migration.va_alert_block.yml
config/sync/migrate_plus.migration.va_healthcare.yml
config/sync/migrate_plus.migration.va_hub.yml
config/sync/migrate_plus.migration.va_main_menu.yml
config/sync/migrate_plus.migration.va_outreach.yml
config/sync/migrate_plus.migration.va_outreach_doc_media.yml
config/sync/migrate_plus.migration.va_outreach_embedded_images.yml
config/sync/migrate_plus.migration.va_outreach_files.yml
config/sync/migrate_plus.migration.va_outreach_image_media.yml
config/sync/migrate_plus.migration.va_outreach_video.yml
config/sync/migrate_plus.migration.va_promo.yml
config/sync/migrate_plus.migration.va_promo_images.yml
config/sync/migrate_plus.migration.va_promo_media.yml
config/sync/migrate_plus.migration.va_support_service.yml
config/sync/migrate_plus.migration.va_work_areas.yml
config/sync/migrate_plus.migration_group.va_gov.yml
config/sync/migrate_plus.migration_group.va_outreach.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_main_menu.yml
docroot/modules/custom/va_gov_migrate/data/megamenu.json
docroot/modules/custom/va_gov_migrate/src/EventSubscriber/PostRowSave.php
docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/source/VaBenefitsMenu.php
docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/source/VaMainMenu.php

This got lost in the shuffle last sprint, but here it is. 
To test:
1. Go to /admin/config/structure/va_gov_migrate/truncate-menu to delete all the items currently in the main menu.
2. Run the 'Import menu links for health care benefits main menus' migration.
The main menu should now match the one on va.gov.

VAGOV-1568 migrate main nav

---

docker/config/engine/scripts/lando-entrypoint-app.sh

we need to create files dir since docker entry point script will expect it to be present in the case we are not using EFS

VAGOV-1681 Create files directory for PRs

---

docroot/sites/default/settings/settings.test.php

Currently getting this on pr-123.* hostnames for https://github.com/department-of-veterans-affairs/va.gov-cms/pull/198:
> Warning: preg_match(): Compilation failed: nothing to repeat at offset 1 in Symfony\Component\HttpFoundation\Request->getHost() (line 1303 of /app/docroot/vendor/symfony/http-foundation/Request.php).The provided host name is not valid for this server.

VAGOV-1757 Fix trusted host pattern to support PR/TEST ENVs.

---

tests/phpunit/PerformancePreviewTest.php
tests/phpunit/SecurityRolesPermissionsTest.php

CI/PR is breaking due to PerformancePreviewTest and SecurityRolesPermissionsTest. 
So far this PR contains fixing the former, which simply adds a `@group disabled`. We need an export for the latter still. 
Update: second part has been committed, tests passing locally.

VAGOV-1962 Fix PHPUnit tests breaking on builds

---

docroot/modules/custom/va_gov_migrate/data/sidebar.json
docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/source/VaBenefitsMenu.php
docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/source/VaMainMenu.php
docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/source/VaMenuBase.php

Code cleanup, removed unneeded 'va.gov' domains from main menu links, and updated sidebar data to be up-to-date with latest menu changes on va.gov.
To test:
Perform update migrations on 'Migrate health care sidebar menu' and 'Migrate VA.gov main menu'. 
Healthcare Benefits Hub menu and Main menu should match va.gov and links should only include domains if they link to sites outside of va.gov.

Vagov 000 update menus

---

config/sync/metatag.metatag_defaults.global.yml
config/sync/metatag.metatag_defaults.node__event.yml

Changes twitter card config in metatag module to display a card with summary and a large image.
[JIRA ticket](https://va-gov.atlassian.net/browse/VAGOV-1532)
Has a non-breaking relationship with this PR: https://github.com/department-of-veterans-affairs/vets-website/pull/9758 Non-breaking meaning that these PRs will work without each other and merging one before the other won't break any builds. Note: Merge in the va.gov-cms one first to get correct styling for the share cards tho.

VAGOV-1532: Update Twitter Metatag Config.

---

docroot/sites/default/settings/settings.dev.php
docroot/sites/default/settings/settings.fast_404.php
docroot/sites/default/settings/settings.test.php

VAEC deploys were breaking with failed includes on STG and PROD but not DEV. Not sure why this wasn't showing up in A6 STG deploy. Also added to TEST/PR ENVs so we can keep functionality the same across ENVs and catch stuff like this earlier in the process.

VAGOV-320 Fix fast404 include and add to DEV and TEST/PR

---

docroot/modules/custom/va_gov_migrate/src/Paragraph/AdditionalInformation.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/QaSection.php
docroot/modules/custom/va_gov_migrate/src/ParagraphMigrator.php

This fixes issues 1. and 6. that Brauer identified. It also adds the "Additional information" (aka Spanish language translation) paragraph. Fixing the test uncovered the fact that that was missing.
I've done spot checks, comparing metalsmithed pages to the live site on about half the pages and it looks good: problems fixed, no new ones introduced.

Vagov 1993 migration fix

---

config/sync/core.entity_form_display.node.landing_page.default.yml
config/sync/core.entity_view_display.node.landing_page.default.yml
config/sync/field.field.node.landing_page.field_title_icon.yml
config/sync/field.storage.node.field_title_icon.yml

Adds a field to choose an icon that will appear next to hub landing page titles. This config is required by this front-end PR: https://github.com/department-of-veterans-affairs/vets-website/pull/9784

VAGOV-1755: Add a field to choose an icon for hub landing page titles

---

config/sync/filter.format.rich_text.yml

Migrated content has a 45 <b> tags that are not currently getting stripped out by Drupal.

VAGOV-2014: Allow <b> tags in rich text editor.

---

docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/source/VaBenefitsMenu.php

This is a request from Jeff Balboni. Apparently, when the menu links to va.gov teamsite pages are relative, the broken link checker thinks they're broken links.

VAGOV-000: Make menu links to va.gov teamsite pages absolute.

---

config/sync/editor.editor.rich_text.yml
config/sync/filter.format.rich_text.yml

Fixes lack of button styling in alert block on https://staging.va.gov/health-care/get-medical-records/
When you're in drupal wysiwyg and on a link, the style list should now include "Primary link button". Selecting it should add class "usa-button-primary" to the link.

VAGOV-1999: Add 'Primary button' option to link styles in wysiwyg.

---

.lando.yml

The S3 bucket for sanitized backups was made private and isn't supposed
to be public, even though we don't have PII in it. We need to manually
download the backup files for now until a permanent internal access
solution is created (in progress).

VAGOV-3079 Fix sync-db, sync-files commands to use manually downloaded files temporarily.

---

config/sync/core.entity_form_display.node.outreach_asset.default.yml
config/sync/core.entity_view_display.node.outreach_asset.default.yml
config/sync/field.field.node.outreach_asset.field_office.yml
config/sync/node_revisions_autoclean.settings.yml
docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
package-lock.json

This pr adds the existing field_office field to the Outreach asset content type. No changes outside of config are introduced, with one exception: a new path introduced for consumer source to fix broken token from github to populate Drupal user guide.
JIRA: https://va-gov.atlassian.net/browse/VAGOV-2960
There is no qa associated with this task.

VAGOV-2973: Updating outreach asset config to add field_office.

---

.gitignore
.lando.yml
README.md
scripts/sync-db.sh
scripts/sync-files.sh

These dumps exist now and these commands are testable. 
Sorry, `lando sync-db` and `lando sync-files` are no more due to us having to access through the proxy. 
New commands are `scripts/sync-db.sh` and `scripts/sync-files.sh` and you must have the proxy running. README.md has also been updated with this PR.

VAGOV-3079 Fix public private S3 bucket, backup issue

---

tests/nightwatch/features/accessibilityCreateBenefitsDetailPage.test.js
tests/nightwatch/features/accessibilityCreateBenefitsHubLandingPage.test.js
tests/nightwatch/features/accessibilityCreateDocumentationPage.test.js
tests/nightwatch/features/accessibilityCreateEvent.test.js
tests/nightwatch/features/accessibilityCreateHealthCareLocalFacility.test.js
tests/nightwatch/features/accessibilityCreateHealthCareRegionDetailPage.test.js
tests/nightwatch/features/accessibilityCreateHealthCareRegionPage.test.js
tests/nightwatch/features/accessibilityCreateOffice.test.js
tests/nightwatch/features/accessibilityCreateOutreachAsset.test.js
tests/nightwatch/features/accessibilityCreatePersonProfile.test.js
tests/nightwatch/features/accessibilityCreatePressRelease.test.js
tests/nightwatch/features/accessibilityCreateRegional-LocalHealthCareServiceDescription.test.js
tests/nightwatch/features/accessibilityCreateStory.test.js
tests/nightwatch/features/accessibilityCreateSupportService.test.js
tests/nightwatch/features/accessibilityDashboard.test.js

Create accessibility tests for node/add forms for all Content Types.
NOTE: There is a known failure in each of these tests. Inclusion in deployment should not fail build.
renamed tests/nightwatch/features/{accessibilityEdit.test.js => accessibilityCreateBenefitsDetailPage.test.js} (95%)
tests/nightwatch/features/accessibilityCreateBenefitsHubLandingPage.test.js
tests/nightwatch/features/accessibilityCreateDocumentationPage.test.js
tests/nightwatch/features/accessibilityCreateEvent.test.js
tests/nightwatch/features/accessibilityCreateHealthCareLocalFacility.test.js
tests/nightwatch/features/accessibilityCreateHealthCareRegionDetailPage.test.js
tests/nightwatch/features/accessibilityCreateHealthCareRegionPage.test.js
tests/nightwatch/features/accessibilityCreateOffice.test.js …

VAGOV-2945 Write new Nightwatch tests for new content types

---

config/sync/migrate_plus.migration.va_alert_block.yml
config/sync/migrate_plus.migration.va_benefits_menu.yml
config/sync/migrate_plus.migration.va_benefits_records.yml
config/sync/migrate_plus.migration.va_benefits_records_menu.yml
config/sync/migrate_plus.migration.va_hub.yml
config/sync/migrate_plus.migration.va_main_menu.yml
config/sync/migrate_plus.migration.va_new_hubs.yml
config/sync/migrate_plus.migration.va_new_landing_pages.yml
config/sync/migrate_plus.migration.va_new_pages.yml
config/sync/migrate_plus.migration.va_outreach.yml
config/sync/migrate_plus.migration.va_outreach_doc_media.yml
config/sync/migrate_plus.migration.va_outreach_embedded_images.yml
config/sync/migrate_plus.migration.va_outreach_files.yml
config/sync/migrate_plus.migration.va_outreach_image_media.yml
config/sync/migrate_plus.migration.va_outreach_video.yml
config/sync/migrate_plus.migration.va_promo.yml
config/sync/migrate_plus.migration.va_promo_images.yml
config/sync/migrate_plus.migration.va_promo_media.yml
config/sync/migrate_plus.migration.va_support_service.yml
config/sync/migrate_plus.migration_group.va_gov.yml
config/sync/migrate_plus.migration_group.va_new_benefits.yml
config/sync/migrate_plus.migration_group.va_outreach.yml
config/sync/migrate_plus.migration_group.va_tests.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_hub.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_new_landing_pages.yml
docroot/modules/custom/va_gov_migrate/src/Paragraph/LinksList.php
docroot/modules/custom/va_gov_migrate/src/Paragraph/QaSection.php

Small migration fixes (note that `migrate_plus.migration.va_new_landing_pages.yml` is for testing only. The changes there just bring it up-to-date with the real migration, `va_hub`.)
To test: Go to /admin/structure/migrate/manage/va_new_benefits/migrations and run `Migrate Records benefits pages from VA.gov` and `Records landing page...` (check the 'Update' option for that one). Then 
1. Edit 'Types of Veteran ID cards' and make sure there's a line break in the last Q&A Section intro:
> At this time, all 50 states and Puerto Rico offer a Veteran designation (an identifying mark) printed on state-issued driver’s licenses or IDs. The type of Veteran designation may vary from state to state.
> 
> If you have a Veteran’s designation, you may be able to get discounts offered to Veterans at …

VAGOV-3305 records migration content bugs

---

composer.json
composer.lock

This PR updates the Drupal GraphQL module to the latest RC version.
**Updating this module requires some changes to query syntax in vets-website. Please see this PR for a summary of changes: https://github.com/department-of-veterans-affairs/vets-website/pull/10085.** 
**This update is not backwards compatible - meaning that after this PR is merged and deployed, the front-end build will be broken until vets-website PR #10085 is merged and deployed.**
See this JIRA ticket for more context about the update: https://va-gov.atlassian.net/browse/VAGOV-3026

VAGOV-3663: Update graphql module

---

docroot/modules/custom/va_gov_migrate/src/Paragraph/Table.php

Code identifies and gets contents from html tables.
To test:
1. Go to /admin/structure/migrate/manage/va_tests/migrations/va_new_hubs/execute and press the "Execute" button.
2. Go have dinner, take a walk, see a movie (this will take a while).
3. When the migration's done, edit "VA Pension Rates For Veterans". There should be 3 table paragraphs and their contents should match https://www.va.gov/pension/veterans-pension-rates/

VAGOV-3531: Add paragraph migration for tables.

---

config/sync/migrate_plus.migration.va_alert_block.yml
config/sync/migrate_plus.migration.va_benefits_menu.yml
config/sync/migrate_plus.migration.va_benefits_records.yml
config/sync/migrate_plus.migration.va_benefits_records_menu.yml
config/sync/migrate_plus.migration.va_hub.yml
config/sync/migrate_plus.migration.va_main_menu.yml
config/sync/migrate_plus.migration.va_new_hubs.yml
config/sync/migrate_plus.migration.va_new_landing_pages.yml
config/sync/migrate_plus.migration.va_new_pages.yml
config/sync/migrate_plus.migration.va_outreach.yml
config/sync/migrate_plus.migration.va_outreach_doc_media.yml
config/sync/migrate_plus.migration.va_outreach_embedded_images.yml
config/sync/migrate_plus.migration.va_outreach_files.yml
config/sync/migrate_plus.migration.va_outreach_image_media.yml
config/sync/migrate_plus.migration.va_outreach_video.yml
config/sync/migrate_plus.migration.va_promo.yml
config/sync/migrate_plus.migration.va_promo_images.yml
config/sync/migrate_plus.migration.va_promo_media.yml
config/sync/migrate_plus.migration.va_support_service.yml
config/sync/migrate_plus.migration_group.va_gov.yml
config/sync/migrate_plus.migration_group.va_new_benefits.yml
config/sync/migrate_plus.migration_group.va_outreach.yml
config/sync/migrate_plus.migration_group.va_tests.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_benefits_records.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_hub.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_new_hubs.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_new_landing_pages.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_new_pages.yml
docroot/modules/custom/va_gov_migrate/src/Obtainer/ObtainTitleUncased.php

To test:
1. Go to /admin/structure/migrate/manage/va_new_benefits/migrations/va_benefits_records/execute and run migration
2. Check the 4 newly created records detail pages (all in draft, all updated on 04/18/2019 - 20:00, all with Owner 'Records benefits hub'). Their titles should all be sentence case, like their titles on va.gov.

VAGOV-3259 Fix migration title casing

---

config/sync/migrate_plus.migration.va_alert_block.yml
config/sync/migrate_plus.migration.va_benefits_menu.yml
config/sync/migrate_plus.migration.va_benefits_pension.yml
config/sync/migrate_plus.migration.va_benefits_pension_menu.yml
config/sync/migrate_plus.migration.va_benefits_records.yml
config/sync/migrate_plus.migration.va_benefits_records_menu.yml
config/sync/migrate_plus.migration.va_hub.yml
config/sync/migrate_plus.migration.va_main_menu.yml
config/sync/migrate_plus.migration.va_new_hubs.yml
config/sync/migrate_plus.migration.va_new_landing_pages.yml
config/sync/migrate_plus.migration.va_new_pages.yml
config/sync/migrate_plus.migration.va_outreach.yml
config/sync/migrate_plus.migration.va_outreach_doc_media.yml
config/sync/migrate_plus.migration.va_outreach_embedded_images.yml
config/sync/migrate_plus.migration.va_outreach_files.yml
config/sync/migrate_plus.migration.va_outreach_image_media.yml
config/sync/migrate_plus.migration.va_outreach_video.yml
config/sync/migrate_plus.migration.va_promo.yml
config/sync/migrate_plus.migration.va_promo_images.yml
config/sync/migrate_plus.migration.va_promo_media.yml
config/sync/migrate_plus.migration.va_support_service.yml
config/sync/migrate_plus.migration_group.va_gov.yml
config/sync/migrate_plus.migration_group.va_new_benefits.yml
config/sync/migrate_plus.migration_group.va_outreach.yml
config/sync/migrate_plus.migration_group.va_tests.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_alert_block.yml

Not much here. This just specifies that only alert blocks on the pension landing page get migrated, and currently, there aren't any.
So to test, go to /admin/structure/migrate/manage/va_gov/migrations and confirm that "Migrate alert blocks from VA.gov" has 'TOTAL' of zero.

VAGOV-3600 pension migration alert

---

config/sync/field.field.node.page.field_meta_tags.yml
config/sync/node.type.health_care_region_detail_page.yml
config/sync/node_revisions_autoclean.settings.yml

This enables the new outreach and events menu on Detail pages. Just a check box that was missed, so didn't create a task, @andyhawks - hope to get this one merged in and part of the build.

VAGOV-000: Adding additional menu option to detail pages.

---

docroot/themes/custom/vagovadmin/css/admin-styles.css

This reverts commit 2b8fbbfd7b0e4e33eb224d0fa80fbc97c8770254.

VAGOV-1895: Revert: Hide history and revision tabs on node edit pages.

---

config/sync/user.role.authenticated.yml
tests/phpunit/SecurityRolesPermissionsTest.php

Adds taxonomy access perm to authenticated user role.
Task: https://va-gov.atlassian.net/browse/VAGOV-4035
**QA:**
- As and admin, visit `admin/people/permissions`
- Visually verify that `Access the taxonomy vocabulary overview page
- Get an overview of all taxonomy vocabularies.` is set to `authenticated user`

VAGOV-4035

---

README.md
composer.json

It works like this:
```bash
$ composer set-path
> # Run the command output below to set your current terminal PATH variable.
> # This will allow you to run any command in the ./bin directory without a path.
> echo "export PATH=${PATH}"
export PATH=/home/jon/Projects/VA/va.gov-cms/bin:/home/jon/.config/composer/vendor/bin:/home/jon/.local/bin:/home/jon/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/jon/.composer/vendor/bin:/var/lib/snapd/snap/bin
```
Then you copy and paste into terminal, and all the commands in the bin become available.
It's then easier to do things in a subdirectory. For example, behat.
```bash
$ cd tests/behat
$ behat
```

Composer command to print out the command to modify the PATH to point to `bin` dir.

---

config/sync/migrate_plus.migration.va_alert_block.yml
config/sync/migrate_plus.migration.va_benefits_careers.yml
config/sync/migrate_plus.migration.va_benefits_careers_menu.yml
config/sync/migrate_plus.migration.va_benefits_menu.yml
config/sync/migrate_plus.migration.va_benefits_pension.yml
config/sync/migrate_plus.migration.va_benefits_pension_menu.yml
config/sync/migrate_plus.migration.va_hub.yml
config/sync/migrate_plus.migration.va_main_menu.yml
config/sync/migrate_plus.migration.va_new_hubs.yml
config/sync/migrate_plus.migration.va_new_landing_pages.yml
config/sync/migrate_plus.migration.va_new_pages.yml
config/sync/migrate_plus.migration.va_promo.yml
config/sync/migrate_plus.migration.va_promo_images.yml
config/sync/migrate_plus.migration.va_promo_media.yml
config/sync/migrate_plus.migration.va_root_pages.yml
config/sync/migrate_plus.migration.va_support_service.yml
config/sync/migrate_plus.migration_group.va_gov.yml
config/sync/migrate_plus.migration_group.va_new_benefits.yml
config/sync/migrate_plus.migration_group.va_tests.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_benefits_careers.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_benefits_pension.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_hub.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_new_hubs.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_new_landing_pages.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_new_pages.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_root_pages.yml

To test: 
1. Go to /admin/structure/migrate/manage/va_new_benefits/migrations/va_benefits_careers/execute and run the migration
2. Go to /admin/content?title=&type=page&moderation_state=editorial-draft and view or edit a node with Owner, "Careers and employment benefits hub". Confirm that the "Meta title tag" field contains the page title with the first letter of each word upper cased followed by " | Veterans Affairs". 
Note that testing should be done on the testing env, not locally. The migration needs an ENV var that's not usually on local.

VAGOV-3365 migrate meta title

---

config/sync/core.entity_form_display.node.event.default.yml
config/sync/core.entity_view_display.node.event.default.yml
config/sync/core.entity_view_display.node.event.teaser.yml
config/sync/field.field.node.event.field_additional_information_abo.yml
config/sync/field.storage.node.field_additional_information_abo.yml
config/sync/filter.format.rich_text.yml
config/sync/node_revisions_autoclean.settings.yml

This changes the additional info field on event nodes to be rich text.
Use case: we need hyperlinks to automagically become hyperlinks. This isn't possible with plain text.

VAGOV-4154: Changing additional info event field to rich text.

---

config/sync/filter.format.rich_text.yml

QA: 
1. Edit a WYSWIYG field with a link in it (eg node/195/edit)
2. Click "Source" button in WYSIWYG
3. Add `login-required` class to link
4. Save node
5. you should see the class on the link (no need to preview)

VAGOV-4506: Allow login-required class in rich text.

---

config/sync/menu_breadcrumb.settings.yml
config/sync/migrate_plus.migration.va_alert_block.yml
config/sync/migrate_plus.migration.va_benefits_careers.yml
config/sync/migrate_plus.migration.va_benefits_careers_menu.yml
config/sync/migrate_plus.migration.va_benefits_housing.yml
config/sync/migrate_plus.migration.va_benefits_housing_extra.yml
config/sync/migrate_plus.migration.va_benefits_housing_menu.yml
config/sync/migrate_plus.migration.va_benefits_life_insurance.yml
config/sync/migrate_plus.migration.va_benefits_life_insurance_menu.yml
config/sync/migrate_plus.migration.va_hub.yml
config/sync/migrate_plus.migration.va_main_menu.yml
config/sync/migrate_plus.migration.va_new_landing_pages.yml
config/sync/migrate_plus.migration.va_new_pages.yml
config/sync/migrate_plus.migration.va_promo.yml
config/sync/migrate_plus.migration.va_promo_images.yml
config/sync/migrate_plus.migration.va_promo_media.yml
config/sync/migrate_plus.migration.va_root_pages.yml
config/sync/migrate_plus.migration.va_support_service.yml
config/sync/migrate_plus.migration_group.va_gov.yml
config/sync/migrate_plus.migration_group.va_new_benefits.yml
config/sync/migrate_plus.migration_group.va_tests.yml
config/sync/node.type.page.yml
config/sync/system.menu.life-insurance-benefits-hub.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_benefits_housing_extra.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_benefits_life_insurance.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_benefits_life_insurance_menu.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_hub.yml

New/updated migrations (/admin/structure/migrate/manage/va_new_benefits/migrations):
- "Migrate additional Housing benefits pages from Heroku"
- "Migrate Housing and Life insurance landing pages - NEVER ROLLBACK"
- "Migrate Life insurance pages from va.gov"
- "Migrate Life insurance sidebar menu"
Also adds "Life insurance benefits hub" menu in config.

VAGOV-4302: life insurance migration

---

composer.json
composer.lock

https://va-gov.atlassian.net/browse/VAGOV-4662

VAGOV-4662: Patch drupal core to allow unpublished parent menu items.

---

config/sync/core.entity_form_display.node.office.default.yml
config/sync/field.field.node.office.field_asset_library_description.yml
config/sync/field.field.node.office.field_body.yml
config/sync/field.field.node.office.field_event_listing_description.yml
config/sync/field.storage.node.field_asset_library_description.yml
config/sync/field.storage.node.field_event_listing_description.yml
docroot/modules/custom/va_gov_backend/va_gov_backend.install

**This mr:**
- Adds description for events, description for benefits, and body to office node. @kevwalsh: This content model change is necessary because we are eliminating subordinate office pages for events listing and asset listings, and now accessing them via query parameter (as opposed to node / arg pattern for real node pages). Both event and asset listing views require intro description text, so most logical place to add is the office node with which they are associated.
- Migrates outreach assets to new path
- Cures double events/events in  path bug
**QA:**
- Visit `admin/structure/menu/manage/outreach-and-events` and confirm that three menu items appear
- Visit the edit view for an outreach node and confirm that `Healthcare system or related office` field is set to `Outreach and …

VAGOV-4361

---

config/sync/core.entity_form_display.node.health_care_region_page.default.yml
config/sync/core.entity_view_display.node.health_care_region_page.default.yml
config/sync/field.field.node.health_care_region_page.field_featured_content_healthser.yml
config/sync/field.storage.node.field_featured_content_healthser.yml

* Go to /node/318/edit
* In the Health Services fieldset, note the new Featured content paragraphs field.
* You should be able to add 3 link teasers to it, but no more.

VAGOV-4625: Add a featured content block for health services page.

---

Dockerfile-appserver

https://github.com/kolypto/j2cli/issues/43

VAGOV-5047 Use 0.3.10 of j2cli `j2` due to upstream bug.

---

config/sync/node.type.health_care_local_health_service.yml
config/sync/node.type.press_release.yml
config/sync/node.type.regional_health_care_service_des.yml

QA:
* Go to /node/add
* You shouldn't see the word "offering" anwyhere.
* You should see "news release" as an option.

VAGOV-4371: Rename press release and health service node types.

---

config/sync/system.menu.outreach-and-events.yml

Updates the `Outreach and Events` menu name to sentence case, e.g.: `Outreach and events`
This is the drupal portion of task 5237. There is a second component: make Outreach and events menu on `/outreach-and-events` (frontend) path open by default. Merged pr = https://github.com/department-of-veterans-affairs/vets-website/pull/10525
Visual

VAGOV-5237: Changing outreach menu name to sentence case.

---

docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.libraries.yml
docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.module

Removes references to js file in va_gov_build_trigger module (was previously removed).

VAGOV-5346: Removing artifacts referencing removed file.

---

config/sync/core.entity_form_display.media.document.default.yml
config/sync/core.entity_form_display.media.document.media_browser.yml
config/sync/core.entity_form_display.media.document.media_library.yml
config/sync/core.entity_form_display.media.image.default.yml
config/sync/core.entity_form_display.media.image.media_browser.yml
config/sync/core.entity_form_display.media.image.media_library.yml
config/sync/core.entity_form_display.media.video.default.yml
config/sync/core.entity_form_display.media.video.media_browser.yml
config/sync/core.entity_form_display.media.video.media_library.yml
config/sync/core.entity_form_display.node.outreach_asset.default.yml
config/sync/core.entity_view_display.media.document.default.yml
config/sync/core.entity_view_display.media.image.default.yml
config/sync/core.entity_view_display.media.video.default.yml
config/sync/core.entity_view_display.media.video.embedded.yml
config/sync/field.field.media.document.field_document.yml
config/sync/field.field.media.document.field_media_in_library.yml
config/sync/field.field.media.document.field_media_submission_guideline.yml
config/sync/field.field.media.document.field_owner.yml
config/sync/field.field.media.image.field_media_in_library.yml
config/sync/field.field.media.image.field_media_submission_guideline.yml
config/sync/field.field.media.image.field_owner.yml
config/sync/field.field.media.video.field_media_in_library.yml
config/sync/field.field.media.video.field_media_submission_guideline.yml
config/sync/field.field.media.video.field_media_video_embed_field.yml
config/sync/field.field.media.video.field_owner.yml
config/sync/field.storage.media.field_media_submission_guideline.yml
config/sync/field.storage.media.field_owner.yml
config/sync/views.view.media.yml
config/sync/views.view.media_library.yml
config/sync/workbench_access.access_scheme.section.yml

This builds on some of the media improvements from VAGOV-5013, adding governance mechanisms and AX improvements. 
Read this for context: 
https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/131235861
As content_editor
[ ] Go to /media/add/document
[ ] Review help text, it should be well written
[ ] Make the document reusable (show in media library, the default)
[ ] Make the Owner Veteran Benefits administrations
[ ] Go to /media/add/image
[ ] Review help text, it should be well written
[ ] Make it _not_ reusable (do not show in media library)
[ ] Make the owner "Pittsburgh Health Care" (under Veterans Health Administration > Facilities)
[ ] Go to /media/add/video
[ ] Review help text, it should be well written
[ ] Make it reusable (leave default
[ ] Make the owner "VA Central Office" 
As …

VAGOV-4629: Media governance updates.

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/lightning_core.versions.yml
config/sync/views.view.my_workflow.yml
config/sync/workflow_participants.settings.yml
docroot/modules/custom/va_gov_notifications/README.md
docroot/modules/custom/va_gov_notifications/src/WorkflowChangeEmail.php
docroot/modules/custom/va_gov_notifications/va_gov_notifications.info.yml
docroot/modules/custom/va_gov_notifications/va_gov_notifications.module
patches/workflowParticipantsUncaughtType.patch

Adds `Workflow participants` tab and form to nodes for assigning users that will track workflow changes.
Sends email alerts to users who have been added to node workflow participants forms.
Alerts are only sent if a workflow state change has occurred, and this is triggered by node save.
- Visual
- Xdebug Profiling
- Email sending via SMTP (locally)
- Full functionality test performed on testing instance: http://internal-test-vagovcms-3879-1510337173.us-gov-west-1.elb.amazonaws.com/ 
- Workflow participants form appears here: `node/{NID}/workflow-participants`
- Adding a user and saving is successful.
- Changing a workflow status sends workflow participant an email like the one in the screenshot above.
- As an admin, edit the email of the account you are using for testing to an email …

VAGOV-1955 - Workflow Participant notifications

---

tests/phpunit/PerformanceLoginTest.php

Test was failing because SAML local_users login setting excluded the
default authenticated_user role.
Added a login before the test to prime the opcache and Drupal cache to
test a real-world login scenario, this means we can test for under 2
seconds now.

VAGOV-5323 - Fix PeformanceLoginTest failure, decrease threshold from 5 > 2.

---

config/sync/entityqueue.entity_queue.home_page_hub_list.yml

*Description*
Contains additional config for the home page full-hub-list entity queue. This config limits the number of hubs added to 11 in order to avoid potentially breaking the home page layout. 
*Testing*
- Navigate to admin/structure/entityqueue/home_page_hub_list?destination=/admin/structure/entityqueue.
- Click **Queue settings**.
- Confirm the max is 11.

VAGOV-4870: Home Page Top Tasks Menu Links

---

config/sync/core.entity_form_display.node.landing_page.default.yml
config/sync/core.entity_view_display.node.landing_page.default.yml
config/sync/field.field.node.landing_page.field_home_page_hub_label.yml
config/sync/field.storage.node.field_home_page_hub_label.yml

**Description**
Includes config for new field_home_page_hub_label. 
The idea is that these titles...
... will be fed by this new field: 
**Testing**
- Navigate to benefit hub landing page's field config at admin/structure/types/manage/landing_page/fields.
- Confirm **Home page hub label** is there.

VAGOV-5586: Add config for new Home page hub label field

---

config/sync/editor.editor.rich_text.yml
config/sync/filter.format.rich_text.yml

QA: 
* /node/add/page
* Add a wysiwyg content block
* Add a link using the linkit dropdown, by searching for "VA blind and low vision" and picking "VA blind and low vision rehabilitation services"
* Add another link, paste in http://prod.cms.va.gov/health-care to the link dialog
* Fill out required fields with whatever, and hit save
* ~~The first link should appear in the front end as /health-care/about-va-health-benefits/vision-care/blind-low-vision-rehab-services (not "/node/2")~~ **As discussed, this will show up as /node/2, unless a user enters a link after selecting text**
* The second one should be linked to [whatever test environment].va.gov/health-care  NOT health-care

VAGOV-5510: Enable Linkit and Pathologic filters on rich text.

---

config/sync/views.view.redirect.yml

- Adds redirect view identical to admin redirect view for content api user role, sans editing options
- As a user who has content api user role, go to `admin/config/search/redirect` - you should see an access denied message
- As a user who has content api user role, go to `redirects-list` - you should a list of redirects, sans editing and bulk operations options
- Visually verify that `Redirect List` appears under `Content` in admin menu.

VAGOV-4960: Adding content api user redirect view.

---

tests/behat/features/bootstrap/FeatureContext.php

`.env` file is no longer in the repo or automatically copied. 
I left the DotEnv stuff in behat's `FeatureContext.php` accidentally: it is no longer needed, I think.
CI will decide if it's true.
@swirtSJW @ElijahLynn can you test on lando from a truly fresh clone?
`rm -rf * .env && git reset --hard && lando rebuild && lando start && lando test` will:
1 .wipe all files except what is in git. (vendor, .env, everything).
2. rebuild lando containers from new environment files and lando.yml config.
3. restart lando containers, including composer install.
4. Run `composer yaml-tests` (alias `lando test`)

VAGOV-5683: Only load .env if it exists.

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/lightning_core.versions.yml

- Installs and enables entity_clone module
- As a site user, I would like a way to easily duplicate content
- As an admin, visit `admin/content/bulk` and choose `Clone` from the `Operations` button for any node in the table.
- Complete the subsequent form, visually verifying that clone operation is successful

VAGOV-5843 Entity clone

---

config/sync/feature_toggle.features.yml

• Adds a new feature flag for development of the Drupal-powered megamenu.
This flag should allow us to turn the Drupal-powered header "on" and "off" as needed.

VAGOV-4871: Header Feature Flag

---

config/sync/core.entity_form_display.block_content.promo.default.yml
config/sync/core.entity_form_display.paragraph.link_teaser.promo_link_teaser.yml
config/sync/core.entity_form_mode.paragraph.promo_link_teaser.yml
config/sync/field.field.menu_link_content.header-megamenu.field_promo_reference.yml
config/sync/field.field.paragraph.link_teaser.field_link_summary.yml

This code does the following:
- Updates the label and help text for field_promo_reference on the header megamenu so that it also applies to benefit hub promos.
- Adds a new form display for the link teaser paragraph type.
- Applies that new form display to promo blocks.

VAGOV-5984 Update header menu promo reference

---

docroot/modules/custom/va_gov_build_trigger/src/Form/BuildTriggerForm.php
docroot/modules/custom/va_gov_login/va_gov_login.module
simplesamlphp-1.17.2/config/config.php

- Replaces all instances of `cms-admin@va.gov` with `vacmssupport@va.gov`
- Search codebase for `cms-admin@va.gov` - should return no results

VAGOV-6017: Replace legacy support email with new.

---

config/sync/feature_toggle.features.yml

**Description**
This PR adds a footer menu feature flag to the CMS. There is no implementation of this on the front-end yet. We are merely preparing the back-end for the front-end implementation.

VAGOV-6020: Footer Menu Feature Flag II

---

config/sync/system.theme.yml
docroot/themes/custom/vagovadmin/css/wysiwyg.css
docroot/themes/custom/vagovadmin/vagovadmin.info.yml
tests/behat/features/decoupled.feature

https://va-gov.atlassian.net/browse/VAGOV-6064
* Create a page
* Add a wysiwyg field in the content block
* Try out every HTML element, paragraph format, and block style, including link buttons. 
* They should approximate what the VA Design system
* Save the node
* On the node view page, everything in `div.node__content`  should look more like the front end.

VAGOV-6064: Truer wysiwyg.

---

docroot/sites/default/settings.php

sms: protocol was being stripped from wysiwyg content areas and it looked like a cache issue but was just that the `filter_protocols:` key in services.yml that had `sms` as a whitelisted protocol, wasn't being loaded.
This may affect other things in CI, but mostly for the better as the services.yml wasn't being loaded all this time.

VAGOV-6107 - Load services.yml in CI environments too.

---

docroot/.htaccess

VAGOV-6156: Disable access to web.config because of Nessus scan.

---

docroot/modules/custom/va_gov_consumers/src/FacilityConsumer.php
docroot/modules/custom/va_gov_consumers/va_gov_consumers.module

- Adds facility api consumer class
- Takes into account new prod api key (set as env var on prod)
-- Prod has unique key, all other environments use the original dev key (per api team instruction)
- Env var has same naming convention in all environments, so no env switch necessary in code.

VAGOV-5333 Facility API

---

config/sync/core.entity_form_display.node.health_care_region_page.default.yml
config/sync/core.entity_view_display.node.health_care_region_page.default.yml
config/sync/field.field.node.health_care_region_page.field_link_facility_emerg_list.yml
config/sync/field.field.node.health_care_region_page.field_link_facility_news_list.yml
config/sync/field.storage.node.field_link_facility_emerg_list.yml
config/sync/field.storage.node.field_link_facility_news_list.yml
tests/behat/drupal-spec-tool/content_model.feature

- Adds two new link fields to VAMC system content type for subscribing to emergency notifications or email lists
- Moves old email subscription field out of node form

VAGOV-6167: Adding new links fields to VAMC.

---

config/sync/core.entity_form_display.node.health_care_local_health_service.inline_entity_form.yml
config/sync/core.entity_form_display.node.regional_health_care_service_des.default.yml
config/sync/core.entity_form_display.node.regional_health_care_service_des.inline_entity_form.yml
config/sync/core.entity_view_display.node.health_care_local_health_service.ief_table.yml
config/sync/field.field.node.regional_health_care_service_des.field_body.yml
config/sync/field.field.node.regional_health_care_service_des.field_local_health_care_service_.yml
config/sync/field.field.node.regional_health_care_service_des.field_region_page.yml
config/sync/node.type.health_care_local_health_service.yml
config/sync/node.type.regional_health_care_service_des.yml
tests/behat/drupal-spec-tool/content_model.feature

VAGOV-6182: Improve editorial experience for VAMC health services.

---

composer.json

Patched no longer needed with 8.x-1.4 https://www.drupal.org/node/2907094

VAGOV-000: Remove patch no longer needed for field_group & paragraphs.

---

tests.yml

This does add about 6 seconds to tests locally. It prevents unimportable config from being merged.

VAGOV-000 Test config:import imports cleanly.

---

composer.json

This keeps samlsessiondb.sq3 from always showing up in git status.

VAGOV-000 Ignore samlsessiondb.sq3 for all users on composer install hook.

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/image_style_warmer.settings.yml
config/sync/lightning_core.versions.yml
config/sync/views.view.image_style_warmer_warmup_files.yml
docroot/sites/default/settings.php
tests/behat/drupal-spec-tool/views.feature

VAGOV-6276
- Adds Image Style Warmer module
- Disables `itok` DDoS prevention. 
- Adds VBO View for Image Style Warmer operation to process existing images (initial PROD deployment step needed)

VAGOV-6276 Image Style Warmer & disable `itok` DDoS prevention.

---

config/sync/core.entity_form_display.node.health_care_region_page.default.yml
config/sync/core.entity_view_display.node.health_care_region_page.default.yml
config/sync/field.field.node.health_care_region_page.field_govdelivery_id_emerg.yml
config/sync/field.field.node.health_care_region_page.field_govdelivery_id_news.yml
config/sync/field.storage.node.field_govdelivery_id_emerg.yml
config/sync/field.storage.node.field_govdelivery_id_news.yml
tests/behat/drupal-spec-tool/content_model.feature

Adding two 10 character text fields to facility type to capture GovDelivery email list ids, and disabling previous 2 full url capture fields.
Go to `node/318/edit` and visually verify that new fields and fieldset captured in screenshot below are visible.

VAGOV-6289: Updating config to include govid fields on facility.

---

config/sync/menu_breadcrumb.settings.yml

QA:
* Go to /admin/content
* Open a few random nodes of various types and click Preview.
* None should have the "Home" breadcrumb

VAGOV-6296: Don't add Home link to breadcrumb.

---

config/sync/user.role.content_admin.yml
docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.permissions.yml
docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.routing.yml

Adds the permission for deploying content and assigns it to 'admin' and 'content admin'.
Login as admin
Login as Steve.Tokar2@  (not content  admin )
Login as Randi.Hecht@  ( content  admin )

VAGOV-6249 Add deploy permission.

---

.lando/xdebug/php.ini
composer.json
composer.lock
config/sync/core.entity_form_display.node.full_width_banner_alert.default.yml
config/sync/core.entity_form_display.paragraph.situation_update.default.yml
config/sync/core.extension.yml
config/sync/govdelivery_bulletins.settings.yml
config/sync/lightning_core.versions.yml
config/sync/user.role.anonymous.yml
config/sync/workflows.workflow.editorial.yml
docroot/modules/custom/va_gov_backend/va_gov_backend.module
docroot/modules/custom/va_gov_govdelivery/src/Service/ProcessStatusBulletin.php
docroot/modules/custom/va_gov_govdelivery/va_gov_govdelivery.info.yml
docroot/modules/custom/va_gov_govdelivery/va_gov_govdelivery.module
docroot/modules/custom/va_gov_govdelivery/va_gov_govdelivery.services.yml
tests/phpunit/SecurityRolesPermissionsTest.php

This has a lot of items affected and does not fully get the queue working but it does the following:
1. Removes workbench moderation from the full_width_banner_alert content type.
1. Disables the send email checkbox upon node being published
2. Utilizes the  "publish" checkbox 
3. removes the publish checkbox from situation update paragraph.
4. Adds the logic to decide when to queue  status alert bulletins and when to queue a situation update bulletin.
5.  Logging of adding items to the queue.
6. Adds all current features of govdelivery_bulletins (perms, queue adding, configuration killswitches, endpoint triggering)
https://www.drupal.org/project/issues/govdelivery_bulletins?status=7
7. Can visit /api/govdelivery_bulletins/queue?EndTime=1234567899 to get a 200 response if the EndTime …

VAGOV-6252 Add GovDelivery banner alert processing. Part 1

---

config/sync/core.entity_form_display.node.full_width_banner_alert.default.yml
config/sync/core.entity_view_display.node.full_width_banner_alert.default.yml
config/sync/field.field.node.full_width_banner_alert.field_alert_inheritance_subpages.yml
config/sync/field.storage.node.field_alert_inheritance_subpages.yml
tests/behat/drupal-spec-tool/content_model.feature

- Recreates https://github.com/department-of-veterans-affairs/va.gov-cms/pull/721 = adds `Only show on VAMC System Page & Operating Status Page` boolean to banner content type.

VAGOV-5991: Restoring field_alert_inheritance_subpages on banner

---

Jenkinsfile.cd

Reverts department-of-veterans-affairs/va.gov-cms#754
We are clear to re-enable CD to STAGING now.

Revert "Disable automatic STAGING deploys temporarily"

---

READMES/brd.md

Adding more documentation about BRD and DevOPs to the CMS repo.

VAGOV-5911-cms-docs: Adding BRD release process docs

---

composer.json
composer.lock
config/sync/core.entity_view_display.user_history.user_history.default.yml
config/sync/core.entity_view_display.user_history.user_history.tab.yml
config/sync/core.entity_view_mode.user_history.tab.yml
config/sync/core.extension.yml
config/sync/lightning_core.versions.yml
config/sync/user.role.authenticated.yml
config/sync/user_history.settings.yml
config/sync/views.view.user_creation_editing_activity.yml
config/sync/views.view.user_history.yml
config/sync/views.view.user_history_list.yml
docroot/modules/custom/va_gov_backend/va_gov_backend.module
tests/behat/drupal-spec-tool/views.feature
tests/phpunit/SecurityRolesPermissionsTest.php

- Adds a user history tab to user pages for tracking user creation and editing events
- Adds a user history list page: `/user_history/list`
- Go to `/user_history/initialise` or visit the status report and click on the link.
- Visit user edit page, look for history tab.
- Visually verify that creation / editing events are being logged.
- Go to `user_history/list` and visually verify that all users and account history appears

VAGOV-6065: Adding user_history module and patch.

---

config/sync/system.site.yml
docroot/modules/custom/va_gov_login/va_gov_login.module
tests/behat/features/user.feature

VAGOV-5133
To test on BRD environments (CI doesn't work just yet) you must set the users email to something, as they are all empty by default on DEV/STAGING due to DB sanitization. PROD should work out of the box now.
The sitename in this PR changes it from "Veterans Affairs" to "VA.gov CMS".

VAGOV-5133 Unhide password reset tab, email sending works now.

---

config/sync/node.type.health_care_region_detail_page.yml

- Enables all VAMC system menus on detail pages
- Go to `admin/structure/types/manage/health_care_region_detail_page` click the menu tab and visually verify that all VAMC systems are checked (in addition to outreach menu).

VAGOV-6375: Enabling vamc menus on detail content type.

---

config/sync/views.view.health_service_offerings.yml
docroot/modules/custom/va_gov_backend/va_gov_backend.module

- Changes table header text, appends system name to services in column 2, and adds a vamc system filter dropdown to view found, here: `health-service-offerings`
- Visit `health-service-offerings` as admin.
- Visually verify that headers match screenshot
- Visually verify that column 2 items are appended with system name (e.g. `Addiction and substance abuse treatment at VA Altoona health care`)
- Go to `node/324/edit` and change VAMC system to VA Altoona health care
- Go back to `health-service-offerings` and filter by VA Altoona health care
- Visually verify that node 324 appears in filtered results.

VAGOV-6236

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module

Addresses #851 
- Removes build time info footer text from node edit form
Bad:
Good:

VAGOV-851: Remove node build footer info from node form.

---

config/sync/pathauto.pattern.event.yml

- Adds node title to event type path alias (pattern was copied inadvertently from event_listing type, missing the final node:title token). This fixes broken breadcrumb issue related to drupal not having title string for output.
- Add an event to outreach and asset event listing (in Drupal).
- Rebuild front end
- Visually verify that event has functional breadcrumb, and doesn't output node id in lieu of node title

VAGOV-877: Adding title to event breadcrumb alias.

---

docroot/themes/custom/vagovadmin/templates/layout/fieldset.html.twig

- Moves fieldset description text from bottom of fieldset to top (just below title / legend on node form).
- On content type, add some description text to a fieldset on node form view page
- Create a new piece of this content type, and confirm the help text appears below title.
- `Do some stuff` is the description text

VAGOV-860: Change fieldset layout.

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module

Removes `History` node tab, per #889

VAGOV-889: Remove the history tab from node.

---

docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.module

- Removes "Preview" button from node view page for 5 node types.
- Go to `admin/content`
- Visit the node view page and confirm "Preview" button does not appear for 1 of each type:
1. outreach_asset
2. person_profile
3. support_service
4. regional_health_care_service_des
5. health_care_local_health_service

VAGOV-1738: Adding excluded type logic for previews.

---

.lando.yml
.lando/zzz-lando-my-custom.ini

This may not be great to merge but does solve a local development issue when running `lando composer va:web:build` which times out on cold cache hits at /graphql. Worth noting that all our CI/CD environments are set to 60. And oddly, requests DO take longer than 60 seconds on those and they don't timeout. 
Ultimately, we shouldn't have graphql taking so long, so this is definitely a workaround/mitigation.
To test, `hub pr checkout 906` then `lando rebuild`. 
update: tested to make sure `lando xdebug-on/off` still works, :+1:

Increase local lando max_execution_time from 90 > 190

---

composer.json
composer.lock

Fixes #938 :
Prevents recursive references to child nodes when cloning content. This behavior is not needed for VA, and results in time outs.
Visual / manual
As user with any role

VAGOV-938: Adding entity_clone patch to prevent child node ref recursion

---

docroot/modules/custom/va_gov_build_trigger/src/Service/BuildFrontend.php

See #980. 
Tested locally with manipulating values to make it act like devshop.  
Devshop is currently in a "working" state so this can not be fully tested, but does not warrant wiping devshop to fully test.

VACMS-980 Add logging to build trigger if devshop config is not in place.

---

docroot/modules/custom/va_gov_build_trigger/src/Form/BuildTriggerForm.php
docroot/modules/custom/va_gov_build_trigger/src/Service/BuildFrontend.php

Related to issue #980 
When a frontend build is triggered and the request fails on the drupal side, drupal should unset the build pending flag.
Can't easily reproduce failure.
- [-] A link has been provided to the originating GitHub issue (or connected to it via ZenHub)

VACMS-980 Unset deploy pending flag on failure.

---

tests/behat/features/decoupled.feature

See #988  
The tests run and pass

VACMS-988 Remove redundant behat vaweb build.

---

config/sync/core.extension.yml
config/sync/health_check_url.settings.yml
docroot/modules/custom/va_gov_db/va_gov_db.install

See #1025 
1. As admin enable maintenance mode at /admin/config/development/maintenance
1. In an incognito window with your browser network inspector open, visit /health

VACMS-1025 Uninstall health_check module.

---

composer.json
composer.lock
config/sync/node_link_report.settings.yml

See #844 and $856 
Examine the following pages which had notoriously high numbers of falsely reported broken links.
/health-care/how-to-apply
/health-care/after-you-apply
/education/transfer-post-9-11-gi-bill-benefits
/pittsburgh-health-care/staff-profiles/brenda-shaffer
/outreach-and-events/events/events-10
/pittsburgh-health-care/stories/stroke-survivortime-is-brain
/pittsburgh-health-care/research/safety-security/animal-research
/disability/va-claim-exam
/disability
As as an admin or content admin (the only roles who can see the node link report) visit the following pages and validate there are no fake broken links.

VACMS-844 Update node_link_report to reduce false failures.

---

composer.json
composer.lock

Drag and drop patch applied to tablefield module isn't being rendered properly in frontend build. This pr removes this patch.
- Expected: dragging and dropping rows in tablefield found on `node/767/edit` will render in new order here: `life-insurance/options-eligibility/sgli/`
- Actual: new ordering is not respected, and additional column representing each row's weight is generated
Visual
- As an admin, go to `node/767/edit` and visually verify that you cannot drag table rows.
- Save node, build front end, visually verify that weight column does not appear.

VACMS-000: Removing table field drag and drop patch.

---

config/sync/views.view.user_email_csv.yml

See #1073 . 
Locally
As yourself
1. Visit /admin/people/ 
-[ ] Validate the 'Email list' tab is present 
1. Click that tab.  
-[ ] Validate that you see a list of email addresses.
1. Click the "Download the csv" link

VACMS-1073 Add menu item for user email view.

---

composer.json
composer.lock
config/sync/node_link_report.settings.yml

See #1009 . 
This brings with it an update to node_link_report focusing on UX improvements to the display of the reports
https://www.drupal.org/project/node_link_report/releases/8.x-1.9
1. Visit random content, 
http://pr1085.ci.cms.va.gov/lebanon-health-care
http://pr1085.ci.cms.va.gov/pittsburgh-health-care/research/safety-security/human-research
http://pr1085.ci.cms.va.gov/health-care

VACMS-1009 Update node_link_report for improved UX

---

config/sync/field.field.paragraph.table.field_table.yml
tests/behat/drupal-spec-tool/content_model.feature

See #1120  
1. Login with any editorial role
1. Then go to /node/748/edit
1. Edit one of the table paragraphs. 
1.  Delete the content out of one of the cells, make sure you leave no spaces in the cell.
1. Save the node

VACMS-1120 Make table field not required.

---

tests/behat/drupal-spec-tool/content_model_bundles.feature
tests/behat/drupal-spec-tool/content_model_fields.feature

Break content model fields into own feature.  
This is done to allow the spectool to output two diffrent features instead of concat erroring trying to do one big one.
automated tests pass.
The behat tests in the spectool have been altered to have two separate spots to copy from on the content model.  One is the bundles, the other is fields.
1. Validate behat tests pass.

VACMS-000 Break content model feature into two

---

docroot/modules/custom/va_gov_db/va_gov_db.install

See #1202 
Visual
- As admin, for each of these nodes: `[68, 71, 72, 73, 74, 77, 78, 79]` go to `/node/{NID}/revisions` and visually verify page loads (was throwing fatal when dateless revisions existed).

VACMS-1202: Removing dateless revisions in update hook.

---

.gitignore

This is how I am overriding my local php settings to get xdebug to work and the db port so I can access consistently from my external db tools.
.lando.local.yml:
```
services:
appserver:
config:
php: ./lando/.zzzz-local.ini
database:
portforward: 33242
```
.lanod/zzz-local.ini
```
[PHP]
; File is named zzz-lando-my-custom.ini because Lando renames on copy to /usr/local/etc/php/conf.d/
; Default is 90, this is higher because /graphql requests timeout locally for WEB builds otherwise.
max_execution_time = 190
; Xdebug
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
; Extra custom Xdebug setting for debug to work in VSCode.
xdebug.remote_enable = 1
xdebug.remote_autostart = 1
xdebug.remote_log = /tmp/xdebug.log
xdebug.remote_port=9001
xdebug.collect_assignments=1 …
```

update gitignore to allow for custom php config and custom lando

---

composer.json
composer.lock
config/sync/block.block.sitealert.yml
config/sync/block.block.vagovadmin_page_title.yml
config/sync/block.block.vagovadmin_primary_local_tasks.yml
config/sync/core.extension.yml
config/sync/lightning_core.versions.yml

See #1023. 
Tested locally
1.  Go to /admin/config/system/site-alerts and add a new site_alert.  
2.  In  a new tab, edit the site_alert and save it.
3. Validate Drush commands either by pulling locally or by sshing into CI.

VACMS-1023 Add module site_alert and patch to add drush commands.

---

composer.json
composer.lock

See #1207 
Adds the patch from https://www.drupal.org/project/site_alert/issues/3120303 to make the output 508 accessible.
Populated with site_alerts
Empty block (no active site alerts)
Login as any user other than anon
1. Go to any page in the cms,  admin or otherwise.
1. Then inspect the area just above the h1.

VACMS-1207 Add patch for site_alert 508.

---

config/sync/core.entity_form_display.node.page.default.yml
config/sync/core.entity_form_display.paragraph.alert.default.yml
config/sync/core.entity_view_display.block_content.alert.default.yml
config/sync/core.entity_view_display.node.page.default.yml
config/sync/entity_browser.browser.alert_blocks.yml
config/sync/user.role.content_admin.yml
config/sync/user.role.content_creator_benefits_hubs.yml
config/sync/user.role.content_editor.yml
config/sync/user.role.content_publisher.yml
config/sync/user.role.content_reviewer.yml
config/sync/user.role.vamc_content_creator.yml
config/sync/views.view.custom_block_entity_browsers.yml
tests/behat/drupal-spec-tool/content_model_fields.feature
tests/behat/drupal-spec-tool/views.feature
tests/phpunit/SecurityRolesPermissionsTest.php

See #1273 . 
See QA steps below.
Before
After
As randi.hecht@va.gov

VACMS-1273: Entity browser for alert block, and improved view display.

---

config/sync/core.entity_form_display.block_content.promo.default.yml
config/sync/field.field.block_content.promo.field_image.yml

See #1282 
1. Go to /block/add/promo

VACMS-1282 Add media browser to block promo image.

---

drush/drushrc.local.php
drush/drushrc.php

Added drusrc.php and drushrc.local.php files in order to set base url to be used in `lando drush uli`. 
Local environment cli

VACMS-0: Generate fully qualified local domain link with lando drush uli

---

config/sync/diff.settings.yml

See #1081 . 
1. log in and visit /node/35/revisions and click "Compare selected revisions"
##

VACMS-1081: Set visual_inline as default diff view.

---

config/sync/field.field.node.event_listing.field_intro_text.yml
config/sync/field.field.node.health_services_listing.field_intro_text.yml
config/sync/field.field.node.leadership_listing.field_intro_text.yml
config/sync/field.field.node.locations_listing.field_intro_text.yml
config/sync/field.field.node.press_releases_listing.field_intro_text.yml
config/sync/field.field.node.publication_listing.field_intro_text.yml
config/sync/field.field.node.story_listing.field_intro_text.yml
tests/behat/drupal-spec-tool/content_model_fields.feature

See #1144 
Visual
As an admin, visit
- `/admin/structure/types/manage/story_listing/fields/node.story_listing.field_intro_text`
- `/admin/structure/types/manage/publication_listing/fields/node.publication_listing.field_intro_text`
- `/admin/structure/types/manage/story_listing/fields/node.story_listing.field_intro_text`
- `/admin/structure/types/manage/press_releases_listing/fields/node.press_releases_listing.field_intro_text`
- `/admin/structure/types/manage/locations_listing/fields/node.locations_listing.field_intro_text`
- `/admin/structure/types/manage/leadership_listing/fields/node.leadership_listing.field_intro_text`
- `/admin/structure/types/manage/health_services_listing/fields/node.health_services_listing.field_intro_text`
- …

VACMS-1144: Change intro text field on listings to optional.

---

docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.module

See #1189 . 
Visual + code review

VACMS-1189: Do not render Preview btn for banner alerts

---

config/sync/core.entity_form_display.block_content.promo.default.yml
tests/behat/drupal-spec-tool/content_model_fields.feature

See #1319. 
1. Go to /block/add/promo
2. Click on "Add media" button

VACMS-1319 Change entity browser to media_library on block:promo.

---

composer.json
composer.lock

See #1172 . 
This is a contrib module update which pulls in a fix for sites that reject header only curls.
As an admin visit /health-care/health-needs-conditions/mental-health
- Click the edit tab, then save  (no changes needed) this is just to cause the node link report to be rebuilt.

VACMS-1172 Update node_link_report to get 1.13.

---

config/sync/core.entity_form_display.node.landing_page.default.yml
config/sync/core.entity_view_display.node.landing_page.default.yml
tests/behat/drupal-spec-tool/content_model_fields.feature

This is a follow up to #1274, in which i missed one field instance. 
Validated on /health-care and the edit screen for /health-care.
As randi.hecht@va.gov

VACMS-1273: Adding form widget and display setting for alert.

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module

See #1314 
Approach: when an item is feature toggled on, toggle off all other content of same bundle in system.
Disregard 1st/2nd placement select list (it isn't used, and will probably be removed)
Visual

VACMS-1314: Adding logic to prioritize last featured item.

---

config/sync/core.entity_form_display.taxonomy_term.health_care_service_taxonomy.default.yml
config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml
config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_owner.yml
docroot/modules/custom/va_gov_backend/va_gov_backend.install
tests/behat/drupal-spec-tool/content_model_fields.feature

See #1047 . 
- Sets default value for field_owner to "National health care service descriptions (46)" for all terms within `VHA health service taxonomy` vocabulary
- Disables field_owner on taxonomy term form display and taxonomy term view page
- Adds hook_update that standardizes field_owner value for all terms within the vocabulary by setting it to "National health care service descriptions (46)"
Visual + code.
[PR env link](http://pr1331a.ci.cms.va.gov/admin/reports/dblog?type%5B%5D=va_gov_backend)
1. `lando drush updb -y`, then check dblog for the number of terms updated. You should see the following summary message - `VHA health service taxonomy: Successfully updated an owner for 6 out of 95 terms. Failed to update 0 out of 95 terms.` . Logs in PR env …

VACMS-1047: term owner

---

config/sync/views.view.media_library.yml
tests/behat/drupal-spec-tool/views.feature

See #1089 
THis PR essentially reverts the views to what media_library defines, then adds our customizations back to it.
1. As a content admin got to /node/add/documentation_page
1. Then scroll down to "Main Content" and click the "Add Content block" button.
1. Select the "EMBEDDED IMAGE" block type
1. Click "Add media" button.
5. Add another content block, by clicking "Add content block" 
6. Scroll down and select "LINK TO FILE OR VIDEO"
7.  Click "Add media" button.

VACMS-1089 Get medialibrary widget working properly.

---

composer.json
composer.lock

See #1313 . 
- Fixed a bug in entity_browser display plugin - https://www.drupal.org/project/entity_browser/issues/3123876
Visual + CR.
Optional: to reproduce fixed bug, switch to master branch, repeat same steps, note bug on the last step

VACMS-1313: Patch entity_browser.

---

config/sync/core.entity_form_display.node.event.default.yml
config/sync/core.entity_form_display.node.news_story.default.yml
config/sync/core.entity_form_display.node.outreach_asset.default.yml
config/sync/core.entity_form_display.node.press_release.default.yml
config/sync/node_revisions_autoclean.settings.yml
tests/behat/drupal-spec-tool/content_model_fields.feature

See #1378 . 
As an admin
1. vist the following pages:
/admin/structure/types/manage/outreach_asset/form-display
/admin/structure/types/manage/event/form-display
/admin/structure/types/manage/press_release/form-display
/admin/structure/types/manage/news_story/form-display

VACMS-1378 export field listing display

---

Jenkinsfile.cd

Also follows up on https://github.com/department-of-veterans-affairs/devops/pull/6654 and https://github.com/department-of-veterans-affairs/devops/pull/6641.

VACMS-1359 Use correct Slack channel for PROD deploy failures, add success message.

---

config/sync/views.view.facility_governance.yml
docroot/modules/custom/va_gov_backend/va_gov_backend.module
tests/behat/drupal-spec-tool/views.feature

See #1369 . 
- Adds view page "Facility Status" at **/admin/content/facility-status**
- View is only available for users w/ roles: Content Admin, Administrator
**NOTE:** 
- due to the defect #1384 , "Modify field values" VBO action is not functional and may need to further configured once the defect is addressed. 
- Owner filter currently has only two options; once additional facility owner term are created on prod, I'll add them within #1375 .
Visual + CR
As user with Content Admin role (e.g. 1203 david.conlon@va.gov)

VACMS-1369: Facility governance dashboard.

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module
docroot/modules/custom/va_gov_db/va_gov_db.install
tests/behat/drupal-spec-tool/content_model_fields.feature

VACMS-1163: Updating new field with old field data in update hook.

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module
docroot/modules/custom/va_gov_db/va_gov_db.install

See #939 - oriignal update hook didn't set text format for new wysiwyg field, resulting in tags being encoded in output. This pr sets text format for new field, and prevents this from happening.
Visual

VACMS-939: Updating wysiwyg text format to fix tag output.

---

config/sync/core.extension.yml
docroot/modules/custom/va_gov_db/va_gov_db.install

See #1384 . 
Uninstalls `hide_revision_field` contrib module.

VACMS-1384: Uninstall hide_revision_field contrib.

---

config/sync/va_gov_post_api.settings.yml
docroot/modules/custom/va_gov_post_api/config/install/va_gov_post_api.settings.yml
docroot/modules/custom/va_gov_post_api/src/Form/VaGovPostApiSettingsForm.php
docroot/modules/custom/va_gov_post_api/va_gov_post_api.links.menu.yml
docroot/modules/custom/va_gov_post_api/va_gov_post_api.module
docroot/modules/custom/va_gov_post_api/va_gov_post_api.routing.yml

See #1533. 
- adds settings form for `va_gov_post_api` module
- adds menu item within Post Api menu "VA.gov Post API Settings"
- adds `bypass_data_check` flag; when checked, updated data comparison is bypassed an item payload is immediately returned + entity queued for syncing
Manual 
As user 1

VACMS-1533: va_gov_post_api bypass_data_check setting.

---

config/sync/pathauto.pattern.event.yml
config/sync/pathauto.pattern.news_story.yml
config/sync/pathauto.pattern.press_releases.yml

See #1546. 
Manual
As user ryan.stubblebine@va.gov with content_publisher role
1. Create a story, event, and news release
1. Assign all to Pittsburgh (owner and listing)
1. URLs should all start with /pittsburgh-health-care

VACMS-1546: Fix URL aliases for events news stories and press releases.

---

docroot/modules/custom/va_gov_backend/src/Service/UserPermsService.php

See #1548. 
Manual
**Note: this fixes caching issue for field_listing value storage. Permissions for some entities still need to be addressed.**

VACMS-1548: Fix cache cid for field_listing values storage.

---

composer.lock
config/sync/post_api.settings.yml

See #1556 . 
https://git.drupalcode.org/project/post_api/commit/ed3f8a9 
Queued 7 items.
Enabled xDebug and set breakpoints throughout processQueue() method to ensure I can delay the last item execution until 60 seconds have passed.
Ran queue process manually.
As expected, last item was not processed (no exp date) because it fell outside of the 60 sec runtime limit.
- make sure you have no real credentials added in settings.php in order to have item fail and go back to queue
- add at 3-5 items to queue
- set runtime settings to something ridiculous like 1 second at /admin/config/post-api/config
- Process queue manually
- check that queue items that were processed have expiration dates set. Locally, 1 seconds allowed for 1 processed item for me. For you mileage can very

VACMS-1556: QueueWorker max runtime.

---

docroot/modules/custom/va_gov_post_api/va_gov_post_api.install
docroot/modules/custom/va_gov_post_api/va_gov_post_api.module

Warning.  This update hook takes a long time to run.
The results look good related to all items being processed.
As admin user
Proof from CI

VACMS-1552 Update all facilities in lighthouse.

---

config/sync/views.view.facility_governance.yml

See #1582 . 
Visit /admin/content/facility-status

VACMS-1582 Add facility locator id to facility governance view.

---

composer.lock
docroot/modules/custom/va_gov_post_api/src/EventSubscriber/QueueItemProcessedEventSubscriber.php
docroot/modules/custom/va_gov_post_api/src/EventSubscriber/QueueProcessedEventSubscriber.php
docroot/modules/custom/va_gov_post_api/va_gov_post_api.services.yml

See #1581, #1580, #1553 
- added dispatch of event on successful item processing - when 200, 201, 202 HTTP codes are returned
- fixed Slack notification message for 0 items and empty message w/ flag icon
- added Event subscriber that logs a message when queue item POST returns 201, 202 codes. NOTE: it is also logged in Slack.
- added environment indicator to Slack notifications coming from va_gov_post_api
Sample slack messages below
1. add api sandbox creds in settings.php
1. add test slack webhook in settings.php to QA slack notifications
1. in order to test 201, 202 code responses ->  add `200` code to array of options at this line {INSERT}
1. add legit item to queue
1. process queue manually

VACMS-1581: post api 201/202 + VACMS-1580: Slack notification fix + VACMS-1553: Slack notification ENV

---

composer.json

This fixes the Fetching Packages failure on local Lando.
> error Couldn't find match for "e5a89baa54cde250d9ab7c553ebf398de9cba5af" in

Clear yarn cache on `composer nuke`.

---

config/sync/node_revisions_autoclean.settings.yml

The setting of cron was adding an item to the queue for every node saved.
This was causing the queue table to grow out of control to the point
where it got too big to process on cron.
As user _uid_ with admin
1. Go to here /admin/config/content/revisions-autoclean

VACMS-1528 Disable revision autoclean cron and set limits on unlimited.

---

config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
config/sync/core.entity_form_display.node.nca_facility.default.yml
config/sync/core.entity_form_display.node.vba_facility.default.yml
config/sync/core.entity_form_display.node.vet_center.default.yml
tests/behat/drupal-spec-tool/content_model_fields.feature

See #1415. 
Manual 
As Administrator or Content Admin user:

VACMS-1415: Set char limit for Operating Status - More Info field

---

config/sync/core.entity_form_display.node.event.default.yml
tests/behat/drupal-spec-tool/content_model_fields.feature

See #1604
Manual
As any user go to /node/add/event and review help text for the "online event" URL. it should prevent users from entering /node/2364 etc, and should specify that it must be an external URL.

VACMS-1604: Change event URL form widget from linkit to link.

---

composer.json
composer.lock

See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1625.  This. applies a patch from https://www.drupal.org/project/drupal/issues/3057267 to not log our users during a deploy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/1627)

Add patch from https://www.drupal.org/project/drupal/issues/3057267

---

config/sync/migrate_plus.migration.va_node_facility_nca.yml
config/sync/migrate_plus.migration.va_node_facility_vba.yml
config/sync/migrate_plus.migration.va_node_facility_vet_centers.yml
config/sync/migrate_plus.migration.va_node_facility_vet_centers_status.yml
config/sync/migrate_plus.migration.va_node_health_care_local_facility.yml
config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_nca.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vba.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers_status.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml

Revision history on the sidebar has not matched the updated dates and the history in the revisions tab.
This PR makes them all match
Content View
Revisions Tab
Triggering migrations on  pr environments will not have effect now that they are not being run as updates.

VACMS-1615 Set revisions correctly.

---

.dependabot/config.yml

Until https://github.com/department-of-veterans-affairs/va.gov-cms/issues/910 is resolved.

Get dependabot working again with just security updates (no va-gov/web)

---

docroot/modules/custom/va_gov_db/va_gov_db.install

Fixes batch process to process all nodes when updating text format for `field_intro_text_limited_html`
Visual
Published`

VACMS-1572: Fixing update hook to set text format for benefits field.

---

composer.json
composer.lock

See #1563
Added patch for site_alert - https://www.drupal.org/project/site_alert/issues/3132216
1. Do this
1. Then that

VACMS-1563: Patch site_alert to allow access in maintenance mode.

---

Jenkinsfile.cd

Our CMS-TEST jobs were auto-deploying to the wrong DEV & STAGING servers (CMS). This fixes that.
https://dsva.slack.com/archives/CT4GZBM8F/p1588204166333000

Parameterize the jenkinsfile.cd

---

composer.lock
docroot/modules/custom/va_gov_post_api/src/Form/VaGovPostApiSettingsForm.php

See #1506 .
-  Added Post API status UI.
- Added VA.gov Post API status UI - check if Slack Webhook is set
**variables are set**
**variables are NOT set**
**variables are set**
**variables are NOT set**
As an Administrator, locally

VACMS-1506: Post API Status UI

---

config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
config/sync/core.entity_form_display.node.health_care_region_page.default.yml
config/sync/core.entity_view_display.node.health_care_local_facility.default.yml
config/sync/core.entity_view_display.node.health_care_region_page.default.yml
tests/behat/drupal-spec-tool/content_model_fields.feature

See https://github.com/department-of-veterans-affairs/va.gov-team/issues/8188
- Build cms and then vets-website locally - build success
N/A
- As an admin, visit `http://va-gov-cms.lndo.site/admin/structure/types/manage/health_care_region_page/form-display` and `http://va-gov-cms.lndo.site/admin/structure/types/manage/health_care_local_facility/form-display`, visually verifying `field_nickname_for_this_facility` is disabled

VAGOVTEAM-8188: Removing nickname field from cms form and view.

---

docroot/modules/custom/va_gov_consumers/va_gov_consumers.module

See #1371  
1. Create a new VBA facility
2 Give it the title of "Mythical VBA" and locator ID of 'vba_2020' then save as draft.
3. Edit the node you just saved.
5. Visit an existing VHA Facility by going here /node/1706/edit

VACMS-1371 disable api fields

---

docroot/modules/custom/va_gov_post_api/src/Form/VaGovFacilityForceQueueForm.php
docroot/modules/custom/va_gov_post_api/va_gov_post_api.links.menu.yml
docroot/modules/custom/va_gov_post_api/va_gov_post_api.routing.yml

See #1585 . 
- Adds UI that allows to force-queue facilities of specific type for sync to Lighthouse
New menu item 
Form
As user 1

VACMS-1585: UI to force-queue facilities.

---

config/sync/block.block.user_sections.yml
config/sync/core.extension.yml
config/sync/lightning_core.versions.yml
config/sync/views.view.sections_tree.yml
docroot/modules/custom/va_gov_backend/va_gov_backend.module
docroot/modules/custom/va_gov_backend/va_gov_backend.services.yml
docroot/modules/custom/va_gov_user/src/Plugin/Block/UserSections.php
docroot/modules/custom/va_gov_user/src/Service/UserPermsService.php
docroot/modules/custom/va_gov_user/va_gov_user.info.yml
docroot/modules/custom/va_gov_user/va_gov_user.module
docroot/modules/custom/va_gov_user/va_gov_user.services.yml

See #1243. 
- adds custom block that renders user sections on user profile
- block output varies depending on whether user has no sections assigned, some section assigned, root section assigned "All sections" or user has roles Administrator or Content Admin
- users can now view own and other users' sections by visiting their profiles (given they have permission to view other users' profiles)
Note: decision was made to add custom block instead of View, due to the following factors:
- control of pages on which the block appears is much simpler via custom route check - e.g. render only on /user/* would render block on user view page but also on user edit pages and others. We'd need to add another contrib module in order to set correct path pattern in Block UI
- logic for differentiating …

VACMS-1243: Render user sections on their profiles.

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module

This operation currently acts on all content types and make the assumption of the property 'field_administration' being there.  If the content type is new, and does not have the property, a fatal error creates white screen.
The PR simply removes the assumption so there is no catastrophic failure.
1. Do this
1. Then that

VACMS-000 Eliminate fatal error making a new content type.

---

composer.json
composer.lock

See #998  
THis module has already been uninstalled and made its way to production.  This is simply the followup to remove it from the codebase.
There is no QA as there is nothing to test.

VACMS-998 Remove redirect_after_login from codebase.

---

docroot/modules/custom/va_gov_build_trigger/src/Service/BuildFrontend.php

See #1646 . 
This testing can only be done on dev or staging.

VACMS-1646 Disable build trigger if cli runs on BRD.

---

tests/phpunit/CreateMediaTest.php
tests/phpunit/CreateTaxonomyTermTest.php
tests/phpunit/PerformanceCreateNodeTest.php
tests/phpunit/PerformanceEditNodeTest.php
tests/phpunit/PerformanceLoginTest.php
tests/phpunit/PerformancePreviewTest.php

See #1657.
This PR:
* Increases the ceiling from 2 to 3 - see https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1657#issuecomment-631755887
* Adds a drupalLogout()
* Adds `__METHOD__` names to the output so we know what test is running/passing, instead of waiting until the end for a failure.

VAGOV-1657: Increase PerformanceLoginTest ceiling from 2 to 3.

---

docroot/modules/custom/va_gov_backend/js/gtm_tag_trackers.js

Per convo with Brian Martin (VSP Analytics and Insights team):
> One issue I found is that the uniqueEventId persists between events when the page isn't being reloaded. 
> Maybe a delete dataCollection['gtm.uniqueEventId']  before the push to the dataLayer
Click and console.
Will be qa'd by analytics team after merge (they need to test against staging).

VACMS-000: Fixing unique event ID persistence on gtm push.

---

composer.json
composer.lock

See #1522 . 
Create a site alert with low severity that expires at a specific time.

VACMS-1522 Update site_alert and related patches.

---

config/sync/field.field.node.event.field_facility_location.yml

See #1904. 
Manual.
Go to /node/add/event. For the facility field, help text no longer instructs user to not include the address.

VACMS-1904: Improve help text for event facility fields.

---

composer.json
composer.lock
tests/phpunit/PostApiQueueTest.php

See #1534 . 
- added phpunit tests for Post API that are project-specific. Test verifies item expiration logic, for which we have applied a core patch. It is important, because it will notify us immediately if the core patch no longer applies
- added php unit tests to DO contrib post_api that verify basic queue functionality, dedupe logic and expiration logic. NOTE: expiration logic test is reversed see [comments in code](https://git.drupalcode.org/project/post_api/-/blob/2.x/tests/src/Kernel/PostApiQueueTest.php#L59). 
P.S. this PR is constantly getting out of date, so I'll rebase again once reviewed.

VACMS-1534: Project-specific post_api tests.

---

config/sync/filter.format.rich_text.yml

See #1957. 
Manual 
- Go to /node/add/page
- Add a link in a WYSIWYG field like so: `<a href="tel:711" aria-label="TTY. 7 1 1.">711</a>`
- Save the node
- aria-label should be retained in the content

VACMS-1957: Allow aria-label attribute for links.

---

docroot/modules/custom/va_gov_user/src/Service/UserPermsService.php

See #2015 
the fix in this PR is temporary
`hasPermission()` method does not return expected results by role and this issue need a more thorough investigation.
let's deploy this temp fix today, then I'll follow up w/ part II
See #2015 
login as admin

VACMS-2015: Sections access for content admins (TEMP fix).

---

config/sync/core.base_field_override.node.event.title.yml
config/sync/core.entity_form_display.node.event_listing.default.yml
config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
config/sync/core.entity_form_display.node.health_care_region_detail_page.default.yml
config/sync/core.entity_form_display.node.health_care_region_page.default.yml
config/sync/core.entity_form_display.node.health_services_listing.default.yml
config/sync/core.entity_form_display.node.landing_page.default.yml
config/sync/core.entity_form_display.node.leadership_listing.default.yml
config/sync/core.entity_form_display.node.locations_listing.default.yml
config/sync/core.entity_form_display.node.news_story.default.yml
config/sync/core.entity_form_display.node.office.default.yml
config/sync/core.entity_form_display.node.outreach_asset.default.yml
config/sync/core.entity_form_display.node.page.default.yml
config/sync/core.entity_form_display.node.person_profile.inline_entity_form.yml
config/sync/core.entity_form_display.node.press_releases_listing.default.yml
config/sync/core.entity_form_display.node.regional_health_care_service_des.default.yml

See #1959 . 
As an admin
1. review all content type forms for standardized display of the Editorial workflow fieldset
1. visit /node/add and open each form in new tab, then examine Editorial workflow fieldset while confirming that Revision log messaage is displayed right under the content state dropdown.
NOTE: two exceptions to the rule are:
1) VACM Facility Health Service content type `/node/add/health_care_local_health_service` since it is not. apart of a workflow
2)  Support service `/node/add/support_service`, which has an extra field in the Editorial workflow fieldset. I am not aware of this exception's purpose, so please confirm that the date field must like within the Editorial workflow fieldset

VACMS-1959: Standardize editorial workflow fieldset for all content types

---

docroot/sites/default/settings/settings.prod.php

We originally had 20+ minute build/deploy times and this didn't matter
much, but now that we are going for sub-1minute times this matters a
lot.
Resolves #2081.   
1. Do this
1. Then that

Lower content-only deploy release_wait time from 5 to 0.

---

docroot/modules/custom/disable_node_menu_item/disable_node_menu_item.module

See #1645 . 
This PR fixes PHP warning specified in #1645 
Original assumption was that this warning may have contributed to DB locks.
Unfortunately, this fix will not have any significant effects on reducing DB locks, since database writes have only been reduced on account of less messages written to DBlog.
As Admin user:

VACMS-1645: Fix disable_menu_link warning.

---

config/sync/core.menu.static_menu_link_overrides.yml
config/sync/field.field.node.va_form.field_administration.yml
config/sync/metatag.metatag_defaults.node__va_form.yml
config/sync/migrate_plus.migration.va_node_form.yml
config/sync/views.view.va_forms.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_form.yml

See #2108 . 
As an admin
1. go to /admin/content/va-forms
2 Go to /node/add/va_form  and open the "Forms DB Data" field group.  
3. Open the "Meta Tags" field group on the right rail. 
4.  Title case fixes require for an update migration to be run. Go to  `/admin/structure/migrate/manage/forms/migrations/va_node_form/execute`
Click the "Update" checbox and then click the "Execute" button
When the migration completes, Go to /admin/content/va-forms
-  [ ]  Following deployment to production go to `/admin/structure/migrate/manage/forms/migrations/va_node_form/execute`
Click the "Update" checbox and then click the "Execute" button.   This will correct the capitalization of titles.

VACMS-2108 VA Form modifications

---

composer.json
composer.lock
config/sync/user.role.content_api_consumer.yml
docroot/modules/custom/va_gov_consumers/src/Routing/RouteSubscriber.php
docroot/modules/custom/va_gov_consumers/va_gov_consumers.info.yml
docroot/modules/custom/va_gov_consumers/va_gov_consumers.services.yml
docroot/modules/custom/va_gov_content_export/src/Archive/ArchiveDirectory.php
docroot/modules/custom/va_gov_content_export/src/Event/ContentExportPreTarEvent.php
docroot/modules/custom/va_gov_content_export/src/EventSubscriber/ContentExportPreTarSubscriber.php
docroot/modules/custom/va_gov_content_export/va_gov_content_export.info.yml
docroot/modules/custom/va_gov_content_export/va_gov_content_export.services.yml
tests/phpunit/SecurityRolesPermissionsTest.php

See #2127 . 
AC:
As an unauthenticated user
1. Visit `/openapi/jsonapi?_format=json`
2. visit /cms-export/content
3. Save the tar and then open it.  
4. Open the `schema.json` file.

VACMS-2127 generate entity schemas

---

config/sync/core.menu.static_menu_link_overrides.yml
config/sync/node.type.event.yml
config/sync/node.type.event_listing.yml
config/sync/node.type.health_care_local_facility.yml
config/sync/node.type.health_care_region_detail_page.yml
config/sync/node.type.health_care_region_page.yml
config/sync/node.type.health_services_listing.yml
config/sync/node.type.leadership_listing.yml
config/sync/node.type.locations_listing.yml
config/sync/node.type.news_story.yml
config/sync/node.type.person_profile.yml
config/sync/node.type.press_release.yml
config/sync/node.type.press_releases_listing.yml
config/sync/node.type.publication_listing.yml
config/sync/node.type.story_listing.yml
config/sync/node.type.vamc_operating_status_and_alerts.yml
config/sync/system.menu.va-eastern-oklahoma-health-care.yml
config/sync/system.menu.va-oklahoma-health-care.yml
config/sync/system.menu.va-salt-lake-city-health-care.yml
config/sync/system.menu.va-sheridan-health-care.yml
tests/behat/drupal-spec-tool/menus.feature

Map out and Create Admin and Editorial Menus for VISN-19 Systems( Issue id : #10342).
As admin
Visit <Manage/content/menus/VAMC system menus> and validate that menus displayed match this.
Visit </admin/structure/types/manage/health_care_region_detail_page> and validate that the content type 
have new Menu items (VISN-19 systems) selected as enabled (check box) to match this.
Visit </admin/structure/types/manage/health_services_listing> and validate that the content type have new 
Menu items (VISN-19 systems) selected as enabled (check box) to match this.
Visit <Sections/veterans health administration/VAMC facilities> and validate that menus displayed for 
VISN-19 match this.
Visit <Manage/Content/Menus/CMS administration/Administration> and validate that VISN 19 systems are 
assigned as …

VISN 19 SECOND GROUP SYSTEM MENUS

---

composer.json

See #2223 
Visual
- As an admin, go to `/admin/structure/paragraphs_type/q_a_section/form-display` and create a `Details` group, adding all existing fields, and save
- As an admin, go to `node/23/edit` and open the first `Q&A Section` under `Main Content`
- Visually verify that the new fieldset appears, and all fields from the paragraph are contained within

VACMS-2223: Adding patch to fix paragraph node form fieldset displays.

---

docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.module

See #2064 
Turns out ief needs to have `#ief_submit_trigger` flag added to submit handler to attach parent entity, otherwise it's thrown away when parent form us saved.
Visual
As and admin, go to `/node/72/edit`, and add an item to `Support Services` in right rail.
Click `Save and continue editing` and visually verify that item added is still available.

VACMS-2064: Adding ief trigger submit to our preview submit.

---

docroot/modules/custom/va_gov_backend/js/gtm_tag_push.js
docroot/modules/custom/va_gov_backend/va_gov_backend.module

Per @jonwehausen, gtm needs to be pointed to `env-2` (currently points to `env-5`). This pr replaces 2 instances of `env-5` with env-2
Codebase grep
N/A
N/A

VACMS-000: Update gtm to use env-2 instead of env-5.

---

composer.json
docroot/modules/custom/va_gov_backend/va_gov_backend.module
docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
docroot/modules/custom/va_gov_migrate/va_gov_migrate.install
docroot/modules/custom/va_gov_migrate/va_gov_migrate.module
docroot/modules/custom/va_gov_post_api/va_gov_post_api.install
docroot/modules/custom/va_gov_post_api/va_gov_post_api.module

VACMS-2243: Add extensions that should be scanned by phpcs.

---

docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.module

See #1697 
Visual
N/A
- As an admin, go to `/node/5676/edit`
- Add a revision log message, and click the `Save and continue editing` button
- Go to `node/5676/revisions` and visually verify that the message you entered appears next to the revision you just created.

VACMS-1697: Remove custom revision message to allow core drupal revision message behavior.

---

config/sync/core.entity_form_display.node.health_care_local_health_service.default.yml

See #2254 
Visual
- As an admin, go to `/node/add/health_care_local_health_service` and visually verify that phone paragraph instance fields do not appear

VACMS-2254: Changing default paragraph instance for phone number to none

---

composer.json
composer.lock

Core patch to fix error
Confirmed patch worked.
1. Go to http://pr2276.ci.cms.va.gov/node/716/edit
1. Expand Scroll down to the "Main content" field and edit the "list of link teasers"
1. Change the /disabilty link text from `Disability` to `Disability BOO`
1. Set the workflow to Draft and click the "Save" button.
1. Scroll down and validate that the unpublished revision now has `Disability BOO` 
1. Edit the latest revision and scroll down to The link teaser and change `Disability BOO` back to `Disability` and save the revision as either published or draft (makes no difference)
1. Scroll down the page and see that the page now contains `Disability` (no 'BOO')

VACMS-2091: Add patch to fix error when changing paragraph field to published value.

---

composer.json
composer.lock

See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/2338

VACMS-2338: Removed node_revisions_autoclean from composer management

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module

Submit handler had name of old module - enamed to match new module.

VACMS-000: Fix mismatched submit handler not renamed for new module namespace.

---

docroot/modules/custom/va_gov_content_export/src/TomeExporter.php

See #2399. 
Post release steps:

VACMS-2399 Exclude documentation_page from content export.

---

docroot/modules/custom/va_gov_content_export/src/ListDataCompiler.php
docroot/modules/custom/va_gov_content_export/src/Normalizer/ContentEntityNormalizer.php
docroot/modules/custom/va_gov_content_export/src/TomeExporter.php
docroot/modules/custom/va_gov_content_export/va_gov_content_export.services.yml

See  https://github.com/department-of-veterans-affairs/va.gov-team/issues/11312. 
##Acceptance Criteria
All QA steps
As an admin:
1. Edit a list node `/pittsburgh-health-care/events`
a.  Save the node
2. Add a new event 
a. Go to /node/add/event and assign it to  event listing "VA Pittsburgh Health care events"  Fill out all required fields.
b. Publish and save the node.  Make note of its node id.
3. Run the full content export  Steps -> https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/cms-export.md#caveats

VATEAM-11312 Add ListDataCompiler to va_gov_content_export.

---

docroot/modules/custom/va_gov_content_export/src/ListDataCompiler.php

See #2528. 
Saved list node, validated that list items have the new format.  
1. Go to /node/2805/edit and save the node.
2. View the export file created for that node  docroot/sites/default/files/cms-export-content/node.ff3b83fc-7cae-4d5b-8278-9692e0964011.json
3. Scroll to the end of the node file
```
"reverse_field_list": [
{
"target_type": "node",
"target_bundle": "press_release",
"target_id": "395",
"target_uuid": "b1439fe5-db2a-4929-94a3-c9f571b882cf"
},
{
"target_type": "node",
"target_bundle": "press_release",
"target_id": "396",
"target_uuid": "1cf543f6-6be5-4a22-bba1-21f652e663ef"
},
{
"target_type": "node",
"target_bundle": "press_release",
"target_id": "401",
"target_uuid": "909d036c-6082-49f8-b19d-4499b736bb1f"
},
...
```

VACMS-2528 Reformat reverse_field data on lists.

---

config/sync/node.type.event_listing.yml
config/sync/node.type.health_services_listing.yml
config/sync/node.type.leadership_listing.yml
config/sync/node.type.locations_listing.yml
config/sync/node.type.press_releases_listing.yml
config/sync/node.type.story_listing.yml
config/sync/views.view.taxonomy_term.yml
tests/behat/drupal-spec-tool/content_model_bundles.feature
tests/behat/drupal-spec-tool/content_model_content_type_fields.feature

See #2385
Visual / Behat
As an admin, confirm that each of the listing types defined in #2385 have had their human readable names changed on the content type page.

VACMS-2385: Update human names for listing types.

---

docroot/modules/custom/va_gov_content_export/src/ListDataCompiler.php
docroot/modules/custom/va_gov_content_export/src/Normalizer/ContentEntityNormalizer.php
docroot/modules/custom/va_gov_content_export/src/TomeExporter.php

See #2529 . 
Handles multiple references to the same target :+1: 
Handles multiple content types using same reference field
As user _uid_ with editorial privs 
1. Go to /node/370/edit   and save the node.   This node has both a  reference to a `field_list` and a `field_facility_location`  So it will update two different list type entities. and itself.

VACMS-2529 Add reverse field data export for all reverse fields.

---

docroot/modules/custom/va_gov_content_export/src/Archive/ArchiveDirectory.php
docroot/modules/custom/va_gov_content_export/src/Controller/ContentExport.php
docroot/modules/custom/va_gov_content_export/src/SiteStatus/SiteStatus.php
docroot/modules/custom/va_gov_content_export/src/SiteStatus/SiteStatusInterface.php
docroot/modules/custom/va_gov_content_export/va_gov_content_export.services.yml

See #2347 
When the setting `va_site_deploy_mode` is set then the export endpoint should not re-tar the content.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/2568)

VACMS-2347 Do not tar files on cms export during deploy

---

config/sync/core.entity_form_display.node.va_form.default.yml
config/sync/core.entity_view_display.node.va_form.default.yml
config/sync/core.entity_view_display.node.va_form.external_content.yml
config/sync/core.entity_view_display.node.va_form.teaser.yml
config/sync/field.field.node.va_form.field_va_form_language.yml
config/sync/field.field.node.va_form.field_va_form_row_id.yml
config/sync/field.storage.node.field_va_form_language.yml
config/sync/field.storage.node.field_va_form_row_id.yml
config/sync/migrate_plus.migration.va_node_form.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_form.yml
tests/behat/drupal-spec-tool/content_model_content_type_fields.feature

See #2537 and #2540 . 
- evaluated forms
- behat tests
- ran migration with --update flag and validated that the row id was populated.
1.  Visit /node/6059/edit
This will update all the nodes to make them all have row ids.

VACMS-2537 add rowid to va form

---

docroot/modules/custom/va_gov_backend/js/gtm_tag_push.js
docroot/modules/custom/va_gov_backend/va_gov_backend.module

See https://github.com/department-of-veterans-affairs/va.gov-team/issues/11163
Per @jonwehausen , we need a switch to differentiate production from all other environments. So, if we are on prod, gtm is environment 2. All others are tracked as environment 5.
Visual inspection in console.

VACMS-11163: Add production environment variable id switch.

---

config/sync/config_ignore.settings.yml

The issue is menu breadcrumbs are being altered in prod but are trickling down to content export which does not reflect the current state of prod expected from other developers content export.

VACMS-000 Remove menu_breadcrumb from config ignore.

---

config/sync/views.view.child_terms.yml

See #2687. 
Before
After
1. Go to /section/vamc-facilities and check sorting

VACMS-2687: Sort child terms by term weight not TID.

---

scripts/sync-db.sh

see #2556 
https://github.com/department-of-veterans-affairs/devops/pull/7415
Tested locally with lando by `export CMS_IS_BRD="true"` and `export CMS_APP_NAME="cms-test"` and also without, works.

sync-db.sh add env var to pull sanitized db from correct s3 bucket

---

config/sync/core.base_field_override.node.media_list_videos.promote.yml
config/sync/core.base_field_override.node.media_list_videos.status.yml
config/sync/core.base_field_override.node.media_list_videos.title.yml
config/sync/core.entity_form_display.node.media_list_videos.default.yml
config/sync/core.entity_view_display.node.media_list_videos.default.yml
config/sync/core.entity_view_display.node.media_list_videos.teaser.yml
config/sync/core.menu.static_menu_link_overrides.yml
config/sync/field.field.node.media_list_videos.field_administration.yml
config/sync/field.field.node.media_list_videos.field_alert_single.yml
config/sync/field.field.node.media_list_videos.field_buttons.yml
config/sync/field.field.node.media_list_videos.field_buttons_repeat.yml
config/sync/field.field.node.media_list_videos.field_description.yml
config/sync/field.field.node.media_list_videos.field_intro_text_limited_html.yml
config/sync/field.field.node.media_list_videos.field_media_list_videos.yml
config/sync/field.field.node.media_list_videos.field_meta_title.yml
config/sync/field.storage.node.field_alert_single.yml
config/sync/field.storage.node.field_media_list_videos.yml
config/sync/node.type.media_list_videos.yml
config/sync/search_api.index.content.yml
config/sync/views.view.search.yml
config/sync/workbench_access.access_scheme.section.yml
config/sync/workflows.workflow.editorial.yml
docroot/modules/custom/va_gov_backend/js/script.js
tests/behat/drupal-spec-tool/content_model_bundles.feature
tests/behat/drupal-spec-tool/content_model_content_type_fields.feature

See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/2456
As an admin
1. Login
1. Navigate here: admin/structure/types/manage/media_list_videos
3. Confirm the following AC
optional directly under "Title and introduction" fieldset
list - Videos" | cardinality - single
4. Regression test the Alert Single component field on the Media List - Videos content type as well as the Step-by-step content type.

VACMS 2456 media list videos content type

---

config/sync/core.entity_form_display.paragraph.checklist.default.yml
config/sync/core.entity_form_display.paragraph.checklist_item.default.yml
config/sync/core.entity_view_display.paragraph.checklist.default.yml
config/sync/core.entity_view_display.paragraph.checklist_item.default.yml
config/sync/field.field.paragraph.checklist.field_section_intro.yml
config/sync/field.field.paragraph.checklist_item.field_section_intro.yml
tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature

See #2814 
Visual / behat
- As an admin, go to `/admin/structure/paragraphs_type/checklist/fields` & `field /admin/structure/paragraphs_type/checklist_item/fields`
- Visually verify that fields on form and in node view mode are ordered with intro below header
- Visually verify that header is limited to 70 chars, and intro is limited to 300 chars.

VACMS-2814: Adding new paragraph checklist field config.

---

composer.json
composer.lock

In addition, add "composer/installers" to prevent autoloader errors occuring from loss of
autoload logic provided by lightning. See https://www.drupal.org/forum/support/installing-drupal/2019-02-14/php-fatal-error-cannot-redeclare-config_get_config
See #2388 
Removed all composer installed dirs: `vendor`, `core`, `libraries`, `modules/contrib`, ran `lando composer install` then `lando rebuild -y` then `./scripts/sync-db.sh` and confirmed successful rebuild. Then accessed local instance of site, visiting multiple nodes, user pages, and modules admin page. All looked good.

VACMS-2388: Remove lightning and dependencies from composer and lock.

---

composer.json
composer.lock

See #2866.
This adds back the composer-plugin `oomphinc/composer-installers-extender` from the lightning-api that was removed in #2388.
STAGING didn't catch this because it actually does install DEV dependencies, it is only DevShop that has an initial step that does a `composer install --no-interaction --no-progress --no-dev --ansi` in the "install task" and then after that we have in tests.yml another one of `omposer install --dev --no-interaction --no-progress --ansi` which does get it, but we are failing before we get this. It was getting installed before as a dev dependency in lightning and normally CI would catch this but I think the PR that got this in had maybe got force pushed to once and it already had yarn installed.

VACMS-2866: Fix Yarn and consumer entity type missing in composer install

---

docroot/modules/custom/va_gov_content_export/src/Normalizer/LinkItemNormalizer.php
docroot/modules/custom/va_gov_content_export/va_gov_content_export.services.yml

See https://github.com/department-of-veterans-affairs/va.gov-team/issues/13177. 
Link fields were not exporting the full url.  They were using the Drupal uri schema.  GraphQL has it's own logic (`Drupal\graphql_core\Plugin\GraphQL\Fields\Entity\Fields\Link\LinkUrl`)to change the format of a link field outside of using normalizers.  My solution is to use a normalizer on JSON output.
Ran bulk export and saved the node to note the output of link files.
* View json file `docroot/sites/default/files/cms-export-content/paragraph.98ab52e2-2bc4-44a8-b05a-33024e467572.json`
* See that is contains the incorrect format for `field_link`
```
"field_link": [
{
"uri": "entity:node/1e8a72b4-c54c-432e-b53a-ef6a7969f40e",
"title": "Get help from a patient advocate",
"options": []
}
],
```
* Save node …

Add LinkItem normalizer

---

docroot/sites/default/maintenance.html

The current language gives conflicting instructions.   This removes the conflict.
(scale of text did not change... that is just due to the screenshot sizes)
It will look like 
Cpde was also added to make the browser auto-refresh every 20 seconds to make this behave in a manner similar to the actual site alert screen.

VACMS-000 Remove conflicting language on maintenance page.

---

config/sync/field.field.node.q_a.field_answer.yml

VACMS-2925: Remove Alert option within Q&A answer field.

---

config/sync/taxonomy.vocabulary.lc_categories.yml
tests/behat/drupal-spec-tool/content_model_bundles.feature

See #2924 
Visual / Behat
Verify `admin/structure/taxonomy/manage/lc_categories/overview` exists

VACMS-2924: Adding lc categories vocab.

---

docroot/sites/default/settings.devshop.php
docroot/sites/default/settings.php
docroot/sites/default/settings/settings.dev.php
docroot/sites/default/settings/settings.lando.php
docroot/sites/default/settings/settings.prod.php
docroot/sites/default/settings/settings.staging.php

See #2756 . 
1. Saved a node with a defined image `/node/2299/edit`
2. inspected the output of that page in the content export 
`node.5f30741e-d04b-4d0e-858a-3ab94334e3ca.json`
3. examined metatag image paths to make sure they contained the proper domain and path.
4. Examined path to page and made sure it was unaffected.
5. Examined view of the page to make sure the rendering of the image still worked
`/wilkes-barre-health-care/locations/northampton-county-va-clinic`
Testing wont be possible in CI because those paths are dyanmic and unaffected by these changes.   Will need to be tested on dev or staging.
As an admin:
`docroot/sites/default/files/cms-export-content/node.5f30741e-d04b-4d0e-858a-3ab94334e3ca.json`
`"image_src": "\/sites\/default\/files\/2020-04\/Northampton_480x330.jpg",` …

VACMS-2756 metatag entity paths B

---

docroot/modules/custom/va_gov_content_export/src/ListDataCompiler.php
docroot/modules/custom/va_gov_content_export/src/TomeExporter.php

See #2464. 
1. Edit /node/7829 (an event) and change its " Where should the event be listed?" from "Outreach: to "Va Coatseville health care Events" and save the node.
/docroot/sites/default/files/cms-export-content/node.30295cab-89be-4173-a33c-8c0ca0a85d07.json
does not contain an entry for  node 7829 in `"reverse_field_listing": [`    (the entries are in order, it would be the last one in the file if it was there)
/docroot/sites/default/files/cms-export-content/node.92fad4d5-d4b0-472d-894d-7dbf5a01d2c5.json  contains an entry in `"reverse_field_listing": [` 
2. Delete node/7829
/docroot/sites/default/files/cms-export-content/node.92fad4d5-d4b0-472d-894d-7dbf5a01d2c5.json  contains no entry for node 7829 in `"reverse_field_listing": [`

VACMS-2464 Alter reverse field logic for deletes and unpublishes

---

docroot/modules/custom/va_gov_content_export/src/AddBreadcrumbToEntity.php

See #2906 . 
* Ran the bulk export and no longer saw the error message
`lando drush va-gov-cms-export-all-content --process-count=8 --entity-count=500`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/2976)

Add section_association to exclude list for cms export breadcrumb creation

---

docroot/modules/custom/va_gov_content_export/src/ExportCommand/BuildCommands.php
docroot/modules/custom/va_gov_content_export/va_gov_content_export.drush.inc
docroot/sites/default/settings.php

See #2903. 
* Ran all cms export on with out the `export-dir` options: `lando drush va-gov-cms-export-all-content --process-count=8 --entity-count=500`
* Ran all cms export overriding the export directory: `lando drush va-gov-cms-export-all-content --process-count=8 --entity-count=500 --export-dir="public://cms-export-2"`
* Checked to see to see the new directory was created and contains contents
* Ran a diff on the two directories and they are the same.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/3014)

VACMS-2903 Allow export dir to be changed in the drush command

---

docroot/modules/custom/va_gov_content_export/src/ExportCommand/BuildCommands.php

Follow up to #3014
The issue was with the `--export-dir` not being passed.  I ran the script and it exported to the default path correctly.
```lando drush va-gov-cms-export-all-content --process-count=8 --entity-count=500 --delete-existing```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/3020)

Add a default value for export dir

---

tests/phpunit/PerformanceLoginTest.php

See #3042 
as a DevOps Engineer:

VACMS 3042 Increase PHPUnit loginPerformance benchmark time to 5

---

phpunit.xml

See #2569 . 
* Ran `lando composer yaml-tests phpunit --dry-run` and did not see the messages anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/3104)

Add HTTP_POST server variable to phpunit

---

simplesamlphp-1.17.2/config/config.php

Reverts department-of-veterans-affairs/va.gov-cms#3083
This broke SSO login on PROD, and it was 
It was creating these SQLite files in other locations, so this code needs some more logic here.

Revert "Make path determination for samlsessiondb.sq3 work better."

---

config/sync/core.entity_form_display.node.basic_landing_page.default.yml
config/sync/core.entity_form_display.node.checklist.default.yml
config/sync/core.entity_form_display.node.faq_multiple_q_a.default.yml
config/sync/core.entity_form_display.node.media_list_images.default.yml
config/sync/core.entity_form_display.node.media_list_videos.default.yml
config/sync/core.entity_form_display.node.step_by_step.default.yml
config/sync/core.entity_view_display.node.basic_landing_page.default.yml
config/sync/core.entity_view_display.node.basic_landing_page.teaser.yml
config/sync/core.entity_view_display.node.checklist.default.yml
config/sync/core.entity_view_display.node.checklist.teaser.yml
config/sync/core.entity_view_display.node.media_list_images.default.yml
config/sync/core.entity_view_display.node.media_list_images.teaser.yml
config/sync/core.entity_view_display.node.media_list_videos.default.yml
config/sync/core.entity_view_display.node.media_list_videos.teaser.yml
config/sync/core.entity_view_display.node.step_by_step.default.yml
config/sync/core.entity_view_display.node.step_by_step.teaser.yml
config/sync/field.field.node.basic_landing_page.field_table_of_contents_boolean.yml
config/sync/field.field.node.checklist.field_table_of_contents_boolean.yml
config/sync/field.field.node.media_list_images.field_table_of_contents_boolean.yml
config/sync/field.field.node.media_list_videos.field_table_of_contents_boolean.yml
config/sync/field.field.node.step_by_step.field_table_of_contents_boolean.yml
tests/behat/drupal-spec-tool/content_model_benefits_hubs_content_type_fields.feature
tests/behat/drupal-spec-tool/content_model_lc_content_type_fields.feature
tests/behat/features/content_editing.feature
tests/behat/features/save_and_continue.feature

See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3013
As an editor
- Navigate to `node/add/checklist`
- Select the checkbox
- Complete all required fields.
- Save form.
- **GENERATE A TABLE OF CONTENTS FROM MAJOR HEADINGS**
Include table of contents
- Navigate to `node/add/step_by_step`
- DO NOT Select the checkbox
- Complete all required fields.
- Save form.
- **GENERATE A TABLE OF CONTENTS FROM MAJOR HEADINGS**
No table contents
- Navigate to `node/add/media_list_images`
- Select the checkbox
- Complete all required fields.
- Save form.
- **GENERATE A TABLE OF CONTENTS FROM MAJOR HEADINGS**
Include table of contents
- Navigate to `node/add/media_list_videos`
- DO NOT Select the checkbox
- Complete …

VACMS-3013: Enable TOC On LC Content Types

---

config/sync/field.storage.node.field_online_scheduling_availabl.yml
config/sync/field.storage.node.field_referral_required.yml
config/sync/field.storage.node.field_walk_ins_accepted.yml
config/sync/user.role.content_editor.yml
tests/phpunit/SecurityRolesPermissionsTest.php

See #3130 #3133 
Visual & PhpUnit
- Go to user perms page, and filter by va forms. Visually verify that content editor does not have the create permission.
- Go to a facility service form, and visually verify that unknown is an option for the three select fields.

VACMS-3130_3133

---

config/sync/linkit.linkit_profile.default.yml

See #3176 
Verified that R&S content is available to link with linkit widget.
As a user with the content admin role:
1. Create a "press release" node

VACMS-3176: Add R&S content types to linkit profile

---

config/sync/workflows.workflow.editorial.yml
tests/behat/drupal-spec-tool/workflow.feature

See #3189 
- Logged in as a user with the 'content admin' user.
- Tested approved -> published transition
- Tested approved -> archived transition
As a user with the content admin role:
- Create a node and set it to the "Approved" state
- Create a node and set it to the "Approved" state

VACMS-3189: enable transitioning nodes from approved to published

---

config/sync/core.entity_form_display.paragraph.rich_text_char_limit_1000.default.yml
config/sync/core.entity_view_display.paragraph.rich_text_char_limit_1000.default.yml
config/sync/field.field.node.q_a.field_answer.yml
config/sync/field.field.paragraph.rich_text_char_limit_1000.field_wysiwyg.yml
config/sync/field.storage.node.field_answer.yml
config/sync/paragraphs.paragraphs_type.rich_text_char_limit_1000.yml
scripts/content/VACMS-3196-qa_rich_text_field_content_migration-2020-10.php
tests/behat/drupal-spec-tool/content_model_bundles.feature
tests/behat/drupal-spec-tool/content_model_lc_content_type_fields.feature
tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature

Part 1 of #3196 
**Goals**:
* allow only one instance of Rich text field to be attached as an answer on a node of Q&A content type
* allow maximum of 1000 characters per answer - current Rich text field allows unlimited chars
* editors should use Rich text limited text format for the answer - currently "Rich text" paragraph defaults to "Rich text" format with extended toolbar.
To accomplish these goals, a new paragraph with specific form display configuration needed to be created, which also requires a migration of existing paragraph value for field_wysiwyg to a new paragraph. See below
**Implementation:**
* created paragraph type `Rich text - char limit 1000` and configured form display mode to render rich text field w/ default (and only) text format - Rich Text Limited with a char …

VACMS-3196: Q&A field_answer refactoring

---

config/sync/migrate_plus.migration.va_node_form.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_form.yml

See #3234 
Tested import with link_name field:
- empty
- only containing whitespace
- containing a url
- containing a url with leading/trailing whitespace
1. Run the VA forms import

VACMS-3234: trim link_name url field on import

---

tasks-periodic.yml

See #3233 . 
Running  `composer yaml-tests --tests-file=tasks-periodic.yml daily` only runs migrate/va_forms once.
This job is run by jenkins each night.  
Devshop does not have access to the url to get the source data CSV, do it will not be able to run the migration.
This is a removal of a duplicate only, it is low risk and needs no extended testing on CI.  (fully realizing I have jinxed myself by stating that)

VACMS-3233 Remove duplicate yml task for daily/migrate/va_forms.

---

phpunit.xml

See #3311 
Ran phpunit locally.
1. Run phpunit

VACMS-3311: remove extra characters

---

composer.json
composer.lock
docroot/modules/custom/va_gov_backend/js/smart_date_interactions.js
tests/behat/features/content_editing.feature

See #3326 
Local testing, added behat test.
As a user with the content editor role,
1. Visit a node with a systemwide banner alert, e.g. /node/1010/edit
1. Click the edit button in the 'System-Wide Alerts' fieldgroup
Edit a facility health service

VACMS-3326: fix ief button on systemwide alerts

---

config/sync/menu_breadcrumb.settings.yml

See #2992 Visual. 
Visual.
As anon, go to /decision-reviews
Should be no "Health care" in the breadcrumb.

VACMS-2992: Fix Decision reviews homepage breadcrumb.

---

config/sync/core.entity_view_display.node.landing_page.default.yml
docroot/modules/custom/va_gov_backend/va_gov_backend.module
tests/behat/Drupal/FeatureContext.php
tests/behat/features/content_editing.feature
tests/behat/features/decoupled.feature
tests/behat/features/perms.feature

See #2912.
I'm fairly new to this process, so any omissions/failures/errors/etc are unintentional.
Created and ran a Behat test.
Edit Form:
Proofing (Such As Is):
As user with permission to create a node of a type with moderation enabled, e.g. `press_release`.
1. Open a form to create a new node of that type.
2. Confirm that "Published" is not an option for the Moderation State widget.
3. Save the node as a draft or for review.
4. Confirm that "Published" is now an option for the Moderation State widget.

VACMS 2912: Force editors to save first as draft or in review, then publish on the proofing pages.

---

docroot/themes/custom/vagovadmin/assets/js/anchor_links.js
docroot/themes/custom/vagovadmin/vagovadmin.info.yml
docroot/themes/custom/vagovadmin/vagovadmin.libraries.yml

See #2729 
Manual testing on "How to edit detail pages — for VAMCs" page
As a user with the "authenticated" role:
1. Go to /help/product-guides/vamc/by-content-type/detail-pages
1. When clicking anchor links (e.g. "How to find existing Detail Page content to edit")
As an anonymous user:
1. Go to /help/product-guides/vamc/by-content-type/detail-pages
1. When clicking anchor links (e.g. "How to find existing Detail Page content to edit")

VACMS-2729: Take toolbar height into account when going to anchor links

---

config/sync/core.entity_view_display.node.health_care_local_health_service.default.yml
config/sync/core.entity_view_display.node.va_form.default.yml
config/sync/core.entity_view_display.node.vamc_operating_status_and_alerts.default.yml
config/sync/core.entity_view_display.node.vet_center.default.yml
tests/behat/features/content_editing.feature

See #3395 (and, for background, #2912 ).
I missed some content types when ensuring that the moderation controls were always visible and at the top of their view displays.
The affected content types were:
- `health_care_local_health_service`
- `va_form`
- `vamc_operating_status_and_alerts`
- `vet_center`
For each of these, the moderation control on the edit form was updated correctly, but the moderation control on the default display was disabled and consequently nodes of these types could not be published.
Added more test cases for Behat behavioral tests.
As a user with a role having publish permissions:
1. For each of the content types in moderation, view a node of the specified type that is in a non-published moderation state and verify that it has a moderation control present and that …

VACMS-3395: Editors can't publish some content types.

---

composer.json
scripts/content/VACMS-3325_paragraph_revision-2020-10.php

See #3325.  This fix adds a patch to fix the underlining issue of the paragraph always saving the `latest` revision as the `default` revision.  This was causing issues when the `paragraph` is loaded outside the context of the field.  The specific issue is with CMS export.
Looking at the data from the field we can see the revision paragraph ids.  These are used to test the script and verify the results.  The selection of the node came from the reported issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/15321
The update script updates the revision on the paragraph tables to the correct revision.  Originally I attempted to re-save the node to update the revision but this solution only worked if there weren't any draft node revisions.  
These queries show the data out …

VACMS-3324: Fix paragraph and Node being out of sync

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module

See #2457. 
Checked the field settings form for a couple of fields.
As an administrator:

VACMS-2457: Updates TableField caption help text.

---

config/sync/entity_clone.settings.yml

See #3449. 
Attempted to clone a node with paragraphs and noted that the form no longer contains checkboxes for the paragraph children of the original node.  Clone completed successfully and verified in Views that this created new paragraphs whose parents were the newly cloned node.
As any user with the permission to clone a node:
1. Clone [a node with paragraphs](http://va-gov-cms.lndo.site/entity_clone/node/2768)
1. Verify that:
It's just a config update.

VACMS-3449: Forces paragraphs to clone and hides their checkboxes on the clone form.

---

config/sync/core.entity_form_display.node.event.default.yml
config/sync/core.entity_form_display.paragraph.situation_update.default.yml
config/sync/core.entity_view_display.node.event.default.yml
config/sync/core.entity_view_display.node.event.teaser.yml
config/sync/core.entity_view_display.paragraph.situation_update.default.yml
config/sync/core.entity_view_display.paragraph.situation_update.preview.yml
config/sync/field.field.paragraph.situation_update.field_datetime_range_timezone.yml
scripts/content/VACMS-2812-update-timezone-data-2020-11.php
tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature
tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature

See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/2812
- Pull this branch down locally and stand up a local environment.
- Navigate here: `/node/9589/edit`
- Confirm original `field_date` values in the database:
- Navigate here: `/node/9589/revisions`
- Confirm original `field_date` revisions values in the database:
- Only a single content items exist that use the 'Situation Updates' paragraph field. 
- Navigate here: `/node/6922/edit`
- Scroll down to the 'SITUATION UPDATES' group
- Select Edit next to any of the situation updates
- Navigate here: `/node/6922/revisions`
- Select the very last revision by selecting the datetime under the revisions column
- Confirm the migration of data from …

VACMS-2812: Timezone Migration

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module

…andalone Page checkbox
See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3485
- Navigate to QA node add page here : `/node/add/q_a`
- Do NOT check **Enable standalone page** and fill out the fields within the **Question & Answer** group at the very top
- Fill out the fields within the **Question & Answer** group at the very top
- Select an owner from the sidebar within Governance.
- Navigate to QA node add page here : `/node/add/q_a`
- CHECK the **Enable standalone page**
- Fill out all required fields.
- Select an owner from the sidebar within Governance.

VACMS-3485: QA Standalone Fix

---

.lando.yml

Lando now includes a `composer_version:` setting which defaults to composer 2 and our site doesn't work on composer 2.  This PR hard codes the version to 1.10.1

Hard Code Composer version for lando

---

config/sync/views.view.right_sidebar_latest_revision.yml

See #3508
Confirmed that sort is correct on revision sidebar and revisions tab.
As a user with the 'Content Admin' role
1. Perform several moderation actions on a node during the same clock minute
1. Then validate Acceptance Criteria from issue:

VACMS-3508: Use revision creation time for right sidebar view sort

---

composer.json
composer.lock

Restore vets-website to use version in composer instead of commit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/3611)

Restore vets-website to use version in composer instead of commit

---

.lando.yml
composer.json
docroot/sites/default/settings.devshop.php
tests.yml

#3530 and #3600. 
This is to get Lando working with a composer install which does a yarn install for the latest vets-website. The python dependency gets farther but currently fails on Lando with:
> gyp gyp format was not specified; forcing "make
> gyp ERR! configure error                              
> gyp ERR! stack Error: `gyp` failed with exit code: 1

Update lando for vets-website install/make dependencies.

---

config/sync/core.entity_form_display.node.event.default.yml
config/sync/core.entity_form_display.paragraph.situation_update.default.yml

See #3555 
Visual / behat
As an admin, go to `node/7825/edit` and visually verify that the timezone choices only include the following:
```Americas
- Anchorage
- Chicago
- Denver
- Los Angeles
- New York
- Phoenix
Pacific
- Guam
- Honolulu
- Saipan
```

VACMS-3555: Limit tz choices.

---

docroot/modules/custom/va_gov_build_trigger/src/Form/BuildTriggerForm.php
docroot/modules/custom/va_gov_build_trigger/src/Service/BuildFrontend.php

See #3633. 
- Trigger web build on `admin/content/deploy` and do not see message `Web Rebuild & Deploy is in progress`
- Verify the build has been queue to run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/3649)

VACMS-3633: Do not set va build flag on devshop front end builds

---

composer.json
composer.lock

This is for an urgent issue to fix the builds on our new CI environments which have hyphens in the URLs
See https://github.com/department-of-veterans-affairs/vets-website/pull/15350
After this commit is tagged in the next release, we need to go back to the tag again with `composer require va-gov/web:^0.1`.

VACMS-000: composer require va-gov/web:dev-master#7b4c8725 (fix broken CI builds caused by hyphens in new URL pattern)

---

config/sync/field.field.block_content.alert.field_node_reference.yml

See #3731 
Visit /admin/structure/block/block-content/manage/alert/fields/block_content.alert.field_node_reference

VACMS-3731 Add content newer content types to alert block scope.

---

.tugboat/tugboat-grant-all-users-all-projects.sh  

This will be in the DevOps repo eventually. This runs every minute right now.

VACMS-000: Add tugboat-grant-all-users-all-projects.sh crontab script.

---

config/sync/core.entity_form_display.node.health_care_region_page.default.yml
docroot/modules/custom/va_gov_backend/va_gov_backend.install

See #3487 
Step 3 of 3. (Step 1 = remove fields from vets-web, Step 3 = remove fields from db in update hook)
Do not merge until https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3523 is merged
VIsual / Behat (will need to update tests before changing from draft to ready for review)
- As as admin, go to `admin/structure/types/manage/health_care_region_page/form-display` and visually verify that `Regional Health Service Offerings.` is disabled
- As an admin, go to `admin/structure/types/manage/health_care_region_page/fields` and visually verify that Featured content and Press release blurbs fields have been removed.

VACMS-3487 remove system fields step 3 of 3

---

config/sync/core.entity_form_display.node.support_service.default.yml
config/sync/core.entity_form_display.node.support_service.inline_entity_form.yml
config/sync/core.entity_view_display.node.support_service.default.yml
config/sync/core.entity_view_display.node.support_service.support_services_listing.yml
config/sync/core.entity_view_display.node.support_service.teaser.yml
config/sync/field.field.node.support_service.field_health_service_appt_leadin.yml
config/sync/field.storage.node.field_health_service_appt_leadin.yml
tests/behat/drupal-spec-tool/content_model_benefits_hubs_content_type_fields.feature

See #3840 
Attn: @mmiddaugh @kevwalsh @mpelzsherman @brangi 
- Add `fieldHealthServiceApptLeadin` to `src/site/stages/build/drupal/graphql/supportService.graphql.js`
- Update templates that use services data (e.g.: `src/site/facilities/health_service.drupal.liquid`, etc.) to include `fieldHealthServiceApptLeadin` - add check so that when field is empty, output this default text: `Contact us to schedule, reschedule, or cancel your appointment. If a referral is required, you’ll need to contact your primary care provider first.`
Visual/Behat
As an administrator, go to `admin/structure/types/manage/support_service/form-display` and visually verify that `Appointment lead-in text` appears identical to screenshot (when cog is clicked)

VACMS-3840: Add new leadin field to services.

---

composer.json
composer.lock
config/sync/advancedqueue.advancedqueue_queue.command_runner.yml
config/sync/core.extension.yml
config/sync/views.view.advancedqueue_jobs.yml
tests/behat/drupal-spec-tool/views.feature

See #3791 - This is a first PR that only enables the advancedqueue module, to prevent the [main PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3864) from failing to deploy.
Automated testing.
1. Do this
1. Then that

VACMS-3791: Add advancedqueue module and associated config

---

READMES/migrations-facility.md
READMES/vamc-facilities.md
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.health_care_region_page.yml
docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityService.php
docroot/modules/custom/va_gov_post_api/va_gov_post_api.module
docroot/modules/custom/va_gov_post_api/va_gov_post_api.services.yml

This PR has been tested against lighthouse sandbox and is working.  
It does not include the moderna data but that can be added at any time the migration run to bring those in.
~This PR is as far as we can take it until Lighthouse tells us the data format they want.~
When a system service node is saved, it checks to see if it belongs to the Covid 19 Vaccines term and if it does, it queues up a delivery to post to lighthouse.
Here is an example from the current code.
Tested with lighthouse on slack here 
https://dsva.slack.com/archives/C0FQSS30V/p1610129469068600?thread_ts=1607551861.482000&cid=C0FQSS30V
As an content_admin or admin
- Navigate to `/node/add/health_care_local_health_service` to add a new facility health care service.
- Under Health Service and Facility Basic Info Choose …

VACMS-3682 push facility covid service status

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module

…n a more defensive way
See _issueid_. https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3840
- Navigate here: `/node/add/health_care_local_health_service`
- Fill out required fields
- Leave Appointment Intro Text selection as : `Use default appointments intro text`
appointment. If a referral is required, you’ll need to
contact your primary care provider first._
- Save
- Confirm the following on the preview:
Use default appointments intro text
Contact us to schedule, reschedule, or cancel your
appointment. If a referral is required, you’ll need to
contact your primary care provider first.
- Navigate here: `/node/add/health_care_local_health_service`
- Fill out required fields
- Select …

VACMS-3840: Appt Intro Select Logic Fix

---

composer.lock

This update includes https://github.com/department-of-veterans-affairs/vets-website/pull/15601 which dramatically reduces build memory consumption and shaves ca. 30s off the build time. (Every little bit counts...)

Update va-gov/web (v0.1.1217 => v0.1.1227)

---

composer.json
composer.lock
config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
config/sync/views.view.benefits_hub_categories.yml
tests/behat/drupal-spec-tool/content_model_campaign_landing_page_content_type_fields.feature
tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature

See #3925 
Visual / behat
- As an administrator, go to `node/15068/edit`, open up the VA benefits panel, and click Select Benefit hubs button
- Visually verify that all items in browser have a description
- Close browser, and visually verify that selected items are in a sortable table.

VACMS-3925: Update browser to show r&s hub description info.

---

docroot/modules/custom/va_gov_backend/js/script.es6.js
docroot/modules/custom/va_gov_backend/js/script.js

See #4104 
Visual
- As and administrator, go to `node/add/health_care_local_health_service` and visually verify that the first service location does not have a remove button above.
- Add a second service location, and visually verify that a remove button appears above it.

VACMS-4104: Remove first service location removal button.

---

config/sync/views.view.content_release_logs.yml
docroot/modules/custom/va_gov_build_trigger/src/Plugin/Block/ContentReleaseStatusBlock.php
tests/behat/drupal-spec-tool/views.feature

See #4158 
Manual testing
As a user with the `content admin` role,
1. Go to the 'release content' page
1. Create a new build

VACMS-4158: Add content release logs view

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module

Fix tablefield sanitize function for caption
Saved node which has a paragraph with a table field with a caption.
Make sure the caption still exists on edit after save!
Did this on video call with @swirtSJW and @ndouglas
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/department-of-veterans-affairs/va.gov-cms/4181)

Fix tablefield sanitize function for caption

---

docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
docroot/sites/default/settings.php

The `exec()` call in #4149 didn't succeed, and then the attempt to log the output failed catastrophically.  This reverts the calls while leaving the function itself intact.
None.

VACMS 3955: Reverts changes to Jenkins API fetching to unbork main branch.

---

composer.json
composer.lock
config/sync/core.entity_form_display.node.vamc_system_policies_page.default.yml
config/sync/core.entity_view_display.node.vamc_system_policies_page.default.yml

See #4077 and #4138.
1. As an admin go to https://pr4224-0d61wv7bdc2wtwjdqvqwb9r4mdg3qbrt.ci.cms.va.gov/node/add/vamc_system_policies_page

VACMS-4077 Hide field labels and source data for entity field fetch fields.

---

config/sync/views.view.content.yml
tests/behat/drupal-spec-tool/views.feature

See #4212 
Per convo with @swirtSJW & @kevwalsh , decision made is to create an events tab with an exposed filter to sort by date. This view (for now) is only visible to administrators. 
Visual / Behat
- As an administrator, go to `admin/content/events/past` and visually verify (by clicking into individual events) that only past items are present.
- Confirm that filters and bulk op archive ops work as expected.

VACMS-4212: Add past events bulk ops view.

---

docroot/modules/custom/va_gov_graphql/va_gov_graphql.info.yml

va_gov_graphql uses basic_auth but did not declare its dependency.  THis remedies that so no detective work is needed. 
As admin  
1. go to /admin/modules
2. filter for "graph"

VACMS-000 Add dependency to va_gov_graphql.

---

docroot/modules/custom/va_gov_backend/css/toolbar.css
docroot/modules/custom/va_gov_backend/va_gov_backend.module

Follow-on to #3984 - improves accessibility.
Tested with voiceover on a mac, it reads "Last Content Release Time Button" and then the tooltip content.

Improve content release icon accessibility

---

.lando.yml
.tugboat/config.yml

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4240
Tested a base build w/no preview on this branch. Works. 
See the 10.5.8 here.

VACMS-4240: Upgrade Tugboat from Mysql to MariaDB 10.5

---

composer.json
composer.lock
patches/duplicate-row-message.patch

Removes a bunch of unused modules, and moves a remote diff based patch to our local patches dir. All modules were previously disabled, so this just ensures that they aren't sucked in by composer. I checked for orphaned tables, unused variables / config in settings files, etc.
Also checked that the local patch applies cleanly.
See:
#4252 
#4253 
#4254 
#4255 
#4256 
#4257 
#4314 
Build, log checks, spot checks
N/A

VACMS-4252_4253_4254_4255_4256_4257_4314 module removal and patch update

---

docroot/modules/custom/disable_node_menu_item/disable_node_menu_item.info.yml
docroot/modules/custom/va_gov_backend/va_gov_backend.info.yml
docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.info.yml
docroot/modules/custom/va_gov_bulk/va_gov_bulk.info.yml
docroot/modules/custom/va_gov_consumers/va_gov_consumers.info.yml
docroot/modules/custom/va_gov_content_export/va_gov_content_export.info.yml
docroot/modules/custom/va_gov_db/va_gov_db.info.yml
docroot/modules/custom/va_gov_db/va_gov_db.install
docroot/modules/custom/va_gov_flags/va_gov_flags.info.yml
docroot/modules/custom/va_gov_govdelivery/va_gov_govdelivery.info.yml
docroot/modules/custom/va_gov_graphql/va_gov_graphql.info.yml
docroot/modules/custom/va_gov_help_center/va_gov_help_center.info.yml
docroot/modules/custom/va_gov_login/va_gov_login.info.yml
docroot/modules/custom/va_gov_migrate/va_gov_migrate.info.yml
docroot/modules/custom/va_gov_post_api/va_gov_post_api.info.yml
docroot/modules/custom/va_gov_preview/va_gov_preview.info.yml
docroot/modules/custom/va_gov_resources_and_support/va_gov_resources_and_support.info.yml
docroot/modules/custom/va_gov_user/va_gov_user.info.yml
docroot/modules/custom/va_gov_workflow_assignments/va_gov_workflow_assignments.info.yml
docroot/modules/custom/zippylib/zippylib.info.yml

See #4274. 
This issue has two main AC's.
The first of which is that we need to ensure that the line `core_version_requirement: ^8 || ^9` replaces `core: 8.x` in all custom modules.
This can be tested by running the following commands from the repo root:
1.  `grep -L "core_version_requirement" docroot/modules/custom/*/*.info.yml` -- search for files matching the latter pattern that _don't_ contain the new string -- this should return no results.
2. `grep "core:" docroot/modules/custom/*/*.info.yml` -- search for files that _do_ contain the old string -- this also should return no results.
The second is that we need to ensure the absence of any deprecated code.  This is not practical without [some static analysis system](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4231 …

VACMS-4274: Make custom modules Drupal 9 compatible.

---

.lando.yml
READMES/local.md

As a developer, I want to be able to easily capture and view emails sent by the system, in order to easily debug mail-sending issues.
1. `lando rebuild`
2. run `lando info` to get the mailhog URL
3. generate an email, e.g. by creating a new user account

Add mailhog service to Lando

---

tests.yml
tests/scripts/build-web.sh

`yaml-tests` does not report an error when `composer va:web:build` exits with an error status, due to the use of `tee`. To reproduce the issue:
1. remove a dependency, e.g. `rm -r /web/node_modules/chokidar`
2. run `composer yaml-tests build`
You should see output similar to this:
```
✔ Process Succeeded in 1.272s Output: /path/to/file
✔ GitHub Status: va/web/build: success
```
tested with and without the missing dependency.

VACMS-4194: Fail the yaml test when va:web:build errors out

---

.lando.yml
.tugboat/config.yml
tests.yml

1) The deploy steps in tests.yml was only for DevShop to run things because we were using it outside its expected behavior. DevShop is gone now and we don't need these anymore.
2) The deploy steps order is changed to match the `drush deploy` recommendations. See https://www.drush.org/latest/deploycommand/
3) The composer install autoloader options are removed from Tugboat as we have them in composer.json config section. 
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3904
Deploy steps changes are also in BRD here > https://github.com/department-of-veterans-affairs/devops/pull/8557
- Tested locally on Lando
- Tested on Tugboat, this PR - passed
- Testing on BRD now, build works and doing a DEV deploy now and then tests should run and pass too

VACMS-3904 Remove deploy steps from tests.yml & change order of deploy steps to match `drush deploy`

---

config/sync/core.entity_form_display.taxonomy_term.health_care_service_taxonomy.default.yml
config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml
config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vet_center_com_conditions.yml
config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vet_center_friendly_name.yml
config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vet_center_service_descrip.yml
config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vet_center_type_of_care.yml
config/sync/field.storage.taxonomy_term.field_vet_center_com_conditions.yml
config/sync/field.storage.taxonomy_term.field_vet_center_friendly_name.yml
config/sync/field.storage.taxonomy_term.field_vet_center_service_descrip.yml
config/sync/field.storage.taxonomy_term.field_vet_center_type_of_care.yml
tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature

See #4147 
Visual / Behat
- As an administrator, go to `admin/structure/taxonomy/manage/health_care_service_taxonomy/add` and visually verify new fieldset and fields appear as in above screenshot.

VACMS-4147: Add new fields to vha vocab.

---

.lando.yml
.lando/zzz-lando-my-custom.ini
.vscode/launch.json
READMES/debugging.md

See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4519. 
1. Pull this PR locally.
2. `lando rebuild -y`
3. close and restart your vscode
3. Set a breakpoint in docroot/sites/default/settings.php
3. Activate "Listen for XDebug" in vscode.
4.  load drupal in your browser
5. close your browser tab and any other tabs showing lando so sitealert polling does not trigger new requests.
6. in your terminal `lando drush cr`
7.  `lando xdebug-off` to disable xdebug.  
8. Activate "Listen for XDebug" in vscode.
9.   load drupal in your browser
10. `lando xdebug-on` to enable xdebug.  
11. Activate "Listen for XDebug" in vscode.
12.   load drupal in your browser

VACMS-000 configure xdebug3 and connect to VScode.

---

composer.json
composer.lock

See #4553 
THis PR gets a necessary entity id to the FE team, but requires a re-save of all existing VAMC System policy node pages (currently there is only 1 :) 
/admin/content/bulk?title=&type=vamc_system_policies_page&moderation_state=All&taxonomy_entity_index_tid_depth=All
The also removed the theme errors we have been seeing related to entity_filed_fetch
1. Do this
1. Then that

VACMS-4553 Update entity_field_fetch to use ids.

---

config/sync/core.entity_form_display.node.campaign_landing_page.default.yml
config/sync/core.entity_view_display.node.campaign_landing_page.default.yml

See #4629 
Visual / behat
- Go to `/node/add/campaign_landing_page` and create a clp, sand Downloadable resources.
- Save, and visually verify that an empty Downloadable resources panel does not appear.

VACMS-4629: Prevent empty resources panel on node view.

---

docroot/modules/custom/va_gov_post_api/src/Form/VaGovFacilityForceQueueForm.php
docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityService.php
docroot/modules/custom/va_gov_post_api/va_gov_post_api.module

See #4484 and #4901
As admin
1. Visit here https://pr4889-7odr5cgaf5xv5bptmu1suz5d0srncuqk.ci.cms.va.gov/admin/config/post-api/queue  The api queue should either be empty or have one item in it matching `"uid":"facility_status_vha_999999"`  which is an artifact from automated testing.  Pressing the "Process queue" button should cause the list to empty.
2. Visit https://pr4889-7odr5cgaf5xv5bptmu1suz5d0srncuqk.ci.cms.va.gov/node/15380/edit  and save the node as draft
3.  visit https://pr4889-7odr5cgaf5xv5bptmu1suz5d0srncuqk.ci.cms.va.gov/admin/config/post-api/queue
4. Visit https://pr4889-7odr5cgaf5xv5bptmu1suz5d0srncuqk.ci.cms.va.gov/node/15380/edit and save the node as published
5.  visit https://pr4889-7odr5cgaf5xv5bptmu1suz5d0srncuqk.ci.cms.va.gov/admin/config/post-api/queue
6. Visit …

VACMS-4484 and 4901 Send covid appointment data to lighthouse.

---

composer.json
composer.lock
tests/behat/Drupal/FeatureContext.php

See #4950.  This extension is blocking the upgrade to Drupal 9, and as far as I can tell isn't actually used aside from a class subclassed by one of our Behat context classes (`\CustomDrupal\FeatureContext`).  I edited the subclass to subclass `Drupal\DrupalExtension\Context\RawDrupalContext` directly, ran tests, and didn't see any unanticipated failures.  Let's see if they still pass in Tugboat...
Ran Behat tests.
As a developer:
1. Observe that Behat tests have passed successfully.
1. Then validate Acceptance Criteria from issue #4950

VACMS 4950: Remove devshop/behat-drupal-extension

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module
docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.module

See #4541
Visual / Behat
- As an administrator, add Content publisher and Content creator - Vet Center roles to `vanessa.luxen@va.gov` account
- Add Create perms on main perms page for Vet Center Locations List, Vet Center Outstation and Vet Center Mobile Vet Center content types for Content creator - Vet Center role
- Assign `vanessa.luxen@va.gov` account all Vet Center sections.
- Add a VC Cap, and visually verify that all vc's are available in Owner dropdown
- Edit an existing Vet Center Outstation, and visually verify that the Owner dropdown is disabled.

VACMS-4541: Prevent non admin user from editing administration.

---

config/sync/core.entity_form_display.taxonomy_term.health_care_service_taxonomy.default.yml

…reated and fields moved into fieldgroup, change to open by default for both the VAMC and Vet Center fieldgroup
See _issueid_. #4993 
- Navigate to PR environment
- Navigate here: `/admin/structure/taxonomy/manage/health_care_service_taxonomy/add`
- 

VACMS-4993: Update VHA health service taxonomy to group VAMC and Vet Center fields

---

tests.yml

See #5081.
The Task task runner does not obey the expected rules for evaluating exit codes, which means the task runner can improperly interpret failed test tasks as having executed successfully.  This is a bad thing.
This PR rewrites all of the tasks in the `tests.yml` file as HEREDOCs and executes them in Bash so that the exit code will be properly interpreted and failed tests will be correctly recognized.
1. Do this
1. Then that

VACMS-5081: Refine tests taskfile.

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module

…made both the uri and title of the field_related_information optional in code
See _issueid_. #4753 
- Navigate to PR env.
- Navigate here: '/node/15603/edit'

VACMS-4753: Standalone-Page-Required-Hidden-Field

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module
docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.module

…n another field, added logic to unset the build of the office hours field on proofing page if the choice was to hide the office hours field
See _issueid_. #4972 
- Navigate to an existing vet center community access point form:
- `/node/16626/edit`
- `/node/16624/edit`
- `/node/16625/edit`
- Navigate here: node/16585/edit
- Navigate here: `/node/add/health_care_local_health_service`
- Fill out required fields
- Leave Appointment Intro Text selection as : `Use default appointments intro text`
appointment. If a referral is required, you’ll need to
contact your primary care provider first._
- Save
- Confirm the following on the preview:
Use default appointments intro text
Contact us to schedule, reschedule, or cancel your
appointment. If a referral is …

VACMS-4972: Vet-Center-Office-Hours-Opt-In

---

config/sync/config_split.config_split.dev.yml

See #5175.  Looks like the kint-devel thing might need to be done in multiple steps.
1. Do this
1. Then that

VACMS-0000: Removes kint module from dev config_split configuration.

---

config/sync/views.view.user_admin_people.yml

See #3263 #5040 #5041. (epic #5039)
Manual.
Helpdesk should perform this QA. 
As an admin
* go to https://pr5212-qn03aywof9kg7zylcur4nyqpt9kuk3xn.ci.cms.va.gov/admin/people
* Filter by various sections. The filter should work as expected (filtering by VISN 4 should show all users with associations to child sections
* Click edit on the Roles column. this should take you to the Roles tab instead of the full user form, which is easier to use.
* Click CSV to export to CSV. it should respect the filters. 

VACMS-3263-5040-5041: Improve /admin/people page for user admin.

---

composer.json
composer.lock

See #4947. 
This PR is to deal with the issues posed by certain contrib modules that haven't been updated since before Drupal 9's release.
These modules might be compatible in terms of PHP code, and indeed even have the `core_version_requirement: ^8 || ^9` snippet indicating that they're Drupal 9-compatible, but nevertheless conflict on a package level with Drupal 9 because they require Drupal 8.
This poses little risk because the code remains the same, but there's some due diligence involved in that package-level dependencies need to be dealt with specially.  So far this hasn't been an issue, but it might be as I continue work.
Previous PR seemed a little weird, so recreating.
1. Do this
1. Then that
Is an …

VACMS-4947: Add workaround repositories for certain modules.

---

composer.json
composer.lock
docroot/modules/custom/va_gov_build_trigger/src/Plugin/Block/ContentReleaseStatusBlock.php

See #5194.   The `content-build` repo needs to use source so the branch changes work correctly.
Search for a branch
Auto-complete PR:
Full Build

 VACMS-5194: Change content-build repo to use source

---

config/sync/field.field.node.documentation_page.field_administration.yml
config/sync/field.field.node.full_width_banner_alert.field_administration.yml
config/sync/field.field.node.nca_facility.field_administration.yml
config/sync/field.field.node.support_service.field_administration.yml
config/sync/field.field.node.va_form.field_administration.yml
config/sync/field.field.node.vamc_operating_status_and_alerts.field_administration.yml
config/sync/field.field.node.vba_facility.field_administration.yml
config/sync/field.field.node.vet_center.field_administration.yml
config/sync/field.field.node.vet_center_facility_health_servi.field_administration.yml
config/sync/field.field.node.vet_center_locations_list.field_administration.yml
config/sync/field.field.node.vet_center_mobile_vet_center.field_administration.yml
config/sync/field.field.node.vet_center_outstation.field_administration.yml
docroot/modules/custom/va_gov_backend/va_gov_backend.module
docroot/modules/custom/va_gov_user/src/Service/UserPermsService.php
tests/behat/features/content_editing.feature
tests/behavioral/cypress/integration/common/i_create_a_node.js

VACMS-4604: Change default field_administration to _none

---

tests/behavioral/cypress/support/commands.js

See #5361.  Used a deprecated function which will bite us in D9.  This is good to merge provided tests pass, as the code is only used in the tests that it breaks in D9.
1. Do this
1. Then that

VACMS-5361: Fixes user-loading in behavioral test.

---

config/sync/node_link_report.settings.yml

See #5296 
Visual
As an administrator, go to `admin/config/content/node_link_report` and visually verify that three whitelist domains have been added to exemption list, per screenshot.

VACMS-5296: Add three domains to link check whitelist.

---

config/sync/core.entity_form_display.node.vet_center_locations_list.default.yml
docroot/modules/custom/va_gov_backend/va_gov_backend.module

See #5390
Visual
As an administrator, go to `/node/16478/edit` and visually verify that you can remove nearby locations from either of the tables, without adding a revision message.

VACMS-5390 Remove buttons validation logic.

---

tests/behavioral/cypress/integration/common/i_select_the_benefits_hub.js
tests/behavioral/cypress/integration/entity_reference_validation.feature

See #5371.  I ran a total of about 120 trials of this and it failed twice in that time, for two different reasons -- one because the delay to wait for the iframe to complete loading was insufficient, and once because the delay between selecting benefit hubs wasn't long enough to allow Drupal to finish processing the side effects of the first selection.
I'd love to find an intelligent way of dealing with these issues, but there's a cost/benefit ratio to consider here.
Ran _a lot_ of tests.
1. Do this
1. Then that

VACMS-5371: Toughen entity reference validation behavioral test.

---

config/sync/field.storage.taxonomy_term.field_vet_center_type_of_care.yml

See #4893
~~1. Create a PR that adds the new key~~
~~2. Release it to prod~~
~~3. Edit the content on prod~~
**4. Create a PR that removes the old key - current PR**
5. Release to prod

VACMS-4893: Remove deprecated counselling value from field.

---

config/sync/core.entity_form_display.node.health_care_region_detail_page.default.yml
config/sync/node.type.health_care_region_detail_page.yml
tests/behat/drupal-spec-tool/content_model_bundles.feature
tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature

See #5120
Visual / behat
As an administrator, go to `admin/structure/types/manage/health_care_region_detail_page` and visually verify label reads `VAMC Detail Page`

VACMS-5120: Change detail page label to VAMC Detail page.

---

config/sync/user.role.content_publisher.yml
tests/phpunit/Security/RolesPermissionsTest.php

See #5447
Visual / phpunit
- Login as `user/34` and visually verify the content release button no longer appears in admin content menu.
- Visit `admin/content/deploy` and visually verify you see an access denied page.

VACMS-5447: Update content release perms.

---

.tugboat/config.yml

- Match Tugboat Memcached version to Elasticache version
- Use custom vacmsbot/docker-memcached-tugboat:1.6.6 image with 1GB ram.
See #5491 
Tested by rebuilding a base image from this branch on the Tugboat CMS-TEST Project and making 15 pull requests using the new image. 
No more out of memory errors.
Before:
After:
1. Do this
1. Then that

VACMS-5491: Memcache out of memory fix, 1GB container image

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module

On editing a vet_center  the following php notices are seen
```
Notice: Undefined index: field_nearby_vet_centers in _va_gov_vet_center_require_revision_message() (line 621 of modules/custom/va_gov_backend/va_gov_backend.module).
Warning: Invalid argument supplied for foreach() in _va_gov_vet_center_require_revision_message() (line 621 of modules/custom/va_gov_backend/va_gov_backend.module).
```
There are cases where that value is not present and should not be treated as an array.
As user admin
1. visit `/node/3612/edit`

VACMS-000 Fix source of php notice_va_gov_vet_center_require_revision_message

---

config/sync/image.style.viewport_width.yml
tests/behat/drupal-spec-tool/media.feature

See #5625
Once this is merged / depoloyed, @kelsonic will able to apply to clp templates.
Behat
- As and administrator, go to `admin/config/media/image-styles/manage/viewport_width` and visually verify `Scale width 2500` is set

VACMS-5625: Add viewport_width image style.

---

docroot/modules/custom/va_gov_backend/js/script.es6.js
docroot/modules/custom/va_gov_backend/js/script.js

See #4056
Visual
As an administrator, visit `/node/16142/edit` and visually verify that deletes, actions (the three vertical dots elements), row drags, and `Show row weights` action link appear.
Log in as a user who is not a content admin / admin, visit `/node/16142/edit` and visually verify that deletes, actions (the three vertical dots elements), row drags, and `Show row weights` action link do not appear.

VACMS-4056: Add logic to restrict elements to certain roles on centralized content.

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module
docroot/modules/custom/va_gov_db/va_gov_db.install

See #5739
Visual, updb
As an admin, go to `/admin/structure/taxonomy/manage/administration/overview` and visually verify that all children of vamc and vc have weight set to 0.

VACMS-5739: Set vamc and vc terms to 0 in hook and in subsequnt saves.

---

config/sync/core.entity_form_display.node.vamc_operating_status_and_alerts.default.yml

See #5764 
Visual / behat
- Go to `node/2370/edit` and visually verify presence of moderation widget 

VACMS-5764: Restore moderation widget on op status form.

---

docroot/modules/custom/va_gov_user/va_gov_user.module

See #5086
Visual
Login as `vanessa.luxen@va.gov` and visually verify you are redirected to Butler section page.

VACMS-5086: Add redirect on login for one section users.

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module

Leave empty array and function in place to allow for upcoming pr to add
content type to array and function.
VAMC Detail pages should have aliases locked after publish.
Visual
@kevwalsh to qa (please)

VACMS-000: Remove VAMC Detail page from alias unlock array.

---

tests/phpunit/FrontendBuild/Brd/BrdEnvironmentTest.php
tests/phpunit/FrontendBuild/Brd/BuildTimeRecorderTest.php
tests/phpunit/FrontendBuild/Brd/JenkinsClientTest.php
tests/phpunit/FrontendBuild/Brd/SystemsManagerClientTest.php

The kernel tests broke on staging post-deploy tests because the AMI has a too-old version of SQLite installed.
So I changed the tests to ExistingSiteBase tests.
These shouldn't interfere with other tests or the normal operation of the site once the test is completed because the container should be reset in the tearDown() method.
1. Do this
1. Then that

VACMS-0000: Changes KernelTests to ExistingSiteBase tests.

---

docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php

This is to resolve the notices from array merge trying to merge an array with a nothing.
1. Do this
1. Then that

VACMS-4988 Prevent notice when Menu form is not present.

---

docroot/modules/custom/va_gov_user/va_gov_user.module

path.alias_manager  is now path_alias.manager
causes this error when logging in with a non-admin account who only has one section assigned.
Introduced by https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5752/files
1.  https://cms-2tgedegcc2xecvh0jc23exmuhq5yz6ec.ci.cms.va.gov and Login as Ryan.Stubblebine@va.gov
1. Do this
1. Then that

VACMS-000 Update call to depricated path.alias_manager.

---

composer.lock

For https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5545.  
Upstream code for this release update is here > https://www.drupal.org/project/govdelivery_bulletins/issues/3223883
Tested this live on STAGING with opcache and memcache clearing, GovDelivery endpoint triggering works consistently now. 
This cannot be tested in a PR with our tests so I am not waiting for tests to pass before merge.

VACMS-5545: Fix GovDelivery Queue Cache issue

---

config/sync/core.entity_view_display.paragraph.address.user_guides.yml
config/sync/core.entity_view_display.paragraph.alert.user_guides.yml
config/sync/core.entity_view_display.paragraph.basic_accordion.user_guides.yml
config/sync/core.entity_view_display.paragraph.button.user_guides.yml
config/sync/core.entity_view_display.paragraph.checklist.user_guides.yml
config/sync/core.entity_view_display.paragraph.checklist_item.user_guides.yml
config/sync/core.entity_view_display.paragraph.collapsible_panel.user_guides.yml
config/sync/core.entity_view_display.paragraph.collapsible_panel_item.user_guides.yml
config/sync/core.entity_view_display.paragraph.contact_information.user_guides.yml
config/sync/core.entity_view_display.paragraph.email_contact.user_guides.yml
config/sync/core.entity_view_display.paragraph.featured_content.user_guides.yml
config/sync/core.entity_view_display.paragraph.link_teaser_with_image.user_guides.yml
config/sync/core.entity_view_display.paragraph.media.user_guides.yml
config/sync/core.entity_view_display.paragraph.media_list_images.user_guides.yml
config/sync/core.entity_view_display.paragraph.process.user_guides.yml
config/sync/core.entity_view_display.paragraph.q_a.user_guides.yml
config/sync/core.entity_view_display.paragraph.q_a_group.user_guides.yml
config/sync/core.entity_view_display.paragraph.q_a_section.user_guides.yml
config/sync/core.entity_view_display.paragraph.spanish_translation_summary.user_guides.yml
config/sync/core.entity_view_display.paragraph.table.user_guides.yml
config/sync/core.entity_view_display.paragraph.wysiwyg.user_guides.yml
config/sync/core.entity_view_mode.paragraph.user_guides.yml

Closes #5847
Visual / behat
Gonna need @kevwalsh to have a look - I looked at a handful of help pages on prod, and didn't find any examples of paragraph labels appearing in the output.

VACMS-5847: Hide labels from fields in paragraphs in Knowledge Base.

---

config/sync/va_gov_menu_access.settings.yml
docroot/modules/custom/va_gov_menu_access/src/Form/VaGovMenuAccessConfigForm.php
docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php

Closes #4988. 
-  [x] i shouldn't be able to add or edit menu items for content types other than Detail Pages
-  [x]  i should be able to place individual menu items of Detail Page content type, using the Menu settings in the right rail, but only with certain parents eligible:
in the UI parent item selector, when creating a health_care_region_detail_page, i should be able to see: 
-  [x]  any menu item that is eligible to have children (and its children, which should also be eligible to have children)
-  [x]  the ancestors of any menu item that is eligible to have children (except the top level, which is always the Health Care System, and is redundant)
-  [x] When editing an existing detail page, I should be able to pick a new menu parent from the allowed list, and have it persist after …

VACMS-4988 Menu Governance

---

config/sync/va_gov_menu_access.settings.yml
docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php

closes #5884 
As user assigned to multiple systems (james.hoehn2@va.gov)  
1.Navigate to https://pr5898-eesb1ll60jncmefcfkfwdpsua5layknl.ci.cms.va.gov/node/add/health_care_region_detail_page

VACMS-5884 Allow vamc facility menu roots to show.

---

config/sync/views.view.user_history.yml

Resolves #5873
Visual
As admin
1. go to user/2019/history 
2. Compare to prod's version for feature completion and readability. 

VACMS-5873: Make user history more readable.

---

composer.json
composer.lock
patches/graphql_8x3x_layout_builder_incompat.patch

See #5952 
Manual testing of /graphql/explorer
1. Do this
1. Then that

VACMS-5952: patch graphql to make the explorer work when layout_builder is enabled

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module

Closes diddly.  Looks like this added by Oksana in a481d5ecdbaa5247817909fff20b695e680960a7 and was only ever called from `_va_gov_backend_sync_office_listing_fields()`, which was removed in cd3dd92753c4c7157914bc3667411618e0a63832 by the Teaguester.  
1. Do this
1. Then that

VACMS-0000: Removes unused(?) function from va_gov_backend.module

---

composer.json

Closes #5974
Visual
- As an administrator, go to `admin/structure/types/manage/vamc_operating_status_and_alerts/form-display` and visually verify that inline entity form table view mode complex widgets now have `Allow users to delete existing facility operating statuses from system.` options. 
- Go to `node/2370/edit` and visually verify that when the delete system option is turned off on config form, a delete system option does not appear for inline entities when deleting from table.
- Confirm the inverse is true (e.g., when it's allowed in config, you see it on the entity form).
- Delete a couple of entities with the option enabled and with it disabled, and confirm it only deletes from the form when the option to remove from system is disallowed, and that it deletes from system when the …

VACMS-5974: Prevent inline entity form entity system delete.

---

composer.json
config/sync/filter.format.rich_text.yml
config/sync/filter.format.rich_text_limited.yml
docroot/modules/custom/va_gov_backend/src/Plugin/Filter/EmailLinkRepairFilter.php
tests/phpunit/Content/EmailLinkRepairFilterTest.php

Relates to #6113. 
Super simple approach based around `filter_var($string, FILTER_VALIDATE_EMAIL)` and a pretty selective XPath query.
TL;DR: If it looks like a bare email address, stick a `mailto:` in front of it.
```php
$urls = [
'test@example.org',
'test%40example.org',
'/test@example.org',
'/test%40example.org',
'mailto:test@example.org',
'mailto://test@example.org',
'https://absolute.url/test@example.org',
'https://absolute.url/test%40example.org',
];
foreach ($urls as $in) {
$out = filter_var($in, FILTER_VALIDATE_EMAIL);
$out = $out === FALSE ? 'Not Matched' : $out;
echo "$in: $out\n"; 
}
```
```
test@example.org: test@example.org
test%40example.org: Not Matched
/test@example.org: /test@example.org
/test%40example.org: Not Matched
mailto:test@example.org: Not Matched …
```

VACMS-6113: Automatically fix broken links to email addresses.

---

composer.lock
tests/phpunit/FrontendBuild/BuildFrontendTest.php

Relates to #4830.  Had worked on this when @mchelen-gov brought it up, decided to finish the job.  Private methods and NodeInterface made this not terribly fun, but my heart will go on.
literally nothing but tests.  a landscape of tests and test data extending boundlessly in all directions.  אור אין סוף
1. Do this
1. Then that

VACMS-4830: Add tests for BuildFrontend.

---

config/sync/core.entity_form_display.paragraph.staff_profile.default.yml
config/sync/field.field.node.leadership_listing.field_leadership.yml
config/sync/field.field.paragraph.staff_profile.field_staff_profile.yml
config/sync/views.view.content_entity_reference_source.yml
tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature
tests/behat/drupal-spec-tool/views.feature

Closes #6136
Visual / behat
- As an administrator go to `node/23354/edit` -> Main content, and add a staff profile block.
- Visually verify that the field is now autocomplete, and choices are displayed in [Name] - [System] format
- As an administrator go to `node/33491/edit` -> Leadership and add another item
- Visually verify that the field is now autocomplete, and choices are displayed in [Name] - [System] format

VACMS-6136: Update staff selection widget to use view.

---

tests/behavioral/cypress/integration/common/i_should_be_at_url.js
tests/behavioral/cypress/integration/user_login.feature
tests/behavioral/cypress/support/index.js

Relates to #6130.  Addresses some requested changes by @acrollet 
1. Do this
1. Then that

VACMS-6130: Some improvements to the user-login-single thing test.

---

.tugboat/config.yml

Relates to #6216 . 
Tested base image build on Tugboat, works now. 
1. Do this
1. Then that

VACMS-6216: Fix "Operation not permitted" in CI base image builds

---

config/sync/user.role.authenticated.yml
tests/phpunit/Security/RolesPermissionsTest.php

VACMS-6098: Allow any user to a workbench access section, regardless of their role.

---

config/sync/core.extension.yml
docroot/modules/custom/va_gov_banner/src/EventSubscriber/EntityEventSubscriber.php
docroot/modules/custom/va_gov_banner/va_gov_banner.info.yml
docroot/modules/custom/va_gov_banner/va_gov_banner.module
docroot/modules/custom/va_gov_banner/va_gov_banner.services.yml
docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
docroot/modules/custom/va_gov_workflow_assignments/src/EventSubscriber/EntityEventSubscriber.php
docroot/modules/custom/va_gov_workflow_assignments/va_gov_workflow_assignments.services.yml

Closes to #6148
Visual / behat
**Scenario 1**
**Scenario 2**
**Scenario 3**
**Scenario 4**
**Scenario 5**
**Scenario 6**
**Not allowed as non content-admins are not allowed to create banners.**
**Scenario 7**
**Not allowed as non-content admins are not allowed to create block alerts.** 
**Scenario 8**

VACMS-6148: Prevent non admins from altering banner scope path fields.

---

config/sync/views.view.content.yml
tests/behat/drupal-spec-tool/views.feature

Closes to #6302. 
Behat
As a content admin, 

VACMS-6302: Add content audit view display for content admins.

---

config/sync/core.entity_form_display.node.documentation_page.default.yml
config/sync/core.entity_form_display.taxonomy_term.products.default.yml
config/sync/core.entity_view_display.node.documentation_page.default.yml
config/sync/core.entity_view_display.node.documentation_page.teaser.yml
config/sync/field.field.node.documentation_page.field_products.yml
config/sync/field.field.taxonomy_term.products.field_kb_landing_page.yml
config/sync/field.storage.node.field_product.yml
config/sync/field.storage.node.field_products.yml
config/sync/field.storage.taxonomy_term.field_kb_landing_page.yml
config/sync/views.view.knowledge_base_article_administration.yml
tests/behat/drupal-spec-tool/content_model_user_guides_content_type_fields.feature
tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature

Relates to #6135 and #6103  
Behat, visual.
6135
6103 
As a content admin 

VACMS-6135: Make product field multivalue in KB articles. 

---

config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml

See #5696
This is a followup to https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5749#pullrequestreview-698247868 = it removes Erie endpoint.
This is on hold until VAMC Erie is ready for full launch, pending a new PAO training.

VACMS-5696 remove Erie operating status endpoint.

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/user.role.anonymous.yml
config/sync/user.role.authenticated.yml
tests/phpunit/Security/RolesPermissionsTest.php

Resolves #6317. 
phpunit, manual.
As anon verify that you can go to admin/appearance/styleguide/vagovadmin

VACMS-6317: Enable style guide for auth and anon users.

---

config/sync/prometheus_exporter.settings.yml
docroot/modules/custom/va_gov_backend/src/Plugin/MetricsCollector/ActiveUserCount.php

Relates to #4904. 
The issue says 60 seconds, I'm leery of the performance impact of 60 seconds, think it should be 180 seconds.
**EDIT** Per discussion at standup, we'll leave this at 180 seconds unless we see an issue with the granularity.
Refreshed `/metrics` and saw my endpoint.  This shouldn't be approved/merged though until the current criteria are discussed.
1. Do this
1. Then that
1. Then validate Acceptance Criteria from issue #4904 

VACMS-4904: Drupal sends number of active users.

---

config/sync/core.extension.yml
docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
docroot/modules/custom/va_gov_workflow/src/Service/WorkflowContentControl.php
docroot/modules/custom/va_gov_workflow/va_gov_workflow.info.yml
docroot/modules/custom/va_gov_workflow/va_gov_workflow.module
docroot/modules/custom/va_gov_workflow/va_gov_workflow.services.yml

Closes #5248
Visual
-  as RS 
- as  LT
-  as RS 
- as  LT
-  as RS 
- as  LT

VACMS-5248: Add logic to prevent non admin archive from node form.

---

tests.yml

The status-error check can fail because of components that are outdated on `main`.  This doesn't really help anything and instead just delays code approval and deployment, results in more resource use on Tugboat, etc.
This PR ignores certain classes of status error explicitly -- outdated core, outdated modules, and security updates -- on the assumption that these are already present on `main` and being handled in other PRs.
The punctuation in the change is intentional -- Drush reads the option as CSV, then transforms it into an array.  Apparently it's maddeningly particular about quotation marks.
```
root@php:/var/lib/tugboat# drush $DRUSH_ALIAS core-requirements --ignore=35 --format=list --severity=2
35
root@php:/var/lib/tugboat# drush $DRUSH_ALIAS core-requirements --ignore='35' …
```

VACMS-0000: Ignores complaints about module and core updates on status-error check.

---

config/sync/migrate_plus.migration.va_node_facility_vet_centers.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers.yml

Closes #6453 
Visual
-  ~Checkout this branch locally~ Go to https://pr6612-ce4wsxcbijctfw0ls3hecx7ixkywk2qh.ci.cms.va.gov and login as admin 
-  ~Clear the site cache with `lando drush cr`~  Tugboat does this as part of its build.
OR 
-  ~As an administrator,~ visit `/admin/structure/types/manage/vet_center/form-display`
- Enable the Official Name field and click Save
-  Visit `admin/content`, filter the list by Content type = Vet Center and click Edit for ~one~ several of the listed items

VACMS-6453: Add Official Name field to Vet Center migration

---

config/sync/views.view.user_admin_people.yml

Relates to #6504
Visual / behat

VACMS-6504: Turn off caching in the people view.

---

config/sync/views.view.user_admin_people.yml

Relates to #6602
Visual / behat

VACMS-6602: Set login time from last to time.

---

config/sync/field.storage.node.field_dismissible_option.yml

Closes issue #6430  
Visual testing
As a user with the admin role:

VACMS-6430: Remove option to dismiss banner for single session

---

docroot/modules/custom/va_gov_backend/src/Deploy/Plugin/HealthCheck.php

Relates to #6201 
- Activated "Deploy Mode" on Tugboat environment with `cp docroot/sites/default/settings/settings.deploy.inactive.php docroot/sites/default/settings/settings.deploy.active.php`
- Curl command without user-agent sent to Preview URL received HTTP 503 response.
- Curl command with `curl-prometheus-check` user-agent sent to Preview URL, received HTTP 200 response.
- Curl command with `Datadog/Synthetics` user-agent sent to Preview URL, received HTTP 200 response.
1. Do this
1. Then that

VACMS-6201: Add Additional Downtime User-Agent for Datadog

---

composer.lock

closes #6725
Automated testing to cover yjod and nothing to test until the FE team alters their query.

VACMS-6725 Bump entity_field_fetch to 1.0

---

config/sync/views.view.vha_health_service_taxonomy.yml

Add "Required Vet Center service" and "Number of Vet Center facilities with service" to the health service dashboard
closes #6749 .
Navigated to view in question and was able to see the new columns and improved column structure. Exported csv and saw the new fields.
As cms admin I am able to:
1. Navigate to `/vha-health-services` and see the view
2. Select a content type to filter the view to either VAMC services or Vet Center services
3. Confirm AC from ticket:

VACMS-6749 Update VHA Taxonomy Dashboard

---

config/sync/node_link_report.settings.yml

Closes #6923
This change has already been made on prod.  This is just getting it into config
https://pr6924-825b31zszo9ak8gqdhsd2hnns6dsh2gf.ci.cms.va.gov/centralized-content/vamc-system-medical-records-page-content

VACMS-6923 Exempt admin paths from node link report scan.

---

docroot/sites/default/settings/settings.prod.php

Relates to #6844.
Turn on Github Actions for Prod.

VACMS-6844: Change Production manual content release to use Github Actions

---

scripts/content/VACMS-5387-facility-services-add-service-location-2021-11.php

Relates to #5387
Visual / logs / console output

VACMS-5387: Add script to attach service location to health service nodes

---

composer.json
config/sync/field.field.node.event.field_datetime_range_timezone.yml
tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature

closes #5167.
Visual, behat.
As any VAMC or Outreach hub content creator, go to https://pr7028-dowvileyxc46dzwu4tpoeb1yvj4r8nnq.ci.cms.va.gov/node/add/event
-  Note that end date is also requried, which may not be ideal (see discussion on #5167)

VAMCS-5167: Date should be required on event nodes.

---

config/sync/field.storage.node.field_related_links.yml
tests/behat/drupal-spec-tool/content_model_benefits_hubs_content_type_fields.feature
tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature

- Updated "VAMC System" content type "Common Links" field (field_related_links) and changed limit to 8.
- Updated two behat tests: content_model_benefits_hubs_content_type_fields.feature and content_model_vamc_content_type_fields.feature.
closes #6918
As user editor
1. Go to `/node/add/health_care_region_page` and try to enter eight or more common links
1. You shouldn't be able to enter more than 8 links

VACMS-6918: Limit number of links added to Common Links on VAMC system content type

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module
docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.module

Closes #7030.  The logic was split out into two separate functions.  Unfortunately, this meant that the preview button would be added to a lot of different types.
I would like to figure out a good way of preserving the original intent of the change.  Also, I would like to add tests so we catch this next time 😃 
| Link | Type | Behavior |
| ---- | ----- | --------- |
| [Link](https://cms-e2yu31m89ruy2isogbs6bxi4jzh0v8mn.ci.cms.va.gov/banner/covid-19-vaccines-at-va) | Banner | Should NOT show a banner |
| [Link](https://cms-e2yu31m89ruy2isogbs6bxi4jzh0v8mn.ci.cms.va.gov/health-care/about-va-health-benefits/vision-care/blind-low-vision-rehab-services) | Benefits Detail Page | Should show a banner |
| [Link](https://cms-e2yu31m89ruy2isogbs6bxi4jzh0v8mn.ci.cms.va.gov/health-care) | Benefits …

VACMS-7030: Fixes appearances of the preview button.

---

config/sync/field.storage.node.field_related_links.yml
tests/behat/drupal-spec-tool/content_model_benefits_hubs_content_type_fields.feature
tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature

Reverts department-of-veterans-affairs/va.gov-cms#7036
The original is causing a change in structure to the graphQL results.

Revert "VACMS-6918: Limit number of links added to Common Links on VAMC system content type"

---

composer.json
patches/weitzman-drupal-test-traits-forbid-connection-reuse.patch

Relates to #7023.  Closes #7113.  This patches the `weitzman/drupal-test-traits` package to forbid it from reusing connections, in the hopes that this might keep it from basically sorta SlowLoris'ing our own machines during PHPUnit tests.
1. Do this
1. Then that

VACMS-7113: Forbids PHPUnit to reuse connections.

---

READMES/interfaces.md

Update documentation on our Feature Flags interface to link to FE Tools team documentation.
1. Do this
1. Then that

[DOCS] Add link to FE tools documentation on feature flags.

---

config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml

closes #7016  
As a github user

VACMS-7016: remove status endpoints for the week of December 1 2021

---

docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
docroot/modules/custom/va_gov_vet_center/src/Plugin/QueueWorker/CronRequiredService.php
docroot/modules/custom/va_gov_vet_center/src/Plugin/QueueWorker/RequiredServiceBase.php
docroot/modules/custom/va_gov_vet_center/src/Service/RequiredServices.php
docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.module
docroot/modules/custom/va_gov_vet_center/va_gov_vet_center.services.yml

Closes #6639 
Manual/visual testing
Changing the required status for a given facility health service
Filtering existing content to only show Vet Center - Facility Services (note the count)
How many missing Vet Center - Facility Services are we creating
Grab a list of Vet Centers to spot check before we run cron (3890, 3891, 3892, etc...)

VACMS-6639: autogenerate required service nodes for all vet centers

---

docroot/modules/custom/va_gov_consumers/va_gov_consumers.module

Relates to #7171
Visual
As witt.cook:
As admin:

VACMS-7171: Disallow non admins vast data editing ability.

---

config/sync/menu_breadcrumb.settings.yml

- Enabled the "VA Lovell Federal health care" menu in menu-breadcrumb.
closes #7163 
1. [x] Go to `/admin/config/user-interface/menu-breadcrumb` and verify and confirm that the **VA Lovell Federal health care** menu is enabled.
1. [x] Then as an anonymous user go to `/lovell-federal-health-care` and verify and confirm that the breadcrumb, page title and left column menu item title all matches and read **Lovell Federal health care**.

VACMS-7163: Fix Lovell Federal health care breadcrumb

---

config/sync/migrate_plus.migration.va_node_health_care_local_facility_status.yml
docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility_status.yml

VACMS-7246 Remove Los Angeles status endpoint.

---

config/sync/views.view.content.yml

- Updated the "Facilities", "Resources and support", "Bulk edit" and "Events" content views displays; moved the "Content revision: Revision user" field on top of the "Content: Changed (Updated)" field and set it to hidden. Then edited the "Content: Changed (Updated)" and with the "Rewrite results" put the fields together "{{ changed }} by {{ revision_uid }}".
closes #7161 
All test passed
**Content:**
**Facilities:**
**Resources and support:**
**Bulk edit:**
**Events:**
1. Go to `/admin/content`
1. Go to `/admin/content/facilities` 
1. Go to `/admin/content/resources-and-support`
1. Go to `/admin/content/bulk`
1. Go to `/admin/content/events`

VACMS-7161: Last updated by [revision user] is broken on /admin/content

---

composer.json
composer.lock
config/sync/core.entity_view_display.node.vamc_system_billing_insurance.default.yml
config/sync/core.entity_view_display.node.vamc_system_medical_records_offi.default.yml
config/sync/core.entity_view_display.node.vamc_system_register_for_care.default.yml
config/sync/core.extension.yml
config/sync/field.field.node.vamc_system_billing_insurance.field_non_clinical_services.yml
config/sync/field.field.node.vamc_system_medical_records_offi.field_non_clinical_services.yml
config/sync/field.field.node.vamc_system_register_for_care.field_non_clinical_services.yml
config/sync/field.field.node.vha_facility_nonclinical_service.field_administration.yml
config/sync/field.field.node.vha_facility_nonclinical_service.field_service_name_and_descripti.yml
config/sync/node_link_report.settings.yml
config/sync/views.view.non_clinical_services.yml

Closes #6874 
Visual Testing
In the following examples all content is part of the VA Alaska health care section:
From the edit view of a given VAMC System Billing and Insurance node:
After clicking the **Add a billing and insurance office** link in the image above:
From the edit view of a given VAMC System Medical Records Office node:
After clicking the **Add a medical records office** link in the image above:
From the edit view of a given VAMC System Register for Care node:
After clicking the **Add an admissions office** link in the image above:
Billing and Insurance
Medical Records Office
Register for Care

VACMS-6874: prepopulate entity reference fields on nonclinical service form when context is known

---

docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
docroot/modules/custom/va_gov_vamc/src/Service/ContentHardeningDeduper.php

Closes #7340.
As a vamc editor (Ryan.Stubblebine@va.gov)
1. Go to https://pr7356-nbt55fbdgc1ptojqbdfeb8dakuxmx763.ci.cms.va.gov/node/add/vamc_system_billing_insurance
2. Fill out all required fields.
3. Save the node as "published"
4.  Go to the node that was listed as archived 
1. Go to https://pr7356-nbt55fbdgc1ptojqbdfeb8dakuxmx763.ci.cms.va.gov/node/add/vamc_system_medical_records_offi
2. Fill out all required fields.
3. Save the node as "draft"
4. Edit and save the node as "draft"
5. Save the node as "published"
6.  Go to the node that was listed as archived 
1. Go to https://pr7356-nbt55fbdgc1ptojqbdfeb8dakuxmx763.ci.cms.va.gov/node/add/vamc_system_register_for_care
2. Fill out all required fields.
3. Save the node as "published"
6.  Go to the node that was listed as archived 
7. …

VACMS-7340 Make toptask deduper fire on node publish.

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module

Relates to #7373
Visual / behat

VACMS-7373: Remove save and continue from edit form for temp fix.

---

.ddev/config.yaml
.lando.yml
.tugboat/config.yml

Relates to #7376 .
1. Do this
1. Then that

VACMS-0000: Pin Composer version to 2.1.8 to fix breaking change

---

config/sync/field.field.node.vet_center_facility_health_servi.field_body.yml

- Updated the "Vet Center - Facility Service" content type "body" field description text.
closes #7333 
Passes all tests.
1. [x] Go to a "Vet Center - Facility Service" node (e.g.: /node/39885/edit) and verify and confirm that the "**Vet Center service description**" reads: _Use this short paragraph and up to six bullet points to detail how your Vet Center provides this service._

VACMS-7333: Update help text on vet center facility service body field

---

config/sync/pathauto.pattern.event.yml

Relates to #7433 .
Created a test event locally and saw that the url was updated to the new format.
See the path config updated to use nid here:
See the correct path in the cms here:
As cms editor I can
1. Create a new event and verify that the url is using the node id in the url and not the name
2. View an old event (/tampa-health-care/events/virtual-move-16-week-weight-management-program) and verify that the url is still using the name and not the node id
3. Run a bulk update on the URLs for events and see that the frontend builds and has no errors on [VAMC ](https://web-vvrcki00pnxyz1i6xolwjrozmcpko2be.ci.cms.va.gov/tampa-health-care/events/42305/) or [Hub ](https://web-vvrcki00pnxyz1i6xolwjrozmcpko2be.ci.cms.va.gov/outreach-and-events/events/27258/) events. 
3. Then validate …

VACMS-7433: Update pathauto for events to use nid instead of title.

---

.ddev/config.yaml
.lando.yml
.tugboat/config.yml
composer.json

Closes #7377.  This PR:
- adds the `config.allow-plugins` object that will be required by future versions of Composer (and in the meantime emits annoying and worrisome messsages)
- reverts Lando pinning Composer version to 2.1.8.
- reverts DDEV pinning Composer version to 2.1.8.
- reverts Tugboat pinning Composer version to 2.1.8.
BRD Composer version pinning is undone in [this Devops PR](department-of-veterans-affairs/devops#10479).
I've tested Lando and DDEV and not seen any issues.  Tugboat shouldn't cause any issues but it's substantially more difficult to test.  That said, given that I'm just reverting Eric's change, it should be safe.  Assuming tests pass this should be good.
Build, deploy, and post-deploy tests on BRD passed (see …

VACMS-7377: Ensures compatibility with Composer >2.2.0.

---

config/sync/node.type.event.yml
config/sync/node.type.event_listing.yml
config/sync/node.type.health_care_local_facility.yml
config/sync/node.type.health_care_region_detail_page.yml
config/sync/node.type.health_care_region_page.yml
config/sync/node.type.health_services_listing.yml
config/sync/node.type.leadership_listing.yml
config/sync/node.type.locations_listing.yml
config/sync/node.type.news_story.yml
config/sync/node.type.person_profile.yml
config/sync/node.type.press_release.yml
config/sync/node.type.press_releases_listing.yml
config/sync/node.type.publication_listing.yml
config/sync/node.type.story_listing.yml
config/sync/node.type.vamc_operating_status_and_alerts.yml
config/sync/node.type.vamc_system_billing_insurance.yml
config/sync/node.type.vamc_system_medical_records_offi.yml
config/sync/node.type.vamc_system_policies_page.yml
config/sync/node.type.vamc_system_register_for_care.yml

- Disabled "VA Lovell Federal health care" menu in all content types.
- Cleared "VA Lovell Federal health care" menu data.
- Deleted "VA Lovell Federal health care" menu.
closes #7163 
Passes all tests.
1. [ ] Go to `/admin/content-models/content` and verify and confirm that the "VA Lovell Federal health care" menu doesn't exist
1. [ ] Go to `/admin/structure/menu/manage/lovell-federal-health-care` and verify that this menu and its menu items are accessible and there are no errors
1. [ ] Go to the `/lovell-federal-health-care` node, edit it, change its page title to "Lovell Federal health care" and verify that there is no "VA Lovell Federal health care" menu available and the "Lovell Federal health care" menu is assigned to it
Is an announcement needed to let editors …

VACMS-7163: Remove "VA Lovell Federal health care" menu in CMS

---

config/sync/field.field.paragraph.link_teaser_with_image.field_media.yml
config/sync/field.field.paragraph.media.field_media.yml
tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature

closes #7274.
Added a benefit detail page and saw that media fields were required.
As a CMS editor, I can
1. Create a benefits detail page (`node/add/page`) 
2. Add a content block paragraph of 'embedded image' 
3. Create a CLP (`/node/add/campaign_landing_page`)
4. Enable the 'stories' panel and add a story and

VACMS-7274 do not allow empty media refs

---

config/sync/views.view.non_clinical_services.yml
docroot/themes/custom/vagovadmin/assets/scss/styles.scss
docroot/themes/custom/vagovadmin/templates/views/views-view-grouping--non-clinical-services.html.twig
docroot/themes/custom/vagovclaro/assets/scss/components/_views.scss
docroot/themes/custom/vagovclaro/templates/views/views-view-grouping--non-clinical-services.html.twig

Closes #7702 
Visual testing
Register for care (multiple locations)
Register for care (no locations)
Billing and insurance
Billing and insurance (no locations)
Medical records offices
Medical records offices (no locations)
[ ] Filter the content to locate a **VAMC System Medical Records** node within the **VA Eastern Colorado health care** section

VACMS-7702: implement UX enhancements for non-clinical services

---

config/sync/node.type.vamc_system_billing_insurance.yml
config/sync/node.type.vamc_system_medical_records_offi.yml
config/sync/node.type.vamc_system_register_for_care.yml
config/sync/node.type.vha_facility_nonclinical_service.yml
tests/behat/drupal-spec-tool/content_model_bundles.feature

Closes #7678 
Visual Testing
**VAMC System Medical records office**
A page about how Veterans can access their medical records within a VAMC system.
**VAMC System Billing and Insurance**
A page about how Veterans can pay a bill within a VAMC system.
**VAMC System Register for Care**
A page about how Veterans can register for care at a specific VAMC system.
**VAMC Facility Non-clinical service**
Address and contact info for offices and other non-clinical service locations. This content is always embedded within a VAMC system non-clinical service page.

VACMS-7678: add descriptions for top task content types

---

composer.json
composer.lock

Relates to #6948.  An alternative to #7374 that may or may not work.  Should not be merged until we're aligned on an approach.

VACMS-6948: Adds patch to explicitly set menu-link bundle. [DO NOT MERGE]

---

config/sync/node.type.vha_facility_nonclinical_service.yml

Closes #7784 
Visual testing
As an admin

VACMS-7784: add help text to non-clinical service forms

---

config/sync/core.entity_view_display.node.vha_facility_nonclinical_service.default.yml

Closes #7819 
Visual Testing
Before
After

VACMS-7819: remove editorial workflow widget from non-clinical node view

---

config/sync/field.field.node.person_profile.field_last_name.yml
config/sync/field.field.node.person_profile.field_name_first.yml
tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature

Closes #7353.
Created a new staff profile, saw fields were required. 
As cms editor I can
1. create a new staff profile (`/node/add/person_profile`) and see the fields for first and last name are now required.
2. Then that

VACMS-7353: Make name fields required on staff profiles.

---

config/sync/core.entity_form_display.node.vet_center_outstation.default.yml
tests/behat/drupal-spec-tool/content_model_vet_center_content_type_fields.feature

Closes #7788 .
As CMS editor, 
1. I can only put up to 300 characters in the operating status more info field.

VACMS-7788 update char count on operating status

---

config/sync/core.entity_form_display.node.health_care_region_detail_page.default.yml

- Removed text that contained the "create a new alert" link from the "Include alert" fieldset in the VAMC Detail Page content type.
closes #7540
As user administrator or editor
1. Go to `/node/add/health_care_region_detail_page` to verify and confirm that the "_You can <a href="/block/add/alert?destination=/admin/content/alerts">create a new alert</a>, or reuse an existing one._" text is not displayed

VACMS-7540: Remove UI help text that says create a new alert in VAMC detail page

---

docroot/themes/custom/vagovadmin/templates/form/form-element--textarea.html.twig

VACMS-7905: Fix broken textarea desriptions.

---

config/sync/core.extension.yml
docroot/modules/custom/va_gov_clp/va_gov_clp.info.yml
docroot/modules/custom/va_gov_clp/va_gov_clp.module

VACMS-5522: Prevent outputting empty clp panels on node view.

---

docroot/modules/custom/va_gov_vamc/js/limit_vamcs_to_workbench.es6.js
docroot/modules/custom/va_gov_vamc/js/limit_vamcs_to_workbench.js
docroot/themes/custom/vagovclaro/assets/scss/components/_alerts.scss
docroot/themes/custom/vagovclaro/assets/scss/components/_buttons.scss
docroot/themes/custom/vagovclaro/assets/scss/components/_centralized_content.scss
docroot/themes/custom/vagovclaro/assets/scss/components/_layout.scss
docroot/themes/custom/vagovclaro/assets/scss/components/_paragraphs.scss
docroot/themes/custom/vagovclaro/assets/scss/pages/_node-view.scss
docroot/themes/custom/vagovclaro/assets/scss/pages/_proofing.scss
docroot/themes/custom/vagovclaro/assets/scss/styles.scss
docroot/themes/custom/vagovclaro/templates/block/node-link-report-block.html.twig
docroot/themes/custom/vagovclaro/vagovclaro.theme

Relates to #7746.
- Updates display of centralized content for editors (help text was getting cut off in the headers)
- Updates system banner alerts to correctly winnow available options for editors in vagovclaro
- Fixes white screen of death when changing revisions in vagovclaro
- Adjusts spacing on the node view tab for consistency
- verified the above in vagovclaro
- made sure the winnowing still works as expected in vagovadmin as well
- made sure revisions could be changed, reverted, compared, without breaking the site.
- enable vagovclaro as the admin & default theme if it is not already
- log in as `randi.hecht@va.gov`
- visit `node/16142/edit` and see centralized content help text not cut off.
- log out
- log in as `ryan.stubblebine@va.gov`
- visit …

VACMS-7746 prelaunch fixes

---

docroot/modules/custom/va_gov_backend/va_gov_backend.module
docroot/modules/custom/va_gov_workflow_assignments/src/Plugin/Block/EntityMetaDisplay.php

VACMS-6696: Prevent previews and url links on no bio staff pages.

---

config/sync/views.view.non_clinical_services.yml
docroot/themes/custom/vagovadmin/assets/scss/styles.scss
docroot/themes/custom/vagovadmin/templates/views/views-view-grouping--non-clinical-services.html.twig
docroot/themes/custom/vagovclaro/assets/scss/components/_views.scss
docroot/themes/custom/vagovclaro/templates/views/views-view-grouping--non-clinical-services.html.twig

Closes #7721
Visual Testing
VA.gov Claro Theme
VA.gov Admin Theme

VACMS-7721: display published status on non-clinical service cards

---

composer.json
composer.lock
patches/graphql_8x3x_query_route_enhancer_update.patch

Relates to #8046. See that issue for tests, screenshots, etc.

VACMS-8046: add patch to stop graphql throwing notices.

---

config/sync/core.entity_form_display.node.health_care_local_facility.default.yml

- Updated the "Learn how to correct or update centrally-managed data" link in the "Facility data" section of the "VAMC Facility" content type in "Manage form display" default display.
closes #7871 
**VAMC Facility content type "Manage form display"**
1. Go to `/admin/structure/types/manage/health_care_local_facility/form-display` to:
2. Then go to `/node/1271/edit` (or any other VAMC Facility node) and:

VACMS-7871: Fix the "Learn how to correct or update centrally-managed data" broken link

---

.github/ISSUE_TEMPLATE/facility-data-change-request.md

The URL alias for the facility itself must be updated first or the bulk updates to facility service nodes will not reflect the new URL.

[docs] Refine steps for VAMC - name change

---

tests/behavioral/cypress/support/commands.js

This test is very flaky and needs a delay.  I don't know why it has recently started failing so frequently and spectacularly.
Waiting for a fixed amount of time is suboptimal.  However, Cypress [does not and will never have a concept of catching errors](https://github.com/cypress-io/cypress/issues/395), so we effectively can't test for the presence of certain fields without asserting that those fields should exist.  Since paragraphs and normal fields behave differently with CKeditor, there's no one-size-fits-all approach that I can find for making Cypress wait for the CKEditor field to appear and be editable.

VACMS-0000: Behavioral test waits for five seconds prior to trying to acquire the CKeditor text field.

---

docroot/themes/custom/vagovadmin/assets/scss/styles.scss

Fixes accessibility error caused by blue link appearing on blue background.
Visual

VACMS-000: Change alert link color to black.

---

config/sync/node.type.media_list_videos.yml

- Disabled the "media_list_videos" content type menu option.
closes #5119 
1. Go to `/node/add/media_list_videos` and

VACMS-5119: Disable the menu option of the "media_list_videos" content type

---

config/sync/user.role.content_admin.yml
tests/phpunit/Security/RolesPermissionsTest.php

- Disabled the "Administer media" and "Administer cms custom menu access" permissions for the "Content Admin" role.
closes #4787 
**Content Admin user without the configuration menu:**
**Media:** 
**VA.gov Menu Access:**
1. Go to `/admin/people/permissions` to verify and confirm that the "Content Admin" role
2. Then login as `suzanne.middaugh@va.gov` (Content Admin role) to verify and confirm the "Configuration" menu isn't available for this role
- See screen shots for reference.

VACMS-4787: Disable "Administer media" permission for "Content Admin" role

---

docroot/modules/custom/va_gov_vamc/src/Controller/EntityAutocompleteController.php
docroot/modules/custom/va_gov_vamc/src/EntityAutocompleteMatcher.php
docroot/modules/custom/va_gov_vamc/src/Routing/AutocompleteRouteSubscriber.php
docroot/modules/custom/va_gov_vamc/va_gov_vamc.services.yml

VACMS-7888: Append system name to facility in autocomplete.

---

composer.lock

This is causing PHPStan failures and Tugboat deployment failures when packages require PHP 7.4.

Removes platform-overrides section from composer.lock

---

docroot/themes/custom/vagovclaro/assets/scss/components/_elements.scss
tests/behat/features/content_editing.feature

Relates to #8016. fixes the button behavior inside the modal when editing a recurring event series.
PR is targeting the `integration-recurring-events` branch.
- log in as admin
- create an event node with a recurring event. save the node.
- edit the saved node, edit the event series
- cancel any event
- hover over the buttons and see that the behavior is fixed
- log in as admin
- create an event node with a recurring event. save the node.
- edit the saved node, edit the event series
- cancel any event
- hover over the buttons and see that the behavior is fixed

VACMS-8016 recurring events claro

---

config/sync/core.entity_form_display.node.office.default.yml
config/sync/core.entity_view_display.node.office.default.yml
config/sync/core.entity_view_display.node.office.teaser.yml
config/sync/field.field.node.office.field_office_id.yml
config/sync/field.field.node.office.field_parent_office.yml
config/sync/field.storage.node.field_office_id.yml
config/sync/field.storage.node.field_parent_office.yml
tests/behat/drupal-spec-tool/content_model_outreach_hub_content_type_fields.feature

Adds two fields to existing content type Office.
Relates to #7772.
As a CMS admin:
1. Visit `admin/structure/types/manage/office/fields`
2. Confirm existence of two new fields
- [] `Sitewide CMS Team`

Adds field_office_id and field_parent_office to Office content type

---

package-lock.json
package.json

Likely fix for stalling issues.
See:
- https://dsva.slack.com/archives/CT4GZBM8F/p1645704377446089
- https://dsva.slack.com/archives/CT4GZBM8F/p1645710803574719?thread_ts=1645704377.446089&cid=CT4GZBM8F

VACMS-0000: Downgrades Cypress to ~8.3.0.

---

docroot/themes/custom/vagovclaro/assets/scss/components/_alerts.scss
docroot/themes/custom/vagovclaro/assets/scss/components/_centralized_content.scss

Closes #8142. Wraps extra long links in the node link report, so the layout is not broken.
Also fixes this regression with centralized content that was reported by @kevwalsh here: https://dsva.slack.com/archives/CDKB88PS8/p1645707959170909
admin looking at:
`/nebraska-western-iowa-health-care/work-with-us/jobs-and-careers/nursing-careers/nursing-careers`
- verified broken links dont break the node link wrapper layout
as witt.cook@va.gov
`node/3877/edit?destination=/section/vha/vet-centers/nashville-vet-center#edit-field-health-services`
- scroll down and see that there's no weird border displayed inside of centralized content anymore
long broken links layout fixed:
before:
after:
admin looking at:
`/nebraska-western-iowa-health-care/work-with-us/jobs-and-careers/nursing-careers/nursing-car …

VACMS-8142 fix node link report layout for long links

---

config/sync/views.view.media.yml
config/sync/views.view.media_images.yml
tests/behat/drupal-spec-tool/views.feature

Closes #8103
Closes #6860 .  Kev and I refined this in a slightly different way the the original ticket's ACs. I created a copy of the media view, filtered it by images and added the alt text field, filter and export. We may add additional functionality to this audit at a later date. 
Views the media page and saw the alt text appearing.
As a cms editor, I can
1. view the new media images page (`admin/content/media/images`) 

VACMS-6860: Update media view to include alt text.

---

docroot/themes/custom/vagovclaro/assets/scss/components/_fields.scss

VACMS-8139: hide operations field for all office hours widgets

---

config/sync/core.entity_form_display.node.health_care_region_page.default.yml
config/sync/core.entity_view_display.node.health_care_region_page.default.yml
config/sync/core.entity_view_display.node.health_care_region_page.external_content.yml
config/sync/field.field.node.health_care_region_page.field_va_health_connect_phone.yml
config/sync/field.field.node.health_care_region_page.field_vamc_ehr_system.yml
config/sync/field.storage.node.field_vamc_ehr_system.yml
docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
docroot/themes/custom/vagovclaro/assets/scss/components/_external_content.scss
tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature

closes #7660
Visual / behat
Editor:
Admin:

VACMS-7660: Unhide EHR and VA Health Connect fields.

---

composer.json
composer.lock

- Removed the "Entity Embed" module from code base.
closes #7995 
1. Go to `/admin/modules` and:

VACMS-7995: Remove "Entity Embed" module from code base

---

tests/accessibility/cypress/integration/nodeCreationAccessibility.spec.js

Relates to #8168.  This is not a fix for the underlying issue; I'll need to look deeper into that.
This PR adds a task to log that the accessibility test completed successfully.  This adds a small amount of log spam to each of the accessibility tests.  However, and more importantly, it also appears to short-circuit accessibility tests that get stuck.
I _think_ it works like the following:
1. The accessibility test for a problematic page (say, `/node/add/health_care_local_facility`) completes normally.
2. For whatever reason, Cypress-Axe does not process the end of the test successfully, but it does invoke the following `cy.task()` expression.
3. The `cy.task()` expression is invoked, and its timeout (`taskTimeout`) is set up.  But the expression cannot complete, and consequently the test …

VACMS-8168: Uses a Cypress logging statement to force timeouts in too-long-running tests.

---

config/sync/views.view.flagged_content.yml

Closes #8295 .
navigated to flagged content view and verified newest results appeared first in the list.
As a cms admin i can
1. navigated to the flagged content view (`/admin/content/flagged`)

VACMS-8295: Update default sort for flagged view.

---

docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityService.php
docroot/modules/custom/va_gov_post_api/va_gov_post_api.module

Closes #8092 
Manual / visual testing
**Updating at the Term level**
**Updating at the System Health Service level**
**Check single facility save**
**Check system service save**
**Check Service term save**

VACMS-8092: push children of service terms and system services on change

---

.github/dependabot.yml

We get a large amount of PRs relating to the AWS PHP SDK.  
It's a good idea to stay updated, of course, but it's definitely not worth the amount of churn to update on every patch update, especially considering that the PHP SDK covers every AWS service and we only use a couple of them.
This PR instructs Dependabot to only open PRs for minor version updates, not patch updates, which should cut the noise down substantially.

VACMS-0000: Ignores AWS PHP SDK patch updates.

---

docroot/themes/custom/vagovclaro/assets/scss/components/_flags.scss
docroot/themes/custom/vagovclaro/assets/scss/components/_views.scss

- Updated _views.scss and added CSS specificity to override default "flag" CSS in Views.
closes #8135 
1. Go to `/admin/structure/views/view/content` (or any node related view):
2. Go to `/admin/content/flagged` (or in `/admin/content` click on the "Flagged" tab):

VACMS-8135: Flag theming breaks some views config

---

.tugboat/config.yml

Tugboat base preview `init` steps were modified to install Datadog's agent. Agent configuration files are also installed and populated dynamically with the Jinja2 templating system.  Move agent config tasks to _after_ the install of Jinja2.
Relates to #8077 
1. Do this
2. Then 

VACMS-0000: Fix Tugboat Init Config Command Ordering

---

composer.lock

VACMS-8410: update drupal core and friends to 9.3.9.

---

READMES/testing.md
tests.yml
tests/behat/features/decoupled.feature

Closes #8424
This PR does the following
- Removes the redundant content build
- Moves the behat decoupled tests that relied on the previously existing content built to AFTER the content build is called by the behat test.  
- Removes some related documentation and some documentation of a [PR that never landed](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/547). 
The only decouple test that was removed was connected to the existing state of content before a save.  It did not test anything explicitly and offered no additional test coverage.  It is fully covered by the remaining tests.
What variations of circumstances (users, actions, values) need to be …

VACMS-8424 reduce content builds in tests

---

docroot/themes/custom/vagovclaro/assets/scss/components/_views.scss
docroot/themes/custom/vagovclaro/templates/views/views-view.html.twig

Closes #8405 
Navigated to a view with an export (`admin/content/media/pdfs`) and confirmed the default 'attachment' badge was now styled like a button and appeared at the top and bottom of the view.
As cms editor, 
1. I can navigate to a view with an export (`admin/content/media/pdfs`)

VACMS-8405: Style views export button.

---

config/sync/node_link_report.settings.yml

Closes #8446
1. Do this
2. Then 

VACMS-8446 Prevent node_link_report from scanning links to /static/.

---

config/sync/core.entity_form_display.paragraph.service_location.default.yml
config/sync/core.entity_view_display.paragraph.service_location.default.yml
config/sync/field.field.paragraph.service_location.field_office_hours.yml
config/sync/field.storage.node.field_hours_for_copay_inquiries_.yml
config/sync/field.storage.node.field_office_hours.yml
config/sync/field.storage.paragraph.field_office_hours.yml
docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
docroot/themes/custom/vagovclaro/assets/scss/components/_fields.scss
docroot/themes/custom/vagovclaro/assets/scss/components/_services.scss
tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature

closes #8400
Visual / Behat
As an editor / content admin not on a `VAMC Facility Non-clinical Service` page
As an admin not on a `VAMC Facility Non-clinical Service` page
As an editor / content admin on a `VAMC Facility Non-clinical Service` page
Node view
**Admin test**
**Content Admin / Editor tests**
~- [ ] As Ryan.stubblebine@va.gov, go to `node/1017/edit` and visually verify the `Use the facility hours` field does not show hours table when option is set to `Provide specific hours for this service`~ This is a `VAMC Facility Health Service` and is covered by `VAMC Facility Health Service` bundle test in next step
**QA Copied from closed pr https://github.com/department-of-veterans-affairs/va.gov-cms/pull/8430**
1. VAMC Facility
2. VAMC System Billing and Insurance
3. Vet Center
4. Vet …

VACMS-8400: Add office hours widget to service location paragraph.

---

docroot/themes/custom/vagovclaro/assets/scss/components/_centralized_content.scss

Closes #8455. Adds spacing to centralized content fieldgroups.
went to https://va-gov-cms.ddev.site/node/add/vamc_system_medical_records_offi and saw there was no spacing, added margin bottom to class and saw that there was spacing.
visit `/node/add/vamc_system_medical_records_offi` and see that the spacing between fieldgroups with borders (centralized content) is present again.

VACMS-8455 add margin to centralized fieldgroups

---

config/sync/core.entity_form_display.taxonomy_term.health_care_service_taxonomy.default.yml
config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml
config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_enforce_unique_combo_servi.yml
config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_health_service_api_id.yml
config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_owner.yml
config/sync/field.storage.taxonomy_term.field_enforce_unique_combo_servi.yml
docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
tests/behat/features/content_editing.feature

VACMS-7557: Enable allow only one on health services.

---

docroot/themes/custom/vagovclaro/assets/scss/components/_fields.scss

VACMS-8475: Broaden styles to target all field_office hours widgets.

---

.ddev/docker-compose.storybook.yaml

https://dsva.slack.com/archives/CT4GZBM8F/p1648478608924889?thread_ts=1648241355.099019&cid=CT4GZBM8F reports from @JayDarnell and @ndouglas that local dev was broken due to the container not installing dependencies. this ensures deps get installed before storybook tries to run locally in a docker container.
- deleted `docroot/design-system/node_modules` and `docroot/design-system/storybook-static` folders to simulate no dependencies installed, nothing generated by default.
- ran `ddev restart`
Jay's report:
```
ddev start
Starting va-gov-cms...
Using custom PHP configuration: [/Users/jaydarnell/workspace/civicactions/va/va.gov-cms/.ddev/php/zzz-va-overrides.ini]
Custom configuration takes effect when container is created,
usually on start, use 'ddev restart' if you're not seeing it take …
```

VACMS-0000 make sure storybook deps are installed for ddev container

---

composer.json
composer.lock

closes #8485 
**This patch:**
1. rerolls original accessibility fix in https://www.drupal.org/project/office_hours/issues/3227169
2. addresses https://www.drupal.org/project/office_hours/issues/3227169#comment-14214820 
3. fixes an additional issue with office hours discovered during testing: leaving start / end times blank when validation is on, but start and end time requirements are not throws notices
Visual, composer install, behat

VACMS-8485 office hours upgrade et

---

composer.json
patches/3174484-add-media-window-and-select-button-text-should-respect-field-cardinality-4.patch

- Added logic that check if the file upload is limited to only one file to fix the reported issue where text was displayed in plural when it should have been displayed in singular.
- Created patch that include these fixes: the select button text and the add media window text.
closes #8504 
Visual, behat and PHPUnit.
**Add single file:**
**Add multiple files:**
1. Go to `/node/add/event` and

VACMS-8504: Adjust Dropzone "Select files" button and "Add file" window text

---

composer.json

Follow up of https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6912
Fixes this message from showing on local DEV. 
```shell
.git/hooks/post-merge: line 3: @cms-devops-engineers: command not found
.git/hooks/post-merge: line 3: #cms-team: command not found
******************************ATTN*******************************
* IMPORTANT: The default master branch will be renamed to main! *
* This will happen 11/4/2021                                    *
* You will have to update your local env                        *
* instructions will be provided by       *                             
* in  Slack                                         *
******************************ATTN*******************************
```
Tested locally with a composer install, message is gone and local …

Fix "The default master branch will be renamed to main" message on local (Remove post-merge hook from .git folder)

---

config/sync/views.view.vha_health_service_taxonomy.yml

Closes #8563 
manual
As a cms user
1. Go to the VHA taxonomy view (`/admin/structure/views/view/vha_health_service_taxonomy`)

VACMS-8563: Remove sortable edit header and update link to button.

---

tests/phpunit/Content/CreateMediaTest.php
tests/phpunit/Performance/CreateNodeTest.php
tests/phpunit/Performance/CreateTaxonomyTermTest.php
tests/phpunit/Performance/EditNodeTest.php
tests/phpunit/Performance/LoginTest.php
tests/phpunit/Performance/PreviewTest.php

Closes #8085.  Just removes some messages that break the output and don't provide much (if any) useful information.
Only affects tests.
1. Do this
2. Then

VACMS-8085: Removes logspam from performance tests.

---

docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRDGHA.php
docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Lando.php

Dispatching a GHA content build in the BRD dev or staging environments shouldn't happen right now. The content release workflow currently only supports production. Let's disable it until it's safe to actually perform that action.
Dispatching a content build in a local ddev environment doesn't work either (the advanced queue stuff needs some work + maybe some path fiddling somewhere). Devs can still run it manually -- just not through the UI.
1. Do this
2. Then
Is an announcement needed to let editors know of this …

Disable content build dispatch in local, dev, and staging because they do not currently work

---

docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php
docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentInterface.php
docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRDGHA.php
docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Lando.php
docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Tugboat.php
docroot/modules/custom/va_gov_build_trigger/src/Service/BuildFrontend.php
tests/phpunit/FrontendBuild/BuildFrontendTest.php

I've tripped over this method name more times than I care to admit. Let's name the method what it actually does.
1. Do this
2. Then

Rename shouldTriggerFrontendBuild to contentEditsShouldTriggerFrontentBuild

---

docroot/modules/custom/va_gov_build_trigger/src/Commands/WebBuildCommands.php
docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentDiscovery.php
docroot/modules/custom/va_gov_build_trigger/src/Environment/EnvironmentInterface.php
docroot/modules/custom/va_gov_build_trigger/src/Form/TugboatBuildTriggerForm.php
docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRDGHA.php
docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Lando.php
docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/Tugboat.php
docroot/modules/custom/va_gov_build_trigger/src/Service/BuildFrontend.php
docroot/modules/custom/va_gov_build_trigger/src/Service/BuildFrontendInterface.php
docroot/modules/custom/va_gov_build_trigger/src/Service/JenkinsClient.php
docroot/modules/custom/va_gov_build_trigger/src/Service/JenkinsClientInterface.php
tests/phpunit/FrontendBuild/BuildFrontendTest.php

The `$full_rebuild` param is present in many of the methods in va_gov_build_trigger, but despite being passed through several layers of abstraction in some places, it's not actually used for anything. It appears to have been added in c6511ac431b39f7b63e15715617aa16a23a4c362 when there was a distinction between a full rebuild and a partial rebuild, but that distinction no longer exists.
1. Do this
2. Then

Remove the full rebuild param. It is not actually used for anything.

---

.github/ISSUE_TEMPLATE/cms-bug-report.md
.github/ISSUE_TEMPLATE/cms-devops.md
.github/ISSUE_TEMPLATE/cms-enhancement.md
.github/ISSUE_TEMPLATE/cms-epic.md
.github/ISSUE_TEMPLATE/cms-section-request.md
.github/ISSUE_TEMPLATE/cms-task.md
.github/ISSUE_TEMPLATE/cms-ux-writing.md
.github/ISSUE_TEMPLATE/runbook-facility-closed.md
.github/ISSUE_TEMPLATE/runbook-facility-name-change.md
.github/ISSUE_TEMPLATE/runbook-facility-new.md
.github/ISSUE_TEMPLATE/runbook-vamc-system-name-change.md
.github/ISSUE_TEMPLATE/tier-1-or-2-ongoing-work.md
.github/pull_request_template.md

Relates to #8585
None, this is just markdown for github templates.
1. Do this
2. Then

[docs] VACMS-8585: Conslidate Content Ops and CMS experience into one label to reflect singular scrum team.

---

.tugboat/config.yml
tests.yml

Relates to #4963.
Setting tasks as _dependencies_ rather than sub commands will run them in parallel. By default, the output will be interleaved which is a PITA. The `group` setting forces all of the output to be grouped for easy reading.
The downside here is that you won't get output for any individual task until the entire task is complete (so you wouldn't be able to e.g. watch the output to see how far along it is).
1. Do this
2. Then

Run test tasks in parallel

---

config/sync/core.entity_form_display.paragraph.service_location.default.yml
config/sync/core.entity_view_display.paragraph.service_location.default.yml
config/sync/views.view.non_clinical_services.yml
docroot/modules/custom/va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php
docroot/modules/custom/va_gov_backend/va_gov_backend.module
tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature

VACMS-8550: hide old service location field_facility_service_hours
