tests/cypress/integration/behavioral/content_release.feature
It didn't occur to me, but these tests are for lower environments only and won't pass on BRD because of the different content-release page.
1. Do this
2. Then
=> VACMS-0000: Skip certain tests on BRD.

tasks-periodic.yml
Relates to #8108
Adds an every minute task (which will be called by https://github.com/department-of-veterans-affairs/devops/pull/10878). We need this so that we can run the content release queues. Ideally, we can remove this in the future in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8849 .
1. Do this
2. Then
=> Add every minute task

tests/cypress/integration/accessibility/nodeCreationAccessibility.spec.js
Closes #8518.
Turns out that the accessibility tests choke on the 8700+-item menu parent select element.
This PR excludes this element from the accessibility tests.
=> VACMS-8518: Exclude parent item menu from accessibility tests.

docroot/modules/custom/va_gov_build_trigger/css/build_trigger_form.css
Closes #8942. Adds one line of css to the build_trigger module css to fix placement from inline after the checkbox field to underneath.
Verified that the form looked as expected locally and on prod (changed my local env type) with these updates. Slightly different forms get rendered per environment, the css functions the same for them all.
prod:
local:
Visit `/admin/content/deploy` and see that the form appears as expected. No functional changes to the form in this PR.
=> VACMS-8942 fix button placement for content deploy form

config/sync/core.entity_form_display.taxonomy_term.facility_supplemental_status.default.yml, config/sync/core.entity_view_display.node.landing_page.default.yml, config/sync/core.entity_view_display.taxonomy_term.facility_supplemental_status.default.yml, config/sync/field.field.taxonomy_term.facility_supplemental_status.field_administration.yml, config/sync/field.field.taxonomy_term.facility_supplemental_status.field_enforce_unique_id.yml, config/sync/field.field.taxonomy_term.facility_supplemental_status.field_guidance.yml, config/sync/field.field.taxonomy_term.facility_supplemental_status.field_status_id.yml, config/sync/field.storage.taxonomy_term.field_administration.yml, config/sync/field.storage.taxonomy_term.field_enforce_unique_id.yml, config/sync/field.storage.taxonomy_term.field_guidance.yml, config/sync/field.storage.taxonomy_term.field_status_id.yml, config/sync/node_link_report.settings.yml, config/sync/taxonomy.vocabulary.facility_supplemental_status.yml, tests/behat/drupal-spec-tool/content_model_bundles.feature, tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
closes #8956
Visual / behat
Vocabulary listing view
Form view
Node view
-  Go to https://pr8963-5dpcxs15ghurgq2tqdxjf19lclvte3h7.ci.cms.va.gov/admin/structure/taxonomy/manage/facility_supplemental_status/add
and add a new term but use the same status ID you used in the first term.
=> VACMS-8956: Add new covid status taxonomy.

config/sync/core.entity_form_display.node.health_care_local_facility.default.yml, config/sync/core.entity_form_display.node.health_care_local_facility.inline_entity_form.yml, config/sync/core.entity_view_display.node.health_care_local_facility.default.yml, config/sync/core.entity_view_display.node.health_care_local_facility.external_content.yml, config/sync/core.entity_view_display.node.health_care_local_facility.ief_table.yml, config/sync/core.entity_view_display.node.health_care_local_facility.teaser.yml, config/sync/field.field.node.health_care_local_facility.field_operating_status_facility.yml, config/sync/field.field.node.health_care_local_facility.field_operating_status_more_info.yml, config/sync/field.field.node.health_care_local_facility.field_supplemental_status.yml, config/sync/field.storage.node.field_supplemental_status.yml, config/sync/views.view.health_care_service_names_and_descriptions.yml, tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature, tests/behat/drupal-spec-tool/views.feature
closes #8949
@swirtSJW @rachel-kauff @JayDarnell
Need link destination for `Learn more about COVID statuses.` - currently paths to `/`
Visual / behat
=> VACMS-8949: Add covid status er select field.

config/sync/core.entity_form_display.node.health_care_local_facility.default.yml, config/sync/field.field.node.health_care_local_facility.field_supplemental_status.yml, tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
closes #9022
As Ryan.Stubblebine@va.  gov
1. Do this
-  Edit a the facility in your system https://va-gov-cms.ddev.site/node/89/edit
=> VACMS-9022 Convert VAMC facilty statuses to radio buttons.

config/sync/feature_toggle.features.yml
=> VACMS-9039: remove care we provide feature flag

docroot/modules/custom/va_gov_build_trigger/src/Controller/PlaceholderController.php, docroot/modules/custom/va_gov_build_trigger/va_gov_build_trigger.routing.yml
Relates to #9008 
Adds no-op routes for content release notifications. This is needed so that we can add the HTTP requests to content release and have them not fail. This code will be replaced in the near future.
1. Do this
2. Then
=> add no-op placeholder routes for content release notifications

config/sync/core.entity_form_display.taxonomy_term.facility_supplemental_status.default.yml, config/sync/core.entity_view_display.taxonomy_term.facility_supplemental_status.default.yml, config/sync/field.field.taxonomy_term.facility_supplemental_status.field_cms_option_label.yml, config/sync/field.field.taxonomy_term.facility_supplemental_status.field_guidance.yml, config/sync/field.storage.taxonomy_term.field_cms_option_label.yml, tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
Relates to #9043 but does not close.
As an admin
1. Go to https://pr9046-ekkjt7zsdqxtharhdv6t0mflm8stb1jh.ci.cms.va.gov/taxonomy/term/1035/edit
2. Visit https://pr9046-ekkjt7zsdqxtharhdv6t0mflm8stb1jh.ci.cms.va.gov//taxonomy/term/1035/
=> VACMS-9043 Add option label to facility supplemental status vocab.

config/sync/views.view.facility_services.yml
Closes #9047
manual
As a cms user, 
1. Go to the facility status view and search for pittsburgh (`/admin/content/facilities/facility-status?Title=pittsburgh`)
=> VACMS-9047 facility status dupes

config/sync/views.view.health_care_service_names_and_descriptions.yml
Closes #9054
As User admin
1. Go edit a VAMC facility /node/37668/edit
=> VACMS-9054 Make covid status sort by term weight.

config/sync/views.view.facility_services.yml
=> VACMS-9117: Update sup status filters.

config/sync/views.view.facility_services.yml
closes #9173
Visual / download csv
=> VACMS-9173: Update csv to account for sup status work.

config/sync/core.entity_form_display.message.va_form_new_form.default.yml
Relates to #8721
This adds in a message template that was having an odd dependency timing problem with config import in the messages stack.   It can be merged after the messages stack makes it to prod. 
was  already tested aas part of 8721 and was only separated out do to a config import timing issue.
=> VACMS-8721 add new form message

docroot/modules/custom/va_gov_db/va_gov_db.install
closes #9249
Visual / drush updb
```
/**
* Publish KB events article.
*/
function va_gov_db_update_9006(&$sandbox) {
$nids = [6483];
return _va_gov_db_publish_nodes($nids);
}
```
=> VACMS-9249: Add publish function for update hooks.

docroot/modules/custom/va_gov_backend/va_gov_backend.module
Closes #4101, realistically.  See [this thread](https://dsva.slack.com/archives/CT4GZBM8F/p1653521229339479).
1. Go to https://cms-xgwacix07qvn8uojceu8i6bhn5q80lql.ci.cms.va.gov/washington-dc-health-care/stories/fast-response-is-key-to-preventing-permanent-disability-after-stroke
2. Open developer console and type `drupalSettings.node`.
3. Observe that there is now useful debugging information, including the node UUID and JSON:API path.
=> VACMS-4101: Add some debugging information to drupalSettings for nodes to make JSON:API development easier.

scripts/content/VACMS-8935-scrub-tz-in-hours-field-comment.php
closes #8935
`ddev drush scr scripts/content/VACMS-8935-scrub-tz-in-hours-field-comment.php`
=> VACMS-8935: Add script to remove tz in hours comments.

docroot/design-system/components/alert/alert.scss
relates to: https://dsva.slack.com/archives/CDKB88PS8/p1654299207997069 https://dsva.slack.com/archives/CT4GZBM8F/p1654220404446529
minor defect from #9171 that i missed 🤦
- went to a node that generated broken links and saw that links were highlighting correctly now
link hover:
=> VACMS-0000 fix alert link colors

config/sync/core.entity_form_display.node.vamc_system_billing_insurance.default.yml, config/sync/core.entity_view_display.node.vamc_system_billing_insurance.default.yml, config/sync/core.entity_view_display.node.vamc_system_billing_insurance.teaser.yml, config/sync/field.field.node.vamc_system_billing_insurance.field_office_hours.yml, tests/behat/drupal-spec-tool/content_model_vamc_content_type_fields.feature
=> VACMS-9360: Add hidden office hours field to billing.

config/sync/block.block.recurringeventsannouncement.yml
Closes #9309. Updates config for the recurring events block so that it is aligned with content.
- Removed outdated events block that was placing the "This block is broken or missing" message on the screen.
- Replaced updated CMS Announcement block for recurring events in the same place.
- Exported config
As a user, create a new event node or edit an existing one. The block should appear at the top of the page below the breadcrumbs.
There should be no message about a block with missing or broken content.
=> VACMS-9309 update block placement config for recurring events block

scripts/content/VACMS-9361-sync-hours-fields.php
closes #9361
**will require CMS platform team to run on prod prior to displaying field_office_hours (attn: @ndouglas)**
`ddev drush scr ./scripts/content/VACMS-9361-sync-hours-fields.php`
=> VACMS-9361: Add field script.

Jenkinsfile.cd
See #9295. This depends on a devops PR here https://github.com/department-of-veterans-affairs/devops/pull/11382. 
1. Do this
2. Then
=> VAGOV-9295: [devops] Add slack_channel for CMS build job to notify of failures

docroot/modules/custom/va_gov_events/js/eventFormHelpers.es6.js, docroot/modules/custom/va_gov_events/js/eventFormHelpers.js
Relates to #9410
1) Go to https://pr9593-z2tm41jng73mcitwl40kpzruinndwc2h.ci.cms.va.gov/node/add/event
2) Fill out all required fields
3) Click the box for "Include registration information"
4) Select an option other than "none" for Call to action.
5) Put in a URL
6) Change the Call to Action select to "- None -"
7. +Save the node.
8. +Edit the node. and change the CTA to an option other than -none-.
8) Select an option other than "none" for Call to action.
9) Put in a URL
10) Uncheck the "Include registration information" checkbox
11) Check the "Include registration information" checkbox
13) +Edit the node.
14) +Set the call to action to "Apply".
15) +Enter a url.
16) +save the node
17) +Edit the node
18) +Uncheck the "Include registration information"
19) +save the node
=> VACMS-9410: Clear event registration info when toggling states.

composer.json, composer.lock, config/sync/core.entity_form_display.sitewide_alert.sitewide_alert.default.yml, config/sync/core.entity_view_display.sitewide_alert.sitewide_alert.default.yml, config/sync/core.extension.yml, config/sync/field.field.sitewide_alert.sitewide_alert.field_alert_title.yml, config/sync/field.storage.sitewide_alert.field_alert_title.yml, config/sync/sitewide_alert.settings.yml
Closes #9510. Adds drush commands for ability to create / enable / disable / delete sitewide alerts. 
TODO: clean up menu placement for sitewide alert... right now it places itself in the tab list on `/admin/content` in the second spot and throws everything off. gross.
Same syntax as site alert drush commands: `"label"`, `"message"`, `--option` flags. Adjust quotes as needed for passing into ddev properly, see below:
**create alert:**
`ddev drush sitewide-alert:create "'test-alert 7' 'testing my new alert' --style=warning --dismissible"`
`ddev drush sitewide-alert:create "'schedule-end' 'a brand new world' --style=shield --end='20 minutes'"`
`ddev drush sitewide-alert:create "'test-alert 4' 'testing my new alert' --style=warning --status=0 --dismissible=0"`
**enable alert:**
`ddev drush …
=> VACMS-9510 add drush command patch, export config for sitewide alerts

.github/ISSUE_TEMPLATE/runbook-facility-closed.md, docroot/modules/custom/va_gov_facilities/src/EventSubscriber/FacilitiesSubscriber.php, docroot/modules/custom/va_gov_facilities/va_gov_facilities.services.yml
Closes #6528
Manual / visual testing
1. Load the Events view /admin/content/events and filter by: Facility title contains = **Rocky Mountain** (note the total number of items)
2. Load the Bulk edit view /admin/content/bulk and filter by: Title = **Rocky Mountain** and Content type = **VAMC Facility Health Service** (note the total number of items)
3. Load the Bulk edit view /admin/content/bulk and filter by: Title = **Rocky Mountain** and Content type = **VAMC Facility Non-clinical Service** (note the total number of items)
4. Load the following VAMC Facility Node page: /eastern-colorado-health-care/locations/rocky-mountain-regional-va-medical-center
5. Edit the Facility node, change the moderation state to Archived
Is an announcement needed to let editors know of this …
=> VACMS-6528: archive related services/events when a facility is archived

composer.json
closes #9591
Visual / filtering
=> VACMS-9591: Augment html_tag_usage filtering

tests/phpunit/Content/BulletinQueueTest.php
Relates to #9839.
This test is idiopathically failing.  I'm disabling it temporarily to unblock PRs while I try to diagnose the root cause.
=> VACMS-9839: Temporarily disable PHPUnit test.

composer.json, composer.lock
Relates to #9829 
workbench_access and menu reference fields interact in unexpected ways when queried via JSON:API. More full explanation here, where I also attached the patch: https://www.drupal.org/project/workbench_access/issues/3298498#comment-14616033
=> VACMS-9829: add patch to handle edge cases where menu references trigger early rendering.

docroot/sites/default/maintenance.html, docroot/themes/custom/vagovclaro/templates/misc/sitewide-alert.html.twig
This slack thread: https://dsva.slack.com/archives/C03LFSPGV16/p1658864433963339 raised some issues with sitewide alert appearances. This PR contains 2 of the 3 fixes:
- empty `<h2>` tag does not print if title field is empty
- maintenance page site shield has added transparency
I attempted to use the `|raw` filter to escape the message content to actually render the html entities... but it appears the escaping is done before the twig render happens in the module somewhere, as I'm still getting html entities in plaintext. 
I don't have the bandwidth today to dig on this further unfortunately
- created a new site alert with `ddev drush sitewide-alert:create "'test-alert 9' 'testing my new alert' --style='warning' --dismissible"` and saw that the empty title tag no longer printed.
- edited …
=> VACMS-0000 update site alert to not print empty h2, fix static shield transparency

config/sync/menu_breadcrumb.settings.yml, config/sync/system.menu.lovell-tricare-health-care.yml, tests/behat/drupal-spec-tool/menus.feature
Closes #9948 
Manually
As an admin 
1. Go to admin/structure/menu
2. Then click "Edit menu"
3. Edit a facility and in field administration, 
4. Then go to /admin/config/user-interface/menu-breadcrumb
- [ x ] `⭐️ Facilities`
=> VACMS-9948 Lovell Tricare menu

tests/cypress/integration/behavioral/navigation.feature
Closes #10049.  Triggered by a brittle test.  
Followup in #10051 to improve the resilience of the test in question.
If tests pass, this is okay to approve and merge.
=> VACMS 10049: Updates text in Cypress test.

config/sync/field.field.node.vet_center_cap.field_geolocation.yml
Closes #9544 
Manually
After changing the endpoint to a "bad" one to make the geocoding fail, I changed the address on a Vet Center CAP:
Because of the failed look-up, the lat and long are now blank.
1. Change the Geocoding Mode on "/admin/config/system/geocoder/geocoder-provider/manage/mapbox" to "BREAKME"
2. Visit a Vet Center CAP, e.g. "node/47735/edit"
=> Changes config to erase geocoding on failed look-up

docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityBase.php, docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityService.php, docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php, tests/phpunit/Content/FacilityStatusQueueTest.php
Closes #9943 
Manual testing
As a user with the admin role:
=> VACMS-9943: block lighthouse updates for Lovell Tricare section

config/sync/core.entity_form_display.node.health_care_local_health_service.default.yml
Closes #10093 
Manually
As user with content edit permissions
1. Go to a add a VAMC Facility Health Service (/node/add/health_care_local_health_service)
2. Click on "Health service and facility basic info" to expand the field group
=> VACMS-10093 Updates instruction from 'Owner' to 'Section'

scripts/content/VACMS-9714-paragraphs-crisis-to-988.php, scripts/content/VACMS-9714-vamc-detail-page-crisis-to-988.php, scripts/content/VACMS-9714-vamc-system-operating-status-crisis-to-988.php, scripts/content/script-library.php, scripts/content/vacms-5744/library.php
Using the CMS Content Audits as a reference: https://airtable.com/shrngt7aaXoIwAenS/tblO7nwMBRn1jWpcJ/viwUPS9GYFKTkAK5j?blocks=hide
This PR provides scripts to update the crisis hotline to 988 for the following airtable (above) sections:
- VAMC Facility
- VAMC System Operating Status
- VAMC Detail Page
Post release note: once these scripts have been run the remaining items not explicitly skipped in the issue description need to be manually checked/fixed. Some of these may have already been fixed.
- Alerts
- Resources and Support
- VAMC System Banner
- Benefits Detail Page
Closes #9714 
Manual testing. 
With terminal access, run the following commands:
=> VACMS-9714: add scripts to update crisis number to 988

config/sync/core.entity_form_display.menu_link_content.lovell-federal-health-care.default.yml, config/sync/core.entity_view_display.menu_link_content.lovell-federal-health-care.default.yml, config/sync/core.extension.yml, config/sync/field.field.menu_link_content.lovell-federal-health-care.field_menu_section.yml, config/sync/field.storage.menu_link_content.field_menu_section.yml, docroot/modules/custom/va_gov_lovell/src/EventSubscriber/LovellEventSubscriber.php, docroot/modules/custom/va_gov_lovell/va_gov_lovell.info.yml, docroot/modules/custom/va_gov_lovell/va_gov_lovell.services.yml
=> VACMS-9956: add new section field to lovell menu items

config/sync/core.entity_form_display.paragraph.q_a_group.default.yml, config/sync/core.entity_view_display.paragraph.q_a_group.default.yml, config/sync/core.entity_view_display.paragraph.q_a_group.user_guides.yml, config/sync/field.field.node.support_resources_detail_page.field_content_block.yml, config/sync/field.field.paragraph.q_a_group.field_rich_wysiwyg.yml, config/sync/node.type.support_resources_detail_page.yml, config/sync/views.view.content_entity_browsers.yml, tests/behat/drupal-spec-tool/content_model_bundles.feature, tests/behat/drupal-spec-tool/content_model_lc_content_type_fields.feature, tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature
Including added features.
* Added a limited rich text description field to Q&A Groups paragraph type
* Added Q&A Groups paragraph type to Resource and Support content type
* Edited Q&A Entity Browser view to include title/keyword filter,
remove archived Q&A from populating and show answer preview
closes #9737
Relates to #9579, #8630
Hand-tested backend content add form.
- Editor can add or edit Resources and Support content, add main content block and choose Q&A Group for a modal to pop up (see above screenshots). Please edit node 47411 so you can run the GraphQL query I provided in t[his comment](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9746#issuecomment-1196292977) below.
- go to …
=> VACMS-9737: Implements Q&A reusability for Resource & Support

composer.lock
https://www.drupal.org/project/drupal/releases/9.3.21
https://github.com/ckeditor/ckeditor5/security/advisories/GHSA-42wq-rch8-6f6j
https://github.com/advisories/GHSA-8274-h5jp-97vr
Closes #10290.
=> VACMS-10290: Upgrades Drupal to 9.3.21 [Security]

composer.json, composer.lock
Closes #9996.
Two packages have upstream upgrades that have fixed the Drupal 9 compatibility.  The remaining, `hms_field`, appears completely abandoned, so I think we'll need to maintain this in the `composer.json` file moving forward.  Opened #10269 to deal with `hms_field`.
- [health_check_url](https://www.drupal.org/project/health_check_url/releases) does not indicate any major changes.  
- The `/health` endpoint functions similarly to prod, without any apparent delays or other effects.
- [feature_toggle](https://www.drupal.org/project/feature_toggle/releases) does not indicate any major changes.
- The `/admin/config/system/feature_toggle` page functions similarly to prod.
- Feature toggles appear normal (`drupalSettings.feature_toggle.enabled`).
=> VACMS 9996:  Reëvaluate packages with composer repository overrides

config/sync/field.field.paragraph.q_a_group.field_rich_wysiwyg.yml, config/sync/field.field.paragraph.q_a_group.field_section_header.yml, config/sync/paragraphs.paragraphs_type.q_a_group.yml, config/sync/views.view.content_entity_reference_source.yml, tests/behat/drupal-spec-tool/content_model_bundles.feature, tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature
Closes #10147
- Local
- Draft PR for automated tests
Note: Introduction (formerly "description") field is disabled for now, you will have to check the code changes to see the help text change.
=> VACMS-10147: Help text for Q&A Group Reusability Components

config/sync/views.view.content_entity_reference_source.yml
Closes #10351 
Checked that the changes to the following file were reverted back to previous state:
config/sync/views.view.content_entity_reference_source.yml
=> VACMS-10351 Reverts changes VACMS-9483

config/sync/update.settings.yml
Closes #10366.
Logged into CMS and verified email address was no longer displayed.  
Also ran `drush cex` on CI instance and verified that config is clean.
As any user with admin privileges:
=> VACMS-10366: Removes no-reply@va.gov from Update Manager preferences.

composer.json, composer.lock
Relates to #10249.
`phpspec/prophecy` is being dropped as a dependency by `phpunit/phpunit` in 8.5.29.  This is causing PRs to fail.
See #10385.
If tests pass, this is good to merge.
=> VACMS-10249: Directly require phpspec/prophecy.

config/sync/views.view.table_audit.yml
Closes #10394
Manually
As an admin
1. Go to /admin/content/audit
2. Click on Table Audit
3. Confirm that the view loads 
=> VACMS-10394 Adds config for Table Audit to be in the menu

docroot/modules/custom/va_gov_build_trigger/src/Commands/ContentReleaseCommands.php
Relates to #7600. (or closes?)
1. Do this
2. Then
=> toggle command outputs the wrong status

docroot/modules/custom/va_gov_lovell/src/EventSubscriber/LovellEventSubscriber.php, docroot/modules/custom/va_gov_lovell/va_gov_lovell.services.yml
Closes #9950 
This PR should not be merged yet. This PR makes assumptions concerning what the URL prefixes for Lovell - VA and Lovell - Tricare should be. Once we have official approval that these assumptions are true we should update the existing node urls to match the new pattern and then merge this code.
Manual testing. 
- Choose Lovell Federal health care for the related office or health care system.
- Choose Lovell Federal health care for the Section
- Choose a parent link to place the item in the Lovell menu system
Added by swirt
=> VACMS-9950: Add alternate alias to nodes that are Lovell both

config/sync/core.entity_form_display.paragraph.q_a_group.default.yml, tests/behat/drupal-spec-tool/content_model_paragraph_fields.feature
Closes 10464
- As user [megan.zehnder@va.gov](https://cms-up9jcanzixoqdnqlxmfrk76ad33dponp.ci.cms.va.gov/user/4031) on https://cms-up9jcanzixoqdnqlxmfrk76ad33dponp.ci.cms.va.gov/ review instance, edit node [15062](https://cms-up9jcanzixoqdnqlxmfrk76ad33dponp.ci.cms.va.gov/node/15062/edit), add content block > Q&A Group > fill out header, introduction and select some Q&As, save as published, and trigger a content release.
Then go to https://web-up9jcanzixoqdnqlxmfrk76ad33dponp.ci.cms.va.gov/resources/life-insurance-dividend-payment-options/ and look at the changes made / added with the Q&A Group and make sure that they are reflected on the front end.
What variations of …
=> VACMS-10464 Make intro field for qa group visible

tests/phpunit/Content/CreateMediaTest.php
Relates to #9905.
The CreateMediaTest threshold was set when the tests ran serially.  It frequently fails now that tests are run concurrently.
I have an issue dedicated to remediating this in the longterm (see #9905), but in the short-term, these spurious test failures are really annoying and do not serve any purpose.
This PR increases the time limit from 2 (which is frequently exceeded, in my experience) to 4, which is very rarely exceeded and may indicate the existence of an actual problem.
If tests pass, this should be good to go.
=> VACMS-9905: Temporarily increase CreateMediaTest threshold.

composer.json
Closes #10570.
`content-build-gql` doesn't create a `.buildlock` file, so it's at risk of being trampled by concurrent content build processes for its environment.  This PR creates and removes the lock file.
I'll rebuild this a few times to ensure all the tests pass and this doesn't mess up any other processes or tests.
If all tests pass reliably, this should be safe to merge.
=> VACMS-10570: Protect `content-build-gql` against concurrent content builds

docroot/modules/custom/va_gov_events/js/eventFormHelpers.es6.js, docroot/modules/custom/va_gov_events/js/eventFormHelpers.js
Resolves https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9649
Go to /node/add/event
Set the location type to "At a VA facility"
Fill in the facility location
Fill in the building number
Without saving, switch the location type to "At a non-VA location"
Switch back to "At a VA facility" location type.
Switch the location type to "Online"
Fill in the URL
Switch back to the "At a non-VA location" location type
Switch back to the "At a VA facility" location type
Switch back to the "Online" location type
=> VACMS-9649: Reset location values on toggle of event location type.

tests/phpunit/Performance/CreateNodeTest.php, tests/phpunit/Performance/CreateTaxonomyTermTest.php, tests/phpunit/Performance/EditNodeTest.php, tests/phpunit/Performance/LoginTest.php, tests/phpunit/Performance/PreviewTest.php
See #9905 and #10522, a previous PR with similar intent.  This is a similar change to increase some other time limits, since I'm seeing some similar failures there too.
This should all ultimately be remedied soon in #9905.
Provided all tests pass, this should be safe to merge.
=> VACMS-9905: Increase time limits on other performance tests.

.github/workflows/check-revision-log-fields.yml, tests.yml
Closes #8084.
If all tests pass, this should be good to go.
This will not currently pass all checks because, well, one of them is removed in this PR.
=> VACMS-8084: Move `revision_log` field check into GitHub Actions.

READMES/drupal-memcache.md, composer.json, composer.lock
Closes #6984 .
This should affect nothing.  We already don't use `drupal-console` anywhere because it no longer works 😭
=> VACMS-6984: Removes Drupal Console.

config/sync/entityqueue.entity_queue.staged_content.yml
Closes  #10408
Validate the staged_content entityqueue only allows 'Benefits Detail Page', and 'Resources & Support Detail Page'
1. Login to https://cms-srjwv2ajtra1pntckggf0rv5xdwuavlq.ci.cms.va.gov/user/login as a content admin or administrator
2. Visit https://cms-srjwv2ajtra1pntckggf0rv5xdwuavlq.ci.cms.va.gov/admin/structure/entityqueue/staged_content/staged_content?destination=/admin/structure/entityqueue
3. Then
=> VACMS-10408: Update staged_content entityqueue allowed content types.

Jenkinsfile.cd
This change is meant to smooth out errors related to transient failures in build jobs. The retry blocks are set to 3 retries after which we probably know we have a real problem that requires intervention. Otherwise let Jenkins silently retry and the issue corrects itself through another attempt.
Relates to #10418. (or closes?)
Similar changes made to va.gov-cms-test repo and CMS-Test Jenkins Jobs.
1. Do this
2. Then
=> VACMS-10418: Wrap CMS build stage in a retry block 

READMES/workflow.md, docroot/modules/custom/va_gov_db/va_gov_db.install, phpstan-baseline.neon
=> VACMS-10657 deprecate uninstall process

config/sync/core.extension.yml, docroot/modules/custom/va_gov_lovell/src/Event/BreadcrumbPreprocessEvent.php, docroot/modules/custom/va_gov_lovell/src/EventSubscriber/LovellEventSubscriber.php, docroot/modules/custom/va_gov_lovell/src/Factory/BreadcrumbPreprocessEventFactory.php, docroot/modules/custom/va_gov_lovell/src/Variables/BreadcrumbEventVariables.php, docroot/modules/custom/va_gov_lovell/va_gov_lovell.info.yml, docroot/modules/custom/va_gov_lovell/va_gov_lovell.services.yml
Closes #10170 
Manual testing
In order to properly test this PR some manual setup is required. 
1. Edit the existing Lovell Federal health care (VAMC System) node: **/node/15007/edit**
(Note: this is to match the future pattern for Lovell page URLs that are NOT Tricare. This is important because the code in this PR looks for the future pattern.)
2. Evaluate breadcrumbs for a Lovell Tricare facility: 
3. Evaluate breadcrumbs for a Lovell VA facility:
=> VACMS-10170: override breadcrumbs for lovell tricare to use correct system

config/sync/core.extension.yml
Relates to #10170
This is simply to enable preprocess-event-dispatcher so that when we build integration that contains a reference to an abstract class, we don't have a chicken and egg problem like this
As admin
- This module serves no testable use at this time so no further testing is needed.
=> VACMS-10170 Enable preprocess_event_dispatcher

.github/workflows/config/config.yml
Closes #10542.
I included the AWS SDK and Datadog's `dd-trace`.
I considered some others, like `phpstan`, `php_codesniffer`, `composer/installers`, etc, but felt like these were getting into a gray area.  
What is safe to automerge?  As little as possible, but I feel like the case can be made for automerging updates from large commercial organizations with dedicated teams, etc. 
I think it's somewhat harder to make this case for community-maintained packages -- not so much because they're maintained by the community, but because there's a very thin line between "maintained by the community" and "maintained by one increasingly radicalized guy in `$state`."
This is more of a security/policy RfC than anything else.  Provided this passes tests, it's good to merge _in theory_, but I welcome …
=> VACMS-10542: Consider some additions to the Dependabot allowlist.

docroot/themes/custom/vagovclaro/assets/scss/components/_recurring_events.scss
~Closes va.gov-cms issue 10324.~  <- Has no magic
Closes #10324.   <-has magic properties
On existing event (https://va-gov-cms.ddev.site/node/48108/edit), using the Chrome browser inspect tool:
1. Extend the length of the "All Day" label to make it more visible and expose it.
2. See that the `.hidden` property being applied to `.allday-label` is overridden. 
3. Find the `display:block` override, deselected it to see if removing the override fixes the issue.
4. Test was successful
(See screenshots below.)
Notes: 
- This adds to work done in [PR #7981](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7981)
- div sandwich:
On https://cms-o4w3pg1yv2dgakucmkw9flhpss6wydd3.ci.cms.va.gov/node/48108/edit, in Chrome inspect or similar tool:
1. Extend the length of the "All Day" …
=> VACMS-10324: Hide all-day checkbox in recurring events

docroot/modules/custom/va_gov_media/va_gov_media.module
Closes #10652.
Tested locally on ddev.
Log in as any user who can create content. Add a Story. Click on Add media and add a new image. Drag any jpg into the drop are when the image details window opens you should see the new alt text guuidance. "Alternative text is important for accessibility. Tips for writing alternative text: include a short, specific description of the image. Avoid words such as “image,” "picture," “photo,” or “graphic”. Do not use the file name of the image." See screenshot.
=> VACMS-10652: Update inline alt text guidance string in CMS

docroot/modules/custom/va_gov_media/va_gov_media.module, docroot/modules/custom/va_gov_migrate/src/ParagraphMigrator.php, docroot/modules/custom/va_gov_user/src/Service/UserPermsService.php, phpstan-baseline.neon, phpstan.neon
Closes #10001.
I tweaked a couple of things in comments and one use of `list()`.  Which I might undo because I'm trying to avoid executed code changes.
I tweaked _a lot_ of things in `phpstan.neon`, which lowered our errors from 288 to 100.  That's a big 🎉 , not least of which because PHPStan throwing errors on these Drupalisms slows development.
=> VACMS-10001: PHPStan optimizations.

composer.json, composer.lock, docroot/themes/custom/vagovclaro/assets/scss/pages/_revisions.scss, docroot/themes/custom/vagovclaro/assets/scss/styles.scss
Closes #10116.
Closes #10161.
Closes #10160.
Tested locally on ddev.
Log in and go to any pice of content. Click on the revisions tab. It shoudl look like the screen shot above. 
=> VACMS-10116: Radio Button labels on CMS Revision page

READMES/local.md
Since our atlassian instance is no longer public this ddev documentation needs to be public so others can use and contribute to our project.
Moved the documentation from here https://vfs.atlassian.net/wiki/spaces/PCMS/pages/1956937732/local+development+with+ddev
=> [DOCS] Add ddev docs from atlassian.

docroot/themes/custom/vagovclaro/assets/js/inline_guidance.es6.js, docroot/themes/custom/vagovclaro/assets/js/inline_guidance.js, docroot/themes/custom/vagovclaro/templates/content-edit/file-managed-file.html.twig
Closes #11045.
Open an existing image to edit and verify that clicking Tips for Alternative Text does NOT reload the page.
=> VACMS-11045: fix for inline guidance bug with existing images

tests/phpunit/Performance/ScalabilityCreateNodeTest.php
This bit of spam can be misinterpreted as an error message and distract from actual error messages.
This should be safe to merge if tests pass.
=> VACMS-0000: Remove distracting test output.

config/sync/views.view.content.yml, config/sync/views.view.facility_services.yml, config/sync/views.view.flagged_content.yml, config/sync/views.view.media.yml, config/sync/views.view.rich_text_field_audit.yml, config/sync/views.view.table_audit.yml, config/sync/views.view.taxonomy_term.yml, config/sync/views.view.va_forms.yml
Closes #9821.
Tested locally. 
Gop to main content admin view, inspect Edit button for a piece of content, There should be only one link. Do the same for the main images admin view.
=> VACMS-9821: Remove hidden edit link in main content listing

docroot/modules/custom/va_gov_workflow_assignments/css/ewa_style.css
Closes #10866.
Tested locally
Find a Sitewide Alert  with a pending url and verify color is correct.
=> VACMS-10866: updated color for pending url

docroot/modules/custom/va_gov_lovell/src/EventSubscriber/LovellEventSubscriber.php, docroot/modules/custom/va_gov_lovell/src/LovellOps.php, docroot/modules/custom/va_gov_workflow_assignments/src/Plugin/Block/EntityMetaDisplay.php, docroot/modules/custom/va_gov_workflow_assignments/va_gov_workflow_assignments.info.yml
Closes #10171 
Manually
1. As an admin, go to ["Lovell both" page](https://pr10946-2rxm2pkngkybcmdpgz1hizncpmunqass.ci.cms.va.gov/node/49925/edit)
2. As an admin, go to ["Lovell VA" page](https://pr10946-2rxm2pkngkybcmdpgz1hizncpmunqass.ci.cms.va.gov/node/49931/edit)
3. As an admin, go to ["Lovell TRICARE" page](https://pr10946-2rxm2pkngkybcmdpgz1hizncpmunqass.ci.cms.va.gov/node/49930/edit)
As an admin, go to a non-Lovell *VAMC facility* page, such as [/fayetteville-coastal-health-care/locations/jacksonville-3-va-clinic](https://pr10946-2rxm2pkngkybcmdpgz1hizncpmunqass.ci.cms.va.gov/fayetteville-coastal-health-care/locations/jacksonville-3-va-clinic)
As an admin, go to a non-Lovell *VAMC facility health service* page, such as [/cheyenne-health-care/locations/northern-colorado-va-clinic/nut …
=> VCMS 10171-update page details block lovell

composer.json, composer.lock
#11216
See https://drupal.org/node/2975602
=> VACMS-11216: patch HTML utilities to properly handle carriage returns.

config/sync/views.view.va_forms.yml, tests/behat/drupal-spec-tool/views.feature
Closes  #10776
Visit the new forms audit view page at: /admin/content/va-forms/audit and validate against the [CMS Views Styleguide](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1740472321/CMS+Views+Style+Guide):
=> VACMS-10776: Add new forms audit view.

docroot/modules/custom/va_gov_backend/va_gov_backend.module
Closes #11084
1. Create a new Landing Page node.
2. In the 'main content' field, add a 'Table' paragraph
=> VACMS-11084: Update tablefield help text.

config/sync/views.view.content.yml
Closes #10923.
Logged in as an admin you should be able to see the Outdate Content report in the `/admin/content` view. There are now three more options in the outdated filter for 30, 60 and 90 days until due.
=> VACMS-10923: updated filters for outdated content report

.github/workflows/default-branch-datadog-metrics.yml
Closes #10921.
This needs to be merged to have any effect whatsoever.  I might end up fighting with this a bit since GHA's are hard to test without putting into production 😩
=> VACMS-10921: Send code coverage metrics to DataDog.

.github/workflows/actions-metrics.yml
Closes #11257.
If this passes tests, it should be safe to merge.
=> VACMS-11257: Sends GitHub Actions metrics to DataDog.

.github/actions/post-checkout/action.yml, .github/workflows/continuous_integration.yml, .github/workflows/dependabot-auto-merge.yml, .github/workflows/pull-request-labels.yml, .github/workflows/s3-backup-retention.yml, .github/workflows/set-tugboat-tests-pending.yml
Closes #10974.  I did this fairly carefully, but possible I made a mistake copypastaing a SHA somewhere.  If so I might need to hotfix `main` after this is merged if I messed up one of the `pull_request_target` action SHAs.
=> VACMS-10974: Pins GitHub Actions at commit SHAs instead of tags/branches.

docroot/modules/custom/va_gov_vamc/src/EventSubscriber/EntityEventSubscriber.php
Closes issue #10528 
Manual testing
**Appointment intro text (VAMC Facility Health Service)**
1. Go to node/25412/edit
2. Scroll down to "appointment intro text"
3. Select "customize text" and add some text
4. Now change your mind and select "use default"
5. Save the node and then go back to edit it again.
6. Scroll down to "appointment intro text" and select "customize text".
**Service location hours (VAMC Facility Health Service)**
1. Go to node/25412/edit
2. Scroll down to "Service Locations -> hours"
3. Select "provide specific hours" and enter some hours if not already present
4. Now change your mind and select "use facility's hours"
5. Save the node and then go back to edit it again.
6. Scroll down to "Service Locations -> hours" and select "provide specific hours".
**Service …
=> VACMS-10528: clear conditional fields that are hidden on node save

config/sync/core.entity_form_display.taxonomy_term.health_care_service_taxonomy.default.yml, config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml, config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_show_for_vamc_facilities.yml, config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_show_for_vba_facilities.yml, config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_show_for_vet_centers.yml, config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vba_com_conditions.yml, config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vba_friendly_name.yml, config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vba_service_descrip.yml, config/sync/field.storage.taxonomy_term.field_show_for_vamc_facilities.yml, config/sync/field.storage.taxonomy_term.field_show_for_vba_facilities.yml, config/sync/field.storage.taxonomy_term.field_show_for_vet_centers.yml, config/sync/field.storage.taxonomy_term.field_vba_com_conditions.yml, config/sync/field.storage.taxonomy_term.field_vba_friendly_name.yml, config/sync/field.storage.taxonomy_term.field_vba_service_descrip.yml, tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
Closes #11137 
Manually
As an admin, edit the Adaptive sports term: /taxonomy/term/112/edit
As an admin, visit the Brockton VA Medical Center page: /boston-health-care/locations/brockton-va-medical-center
=> VACMS-11137 Add VBA fields VA service taxonomy

.ddev/php/zzz-va-overrides.ini, .tugboat/config.yml, composer.json
Fixes #11315. This is against the `VACMS-10870-upgrade-to-php81` branch not `main`. 
This disables JIT and turns back on optimizing the PHP autoloader in composer. See #11315 for discussion. 
1. Do this
2. Then
=> VACMS-11315: Tugboat & DDEV: opcache.jit = disable

config/sync/views.view.content.yml
Closes #11289.
Navigate to main admin content view. Select the Outdate Content tab. You will see an Outdated filter element. It now has 30, 60 and 90 days until due options. These will filter the content shown to jus the content that will be outdate in the next 30, 60 or 90 days.
=> VACMS-11289: updated filters

docroot/modules/custom/va_gov_user/src/Plugin/Block/UserSections.php
Closes #9923 
Manual testing
Logged in as an admin before:
Logged in as an admin after the fix:
Expanded:
Logged in as a Lovell editor after the fix:
As a Lovell editor (example: Katie.Yearley@va.gov
=> VACMS-9923: fix display for Lovell sub-sections in user section block

tests/behat/drupal-spec-tool/content_model_bundles.feature, tests/behat/drupal-spec-tool/menus.feature
Returns original formatting to spec tool tests that  were accidentally reformatted  by
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11114
and sibsequently https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11204
These are whitespace changes only.
Passing tests will suffice.
=> VACMS-000 Restore original spec took formatting (white space only)

config/sync/core.entity_form_display.taxonomy_term.health_care_service_taxonomy.default.yml, config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml, config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_tricare_description.yml, config/sync/field.storage.taxonomy_term.field_tricare_description.yml, tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
=> VACMS-11421: add tricare description to service taxonomy

docroot/modules/custom/va_gov_backend/va_gov_backend.module, docroot/modules/custom/va_gov_user/src/Service/UserPermsService.php
Closes #10739.
Manually.
Because the fix to this bug is to create more specific caches, the only way to test it (especially with memcache running), is to simply edit content types as the user. Even though we never determined a replicable set of steps to trigger the error, a tester should still no longer see the following on the VAMC Facility Detail Page:
As stefanie.gray, edit a [Vet Center Facility Service](https://pr11412-50kwcdiqgmlwz7pgfz485okslscdo6mn.ci.cms.va.gov/node/41100/edit).
As stefanie.gray, start the process to create a new [Vet Center Service](https://pr11412-50kwcdiqgmlwz7pgfz485okslscdo6mn.ci.cms.va.gov/node/add/vet_center_facility_health_servi).
As stefanie.gray, edit a [VAMC Detail Page](https://pr11412-50kwcdiqgmlwz7pgfz485okslscdo6mn.ci.cms.va.gov/node/35189/edit). …
=> VACMS-10739: Cache preventing options from showing

.tugboat/config.yml
This removes a change that caused our tugboat deploys to not match the process that is being use on all other environments.  Updb should continue to before an config import, which is the order utilized by 'drush deploy'
This returns up to the deploy process that has been working for over a year and removes a change that was mistakenly added as part of https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11387
=> VACMS-000 Remove tugboat deploy deviation

config/sync/field.field.node.vba_facility_service.field_body.yml, config/sync/field.field.node.vba_facility_service.field_service_name_and_descripti.yml, config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_also_known_as.yml, config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vba_com_conditions.yml, config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vba_friendly_name.yml, config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vba_service_descrip.yml, config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_vha_healthservice_stopcode.yml, config/sync/views.view.health_care_service_names_and_descriptions.yml, tests/behat/drupal-spec-tool/content_model_vba_facility_content_type_fields.feature, tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
Closes #11473
Closes #11468 
Manually.
1.   [ ] Go to [Adpative Sports](https://pr11483-nmzurj8zhebgxvjdxu7ewhlqfbcyw3gb.ci.cms.va.gov/taxonomy/term/112/edit?destination=/admin/structure/taxonomy/manage/health_care_service_taxonomy/overview)
2.  [ ] **Validate**: The fields labels follow sentence case, as per the ACs of #11468.
3.  [ ] Check the "Show for VBA Facilities" checkbox
4.  [ ] Go to [Addiction and substance abuse care](https://pr11483-nmzurj8zhebgxvjdxu7ewhlqfbcyw3gb.ci.cms.va.gov/taxonomy/term/47/edit?destination=/admin/structure/taxonomy/manage/health_care_service_taxonomy/overview)
5.  [ ] Check the "Show for VBA Facilities" checkbox
6.  [ ] Go to a [VBA Facility](https://pr11483-nmzurj8zhebgxvjdxu7ewhlqfbcyw3gb.ci.cms.va.gov/node/4072/edit)
7.  [ ] Click "Add new service" …
=> VACMS-11473: Adds VBA-related view display and field label configuration

docroot/modules/custom/va_gov_migrate/src/Commands/Commands.php
Relates to #10588 
Manual testing
=> VACMS-10588: omit TRICARE facilities from nightly removed from source scan

.tugboat/config.yml, docroot/modules/custom/va_gov_build_trigger/src/Plugin/AdvancedQueue/JobType/ReleaseRequest.php
Relates to #11413.
will be filled in.
1. Go here, https://pr11694-atynigsghbaog27askiih45iiyuz7gqh.ci.cms.va.gov/admin/reports/dblog?type%5B%5D=va_gov_build_trigger
2. Then go here https://pr11694-atynigsghbaog27askiih45iiyuz7gqh.ci.cms.va.gov/admin/content/deploy  and trigger a content release.
3. Refresh the log page and visit the content release request
=> VACMS-11413: disable continuous content release on Tugboat.

.tugboat/config.yml, docroot/modules/custom/va_gov_build_trigger/src/Commands/ContentReleaseCommands.php, docroot/modules/custom/va_gov_build_trigger/src/Form/BuildTriggerForm.php, docroot/modules/custom/va_gov_build_trigger/src/Plugin/AdvancedQueue/JobType/ReleaseRequest.php
#11413 
1. Created PR, which set up a Tugboat instance.
2. Observed Tugboat instance. Currently a front-end build is started as part of the Tugboat update process, after tests run (see https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.tugboat/config.yml#L189). 
3. Once front-end build completed, waited to see if any subsequent builds started on their own. None did. 
4. Manually triggered a front-end build and let it start running, confirming it was running. Then, pushed an update to the PR, in order to re-trigger the test & front-end build process. This a) interrupted the running front-end build; b) allowed tests to run; c) Started another front-end build once the tests were complete, as expected. 
5. Once the build triggered in 4 completed, no additional front-end …
=> VACMS-11413: tugboat content release modification

docroot/design-system/components/tokens/_variables.scss, docroot/themes/custom/vagovclaro/assets/scss/components/_buttons.scss, docroot/themes/custom/vagovclaro/assets/scss/components/_elements.scss, docroot/themes/custom/vagovclaro/assets/scss/components/_footer.scss, docroot/themes/custom/vagovclaro/assets/scss/components/_layout.scss, docroot/themes/custom/vagovclaro/assets/scss/components/_links.scss, docroot/themes/custom/vagovclaro/assets/scss/styles.scss
…quirements
Closes #10046 
Visual testing
Confirm that all links within the CMS follow the specified design patterns:
- **Standard links**
- Color: `var(--va-blue-dark) #004795`
- Underlined
- 1rem/16px
- Hover/Focus:
- Color: `var(--va-blue-darker) #003e73`
- Background: `var(--va-blue-lighter) #e4eff9`
- No underline
- **Breadcrumbs**
- Same as standard link pattern with 2 exceptions:
- Bold
- .79rem/12.64px
- **Login Screen Footer links**
- Same as standard link pattern with 1 exception:
- Color: `var(--color-white) #fff`
There are elements within the CMS that do not visually appear as links however within the HTML they are `<a>` tags and therefore need to be tested to confirm the styles on these elements do not change.
- Tabs:
- No tabs at all should have an underline
- The main tabs …
=> VACMS-10046: update link colors to meet WCAG 2.0 AAA contrast requirements

tests/cypress/integration/accessibility/accessibility.spec.js
Closes #11761.  We're using CSS transitions with a short-but-nonzero duration when we draw various links, including in the toolbar.  Unfortunately, during this time the accessibility tests can run, and we're not _always_ accessible.
This change simply delays a second after page load and script injection to allow these transitions to complete before actually checking the accessibility of the DOM.
If accessibility tests pass, this should be safe to merge.
=> VACMS-11761: Delay accessibility tests to allow CSS transitions to complete.

config/sync/views.view.vamc_operating_statuses.yml
Relates to #11726 
Visual/manual
Previous checkbox presentation:
Updated checkbox presentation:
Previous view definition:
New view definition:
=> VACMS-11726: make VAMC alert checkbox list alpha sort and cleanup

composer.json, composer.lock, config/sync/core.entity_form_display.node.health_care_local_facility.default.yml
Closes #11484
This is largely a contrib module jump with the removal of a patch that has already been merged upstream and released as the new version.
As user  admin
1. Go to https://pr11809-reccqq790utweyyggpdzilvsgiwsyqk0.ci.cms.va.gov/montana-health-care/locations/miles-city-va-community-living-center
2. Then click the edit tab on that page and scroll down to Covid 19 section.
3. Save the node.
4. Visit https://pr11809-reccqq790utweyyggpdzilvsgiwsyqk0.ci.cms.va.gov/node/add/health_care_local_facility  which will have no existing value.
5. Open your browser inspector to console
Is an …
=> VACMS-11484 Make Covid status show even if empty.

composer.json, composer.lock
Closes #11669.
See this `menu_item_extras` issue: https://www.drupal.org/project/menu_item_extras/issues/3302060
This patch changes the return value for a function called when modules are uninstalled.  As such this has effects only during config import, really.
I'll cook up some screenshots, I think.
=> VACMS-11669: Apply patch to fix warning importing configuration.

.ddev/config.yaml, .ddev/mutagen/mutagen.yml, .ddev/php/zzz-va-overrides.ini, .github/actions/post-checkout/action.yml, .tugboat/config.yml, composer.json, composer.lock, docroot/modules/custom/va_gov_backend/src/Deploy/FileOperationsTrait.php, docroot/modules/custom/va_gov_backend/src/Deploy/Plugin/FeatureFlag.php, docroot/modules/custom/va_gov_migrate/src/EventSubscriber/PrepareRow.php, docroot/modules/custom/va_gov_workflow/src/Service/Flagger.php, docroot/sites/default/settings.php, docroot/themes/custom/vagovclaro/vagovclaro.theme, patches/temporary_fix_for_htmlspecialchars_deprecation.patch, phpunit.xml.bak, tests/behat/Drupal/FeatureContext.php, tests/behat/behat.yml, tests/phpunit/Support/Classes/VaGovExistingSiteBase.php, tests/phpunit/Support/Classes/VaGovUnitTestBase.php
=> VACMS-10870: Upgrade to PHP 8.1

docroot/themes/custom/vagovclaro/templates/field/field--node--field-products.html.twig
Closes #11049.
This was a bear.
Before:
After:
1. Do this
2. Then
=> VACMS-11049: Fix 'attributes' error.

.tugboat/config.yml
Closes #11881.
If this passes tests, it should be safe to merge.  All I did was reorder existing commands, because I think dispatching the build command and then trying to change frontend file permissions is creating a race condition that sometimes throws errors.
=> VACMS-11881: Change order of file permission changes on Tugboat.

config/sync/core.extension.yml, docroot/modules/custom/va_gov_consumers/va_gov_consumers.info.yml, docroot/modules/custom/va_gov_consumers/va_gov_consumers.module
Closes #11890 
Manual testing
1. Logn as Ryan.S___
2. Go to /node/1705/edit
3. Scroll down to 'Facility Data' field group.  
4. The facility data should not be editable but rendered in the same manner as node view
=> VACMS-11890: counter changes made to field_group hook weights

docroot/modules/custom/va_gov_links/va_gov_links.module
Unset-array-key messages are warnings now, whereas they were notices in PHP 7.4.
Closes #11904.
=> VACMS-11904: Fixes undefined array key warning in va_gov_links_form_editor_link_dialog_alter().

composer.json, composer.lock
Closes #11906.
See https://www.drupal.org/project/taxonomy_entity_index/issues/3326616
Need to run the daily tasks or at least the drush command to rebuild the taxonomy term index once this is deployed and tests have run.  If it succeeds, we should be good to merge.
=> VACMS-11906: Patches taxonomy_entity_index to fix rebuild error.

docroot/themes/custom/vagovclaro/vagovclaro.theme
Closes #11905.  Another thing where a notice became a warning.  I added a null-coalescing operator to get rid of the notice, because I think that's generally better than the error-suppression operator, but eh.
=> VACMS-11905: Fixes "Undefined key: req_optional" warning message.

docroot/modules/custom/va_gov_backend/src/Controller/ContentReleaseStatusController.php, docroot/modules/custom/va_gov_backend/va_gov_backend.routing.yml, tests/phpunit/Controller/ContentReleaseStatusControllerTest.php
Closes #11896.  
We shouldn't muck around with [`date_​default_​timezone_​set()`](https://www.php.net/manual/en/function.date-default-timezone-set.php) generally, but in this case I don't think it's necessary anyway since we're operating with a timestamp.
**EDIT**: Wrong.  The `date_default_timezone_set()` call actually affects `ContentReleaseStatusController`, making the test work across environments.  So I'll need to dig in a bit further, I think.
The actual date figuring is done in `ContentReleaseStatusController`, and Drupal's relationship with time zones is substantially more complicated than this would indicate.
I might revisit this when I add unit tests for `ContentReleaseStatusController` and add DI, etc.
=> VACMS-11896: Make ContentReleaseStatusController test more reliable.

config/sync/views.view.managed_links.yml, tests/behat/drupal-spec-tool/views.feature
Closes #11744.
-  ignore the normally Views Style guide requirements as this is just to see if the link checker is going to have too many false alarms, or if it gives us meaningful information.
To access the Status Report:
=> VACMS-11744: external link status report view added

composer.json, composer.lock, config/sync/views.view.content.yml, tests/behat/drupal-spec-tool/views.feature
resolves #11924.
closes #11506
Tested locally. 
As admin
1. Click Content to navigate to teh main Content view. 
2. Then visit a sublevel like /admin/content/linky 
=> VACMS-11924: Admin/content displays "Outdated Content" h1 and breadcrumb

config/sync/views.view.va_blocks_admin.yml
Closes #11973
As a content admin:
=> VACMS-11973: Updates caption title for alert and promo blocks Views.

.github/actions/post-checkout/action.yml, .github/workflows/contextual-advice.yml, .github/workflows/default-branch-datadog-metrics.yml, .github/workflows/dependabot-auto-merge.yml, .github/workflows/s3-backup-retention.yml
Implements https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Ticket: #11948 
Slack discussion: 
The warnings manifest as so:
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
Operations done to a test workflow and then workflow run: https://github.com/department-of-veterans-affairs/content-build/actions/runs/3699616713 (note the ending failure is intentional and not due to the updates)
The test workflow uses the new syntax, and runs as expected. The same new syntax is used for this PR.
=> Update GHA to new output syntax.

docroot/themes/custom/vagovclaro/templates/page/page--node.html.twig
Last saved by and editor block showing on /node/add page. It shouldn't.
Closes #12035.
Tested locally. Verified that Last Saved by an Editor is not showing on /node/add. 
I also checked that it is still showing on node views for Vet Center, VAMCS Detail Page, Event, Staff Profile, Vet Center - Facility Service, and Story.
1. Navigate to /node/add
2. Then view 5 pieces of content from different content types
=> VACMS-12035: Last-saved-by-an-editor block rampaging unchecked throughout CMS

config/sync/user.role.content_admin.yml, tests/phpunit/Security/RolesPermissionsTest.php
Closes #10996.
This permission doesn't seem to actually exist anymore, and it should be _damnatio memoriae_'d.
=> VACMS-10996: Removes obsolete permission from content_admin.

composer.json, composer.lock
Closes #10997.
As far as I can tell, this module is not installed, nor is it referenced anywhere in the codebase.  This should be completely safe.
=> VACMS-10997: Remove `better_field_descriptions` module.

composer.json, composer.lock
Closes #12189.
See also #12187 and #12188.
This rolls back `drupal/auto_entitylabel` to a version we were using previously.  This reintroduces some bugs, but the update should be accomplished as part of #12188.
1. Go [here](https://cms-rm43hk8f5exkbjgahinskc5mcqbfmm9k.ci.cms.va.gov/node/add/person_profile)
2. Add a first name, last name, section, and region.
3. Click Save.
If that works, we're good 🙂
=> VACMS-12189: Rollback `drupal/auto_entitylabel`.

docroot/modules/custom/va_gov_backend/src/Service/VaGovUrl.php, docroot/modules/custom/va_gov_backend/src/Service/VaGovUrlInterface.php, docroot/modules/custom/va_gov_workflow_assignments/src/Plugin/Block/EntityMetaDisplay.php, tests/phpunit/Content/EntityMetaDisplayTest.php, tests/phpunit/Service/VaGovUrlServiceTest.php
Closes #12108 
Manual testing
Events list page (for umbrella system)
Stories list page (for umbrella system)
News release list page (for umbrella system)
=> VACMS-12108: lovell federal list pages should show urls with links

docroot/modules/custom/va_gov_db/va_gov_db.install
Closes #12231.
This update logs verbosely, so we should be able to easily verify that it completed successfully.
...
=> VACMS-12231: Removes `old_%` DB tables.

composer.json
We don't have to use the git source for Drupal Core anymore as our composer install builds are not getting run through the TIC anymore. The only reason we used source is because they were getting blocked sometimes by the TIC (firewall) and we moved our builds out of that network a long time ago and never changed this back. This is old technical debt.
>  - Upgrading drupal/core (9.4.7 => 9.4.10):     Update failed (The .git directory is missing from /var/www/html/docroot/core, see https://getcomposer.org/comm
it-deps for more information)
Would you like to try reinstalling the package instead [yes]? 
This is a follow up to https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11893. 
This PR will speed up the composer install on all environments.
`ddev composer install`
What …
=> Use Drupal package, not source.

composer.json, composer.lock, config/sync/core.extension.yml, config/sync/views.view.content_model_fields.yml, tests/behat/drupal-spec-tool/views.feature
Closes #12286
As an admin  (this report only shows to admins)
1.  Login  https://pr12332-djcvxbj4y6ist5avej2dtuz3xylrdpu4.ci.cms.va.gov/ and pull down the reports menu, 
- Views Style guide  This View is provided via a contrib module we control and as such is only loosely bound to our style guide, however I have tried to maintain as much it that makes sense.
As content admin
- Login as Randi.Hecht@va.gov
- go to https://pr12332-djcvxbj4y6ist5avej2dtuz3xylrdpu4.ci.cms.va.gov/admin/reports/fields/content-model
=> VACMS-12286 Add content_model_documentation module and enable.

docroot/modules/custom/va_gov_lovell/js/limit_lovell.es6.js, docroot/modules/custom/va_gov_lovell/js/limit_lovell.js, docroot/modules/custom/va_gov_lovell/src/EventSubscriber/LovellEventSubscriber.php, docroot/modules/custom/va_gov_lovell/src/LovellOps.php, tests/cypress/integration/behavioral/content_editing_vamc_facility_service.feature
Relates to #12234 
Manually
Go to the [VAMC System page for TRICARE](https://pr12328-v7fhnsgnlptfrsh8cy4kcordmbhs3rps.ci.cms.va.gov/lovell-federal-health-care-tricare)
Go to the [VAMC System page for VA](https://pr12328-v7fhnsgnlptfrsh8cy4kcordmbhs3rps.ci.cms.va.gov/lovell-federal-health-care-va)
Go to a [VAMC System Health Service for TRICARE](https://pr12328-v7fhnsgnlptfrsh8cy4kcordmbhs3rps.ci.cms.va.gov/lovell-federal-health-care-tricare/health-services/homeless-veteran-care-at-lovell-federal-health-care-tricare)
Go to a [VAMC System Health Service for VA](https://pr12328-v7fhnsgnlptfrsh8cy4kcordmbhs3rps.ci.cms.va.gov/lovell-federal-health-care-va/health-services/internal-medicine-at-lovell-federal-health-care-va)
Go to a [Blind and low vision rehabilitation - Captain James A. Lovell …
=> VACMS-12234 Refactor for Lovell name change

tests/cypress/integration/behavioral/common/i_check_the_watchdog_log.js, tests/cypress/integration/behavioral/common/i_create_a_media.js, tests/cypress/integration/behavioral/common/i_create_a_node.js, tests/cypress/integration/behavioral/common/watchdog_log.js, tests/cypress/integration/behavioral/permissions.feature, tests/cypress/support/commands.js
Closes #11895.
Also closes #11880.
It's all tests!  SOYLENT GREEN IS MADE OF TESTS
Mebbe I'll upload some later, give you a little thrill.
Optionally check out locally and:
=> VACMS-11895: Adds Cypress support for counting Watchdog log messages.

tests/phpunit/Content/TrimNodeTitleWhitespaceTest.php, tests/phpunit/Support/Classes/VaGovExistingSiteBase.php
Also reënables the TrimNodeWhitespaceTest test, since it's not inherently flawed and is just an innocent bystander in all this.
The query for watchdog messages isn't restricted to the running process, so they will fail any test that runs concurrently with _any_ failure of a concurrent process, e.g. `content-build-gql`.
=> VACMS-0000: Disables failure-on-watchdog-messages in ExistingSiteBase tests.

tests/phpunit/Content/TrimNodeTitleWhitespaceTest.php
Relates to #11964.
This test creates a taxonomy vocabulary.  It is immediately removed, but because of concurrency this can create errors like the following:
This causes `content-build-gql` to fail.
If tests pass, this should be safe to merge.
=> VACMS-0000: Disables `TrimNodeTitleWhitespaceTest` (again).

docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventDomainsAsPathsInLinks.php, docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventDomainsAsPathsInLinksValidator.php, docroot/modules/custom/va_gov_backend/va_gov_backend.module, tests/phpunit/Content/PreventDomainsAsPathsInLinksValidatorTest.php
Closes #12513.
As any user with the ability to edit content:
1. Edit a node, e.g. [VAMC System Health Service Whole health at VA Cincinnati health care](https://cms-vfislbxy0kemk1sfwjmanwmkes6yeq82.ci.cms.va.gov/node/24426/edit)
2. Insert a relative link containing a VA.gov domain into a rich text field.  For instance: `<a href="/www.navy.mil/test.txt">Example Link!</a>`.
3. Attempt to save the document.  You should see:
4. Edit a media image item, e.g. [August2022.jpg](https://cms-vfislbxy0kemk1sfwjmanwmkes6yeq82.ci.cms.va.gov/media/image/16769)
5.  Insert a relative link containing a URL into a plain text field. For instance, `/www.navy.mil/test.txt`.
6. Attempt to save the media image item.  You should see:
=> VACMS-12513: Prevents relative links that start with `/www.`.

docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
Closes #12303 
Manual testing
LOVELL - Parent select list before code change
LOVELL - Parent select list after code change
OTHER - Parent select list before code change
OTHER - Parent select list after code change
**Lovell Items**
**Other Items**
=> VACMS-12303: add menu section for lovell menu items in parent list

.github/workflows/set-tugboat-tests-pending.yml
Closes #12215.  Work done in #12192 should have fixed this test.
=> VACMS-12215: Reënable status-error test.

config/sync/core.entity_form_display.taxonomy_term.health_care_service_taxonomy.default.yml, config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml, config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.vamc_facility_service.yml, config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.vba_facility_service.yml, config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.vet_center_service.yml, config/sync/field.field.taxonomy_term.health_care_service_taxonomy.field_tricare_name.yml, config/sync/field.storage.taxonomy_term.field_tricare_name.yml, tests/behat/drupal-spec-tool/content_model_vocabulary_fields.feature
=> VACMS-12585: add tricare service name field to va services taxonomy

tests/cypress/integration/common/i_create_a_node.js
Rarely, this test would break because there's a 40-character limit on this field, and Faker might generate 41 or 43 😩
=> VACMS-0000: Use substring of generated text in link-text field to avoid running afoul of character limit.

tests/cypress/integration/content_editing_vamc_facility.feature
Relates to #12217.
Manually
Cypress
Does it pass Cypress tests?
Does it do so consistently?
=> VACMS-12217: Ignoring test for now

docroot/modules/custom/va_gov_backend/src/Plugin/MetricsCollector/OutdatedContent.php
Closes #12845.
As any admin user:
1. Visit [`/metrics`](https://cms-39wxlqb8izeh7nlaj9lkfmmdssu00p1u.ci.cms.va.gov/metrics)
2. Verify:
```
drupal_va_gov_outdated_content_total{lastSaved="30DaysOverdue"} 26523
drupal_va_gov_outdated_content_total{lastSaved="60DaysOverdue"} 25362
drupal_va_gov_outdated_content_total{lastSaved="90DaysOverdue"} 24564
drupal_va_gov_outdated_content_total{lastSaved="AllOverdueContent"} 27456
drupal_va_gov_outdated_content_total{lastSaved="30DaysUntilOverdue"} 824
drupal_va_gov_outdated_content_total{lastSaved="60DaysUntilOverdue"} 1470
drupal_va_gov_outdated_content_total{lastSaved="90DaysUntilOverdue"} 2942
```
3. Visit [`/admin/content/outdated_content`](https://cms-39wxlqb8izeh7nlaj9lkfmmdssu00p1u.ci.cms.va.gov/admin/content/outdated_content)
4. Verify:
=> VACMS-12845: Adds outdated-content prometheus exporter plugin.

composer.lock
Reverts department-of-veterans-affairs/va.gov-cms#12781
This is being reverted due to https://dsva.slack.com/archives/CDHBKAL9W/p1678134778777159    There were no db updates as part of the last release so this should be safe.
##QA and testing
=> Revert "bump drupal/tablefield from 2.3.0 to 2.4.0"

composer.json, composer.lock
Seeing issues attempting to download exactly v16.0.0 of Node.  Felt like it was worth at least opening a PR to check out the latest 16.x.x.
=> VACMS-0000: Allow newer versions of Node 16 locally.

.github/workflows/continuous_integration.yml
This test is throwing errors because we have the default configuration switched on.  Therefore, we've apparently been running two identical tests for some time 🤷🏻‍♂️
=> VACMS-0000: Removes CodeQL CI test.

docroot/modules/custom/va_gov_vamc/src/Plugin/Validation/Constraint/SectionMatcherValidator.php, tests/cypress/integration/content_editing_vamc_facility_service.feature
Closes #13025.
Manually
Cypress
=> VACMS-13025: Adds null check

tests/phpunit/Security/RolesPermissionsTest.php
=> VACMS-0000: Sort permissions arrays before comparison.

docroot/modules/custom/va_gov_backend/va_gov_backend.module
Bug fixes for reusable Q&A editing within FAQ and R&S nodes. There were hidden form validation errors being thrown inside the entity browser modal.
Relates to #12800
Manual testing
1. Visit /node/8475/edit
2. Then check the `Enable standalone Resources and support page for this Q&A.` field
3. Then un-check the `Enable standalone Resources and support page for this Q&A.` field
4. Save the node with the `Enable standalone Resources and support page for this Q&A.` field unset.
5. Visit /node/8483/edit
6. Under Q&A's, click the 'Edit' button next to 'What’s Premium DS Logon?' Q&A label.
7. Then check the `Enable standalone Resources and support page for this Q&A.` field
8. Then un-check the `Enable standalone Resources and support page for this Q&A.` field
9. Save the node …
=> VACMS-12800: Bug Fixes for Editing Reusable Q&A Inside Entity Browser Modal

composer.json, composer.lock
Modifies [tablefield](https://drupal.org/project/tablefield) >= v2.4, disabling its drag-drop functionality.  This follows the comment @swirtSJW added to existing D.o issue [3341971](https://www.drupal.org/project/tablefield/issues/3341971).
Relates to #12861. 
What needs to be checked to prove this works? 
Review of tablefield widgets in https://www.va.gov/education/survivor-dependent-benefits/ should have no superfluous columns.
This change should be isolated to the tablefield widget and have near zero impact on anything else.
=> VACMS-12861: Applied D.o patch disabling tablefield drag drop controls.

READMES/drush.md, config/sync/advancedqueue.advancedqueue_queue.vamc_outdated_content.yml, config/sync/advancedqueue.advancedqueue_queue.vet_center_outdated_content.yml, docroot/modules/custom/va_gov_notifications/src/Service/OutdatedContent.php, docroot/modules/custom/va_gov_notifications/src/Service/OutdatedContentInterface.php, docroot/modules/custom/va_gov_notifications/va_gov_notifications.install
Closes #13047.
Closes #13048.
Tested locally. Queued notifications, verified in queue that notifications were queued. Ran cron, emails were sent and caught by mailhog. Also showed as successfully processed in `/admin/config/system/queues`
=> VACMS-13087: update outdated content notifications

composer.json, composer.lock
Closes #13150 
As an admin
1. Go to /admin/config/search/path?search=/lovell-federal-health-care-tricare/health-services/returning-service-member
2. Go to https://www.drupal.org/project/drupal/issues/3351638 and leave a comment that you reviewed and tested it and that it works.
=> VACMS-13150 Remove path alias truncation in core.path

docroot/modules/custom/va_gov_backend/va_gov_backend.module
Relates to #12800
Relates to #13122
Manual
The warning can be created by editing any node (and not making any changes). In staging and prod, the warnings are not displayed, but are present in the Drupal log.
Example warning that should no longer be thrown:
```php
Warning: Undefined array key "#type" in Drupal\Core\Form\FormHelper::processStates() (line 211 of /var/www/cms/docroot/core/lib/Drupal/Core/Form/FormHelper.php) #0 /var/www/cms/docroot/core/includes/bootstrap.inc(347): _drupal_error_handler_real(2, 'Undefined array...', '/var/www/cms/do...', 211) #1 /var/www/cms/docroot/core/lib/Drupal/Core/Form/FormHelper.php(211): _drupal_error_handler(2, 'Undefined array...', '/var/www/cms/do...', 211) #2 /var/www/cms/docroot/core/lib/Drupal/Core/Render/Renderer.php(400): …
```
=> VACMS-12800: Resolves PHP warning about missing #type

composer.json, composer.lock
Relates #13150  (which has already been closed.)
As an admin
1. Go to https://pr13198-2w92pma8g4qbryqeftqbvjoubjiltr2r.ci.cms.va.gov/admin/config/search/path?search=/lovell-federal-health-care-tricare/health-services/returning-service-member
2. Go to https://www.drupal.org/project/drupal/issues/3351638 and leave a comment that you reviewed and tested it, mark it as RTBC and that it works.
=> VACMS-13150 Update to more recent core truncation patch.

docroot/modules/custom/va_gov_lovell/src/EventSubscriber/LovellEventSubscriber.php, docroot/modules/custom/va_gov_lovell/src/LovellOps.php
Closes #13156 
As an admin
1. Go to https://pr13225-yn0tf6reviz1tvty38wwgotfkyyzkypj.ci.cms.va.gov/node/55028/edit (which is one of the tricare detail pages nodes that has a -0 problem)
2. Add a revison log and publish and save the node.
3. Go to /node/55022/edit (the VA equivalent of that page) /lovell-federal-health-care-va/programs/chaplain-services
4. Publish and save the node
5. Go to a Lovell Federal detail page (appears at two urls) https://pr13225-yn0tf6reviz1tvty38wwgotfkyyzkypj.ci.cms.va.gov/node/36317/edit
6. Make a change to the node and publish and save.
7. Go to …
=> VACMS-13156 Fix Tricare aliases pattern.

config/sync/core.entity_form_display.paragraph.q_a_group.default.yml, config/sync/core.extension.yml, docroot/modules/custom/va_gov_entity_browser/src/Plugin/EntityBrowser/FieldWidgetDisplay/LinkedTitle.php, docroot/modules/custom/va_gov_entity_browser/va_gov_entity_browser.info.yml
Relates to #13220.
Manual
1. View this node /resources/ds-logon-faqs and click Edit to edit it.
=> VACMS-13220:  Remove inline Q&A editing

docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventAbsoluteCmsLinksValidator.php, docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventAbsoluteUrlsAsPathsInLinksValidator.php, docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventDomainsAsPathsInLinksValidator.php, docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventProtocolRelativeLinksValidator.php, docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventVaGovDomainsAsPathsInLinksValidator.php, docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/Traits/TextValidatorTrait.php
Closes #13317.
I used this as an opportunity to perform an overdue refactoring of some common functionality into a trait dedicated to validation of string and text fields.
Manual testing, existing automated tests.
1. Go [here](https://cms-20ujuleyrfct0fofkmda2u7afgnuqrct.ci.cms.va.gov/taxonomy/term/2/edit)
2. Attempt to save the term.
3. Verify that the term is saved successfully.
=> VACMS-13317: Fix saving taxonomy terms, other things.

.github/workflows/continuous_integration.yml, composer.json, composer.lock, config/sync/core.entity_form_display.taxonomy_term.administration.default.yml, config/sync/core.entity_form_display.taxonomy_term.audience_beneficiaries.default.yml, config/sync/core.entity_form_display.taxonomy_term.audience_non_beneficiaries.default.yml, config/sync/core.entity_form_display.taxonomy_term.external_data_source_destination.default.yml, config/sync/core.entity_form_display.taxonomy_term.facility_supplemental_status.default.yml, config/sync/core.entity_form_display.taxonomy_term.health_care_service_taxonomy.default.yml, config/sync/core.entity_form_display.taxonomy_term.products.default.yml, config/sync/core.entity_form_display.taxonomy_term.topics.default.yml, config/sync/core.entity_form_display.taxonomy_term.type_of_redirect.default.yml, config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml, config/sync/workflows.workflow.editorial.yml, docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php, docroot/modules/custom/va_gov_workflow/va_gov_workflow.module, tests/cypress/integration/common/i_create_a_taxonomy_term.js, tests/phpunit/Content/AliasesTest.php, tests/scripts/check-node-revision-logs.sh, tests/scripts/check-taxonomy-revision-logs.sh
Closes #13079 
As user admin
1. Go to https://pr13303-ic1jnjkygvuews05uoo3n7wbhyzv4tzk.ci.cms.va.gov/admin/config/workflow/workflows/manage/editorial
2. Navigate to an existing VA Service term. Caregiver Support https://pr13303-ic1jnjkygvuews05uoo3n7wbhyzv4tzk.ci.cms.va.gov/taxonomy/term/48/edit
3. Navigate to Advice nurse health term https://pr13303-ic1jnjkygvuews05uoo3n7wbhyzv4tzk.ci.cms.va.gov/taxonomy/term/104/edit
4. Trigger a content release https://pr13303-ic1jnjkygvuews05uoo3n7wbhyzv4tzk.ci.cms.va.gov/admin/content/deploy  
While waiting for the content release to complete
5.  Spot …
=> VACMS-13079 Add workflow to Service Taxonomy.

.tugboat/config.yml, docroot/sites/default/settings.php, docroot/sites/default/settings/settings.local.php
Closes #13534.
Base preview build log [here](https://tugboat.vfs.va.gov/log/644ab4b19a752fdd164b74be).
The following code exists just to annoy the TIC and prevent a PR preview environment from building:
```php
file_get_contents()
```
*sigh*
=> VACMS-13534: Installs `memcached` extension on Tugboat.

package.json, tests/scripts/cypress-tests.sh
Closes #13638.
Tested on CMS-Test; top test runs are those after this change, bottom test runs are those prior to the change.
=> VACMS-13638: Increase Cypress smoke test timeout.

docroot/modules/custom/va_gov_lovell/src/LovellOps.php, docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityBase.php, docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php
Closes #7279 
Visual testing
1. Visit /node/1481/edit
2. Modify the operating status to trigger a Facility status push
3. Save your changes
4. Visit /admin/config/post-api/queue
5. Verify the JSON object generated includes the following:
This PR cannot be merged until the Lighthouse team is ready to receive the new facility_url datapoint. Check with the Lighthouse team during their upcoming sprint (June 14 - June 28) to coordinate when this code can be merged and deployed.
https://dsva.slack.com/archives/C02BTJTDFTN/p1654549467258959
=> VACMS-7279: add facility_url and Lovell overrides to Facility API

docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityBase.php, docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php
These methods are not being used yet, but they will be used by two different PRs for Lighthouse that we can not control when they will land.  Adding these here now in andvance helps avoid conflct.
Relates to  #13613
Relates to #8017 
Code is not being used.  Testing will come when either of the PRs that use it are reviewed.
This code is not being used.  Testing will come when either of the PRs that use it are reviewed.
=> VACMS-13613 and 8017 Add PostFacilityBase methods

docroot/modules/custom/va_gov_consumers/src/GitHub/GitHubClient.php
This prevents an error when attempting to invoke content releases from production.
Normally, the `$clientPayload` argument is unspecified and defaults to `NULL`, but it's an error to actually send `NULL` as a value to the GitHub API; it returns a 422 status code like [this](https://dsva.slack.com/archives/CJT90C0UT/p1685130321762009).
1. Do this
2. Then
=> VACMS-0000: Ensure `$clientPayload` is not NULL.

docroot/modules/custom/va_gov_facilities/src/FacilityOps.php, docroot/modules/custom/va_gov_lovell/src/LovellOps.php, docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityBase.php, docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityService.php, docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php, docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityWithoutStatus.php, docroot/modules/custom/va_gov_post_api/src/Service/PostServiceInterface.php, docroot/modules/custom/va_gov_post_api/va_gov_post_api.info.yml, docroot/modules/custom/va_gov_post_api/va_gov_post_api.module, docroot/modules/custom/va_gov_post_api/va_gov_post_api.services.yml, tests/phpunit/Content/FacilityStatusQueueTest.php
Closes #13769
Summary:  
- Adding url pushes needs to make sure we push when the url would change.
- Adding pushes for Vet Center mobile, which we never pushed before because they have no status.
- Reducing the number of testing permutations while adding more data fields that need to be monitored for change.
- Significant refactoring to allow for different status vs non-status push classes, some shared functions that can be used across them, both in a base class and in a static FacilityOps class.
As user admin.
Test an edit of an existing node for one of each facility content types. Changing …
=> VACMS-13769 Fix non page facilities urls pushed to lighthouse

.github/workflows/repair-pr-title.yml
Closes #11365.
See [this PR](https://github.com/department-of-veterans-affairs/va.gov-cms-test/pull/1354). I tested with a fairly pathological title.
1. Do this
2. Then
=> VACMS-11365: Adds GHA workflow to repair PR titles.

config/sync/views.view.content.yml
Closes #12559.
I reviewed other views, but none of them with a sortable moderation_state field seemed to span the non-workflowed content types.
=> VACMS-12559: Removes ability to sort on moderation_state on content view.

composer.json, composer.lock, config/sync/core.extension.yml, docroot/design-system/components/alert/alert.scss, docroot/design-system/components/alert/alert.twig, docroot/modules/custom/va_gov_multilingual/modules/va_gov_multilingual_tmgmt/src/EventSubscriber/FormEventSubscriber.php, docroot/modules/custom/va_gov_multilingual/modules/va_gov_multilingual_tmgmt/va_gov_multilingual_tmgmt.info.yml, docroot/modules/custom/va_gov_multilingual/modules/va_gov_multilingual_tmgmt/va_gov_multilingual_tmgmt.services.yml, docroot/modules/custom/va_gov_multilingual/va_gov_multilingual.info.yml, patches/tmgmt_language_changes.patch
#13780 
Same as QA steps.
1. Log in as admin.
2. Visit https://pr13894-swyq1xt9wttom9yleleqcke7jeuka3rv.ci.cms.va.gov/admin/tmgmt/sources.
3. Select any two items, select 'Spanish' as the target language, and hit 'Request translation'.
4. On the next page, hit 'Submit to provider'. You'll be taken back to the Sources page.
5. Select *one* of the two items from steps 3/4. as well as 1 or more additional 'fresh' items. Select 'Spanish' as the target language and hit 'Request translation'.
6. Hit 'Submit to provider'. You'll be taken back to Sources page.
7. Repeat the process, but select *2 or more* items that have the blue hour glass on the right, in addition to fresh items. Hit 'Submit to provider'.
8. Repeat the process, but this time select *only* items that are already in progress.
=> Set up UX languages changes for TMGMT.

config/sync/migrate_plus.migration.va_node_facility_nca.yml, docroot/modules/custom/va_gov_facilities/src/FacilityOps.php, docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_nca.yml, docroot/modules/custom/va_gov_migrate/src/Commands/Commands.php
Closes #13362 
Manually
- As an admin, go to [National Cemetery of the Alleghenies](https://pr13858-nlnnnfn5vedzn3oopc5rv5gxwhsm2mmz.ci.cms.va.gov/node/4595/edit) and note what data exists currently
- In a separate window, go to [Baxter Springs City Soldiers' Lot](https://pr13858-nlnnnfn5vedzn3oopc5rv5gxwhsm2mmz.ci.cms.va.gov/node/4432/edit) and note what data exists currently
- In a separate window, go to [Benicia Arsenal Post Cemetery](https://pr13858-nlnnnfn5vedzn3oopc5rv5gxwhsm2mmz.ci.cms.va.gov/node/27552/edit) and note what data exists currently
- In a separate window, run the [NCA migration](https://pr13858-nlnnnfn5vedzn3oopc5rv5gxwhsm2mmz.ci.cms.va.gov/admin/structure/migrate/manage/facility/migrations/va_node_facility_nca/execute) (making sure to have Update checked).
- Open a …
=> VACMS-13362: Adds migration for NCA Facilities API data.

docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityWithoutStatus.php
Relates to [Sentry php error notice](http://sentry.vfs.va.gov/organizations/vsp/issues/207391/?referrer=webhooks_plugin) as notified in [Slack](https://dsva.slack.com/archives/CJT90C0UT/p1686055333761799).
Manually
PHPUnit
N/A
- Run [VBA migration](https://pr14007-vu6kalo9e2d8bjzfl71gg2nqskyhthug.ci.cms.va.gov/admin/structure/migrate/manage/facility/migrations/va_node_facility_vba/execute), checking "Update" under "Additional execution options"
- Run [NCA migration](https://pr14007-vu6kalo9e2d8bjzfl71gg2nqskyhthug.ci.cms.va.gov/admin/structure/migrate/manage/facility/migrations/va_node_facility_nca/execute), checking "Update" under "Additional execution options"
=> VACMS-0000: Fixes issue identified by Sentry

docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php
Closes #13649 
Manually
As user an admin user
- Run the [VBA migration](https://pr14035-vwdcgeagk6rx8oojgcesb0qcb24tym6j.ci.cms.va.gov/admin/structure/migrate/manage/facility/migrations/va_node_facility_vba/execute)
- Open the terminal in the Tugboat environment
- Run the following:
- `drush migrate:import va_node_facility_nca --update --idlist=nca_800`
-  `drush migrate:import va_node_health_care_local_facility --update --idlist=vha_557`
- Validate that the following have been formatted and put into comments:
- Validate that the following have not regressed (compared to the Lighthouse api)
=> VACMS-13649: Multi-time pattern passthrough

tests/cypress/support/accessibility.js
Closes #10368.
If tests pass, this should be good to merge.
=> VACMS-10368: Uses WCAG 2.1A and 2.1AA standards.

scripts/cd_metrics/time_to_restore.lib.js, scripts/cd_metrics/time_to_restore.test.js
This script alters the Time-to-Restore calculation algorithm.
Previously, we assumed we had been in a failure condition if and only if the previous commit's combined status was `"failure"`.
However, this breaks under cases like the following:
Here, we enter failure mode at commit `9ab040a`. The following commit (`055b532`) only changes documentation, and therefore no tests are run. Then `7d51500` runs tests and they succeed.
The correct failure period was `9ab040a..7d51500`, but this failure period is never reported.
This PR updates this logic to loop through previous commits until a non-pending commit is found.
I'm slightly concerned that there might be a pathological state where GitHub indicates _all_ commits have a status of "pending". As a result, I've added some logic to escape the …
=> VACMS-0000: A small change to the CD metrics script.

.gitattributes
See [here](https://github.com/github-linguist/linguist/issues/1792).
Won't work immediately, [apparently](https://github.com/github-linguist/linguist/issues/1792#issuecomment-286418120).
@swirtSJW Any other extensions we need to add here? 🤔
=> VACMS-0000: Enable syntax highlighting for *.module and *.install files

config/sync/core.entity_form_display.node.full_width_banner_alert.default.yml, config/sync/core.entity_form_display.node.full_width_banner_alert.inline_entity_form.yml, config/sync/core.entity_view_display.node.full_width_banner_alert.default.yml, config/sync/core.entity_view_display.node.full_width_banner_alert.ief_table.yml, config/sync/core.entity_view_display.node.full_width_banner_alert.teaser.yml, config/sync/field.field.node.full_width_banner_alert.field_enforce_unique_combo.yml
… Updates per system
Closes #11040 
Manual testing
1. Navigate to `/admin/content?title=&type=full_width_banner_alert&moderation_state=All&owner=220`
2. You should see 7 VAMC System Banner Alert with Situation Updates nodes
3. Edit the Coronavirus item in a new tab: `/node/36504/edit` notice this item is published
4. Edit the Telephone Service item in a new tab `/node/49336/edit` notice this item is not published
5. Try to publish this item and it should fail with a notification: "There is existing content: Coronavirus, with identical values..."
6. Leave the Telephone Service item marked as unpublished and try to save it. There should be no error.
7. Edit the Telephone Service item again. Change the section for this item to VISN 6 (the parent section for VA Hampton health …
=> VACMS-11040: limit number of VAMC system Banner Alerts

docroot/modules/custom/va_gov_facilities/src/FacilityOps.php, docroot/modules/custom/va_gov_vamc/src/EventSubscriber/VAMCEntityPreventReuse.php, docroot/modules/custom/va_gov_vamc/va_gov_vamc.install, docroot/modules/custom/va_gov_vamc/va_gov_vamc.module, docroot/modules/custom/va_gov_vamc/va_gov_vamc.services.yml, tests/cypress/integration/common/i_check_the_checkbox.js, tests/cypress/integration/common/should_exist.js, tests/cypress/integration/content_editing_vamc_banner_reuse.feature
Closes #8141
Login as an admin
1 visit https://pr14181-rfsw4ifjca4fum4i40ebyiux9avcuvkg.ci.cms.va.gov/admin/reports/status/rebuild  and rebuild the permissions (get a cup o coffee, this takes a while)
Login as user edgar.cruse  (an editor in chillicothe)
2. Go [here](https://pr14181-rfsw4ifjca4fum4i40ebyiux9avcuvkg.ci.cms.va.gov/section/vha/vamc-facilities/va-chillicothe-health-care) and filter the page for content type = "VAMC System Banner Alert with Situation Updates"
3. GO to the content page https://pr14181-rfsw4ifjca4fum4i40ebyiux9avcuvkg.ci.cms.va.gov/admin/content?title=&type=full_width_banner_alert&moderation_state=All&owner=337
Go to content not  in your section (tampa health care) https://pr14181-rfsw4ifjca4fum4i40ebyiux9avcuvkg.ci.cms.va.gov/admin/content?title=&type=full_width …
=> VACMS-8141 Prevent re-use of VAMC banner alerts.

config/sync/views.view.vamc_alerts_and_operating_statuses.yml
Closes #14247
As and admin 
1. Go to /admin/content/vamc-alerts-and-statuses
=> VACMS-14247 Add published filter to VAMC System banner View

.tugboat/config.yml
`sitewide_alert` alerts added to prod can propagate through the lower environments, but that's not ideal. The information they contain is generally not relevant. If it is relevant, we already know about it and are trying to fix the underlying issue. Either way, the alert can interfere with browser tests that expect certain elements to be visible. 
This can be somewhat difficult to predict, since some elements vary in length, and one that is a few characters too wide can be partially obscured by the JSD widget and thus not visible for test purposes.
This PR should disable all `sitewide_alert` alerts so that our tests run against a more predictable configuration.
=> VACMS-0000: Disable sitewide_alert alerts on Tugboat.

docroot/modules/custom/va_gov_content_release/src/EventSubscriber/FormRouteSubscriber.php, docroot/modules/custom/va_gov_content_release/src/EventSubscriber/FormRouteSubscriberInterface.php, docroot/modules/custom/va_gov_content_release/src/Form/Resolver/Resolver.php, docroot/modules/custom/va_gov_content_release/src/Strategy/Resolver/Resolver.php, docroot/modules/custom/va_gov_content_release/va_gov_content_release.routing.yml, docroot/modules/custom/va_gov_content_release/va_gov_content_release.services.yml, docroot/modules/custom/va_gov_environment/src/Discovery/Discovery.php, docroot/modules/custom/va_gov_environment/src/Discovery/DiscoveryInterface.php, docroot/modules/custom/va_gov_environment/va_gov_environment.services.yml, tests/phpunit/va_gov_content_release/functional/EventSubscriber/FormRouteSubscriberTest.php, tests/phpunit/va_gov_content_release/unit/Form/Resolver/ResolverTest.php, tests/phpunit/va_gov_content_release/unit/Strategy/Resolver/ResolverTest.php, tests/phpunit/va_gov_environment/functional/Service/DiscoveryTest.php, tests/phpunit/va_gov_environment/unit/Environment/EnvironmentTest.php, tests/phpunit/va_gov_environment/unit/Service/DiscoveryTest.php
Closes #13850.
This does not yet replace the `va_gov_build_trigger` route subscriber; I have a separate issue for doing that, #14272.
=> VACMS-13850: Creates `FormRouteSubscriber` service.

config/sync/user.role.content_admin.yml, tests/phpunit/Security/RolesPermissionsTest.php
Removes an invalid permission causing D10 php exception to be thrown any time role dependencies are calculated.
Relates to #14274
Unit
As a content admin:
1. Visit admin/config/content/formats/manage/rich_text
2. Click 'Save configuration'
=> VACMS-14274: Removes entityqueue permission that is no longer valid.

config/sync/views.view.pdf_audit.yml, docroot/modules/custom/va_gov_backend/src/Plugin/views/access/PdfAuditAccess.php, scripts/compile-theme.sh
Closes #14175.
Tested locally. CMS link removed because link to entity is already present in title field. CSV exprot now contains published column for each pdf column. 
1. Log into the CMS and navigate to `/admin/content/media/pdfs`
2. Then click Download CSV
=> VACMS-14175: updates to pdf report, fixes access for POs

docroot/modules/custom/va_gov_content_release/src/Annotation/ContentReleaseStrategy.php, docroot/modules/custom/va_gov_content_release/src/Annotation/EntityEventStrategy.php, docroot/modules/custom/va_gov_content_release/src/EntityEvent/Strategy/Plugin/StrategyPluginBase.php, docroot/modules/custom/va_gov_content_release/src/EntityEvent/Strategy/Plugin/StrategyPluginInterface.php, docroot/modules/custom/va_gov_content_release/src/EntityEvent/Strategy/Plugin/StrategyPluginManager.php, docroot/modules/custom/va_gov_content_release/src/EntityEvent/Strategy/Plugin/StrategyPluginManagerInterface.php, docroot/modules/custom/va_gov_content_release/src/Plugin/EntityEventStrategy/ExceptionTest.php, docroot/modules/custom/va_gov_content_release/src/Plugin/EntityEventStrategy/FalseTest.php, docroot/modules/custom/va_gov_content_release/src/Plugin/EntityEventStrategy/OnDemand.php, docroot/modules/custom/va_gov_content_release/src/Plugin/EntityEventStrategy/TrueTest.php, docroot/modules/custom/va_gov_content_release/va_gov_content_release.services.yml, tests/phpunit/FrontendBuild/EntityEventSubscriberTest.php, tests/phpunit/va_gov_content_release/functional/EntityEvent/Strategy/Plugin/StrategyPluginManagerTest.php, tests/phpunit/va_gov_content_release/functional/Strategy/Plugin/StrategyPluginManagerTest.php
Closes #13854.
This (again) exists independently alongside the content release system within the CMS, and should not affect it yet.
=> VACMS-13854: Create Response Strategy plugin system.

docroot/modules/custom/va_gov_content_release/drush.services.yml, docroot/modules/custom/va_gov_content_release/src/Commands/FrontendVersionCommands.php, docroot/modules/custom/va_gov_content_release/src/FrontendVersion/FrontendVersion.php, docroot/modules/custom/va_gov_content_release/src/FrontendVersion/FrontendVersionInterface.php, docroot/modules/custom/va_gov_content_release/va_gov_content_release.routing.yml, docroot/modules/custom/va_gov_content_release/va_gov_content_release.services.yml, tests/phpunit/va_gov_content_release/functional/EventSubscriber/FormRouteSubscriberTest.php, tests/phpunit/va_gov_content_release/functional/FrontendVersion/FrontendVersionTest.php, tests/phpunit/va_gov_content_release/unit/FrontendVersion/FrontendVersionTest.php
Closes #14271.
This does not yet interact with the current content release system, so risk should be minimal.
=> VACMS-14271: Creates `FrontendVersion` service.

config/sync/field.field.node.landing_page.field_spokes.yml, config/sync/field.field.node.landing_page.field_support_services.yml, config/sync/field.field.paragraph.q_a_section.field_section_intro.yml
Closes #12325 
Will test in test environment; just text changes.
See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12325#issuecomment-1622287110
As any user, go to https://cms-rpxhcmnci1r58oqds0ktydpnxtmepxem.ci.cms.va.gov/node/add/page
1. - [ ] Click "Main content" > Add content block and search for Q&S Section and add. Section Intro help text should say "An optional introduction that explains why these questions may be relevant to visitors."
Go to https://cms-rpxhcmnci1r58oqds0ktydpnxtmepxem.ci.cms.va.gov/node/add/landing_page
3. - [ ] Spokes help text should say "Add a list of link teasers that will provide additional information that relates to the page topic."
4. - [ ] Support services help text should say "Add services that will be useful to veterans such as …
=> VACMS-12325: Replace placeholder with real help text

docroot/themes/custom/vagovclaro/templates/field/field--node--field-description.html.twig, docroot/themes/custom/vagovclaro/templates/field/field--node--field-meta-title.html.twig
Relates to #10154 
Adds `role=presentation` to the table containing data from the description field.  
This field appears in the following content types/bundles:
- Landing Page
- Event
- Events List
- VAMC Facility
- VAMC Detail Page
- VAMC System
- Health Services List
- Benefits Hub Landing Page
- Leadership List
- VAMC Locations List
- Office
- Publication
- Benefits Detail Page
- Staff Profile
- News Releases List
- Publication Listing Page
- Stories List
WAVE Tests were performed to confirm no accessibility violations were introduced.
- go to https://pr14392-huojvklm2al0d20mn7nwow0wzkpcszzh.ci.cms.va.gov/node/8296 or https://pr14392-huojvklm2al0d20mn7nwow0wzkpcszzh.ci.cms.va.gov/resources or any page of the types listed above
- inspect …
=> VACMS-10154: Add role="presentation" to description field

.github/ISSUE_TEMPLATE/__cms-task.md, .github/ISSUE_TEMPLATE/_cms-epic.md, .github/ISSUE_TEMPLATE/change-management-epic.md, .github/ISSUE_TEMPLATE/cms-team-and-sitewide-crew-member-onboarding.md, .github/ISSUE_TEMPLATE/cross-team-intake-request.md, .github/ISSUE_TEMPLATE/defect-report.md, .github/pull_request_template.md
Simply adds AP as a team to github issue and PR templates.
=> Adding AP as an assignable team in CMS github templates.

docroot/sites/default/settings.php
Post-deploy tests failed [here](http://jenkins.vfs.va.gov/job/testing/job/cms-post-deploy-tests-staging/2172/consoleFull).
Verified on staging:
```
$ composer va:test:phpunit-functional
> # Run PHPUnit (functional) tests.
> ! ./scripts/should-run-directly.sh || bin/phpunit --group functional --exclude-group disabled tests/phpunit --
PHPUnit 9.6.10 by Sebastian Bergmann and contributors.
Testing /var/www/cms/tests/phpunit
..........................................S....................  63 / 274 ( 22%)
...........................................SSS................. 126 / 274 ( 45%)
............................................................... 189 / 274 ( 68%)
............................................................... 252 / 274 ( 91%)
...................... …
```
=> VACMS-0000: Fix a settings value that broke staging post-deploy tests

tests/cypress/integration/content_release.feature
Either you use the Cypress step definition for resetting the content release state, or you realize why you wrote the stupid thing 😩 
See:
- https://dsva.slack.com/archives/CJT90C0UT/p1690221718850259
- http://jenkins.vfs.va.gov/job/testing/job/cms-post-deploy-tests-staging/2177/console
We just had a staging test run fail because the content release state wasn't reset prior to or in the setup phase of the test run. These changes should make the tests more reliable.
=> Make content-release Cypress tests more reliable :grimacing:

tests/cypress/integration/content_release.feature
... which causes Cypress tests to fail on staging.
=> VACMS-0000: "Found" another condition that holds only on Tugboat.

docroot/modules/custom/va_gov_backend/src/Controller/ContentReleaseStatusController.php, tests/phpunit/Controller/ContentReleaseStatusControllerTest.php
Closes #14550.
I will test this on the D10 branch.
@edmund-dunn I've cherry-picked this into the D10 branch, fixed the merge conflicts, and I can push when you approve this, or you can merge it separately.
```
nathan.douglas@va-gov-cms-web:/var/www/html$ git diff
diff --git a/docroot/modules/custom/va_gov_backend/src/Controller/ContentReleaseStatusController.php b/docroot/modules/custom/va_gov_backend/src/Controller/ContentReleaseStatusController.php
index 23570e0b3..22059417f 100644
--- a/docroot/modules/custom/va_gov_backend/src/Controller/ContentReleaseStatusController.php
+++ b/docroot/modules/custom/va_gov_backend/src/Controller/ContentReleaseStatusController.php
@@ -125,8 +125,7 @@ public function getLastReleaseResponse(array $status): HtmlResponse {
*   If the build file could not …
```
=> VACMS-14550: Makes ContentReleaseStatusControllerTest D10-compatible.

composer.json, composer.lock
Closes #14405. Apologies for the duplicate pr, I messed up rebasing and it was quicker to start fresh.
Adds two patches necessary for JSON:API. The `consumer_image_styles` patch fixes a schema validation error that is generated while handling image styles resulting from a recent update to the module.
The core patch about `BaseFieldOverride` adds the entity path alias back to the JSON:API response for a given entity. No configuration updates were needed.
running locally, hitting a jsonapi endpoint for a news story node should include a `path` object underneath the `attributes` key:
https://va-gov-cms.ddev.site/jsonapi/node/news_story/1dbd5b1e-0fb2-43fb-8581-a2f9edfe3c83
- What needs to be checked to prove this works?  
Visit the same endpoint without the patches from this PR applied and …
=> VACMS-14405 add patches for jsonapi

docroot/modules/custom/va_gov_post_api/src/Form/VaGovFacilityForceQueueForm.php
Closes #11005.
@omahane I noticed the following code:
```php
....
$vet_center_cap = \Drupal::entityQuery('node')
->condition('type', 'vet_center_cap')
->condition('moderation_state', 'archived', '!=')
->execute();
$form['description'] = [
'#type' => 'markup',
'#markup' => $this->t('This form queues ALL items of a selected type for sync to Lighthouse.'),
];
$form['facility_type'] = [
'#type' => 'radios',
'#title' => $this->t('Content type'),
'#description' => $this->t('Select a content type to queue.'),
'#options' => [
'health_care_local_facility' => $this->t('VAMC facilities') . ' (' . count($health_care_local_facility) . ')',
'health_care_local_health_service' => ' - ' . $this->t('VAMC facility services') . ' (' . count($health_care_facility_service) . ')',
'nca_facility' => …
```
=> VACMS-11005: Updates `va_gov_post_api` for compatibility with D10.

docroot/modules/custom/va_gov_vet_center/js/prevent_select_duplicates.es6.js, docroot/modules/custom/va_gov_vet_center/js/prevent_select_duplicates.js
Closes #14618.
Closes #14620.
This code, as written, does not seem to behave as intended:
```javascript
var winnower = function winnower(context) {
....
};
var alphaSortRows = function alphaSortRows(context) {
....
};
Drupal.behaviors.vaGovPreventSelectDuplicates = {
attach: function attach(context) {
if (servicesFieldset) {
servicesFieldset.addEventListener("change", winnower(context));
context.addEventListener("load", alphaSortRows(context));
}
}
};
```
This code is attached to an Inline Entity Form. 
The event listeners added are the results of evaluating the `winnower(context)` and `alphaSortRows(context)` calls, not references to those functions. 
Since the functions return void, there aren't actually any functions attached and listening to events.
The form works correctly at …
=> VACMS-14618: Fix a couple of returnless functions in prevent_select_duplicates.js

tests.yml
Closes #12851.
Needs a (very simple) DevOps PR as well to function.
=> VACMS-12851: Set staging post-deploy tests pending before starting.

tests/phpunit/Content/BulletinQueueTest.php
Not only do we have a test that edits a pre-existing node, we have two. And they edit the same node. In different suites, so depending on random factors they can come into conflict.
See [this log](http://jenkins.vfs.va.gov/job/testing/job/cms-post-deploy-tests-staging/2217/).
=> VACMS-0000: Fix a contention issue with tests.

docroot/modules/custom/va_gov_post_api/va_gov_post_api.module
Relates to #14761
As an admin
1. Go to the [covid 19 vaccine service term](https://pr14762-ftm3uxhmzjsgdhwrgzuus0riu2scvvmt.ci.cms.va.gov/taxonomy/term/321/edit).
2. make a change to the VAMC desciption.  
3. Save the term as published
4. Then go [to watchdog](https://pr14762-ftm3uxhmzjsgdhwrgzuus0riu2scvvmt.ci.cms.va.gov/admin/reports/dblog?type%5B%5D=va_gov_post_api) and validate that you see multiple entries showing a batches of services being queued.
5. Go to the post_API queue https://pr14762-ftm3uxhmzjsgdhwrgzuus0riu2scvvmt.ci.cms.va.gov/admin/config/post-api/queue
=> VACMS-14761 Restore queue of facility services if service term changes

composer.json, composer.lock, tests/phpunit/API/PostApiQueueTest.php
Relates to #14732
Tested posting to facility API and altering the status code to look like an error.
Note: This was QA's locally because I could intercept request and make it fail.  Testing of the logging of fails can not be tested on tugboat.
Login as admin:
1. edit a facility https://pr14754-fpoqff2lxxpv6v5es6ouubwrwblhar7f.ci.cms.va.gov/node/2287/edit
2. change its status and publish.
3. Go to the queue. https://pr14754-fpoqff2lxxpv6v5es6ouubwrwblhar7f.ci.cms.va.gov/admin/config/post-api/queue
4. process the queue list
6. Visit dblog https://pr14754-fpoqff2lxxpv6v5es6ouubwrwblhar7f.ci.cms.va.gov/admin/reports/dblog
=> VACMS-14732 bump drupal/post_api to 2.0.2

config/sync/views.view.content_entity_browsers.yml
Closes #14604 
Q&A links in modal open in new tab.
Add config to content entity browser view table so that titles are rewritten as links that open as `target=_blank`.
Functional testing: Links in Q&A Entity Browser view table and view preview open in new tab.
As a content editor, go to https://cms-nc2osh79ylhbfkvqvnrpizowutsei8vp.ci.cms.va.gov/node/51915/edit
- Click "Edit" under Main content > Q&A group > Why should I create ...
- Scroll down and click on "Place Q&As"
- Click on any link in the table
=> VACMS-14604: Target blank on title link for entity browser view

docroot/modules/custom/va_gov_db/va_gov_db.install
Updates the `va_gov_db` module to be d10-compliant.
Relates to #11001
The upgrade status tool will not report any issues or warnings for the `va_gov_db` module.
=> VACMS-11001: Updates custom module va_gov_db to be D10-compliant

hooks/git/pre-commit
Closes #14806.
```
$ git branch -a | awk -F/ '{ print $NF }' | while read -r branch; do     check_branch_name "${branch}" && echo "good name ${branch}" || echo "bad name ${branch}"; done
good name VACMS-14687-Remove-old-entity-subscriber-stuff
good name VACMS-14803-Switch-form-classes
bad name * VACMS-14806-Block-VACMS-0000-branch-names
bad name main
bad name REVERT-VACMS-11064
bad name VACMS-00000-disable-flysystem
bad name VACMS-00000-fix-for-sitewide-alert
bad name VACMS-00000-remove-flysystem-modules
bad name VACMS-00000-remove-topfloor-remove-composer-vcs-dir
bad name VACMS-00000-update-simplasamlphp-auth
good name VACMS-10046-update-link-color-across-the-cms-to-meet-wcag-20-aaa-contrast-requirement
good name VACMS-10099-place-qa-modal-in-cms-not-available-with-keyboard
good name …
```
=> VACMS-14806: Block VACMS-0+ branch names.

.github/workflows/continuous_integration.yml
No longer necessary now and might be causing complaints.
=> VACMS-14983: Remove old CodeQL workflow.

config/sync/core.base_field_override.block_content.benefit_promo.info.yml, config/sync/core.base_field_override.block_content.news_promo.info.yml, config/sync/field.field.block_content.benefit_promo.field_promo_headline.yml, config/sync/field.field.block_content.news_promo.field_link_label.yml, config/sync/field.field.block_content.news_promo.field_promo_headline.yml, config/sync/user.role.homepage_manager.yml, docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php, docroot/modules/custom/va_gov_workflow/src/Service/WorkflowContentControl.php
Closes #13863 
Updates text and workflow for promo blocks (news, benefit) according to [this figma mockup](https://www.figma.com/file/sOMpovTM82TgC08ugF0FxF/News-Promo-Block?type=design&node-id=0-1&mode=design&t=4HX5hbqW1RqCYoA5-0) and these concepts:
~~- Makes sure "Delete" option doesn't show up for non-admin users~~
~~- Ensures that user role "homepage manager" can't archive block~~
- Ensures that non-admins can archive block
- Updates news promo block help text: block description, link text, promo headline field
- Updates benefit promo block help text: block description, promo headline field
Functional testing for the promo blocks, non-promo blocks, nodes in the bundle and not in the bundle.
TBD
As user `homepagemanager` with homepage manager role (or grant a user both homepage …
=> VACMS-13863: Improve workflow for promo blocks

config/sync/field.field.taxonomy_term.va_benefits_taxonomy.field_va_benefit_eligibility_ov.yml, tests/phpunit/va_gov_magichead/functional/Field/MaxDepthTest.php
Simple config change for magihead max depth.
Relates to #14289
Tested using drag and drop and accessibliity (show row weights) modes.
As a content admin or administrator
1. Visit /admin/structure/taxonomy/manage/va_benefits_taxonomy/overview/fields/taxonomy_term.va_benefits_taxonomy.field_va_benefit_eligibility_ov
=> VACMS-14289: Changes max depth to 2.

docroot/modules/custom/va_gov_backend/src/Controller/ContentReleaseStatusController.php, tests/phpunit/Controller/ContentReleaseStatusControllerTest.php, tests/phpunit/Deploy/DeployServiceTest.php, tests/phpunit/Support/Traits/RawGitHubApiClientTrait.php, tests/phpunit/va_gov_content_release/unit/Plugin/EntityEventStrategy/OnDemandTest.php, tests/phpunit/va_gov_content_release/unit/Plugin/EntityEventStrategy/VerboseFalseTest.php, tests/phpunit/va_gov_content_release/unit/Reporter/ReporterTest.php
Closes #15059.
From D10 Tugboat:
```
root@php:/var/lib/tugboat# bin/phpunit           --group unit           --exclude-group disabled           --coverage-text           tests/phpunit
PHPUnit 9.6.11 by Sebastian Bergmann and contributors.
Warning:       No code coverage driver available
Testing /var/lib/tugboat/tests/phpunit
...............................................................  63 / 689 (  9%)
............................................................... 126 / 689 ( 18%)
............................................................... 189 / 689 ( 27%)
............................................................... 252 / 689 ( 36%)
............................................................... 315 / 689 ( 45%)
............................................................... 378 …
```
=> VACMS-15059: Fix issues with PHPUnit tests for D10.

.github/workflows/continuous_integration.yml
=> VACMS-15212: Prevent `composer.lock` files-changed check from running on fork PRs.

.gitattributes, tests/phpunit/va_gov_content_release/functional/EventSubscriber/EntityEventSubscriberTest.php, tests/phpunit/va_gov_content_types/unit/ModuleTest.php, tests/phpunit/va_gov_git/functional/BranchSearch/BranchSearchTest.php
=> VACMS-15206: Fix namespaces of some PHPUnit tests.

composer.json, composer.lock
=> VACMS-15199: Fixes Composer scaffolding.

docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php
Quick fix connected to #15187 
Addresses #15242
Temporarily undoes the code that hides the checkbox to create revision log message on promo block types because it also hid the required field.
We will need to follow up on ticket #15187  with work to hide the checkbox again on promo block types or to adjust the promo block content-block forms to match the other block forms structure.
Functional, locally
=> VACMS-15187: Exposes revision log message on promo type blocks

docroot/modules/custom/va_gov_benefits/src/EventSubscriber/BenefitsSubscriber.php, tests/cypress/integration/features/taxonomy_type/va_benefit_taxonomy.feature
Relates to #15222 
Releases the lock down of the Benefit Name and ID fields for during the staging process of that content.
Note: Non-admins do not right now have access to this form but I structured the code so that it will be easier to lock down in the future as well as ensure that those fields aren't exposed to non-admins should access be granted to them.
Functional.
1. Log in as a testcontentadmin and got to admin/structure/taxonomy/manage/va_benefits_taxonomy/add
2. - [ ] Make sure the Name field is editable
3. - [ ] Make sure the ID field is editable
=> VACMS-15222: Unlock benefit taxonomy fields to content admins

config/sync/advancedqueue.advancedqueue_queue.content_release.yml
=> VACMS-15272: Remove old content release queue jobs.

config/sync/core.entity_view_display.paragraph.magichead_group.default.yml, config/sync/core.entity_view_display.taxonomy_term.va_benefits_taxonomy.default.yml, docroot/themes/custom/vagovclaro/assets/scss/components/_fields.scss, docroot/themes/custom/vagovclaro/assets/scss/components/_paragraphs.scss
Updates the styling of the Benefits taxonomy detail page.
Relates to #14860
Local testing in the UI.
As a content admin or administrator
1.  Visit https://cms-qxrabou9k7u2ehqu2bchor80voyrorzy.ci.cms.va.gov/taxonomy/term/1135
=> VACMS-14860: View mode changes for magichead/benefits taxonomy.

config/sync/node.type.q_a.yml, config/sync/paragraphs.paragraphs_type.q_a.yml, config/sync/paragraphs.paragraphs_type.q_a_group.yml, config/sync/paragraphs.paragraphs_type.q_a_section.yml, config/sync/paragraphs_browser.paragraphs_browser_type.content.yml, tests/cypress/integration/features/content_type/campaign_landing_page/faq.feature
Makes changes to the way we refer to reusable vs. non-resuable Question and Answer content. This PR changes various help text and labels in accordance with the mockup and the ticket.
Relates to #15098 
Functional, locally.
As any user:
- Go to add a Benefit Detail page (/node/add/page). 
- Further down, click on the "Add main content" button and then click on "Most Commonly used".
Go to add a Reusable Q&A content (node/add/q_a).
(This will behave the same way on Resources and Support.)
=> VACMS-15098: Q&A Content text changes

config/sync/core.entity_form_display.block_content.promo.default.yml, docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php, tests/cypress/support/main_content_blocks.js
Relates to #15242 
#15187 
~~Revises the workflow module to hide the revision checkbox on promo block types as well as the other custom block types, without unintentionally hiding the required revision log message field on that type.~~
Updates the promo block architecture to match the other custom block types by adding a field set for section settings and moving revision_log, section and workflow state into it.
local functional
As a user with any role, check both promo and non-promo blocks that a) revision log message works, is required and the checkbox is hidden.
=> VACMS-15242: Make Revision log message requirement more inclusive

docroot/modules/custom/va_gov_block_types/va_gov_block_types.module
Relates to #11230 
Previous PR left a line of debugging code that prints an integer to the screen when the alert block is placed. It's very small and we didn't catch it during testing.
Local, functional.
As a user with any role, edit any benefit detail page and place an unpublished alert block. Ensure that an integer is not placed on the screen as shown in the screenshot.
=> VACMS-11230: Follow up to remove debugging code

docroot/themes/custom/vagovclaro/assets/scss/components/_buttons.scss
Adds a11y-friendly visual indication styles to the "Unlock" button located on node edit forms.
Relates to #9919 
- Proceed to https://pr15441-vjmcjb0adr0lmbaxa5vgno54ekn04mw6.ci.cms.va.gov/admin/content and click on the 'Edit' link of any content entry
- Scroll near the bottom of the screen
- Click on the 'Revision log message' form input
- Press the tab button 6 times
=> VACMS-9919: Fixes visual focus styles on node edit form unlock button

config/sync/views.view.orphaned_paragraphs.yml, docroot/modules/custom/va_gov_backend/src/EventSubscriber/OrphansReportViewsEventSubscriber.php
Closes #15447
Tested locally. Report displays with no erros. 
1. Log in and navigate to /admin/reports/orphaned-paragraphs
2. Then navigate to /admin/reports/dblog
=> VACMS-15447: fixed php error in orphans report

config/sync/field.field.node.vamc_operating_status_and_alerts.field_office.yml
Currently when a user goes to [create a new VAMC System Operating Status](https://prod.cms.va.gov/node/add/vamc_operating_status_and_alerts), the VAMC system field defaults to VA Pittsburgh. This is a legacy configuration from VAMC pilot. This should default to none.
=> VACMS-000 Remove Pittsburgh VAMC as default value on VAMC operating status node

docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php
=> VACMS-15088: Removes the covid_url from payload

config/sync/views.view.content_model_fields.yml
closes #15529
As an admin (they are the only users who can see this)
1. [login to the site](https://pr15530-aajkwumdnteo2u1jgy3dgwvtkg5nv9hx.ci.cms.va.gov/)
2. Pull down the reports menu.
=> VACMS-15529 Remove duplicative field menu item.

composer.json, composer.lock, config/sync/core.extension.yml
closes #15595
As an admin
1. Go to [Enabled module report](https://pr15596-3i1296hk72rrrcue425hnlary2agoh8j.ci.cms.va.gov/admin/reports/system/enabled-modules) 
2. Then got to [User report](https://pr15596-3i1296hk72rrrcue425hnlary2agoh8j.ci.cms.va.gov/admin/reports/system/user-roles)
3. Then got to [Workflow diagram](https://pr15596-3i1296hk72rrrcue425hnlary2agoh8j.ci.cms.va.gov/admin/reports/system/workflow/content_moderation/editorial/all)
3. Then go to [Entity reference diagram](https://pr15596-3i1296hk72rrrcue425hnlary2agoh8j.ci.cms.va.gov/admin/reports/content-model/entity-diagram/node/faq_mul …
=> VACMS-15595 Bump content model documentation and config dependency

scripts/remove-git-dirs.sh
Closes #15619.
This won't affect anything else until it goes into the base preview.
=> VACMS-15619: Stop zapping vets-website .git dir.

tests/cypress/integration/features/content_type/event.feature
Relates to #15552 
We inadvertently removed some tests that should have stayed.
Local cypress test
n/a
n/a
=> VACMS-10089: Putting cypress event form conditional test back in

docroot/modules/custom/va_gov_build_trigger/src/Service/BuildRequester.php
=> VACMS-15629: Aligns va_gov_build_trigger and va_gov_content_release frontend version keys.

config/sync/core.entity_form_display.node.health_care_local_facility.default.yml, config/sync/core.entity_form_display.node.health_care_local_facility.inline_entity_form.yml, config/sync/core.entity_view_display.node.health_care_local_facility.default.yml, config/sync/core.entity_view_display.node.health_care_local_facility.external_content.yml, config/sync/core.entity_view_display.node.health_care_local_facility.ief_table.yml, config/sync/core.entity_view_display.node.health_care_local_facility.teaser.yml, config/sync/field.field.node.health_care_local_facility.field_mental_health_contact_phon.yml, config/sync/field.field.node.health_care_local_facility.field_mental_health_phone.yml, config/sync/field.field.node.health_care_local_facility.field_phone_number.yml, config/sync/field.storage.node.field_mental_health_contact_phon.yml, config/sync/migrate_plus.migration.va_node_health_care_local_facility.yml, docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility.yml
Relates to #15647
As `QA Content Editor`
1. Go to [edit a VAMC facility](https://pr15679-nx274uz2uav24soqj9f879jn7bgfsbp6.ci.cms.va.gov/node/2226/edit) 
2. Then enter a phone number for "Mental health contact phone number" and save the change as published.
3. odds and ends
=> VACMS-15647 Add new vamc mental health field.

docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityStatus.php
Relates to #14215
As `QA Content Publisher` 
1. Test push with no mental health phone Edit this https://pr15688-9qhcwttn1a2ppwra05saolrc3vvoczq4.ci.cms.va.gov/node/2181/edit
2. Change the status and publish the change
3. Test push with only API sourced mental health phone: edit this https://pr15688-9qhcwttn1a2ppwra05saolrc3vvoczq4.ci.cms.va.gov/node/2124/edit
4. change nothing and just publish the save.
5. Test push with mental health contact (editor sourced) mental health phone: edit the node and for Mental Health Contact phone number enter `555-444-1111`
6. Publish and save the node.
Is an …
=> VACMS-14215 VAMC mental health phone data push

tests/cypress/integration/features/content_type/full_width_banner_alert.feature
Relates to #15809
This is to unblock an automated test that is failing due to a content condition.  This is an immediate fix to get CI working again, but will need to have a round of improving this test so it can not collide with existing content.
1. Do this
2. Then
=> VACMS-15809 Temporary disable VAMC Banner test.

docroot/modules/custom/va_gov_backend/va_gov_backend.module
=> VACMS-15779: Set `rel="noopener"` in preview links.

config/sync/core.entity_view_display.node.health_care_local_facility.default.yml, config/sync/core.entity_view_display.node.health_care_local_facility.external_content.yml, config/sync/core.entity_view_display.node.nca_facility.default.yml, config/sync/core.entity_view_display.node.nca_facility.external_content.yml, config/sync/core.entity_view_display.node.vamc_system_billing_insurance.default.yml, config/sync/core.entity_view_display.node.vamc_system_billing_insurance.search_index.yml, config/sync/core.entity_view_display.node.vamc_system_billing_insurance.teaser.yml, config/sync/core.entity_view_display.node.vba_facility.default.yml, config/sync/core.entity_view_display.node.vba_facility.external_content.yml, config/sync/core.entity_view_display.node.vba_facility.ief_table.yml, config/sync/core.entity_view_display.node.vet_center.default.yml, config/sync/core.entity_view_display.node.vet_center.external_content.yml, config/sync/core.entity_view_display.node.vet_center.ief_table.yml, config/sync/core.entity_view_display.node.vet_center_cap.default.yml, config/sync/core.entity_view_display.node.vet_center_mobile_vet_center.default.yml, config/sync/core.entity_view_display.node.vet_center_mobile_vet_center.external_content.yml, config/sync/core.entity_view_display.node.vet_center_outstation.external_content.yml, config/sync/core.entity_view_display.paragraph.service_location.default.yml
Relates to #15702
As an admin
1. Flush the cache. (these messages often only appear on the first load of a page, why they appear after save).
2. Then visit the follow pages and validate that you see no notification about field office hours.
=> VACMS-15702 Fix view mode notifications

config/sync/content_model_documentation.settings.yml, docroot/modules/custom/va_gov_migrate/cm_documents/README.md, docroot/modules/custom/va_gov_migrate/cm_documents/adminzZzstructurezZzcm-documentzZzprocesszZz125zZzimporting-site-documentation.yml, docroot/modules/custom/va_gov_migrate/va_gov_migrate.install
Closes #15893
This PR includes both the initial setup for import and export, AND a sample Content Model Document import  about Import / Export (inception much?).
See my comment.
As an admin
1. Go to where the [newly imported doc should be](https://pr15894-ecrdwq9diwefb6d0awbeaa9qe71uz8h1.ci.cms.va.gov//admin/structure/cm_document/process/125/importing-site-documentation)
2. Click on the revisions tab
3. Go to the [recent log messages](https://pr15894-ecrdwq9diwefb6d0awbeaa9qe71uz8h1.ci.cms.va.gov/admin/reports/dblog?type%5B%5D=cm_document) 
Is an announcement needed to let editors know of this …
=> VACMS-15893 Add setup for CM Document export/import.

tests/scripts/ci-wrapper.sh
Closes #15774.
```
+ pushd /var/lib/tugboat
+ : 0
+ set -o allexport
+ set +x
+ set +o allexport
+ test_name=status-error
```
=> VACMS-15774: Stop exposing environment variables in Tugboat build logs.

config/sync/views.view.vet_center_facility_listing.yml
Relates to #15724
Before on left, after on right
This ticket has a UX review AC on it but I am not sure of the scope.  It changes nothing of the layout or appearance, it simply removes archived facilities from showing in the "Satellite locations" list.  Almost anything that is identified is going to be out of scope for this ticket.  Anything found should be turned into new issues.
As jeffrey.deluca@va.gov
1. Go to [your dashboard](https://pr15884-xoxmgnwurmt24ho3fxdfpbqmphqvpcvh.ci.cms.va.gov/section/vha/vet-centers/scranton-vet-center)
This ticket has a A11y review AC on it but I am not sure of the scope.  It changes nothing of the structure, layout or appearance, it simply removes archived facilities from showing in the "Satellite locations" list.  Almost anything that is identified is …
=> VACMS-15724 Remove archived VC CAPS from VC dashboard.

config/sync/easy_breadcrumb.settings.yml
Closes #15842.
Visited various nodes as an admin and poked around sub-tabs (edit, revisions, etc) and noticed that breadcrumbs were no longer visually duplicated. The node view and edit tabs do render different breadcrumbs at the top of the page, because the routes are different (`/actual/path/to/content` vs `/node/{nid}/edit`. The breadcrumbs seen on the node view page are the correct breadcrumbs for the purpose of checking FE.
I built the web environment on this tugboat to ensure that no unexpected changes happen there either (this should be a cms-only change).
You may see erroneous breadcrumbs printing in the node view when checking certain routes! This is fixed separately in: #15858.
Example Node View tab:
Example Node Edit tab:
Links to example pages from each affected content type. …
=> update easy_breadcrumb settings to remove dupe crumb on cms pages

tests/cypress/integration/features/content_type/vamc_operating_status_and_alerts.feature, tests/cypress/integration/step_definitions/common/should_exist.js, tests/cypress/support/commands.js
=> VACMS-15903: Wait for alert type dropdown to appear.

config/sync/views.view.custom_block_entity_browsers.yml, config/sync/views.view.va_blocks_admin.yml
Closes #15721.
Tested localy. Description field now displayed as first column on both the /admin/content/alerts page in the in the entity browser for adding alerts. 
1. Navigate to /admin/content/alerts
2. Then add a Benefits Details page, scroll down to the Include Alert section and click Place Alert
=> VACMS-15721: added description field for alert blocks view and browser

docroot/modules/custom/va_gov_events/src/EventSubscriber/EntityEventSubscriber.php
Relates to #13529
Somewhere wires got crossed between Facilities PO discussion with VHA DM, list of users that was provided to Public Websites, and list of Editors that VHA DM notified to try the new feature. This diff represents users who were notified by VHA DM, but not in our list, so do not currently have access to the feature. Adding them so they do and can test.
=> Add new Editors to beta per VHA DM

config/sync/core.entity_form_display.media.document.default.yml
Close #15979.
Tested locally. 
1.  Navigate to /media/add/document
=> VACMS-15979: fix for reusable documents

config/sync/feature_toggle.features.yml, docroot/modules/custom/va_gov_events/src/EventSubscriber/EntityEventSubscriber.php, tests/cypress/integration/features/content_type/event.feature
Relates to #15747
Manually tested with various user accounts and feature toggle states. Updated cypress test suite for events.
1. Visit the [feature toggle page](https://cms-d1o5mk1v7bc9puuz5ijun6eq7w7j52da.ci.cms.va.gov/admin/config/system/feature_toggle), and ensure that the `FEATURE_EVENT_OUTREACH_CHECKBOX_ALL` is OFF and the `FEATURE_EVENT_OUTREACH_CHECKBOX` is ON (this is the state we will launch in production).
2. Visit the [create Event node](https://cms-d1o5mk1v7bc9puuz5ijun6eq7w7j52da.ci.cms.va.gov/node/add/event) page
3. Fill out the event, ensuring to check the checkbox
4. Save the event
As an Outreach Hub user (eg: triana.poindexter@va.gov)
5. Visit the [create Event node](https://cms-d1o5mk1v7bc9puuz5ijun6eq7w7j52da.ci.cms.va.gov/node/add/event) page
7. …
=> VACMS-15747 Feature toggle to launch nat outreach checkbox for all

config/sync/views.view.user_admin_people.yml
=> VACMS-15984: Remove duplicates from people list.

config/sync/field.field.node.service_region.field_service_location.yml
Relates to #15995
Manually
As an admin, create a [Service Region](https://pr15997-o8bugnlzbpvnl0zgtvniulcc1nnbbsxa.ci.cms.va.gov/node/add/service_region)
Edit the Service Region just created, adding another Service Location
As an admin, create an [entity relationship diagram](https://pr15997-o8bugnlzbpvnl0zgtvniulcc1nnbbsxa.ci.cms.va.gov/admin/reports/content-model/entity-diagram/node/service_region?max_depth=1) for Service Region
=> VACMS-15995: Adds reference to Service location in Service Region.

config/sync/views.view.rich_text_field_audit.yml
Relates to #14214  (or closes?)
As an admin
1. Go to the [phone number audit](https://pr15928-e93u7hz48uyxgxgy1kgz3h0v4wpqdiji.ci.cms.va.gov/admin/content/audit/phone-numbers) 
=> VACMS-14214 Add editable mental health number to phone audit.

config/sync/views.view.content.yml
Relates to #15891 
Addresses feedback in [previous PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15896) that was saved for later.
local
Used style-guide here:
https://prod.cms.va.gov/admin/structure/cm_document/note/124/views-style-guide
As a developer logged in as administrator, go to https://cms-kames06eozeafsydwadkbl4dlywf6edv.ci.cms.va.gov/admin/content/audit/qa
=> VACMS-15891: Fine tuning some things for Q&A Audit View

config/sync/views.view.content.yml, config/sync/views.view.facility_services.yml, config/sync/views.view.metatag_audit.yml, config/sync/views.view.rich_text_field_audit.yml, config/sync/views.view.search.yml, config/sync/views.view.tables.yml
This is a quick follow up to #15891 to address the order of menu tabs (menu local tasks) for content audit Views.
Because the menu tab order is defined using weights, and the weights of existing Views didn't allow for placing the new 'Page-specific Q&A' View alphabetically, several Views had to be updated.
Relates to #15891
Manual.
Before:
After:
1. Visit /admin/content/audit/qa
=> VACMS-15891: Assign weights to content audit views' menu local tasks so tabs appear alphabetically

phpstan-baseline.neon
Closes https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15953. We are choosing to ignore existing phpstan errors so only new errors will fail the `va:test:phpstan` check. This ensures local testing matches the CI behaviour.
Tested locally using the phpstan composer script, i.e. running `composer run-script va:test:phpstan`. No more errors are observed.
Before:
After:
As user with access to this repository
1. Run the command `composer run-script va:test:phpstan` locally
=> VACMS-15953 Regenerate phpstan baselines

docroot/modules/custom/va_gov_content_release/src/Controller/FrontendVersionAutocompleteController.php
=> VACMS-16132: Fix content release on D10.

hooks/git/pre-commit
Closes #16134.
Will require reinstalling pre-commit hook to show an effect.
=> VACMS-16134: Accepts branch names starting with just an issue number.

config/sync/core.entity_form_display.node.vba_facility.default.yml, config/sync/core.entity_view_display.node.vba_facility.default.yml, config/sync/core.entity_view_display.node.vba_facility.external_content.yml, config/sync/core.entity_view_display.node.vba_facility.ief_table.yml, config/sync/core.entity_view_display.node.vba_facility.teaser.yml, config/sync/field.field.node.vba_facility.field_prepare_for_visit.yml
=> VACMS-15977: Adds accordion to VBA Facility Prepare for your visit

composer.json, docroot/modules/custom/va_gov_media/va_gov_media.info.yml, tests/cypress/integration/features/platform/alt_text_validation.feature, tests/cypress/integration/step_definitions/common/i_create_an_image_with_alt_text.js, tests/cypress/integration/step_definitions/common/i_save_an_image_with_alt_text.js, tests/cypress/support/commands.js
=> VACMS-15783: Alt-Text Validation Testing

composer.json
Closes #16198 
Tested locally by running `composer run-script va:phpcbf`
Testing the added command on a subdirectory containing phpcs errors shows that the errors have been fixed:
Note that the error code of phpcbf is returned as 1 even if all errors are fixed: https://github.com/squizlabs/PHP_CodeSniffer/issues/3057. We can choose to ignore this error code but since this script is expected to run locally, I don't think this is necessary.
As user with access to this directory
1. Introduce a phpcs error such as unsorted usings.
- e.g. edit usings of `docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/PreventAbsoluteUrlsAsPathsInLinksValidator.php` to:
```
use Drupal\Component\Utility\Html;
use Symfony\Component\Validator\ConstraintValidator;
use …
```
=> Add command for running PHP Code Beautifier and Fixer (phpcbf)

docroot/themes/custom/vagovclaro/templates/page/page--node.html.twig
Updates node templates to untangle the column order.
Closes #10119.
Performed manual tests in local dev and Q/A environments to assert proper focus order.
https://github.com/department-of-veterans-affairs/va.gov-cms/assets/607178/f57ff8fd-251a-4de6-b8c9-ad3ea88f0312
One can verify by reviewing a VAMC Detail Page (e.g. - https://pr16225-ck8wkzmz2uol9ecn1hd28n5epfarh9x0.ci.cms.va.gov/san-diego-health-care/programs/resources)
Pressing `Tab` repeatedly should cycle through tabs, then breadcrumbs, before cycling focus on content through left, middle, and right columns.
=> VACMS-10119: Updates Column Order on Node Pages

composer.json, composer.lock
Relates to #16232
Removes [legacy d.o. patch #2975602](https://drupal.org/project/drupal/issues/2975602)
Manual testing asserting the double spacing issue is no longer present.
This includes:
- Reviewing previous entries where this issue was known to be present.
- Creating new records and verifying that double spacing doesn't occur.
There's no longer any double spacing in the address area of [the page noted in the original issue](https://pr16266-ddxmaen8oegyetikx6pjima6ad89zkfe.ci.cms.va.gov/resources/how-do-i-notify-va-of-my-intent-to-file)
Created a test Event using the following as its description:
Renders w/o double spacing:
=> VACMS-16232: Removes Legacy Patch Causing Double Spacing

docroot/modules/custom/va_gov_backend/va_gov_backend.module, tests/cypress/integration/features/content_type/q_a.feature, tests/cypress/integration/step_definitions/common/i_create_a_node.js
Relates to #16108
Cypress and manual testing.
As user a content admin
1. Visit /node/add/q_a
2. Fill out the required fields only and save the node
3. Visit /node/add/q_a
4. Select the 'Enable standalone Resources and support page for this Q&A.' checkbox.
=> VACMS-16108: Resolves cannot create reussable qa nodes

config/sync/views.view.facilities_by_system.yml, config/sync/views.view.vamc_facilities_by_system.yml
Relates to #16015
Manually
As an admin
In a private window, go to the export file https://pr16281-oyigwrdbfv3nltbfzwshxbs9nmexjdep.ci.cms.va.gov/admin/content/exports/vamc-facilities-csv
=> VACMS-16015: Adds export view for VAMC facilities

composer.json, composer.lock, config/sync/core.extension.yml, docroot/modules/custom/va_gov_vamc/va_gov_vamc.deploy.php, docroot/modules/custom/va_gov_vamc/va_gov_vamc.install
Relates to #15715 
As an admin
1. Go to the [content View filtered for VA Police](https://pr16277-0bcrespkm9ddsa3mevjqzbx6veutwfql.ci.cms.va.gov/admin/content?title=&type=vamc_system_va_police&moderation_state=All&owner=All) 
2. Click on 5 VA Police pages
=> VACMS-15715 Create and publish VA police pages.

config/sync/prometheus_exporter.settings.yml
=> VACMS-7673: Export node count by content type via prometheus_exporter.

config/sync/image.style.1_1_square_large.yml
Adds a manually cropped, 1:1 image scaled to 500x500.
Relates to #16242
As a content admine
1. Visit /sites/default/files/styles/1_1_square_large/public/2023-07/patient-nurse-hands.png
=> VACMS-16242: Adds large square manually cropped image derivative.

config/sync/core.entity_view_display.taxonomy_term.health_care_service_taxonomy.default.yml
Relates to #16378. (or closes?)
Tugboat verification
Tugboat evidence 
As [tanekwa.bournes@va.gov](mailto:tanekwa.bournes@va.gov)
1. Do this
2. Then
As an admin [christian.burk@va.gov](mailto:christian.burk@va.gov)
1. Do this
2. Then
=> VACMS-16378: Remove content moderation widget from Term View on VA Services Taxonomy

docroot/modules/custom/va_gov_content_types/src/EventSubscriber/EntityBundleCreateEventSubscriber.php, docroot/modules/custom/va_gov_content_types/va_gov_content_types.services.yml, tests/phpunit/va_gov_content_types/functional/EventSubscriber/EntityBundleCreateEventSubscriberTest.php
=> VACMS-7673: Enable metrics collection on new content types when they are created.

config/sync/views.view.facility_services.yml
Relates to #16152 
Manually
As an admin, go to the [Facility services audit view](https://pr16326-v8g5rfw6du6cz0aeonnwskqcxggvojwy.ci.cms.va.gov/admin/content/audit/facility-services)
=> VACMS-16152: Adds new view and export

config/sync/field.field.node.vet_center_outstation.field_official_name.yml
Relates to #16322 
As any user 
1. Go to [a Vet Center Outstation](https://pr16482-b62wvnvjfnjt4fhc1kqi6v4vtzwjwl9g.ci.cms.va.gov/san-juan-vet-center/st-thomas-vet-center-outstation) 
=> VACMS-16322 Fix VC Outstation typo

config/sync/metatag.metatag_defaults.node__vamc_system_va_police.yml
Relates to #16411
As any user
1. Go to [a VA Police page](https://pr16480-geqkb8snbot5m5f7z27j2rnr9pnn54xq.ci.cms.va.gov/tampa-health-care/va-police) and view the page source in the ```<head>```
=> VACMS-16411 Add metatag setup for VA Police.

config/sync/jsonapi_extras.jsonapi_resource_config.node--event.yml, config/sync/jsonapi_extras.jsonapi_resource_config.node--event_listing.yml, config/sync/jsonapi_extras.jsonapi_resource_config.node--news_story.yml, config/sync/jsonapi_extras.jsonapi_resource_config.node--person_profile.yml, config/sync/jsonapi_extras.jsonapi_resource_config.node--story_listing.yml, tests/phpunit/API/JsonApiRequestTest.php
Relates to work in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16382 . Just need to add a field back to the JSON:API response so it can be used on the frontend.
Modified and ran PHPUnit test in `tests/phpunit/API/JsonApiRequestTest.php`. Manually tested using QA steps.
1. Use these paths for testing '/jsonapi/node/event', '/jsonapi/node/event_listing', '/jsonapi/node/news_story', '/jsonapi/node/person_profile', '/jsonapi/node/story_listing'
2. Log into the CMS as a user who can access JSON:API resources. "content_api_consumer" is a role with those permissions. 
3. Load each resource collection listed above and make sure `field_last_saved_by_an_editor` is included in the response.
4. Navigate to an individual item in each collection and make sure …
=> Add field_last_saved_by_an_editor back to JSON:API responses

docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php
Relates to #7563
As an admin
1. Go to a Vet Center locations list page /node/28186/edit
=> VACMS-7563 Change 80 mile radius to 120 in help text.

.github/workflows/tugboat-refresh-cache-dispatch.yml, .github/workflows/tugboat-refresh-cache-responder.yml
Resolves #16561
Tested in va.gov-cms-test using https://github.com/department-of-veterans-affairs/va.gov-cms-test/pull/1469. The last two triggered refreshes were successful. Note the name of the workflow job was updated to clarify functionality.
TBD
- The cache refresh workflow is tested in this PR. The cron trigger update won't take effect until merged to main.
=> Refresh Tugboat Preview ID cache from PR cache scope

config/sync/migrate_plus.migration.va_node_facility_nca.yml, config/sync/migrate_plus.migration.va_node_facility_vba.yml, config/sync/migrate_plus.migration.va_node_facility_vet_centers.yml, config/sync/migrate_plus.migration.va_node_facility_vet_centers_mvc.yml, config/sync/migrate_plus.migration.va_node_facility_vet_centers_os.yml, config/sync/migrate_plus.migration.va_node_health_care_local_facility.yml, docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_nca.yml, docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vba.yml, docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers.yml, docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers_mvc.yml, docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers_os.yml, docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility.yml
Relates to #14238
As an admin
1. Vet Center Outstation - > go to [phone audit](https://pr16500-3l2tvkc7pb0fnsv9iz7hwupxdlici1up.ci.cms.va.gov/admin/content/audit/phone-numbers?title=&type=vet_center_outstation&moderation_state=All&workbench_access_section__section=All&phone=)
2. Vet Center Mobile -go to [phone audit](https://pr16500-3l2tvkc7pb0fnsv9iz7hwupxdlici1up.ci.cms.va.gov/admin/content/audit/phone-numbers?title=&type=vet_center_mobile_vet_center&moderation_state=All&workbench_access_section__section=All&phone=)
3. VBA go to [phone audit](https://pr16500-3l2tvkc7pb0fnsv9iz7hwupxdlici1up.ci.cms …
=> VACMS-14238 Improve parsing of Facility phone numbers in facility migrations

.tugboat/config.yml
Closes #16642.
https://tugboat.vfs.va.gov/6595b708ad79a291083265b6
Drush commands ran successfully. (See logs)
=> VACMS-16642 Remove Drush launcher in preparation for upgrade to drush 12

config/local/simplesamlphp_auth.settings.yml, config/prod/simplesamlphp_auth.settings.yml, config/stg/simplesamlphp_auth.settings.yml, config/tugboat/simplesamlphp_auth.settings.yml
Closes #16543.
Tested on test.prod with my account and Erika Washburns assistance. Confirmed turning this off prevents someone from logging in unless an account has already been created for them. 
Should be good as long as automated testing passes.
=> VACMS-16543: turn off Create for simplesamlphp_auth, prevent ghost accounts

docroot/modules/custom/va_gov_backend/va_gov_backend.module, tests/cypress/integration/features/content_type/vba_facility_service.feature
Relates to #15901
Relates to #15391
Relates to #7538
Relates to #12737
Relates to #15906
Manually
Cypress
Testing Google spreadsheet:
https://docs.google.com/spreadsheets/d/17WXvo_QAPvB02Xlm0_np1uQWy83u3dbfJnRxAQdG_h0/edit#gid=0
=> VACMS-15901: Removes facilities not in user sections

scripts/web-build.sh
See #16237.
This does not fix all of the problem, but I think this fixes the immediate problem. There's a deeper, more significant issue with `vets-website` and `content-build`, I think, that will require considerable more effort (and greater risk) to fix.
- ![Screenshot 2024-01-09 at 5 12 03 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/1318579/dc368ae4-20e7-49be-a22a-fddb48a60438)
=> VACMS-16237: Replace s3 address for assets.

docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/RequiredParagraphAB.php, docroot/modules/custom/va_gov_backend/src/Plugin/Validation/Constraint/RequiredParagraphABValidator.php, docroot/modules/custom/va_gov_backend/va_gov_backend.module, docroot/modules/custom/va_gov_clp/src/EventSubscriber/EntityEventSubscriber.php, docroot/modules/custom/va_gov_clp/va_gov_clp.services.yml, tests/cypress/integration/features/content_type/campaign_landing_page/clp_faq.feature, tests/cypress/integration/step_definitions/common/i_enable_the_segment.js
Relates to #16575 .
As a user with content_admin role
1. Create a new CLP page filling in all of the required fields.
2. Expand the _FAQs_ section and click to _Enable this page segment_
3. Click to _Add Page-Specific Q&A_ and fill out the required fields (Question/Answer).
4. Click to _Add Reusable Q&A Group_, then expand the _Q&As_ section within.
5. Click to _Add Reusable Q&As_
6. Check 10 items in the modal and click to _Select Q&As_
7. Fill in a Revision log message and hit _Save_
8. Remove the Reusable Q&A group by clicking the 3 dot dropdown and selecting _Remove_.
9. Remove the Page-Specific Q&A group by clicking the 3 dot dropdown and selecting _Remove_.
10. Expand the FAQs section and uncheck _Enable this page segment_.
Is an announcement needed to let editors know of this …
=> VACMS-16575: Add extra validation to allow for combination of reusable and single page QAs.

docroot/modules/custom/va_gov_media/src/EventSubscriber/MediaEventSubscriber.php
Relates to #16827
This is the field screenshot (an image field) on a content model document not throwing a white screen error.   
Here is the validation working as intended 
As as an admin
1. Go to https://pr16832-znatffbqk2zl4bpmw6zutmhlayqwav47.ci.cms.va.gov/admin/structure/cm_document/5/edit
2. Go to [edit a benefit detail page](https://pr16832-znatffbqk2zl4bpmw6zutmhlayqwav47.ci.cms.va.gov/node/3011/edit)
3. in the "Main content" field click the "Add content block" button and and choose a "Embedded image" content paragraph.
4. Add an image.  
5. Navigate to [edit an existing Media …
=> VACMS-16827 Fix loading of alt text field definitions.

config/sync/field.field.node.vba_facility.field_banner_types_description.yml
Relates to #16858
As an admin
1. Edit a [VBA facility](https://pr16860-aevvngzthhwkyq4ikzisocrjtpx5808b.ci.cms.va.gov/node/3952/edit) 
2. Scroll down the banner section and check the box to add the banner.
=> VACMS-16858 Fix VBA banner typo.

docroot/modules/custom/va_gov_backend/va_gov_backend.module
Relates to #14623
Manually
As an admin, edit a node that currently has no alias. Such as https://pr16820-fgcq7ewvt3kjxag3eaygv788krkxuroi.ci.cms.va.gov/node/64553
=> VACMS-14623: Staff profile has no alias on publish

config/sync/views.view.user_admin_people.yml
Closes #16449.
1. Navigate to /admin/people and click Download CSV
2. Then click Download CSV of sll Users
=> VACMS_16449: updated date formats

docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php
Closes #16959.
1. Log in as victor.a.mctest
2. Go to /node/6228/edit
3. Click on Parent Link drop down
4. Try to save as published
=> VAMC-16959: editors can't save detail pages under Work with us

docroot/modules/custom/va_gov_media/va_gov_media.module, docroot/modules/custom/va_gov_menu_access/src/Service/MenuReductionService.php, docroot/modules/custom/va_gov_menu_access/va_gov_menu_access.module
Relates to #17018 (or closes?)
As user RS (VAMC Content creator and content publisher in one VAMC health system section)
1. Go to https://pr16994-ksy8sixki8oyk0owsscsp9ijgfxn7pfi.ci.cms.va.gov/node/5579/edit
2. Test creating new Go to https://pr16994-ksy8sixki8oyk0owsscsp9ijgfxn7pfi.ci.cms.va.gov/node/add/health_care_region_detail_page
3. Edit the page you just created and set the menu parent to "Select a value".
=> VACMS-17018 Resolve VAMC menu assignment issues.

composer.json, composer.lock
Relates to #16726. 
1. Browse to the extensions page (/admin/modules)
=> VACMS-16726: Remove block_content_permissions from composer.

config/sync/views.view.service_locations_audit.yml
=> VACMS-16451: Audit view service location

.github/ISSUE_TEMPLATE/taxonomy-update-term.yml
Relates to this [Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1704910454485849) 
As user facilities team member
=> [DOCS] Add steps for fixing aliases and names in the CMS for term changes

config/sync/core.entity_form_display.node.nca_facility.default.yml, config/sync/core.entity_form_display.node.vba_facility.default.yml, config/sync/core.entity_form_display.node.vet_center.default.yml, config/sync/core.entity_form_display.node.vet_center_cap.default.yml, config/sync/core.entity_form_display.node.vet_center_outstation.default.yml, config/sync/field.field.node.vet_center_outstation.field_operating_status_facility.yml
Relates to #16469
Manually
_Note: The steps include a full test of editing a NCA as as admin and adding and editing a VBA Facility as an editor. The other tests are lighter confirmations but should suffice, given that it is the same field on all tested content types._
As an admin, do the following:
As QA Content Publisher, do the following:
As QA Content Publisher, do the following:
As QA Content Publisher, do the following:
=> VACMS-16469: Updates widget to radio buttons

config/sync/core.entity_form_display.node.health_care_local_health_service.default.yml, config/sync/core.entity_view_display.node.health_care_local_health_service.default.yml, config/sync/core.entity_view_display.node.vba_facility_service.default.yml, config/sync/core.entity_view_display.node.vha_facility_nonclinical_service.default.yml, config/sync/core.entity_view_display.paragraph.service_location.default.yml, tests/cypress/integration/features/content_type/facilities/vamc/health_care_local_health_service.feature
Relates to #17142
Manual
As a user with administrative access
1. Go to add a VAMC Facility Health Service node (/node/add/health_care_local_health_service) and verify the following fields are not visible:
2. Edit a Service Region page (i.e. /node/61786/edit)
4. Edit a VAMC Facility Health Service page
5. Edit a VAMC Facility Non-clinical Service page
6. Edit a VBA Facility Health Service page
=> VACMS-17142: Update service content types post-Service Location migration

scripts/content/VACMS-16233-reorder-vamc-menu-items.php, scripts/content/script-library.php
Relates to #16233
This makes it possible to resume the menu altering script from any given point if the script dies like it did the [first two attempts to run it on prod.](https://dsva.slack.com/archives/CT4GZBM8F/p1707842079725229?thread_ts=1707759434.620499&cid=CT4GZBM8F) 
This creates the ability for the execution of batched scripts to keep state using the Drupal State API  to keep track of the last successfully completed  batch and pick up where it left off on subsequent runs.
On prod the script ran out of memory processing  run number 118.   It is most likely that 118 ran successfully and it was actually 119 that failed, but to be safe, we will run it from 117 on by doing the following
- Set the last run state  to 117 with
`ddev drush state:set …
=> VACMS-16233 make script batches pick up where they left off

docroot/modules/custom/va_gov_vamc/src/ServiceLocationMigration.php, scripts/content/VACMS-15559-migrate-service-location-from-node-to-paragraph.php
Relates to #17241
This can not be merged into integration until #17236 is merged to main AND #15622 is then rebased on main.
IN the terminal
1. run `ddev drush scr ./scripts/content/VACMS-15559-migrate-service-location-from-node-to-paragraph.php`
2. Use Ctrl-C to halt the script.
3. Make note of the last reported item to run.
5. run the script again
=> VACMS-17241 Rework service location script for keeping state and reporting

READMES/devops/tugboat.md
=> Update tugboat.md with steps to restart proxy

docroot/modules/custom/va_gov_vamc/src/EventSubscriber/VAMCEntityEventSubscriber.php, docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php, tests/cypress/integration/features/content_type/facilities/vamc/health_care_local_health_service.feature, tests/cypress/integration/features/content_type/facilities/vet_center/vet_center_facility_service.feature
Relates to #14136.
Cypress tests created as well as manual testing
As user `QA Content Editor`
1. Edit a VAMC Facility Health Service node (e.g. 'Pharmacy - Orlando VA Medical Center' /node/22635/edit)
1. Edit a VAMC Facility Health Service node (you can use the same example as above)
2. Edit a Vet Center - Facility Service node (e.g. Jackson Vet Center - Workshops and classes' /node/44823/edit)
=> VACMS-14136: Editors should not be able to rename VAMC facility services.

docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityServiceVamc.php
Relates to #17114
Manually
Make sure it has three service locations with the following values:
```
"payload": {
"detailed_services": [
{
"appointment_leadin": = "<Your custom text>",
"appointment_phones": [
{
[<An array of phone numbers entered plus the main facility phone>]
}
]
"walk_ins_accepted": "yes_with_or_without_appointment"
"online_scheduling_available": "true"
}
]
}
```
**Note: You could do many other runs of this test to confirm that each of the intended "tip of the outlying option" is present in the service-level output. I calculate that there are 48 combinations.**
Other options worth trying:
=> VACMS-17114: Service location fields lighthouse push

docroot/modules/custom/va_gov_vamc/css/set_vamc_system_health_service.css, docroot/modules/custom/va_gov_vamc/src/EventSubscriber/VAMCEntityEventSubscriber.php, docroot/modules/custom/va_gov_vamc/va_gov_vamc.libraries.yml
=> VACMS-13214: Alphabetize all services and identify archived and draft services

config/sync/core.entity_view_display.node.vamc_system_billing_insurance.default.yml, config/sync/core.entity_view_display.node.vamc_system_billing_insurance.search_index.yml, config/sync/views.view.non_clinical_services.yml
@omahane There were a few additional spots where I specified `show_empty: true`. I was originally gonna leave a comment on your PR, but it was faster to just collect my recommendations in their own branch.
On VAMC System and Billing and Insurance pages there is an Office Hours widget that also needs the config to show if empty:
Similarly, the Views for Non-Clinical Services appearing on the 3 different top taps pages should also show hours if all empty
=> Adding in VAMC Top Task pages

docroot/modules/custom/va_gov_backend/js/service_location_hours.es6.js, docroot/modules/custom/va_gov_backend/js/service_location_hours.js
Relates to #17501
Manually
_Note: The facility hours are not being pulled in on VBA, even after saving the node and editing it once more. I'll capture that need in a separate ticket._
=> VACMS-17501: Shows and hides hours appropriately

config/sync/core.entity_view_display.node.health_care_local_health_service.system_services_listings.yml, config/sync/core.entity_view_display.node.regional_health_care_service_des.default.yml, config/sync/core.entity_view_mode.node.system_services_listings.yml
Relates to #12666 .
Manual
<details>
<summary>Screenshot after duplicates are removed</summary>
</details>
1. Browse to a System Health Service page (i.e. /montana-health-care/health-services/radiology-at-va-montana-health-care)
2. Browse  to a Facility Health Service page (i.e. /montana-health-care/locations/dr-joseph-medicine-crow-va-clinic/radiology)
=> VACMS-12666: Removes duplicate sections on system health service pages.

config/sync/pathauto.pattern.vba_facility.yml, config/sync/pathauto.pattern.vba_facility_nca_facility_veterans_center.yml
=> VACMS-15155: Updates the naming schema for VBA, splits with NCA

docroot/modules/custom/va_gov_events/js/eventFormHelpers.es6.js, docroot/modules/custom/va_gov_events/js/eventFormHelpers.js, tests/cypress/integration/features/content_type/event.feature
Forces an Event with a Facility location type to also specify the Facility location.
Relates to #17426
Manual and cypress
1. Visit node/add/event
2. Set the 'Location type' to "At a VA facility"
=> VACMS-17426: Requires VA facility location when the event is using a VA facility location type

config/sync/field.storage.node.field_clp_reusable_q_a.yml
Relates to #17805
Verified no reusable Q&As exist in prod
Manually verified diff of graphql query
1. Edit any [Campaign Landing Page](https://pr17980-fpxmuwqeehnn6ubwaqfgg0jdbsuhzu4b.ci.cms.va.gov/admin/content?title=&type=campaign_landing_page&moderation_state=published&owner=All)
2. Under the FAQs section, add a Reusable Q&A Group (header and introduction are optional)
3. Add 3 Q&As to this group
=> VACMS-17805: Change cardinality of reusable Q&A on CLP to 1.

.github/workflows/default-branch-datadog-metrics.yml, composer.lock
Fixes PR change suggestions for the Service Location MVP integration branch. This PR reverts unwanted changes in composer.lock and .github/workflows/default-branch-datadog-metrics.yml.
Relates to #14683
Relates to integration branch PR [15622](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15622)
1. Do this
2. Then
=> VACMS-14683: Integration Service Location PR Comment Fixes

config/sync/field.storage.paragraph.field_other_phone_numbers.yml
=> VACMS-18112: Changes cardinality of Service location appt phone #s

config/sync/core.entity_form_display.node.va_form.default.yml, config/sync/core.entity_view_display.node.va_form.default.yml, config/sync/core.entity_view_display.node.va_form.external_content.yml, config/sync/core.entity_view_display.node.va_form.teaser.yml, config/sync/field.field.node.va_form.field_va_form_upload.yml, config/sync/field.storage.node.field_va_form_upload.yml
Relates to #17962
Tested that field exists on VA Form
As a Content Admin
1. Visit node/add/va_form
=> VACMS-17962: Adds the form upload field to VA Forms.

docroot/modules/custom/va_gov_vamc/va_gov_vamc.module
Relates to #17515 
Locally and in Tugboat
=> VACMS-17515: Adds condition for new nonclinical service

.ddev/mutagen/mutagen.yml, docroot/sites/default/settings.php, docroot/sites/default/settings/settings.local.php, docroot/sites/default/settings/settings.prod.php, docroot/sites/default/settings/settings.staging.php, docroot/sites/default/settings/settings.tugboat.php
This work will check for a response header (File-Public-Base-Url-Check) to be present. If it is, it will set the file-base-url for assets to point to the appropriate s3 bucket. If not, it will use webhost variable. This work will initially not have any effect. Once the header has been set in next-build, we should see the assets' paths being directed to the s3 buckets.
Relates to #_18070_. (or closes?)
Setting variable to both pass and fail to check results in the settings files.
This is an image of a media asset pulling from the staging s3 bucket because the logic passed:
This is the same media asset with the check failing and it pulling from webhost variable:
We need to first set the response header in next-build to the …
=> VACMS-18070: Adding a check for response header for files to pull from s3 buckets.

docroot/modules/custom/va_gov_media/src/EventSubscriber/VaGovMediaAddRouteSubscriber.php
Closes #18244 
As Stephen.Westerfield@va.gov
1. Log in and 
2. Then
=> VACMS-18244: comment out access chagnes for add media forms

docroot/modules/custom/va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php, tests/cypress/integration/features/content_type/facilities/vet_center/vet_center_facility_service.feature
Relates to #17676 
Manually and with Cypress
Edit as an admin
=> VACMS-17676: prevent removal required services

docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityServiceBase.php
Relates to #18178
Manually and with Lighthouse
N/A
=> VACMS-18178: Removed Mental Health from services to withhold

composer.json, composer.lock
Relates to #18404
1. Do this
2. Then
=> VACMS-18404: Updates content-build version

config/sync/core.entity_form_display.node.vba_facility.default.yml, config/sync/field.field.node.vba_facility_service.field_administration.yml, config/sync/field.field.node.vba_facility_service.field_office.yml, docroot/modules/custom/va_gov_vba_facility/src/EventSubscriber/VbaFacilitySubscriber.php
=> VACMS-17885: Create facility services links on VBA Facility page

composer.json, composer.lock
This ticket is to update form Drupal Diff 1.1 to 1.7. The Dependabot ticket was not working due to other module upgrades so this ticket was created for the upgrade. Two drupal/diff patches were also updated.
Verify that Drupal Diff was upgraded to 1.7 and all tests have passed.
=> VACMS-18306: Upgraded Drupal diff and fixed two patches.

config/sync/eca.eca.aging_content_expired_fwb.yml, config/sync/eca.eca.aging_content_warn_fwb.yml, docroot/modules/custom/va_gov_notifications/src/JobTypeMessageNotifyBase.php, tests/phpunit/va_gov_notifications/functional/AgingContentFullWidthBannerTest.php, tests/phpunit/va_gov_notifications/kernel/JobTypeMessageNotifyBaseTest.php
Relates to #18311
Adds both a comprehensive whitelist (allow_delivery_only_to) , and a blacklist (restrict_delivery_to), to recipient delivery access checks in Aging Content's custom message delivery Job Type. The lists accept any number of user id's for which to restrict/allow.
Tested using a combination of white and blacklisted users.
As a administrator
1. Visit /admin/config/workflow/eca/aging_content_expired_fwb/edit
2. Under 'Workflow options', check the 'Enabled' checkbox, and save the form
3. Visit /admin/config/workflow/eca/aging_content_expired_fwb/action/create_advancedqueue_job/edit
4. …
=> VACMS-18311: Limit Aging Content Email to Specific Users

config/sync/core.entity_form_display.paragraph.phone_number.default.yml, config/sync/field.field.paragraph.phone_number.field_phone_extension.yml, config/sync/field.field.paragraph.phone_number.field_phone_label.yml, config/sync/field.field.paragraph.phone_number.field_phone_number.yml, config/sync/field.field.paragraph.phone_number.field_phone_number_type.yml
Relates to #18281 & #15803
Using the [entity relationship diagram](https://pr18542-bqc641quszrp87hs4gatpmdax0eaaubv.ci.cms.va.gov/admin/reports/content-model/entity-diagram/paragraph/phone_number?max_depth=1), I identified 4 different Drupal entities that currently use the Phone Paragraph type
- VAMC System VA police Page -> Tested directly
- Service Location paragraph -> Tested via VAMC Facility Health Service
- Contact Information paragraph -> Tested via Resources and Support Detail Page
- VAMC Facility Health Service node -> (A legacy field which is hidden in the UI, [but hasn't been deleted yet](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17137))
<details><summary>Character counts updates without help text changes</summary>
</details>
<details><summary>  Help …
=> VACMS-18281 Added character counters & help text to phone paragraph type

config/sync/core.base_field_override.node.digital_form.promote.yml, config/sync/core.base_field_override.node.digital_form.title.yml, config/sync/core.entity_form_display.node.digital_form.default.yml, config/sync/core.entity_view_display.node.digital_form.default.yml, config/sync/core.entity_view_display.node.digital_form.external_content.yml, config/sync/core.entity_view_display.node.digital_form.teaser.yml, config/sync/field.field.node.digital_form.field_administration.yml, config/sync/field.field.node.digital_form.field_last_saved_by_an_editor.yml, config/sync/field.field.node.digital_form.field_meta_tags.yml, config/sync/field.field.node.digital_form.field_omb_number.yml, config/sync/field.field.node.digital_form.field_va_form_number.yml, config/sync/field.storage.node.field_omb_number.yml, config/sync/language.content_settings.node.digital_form.yml, config/sync/node.type.digital_form.yml, config/sync/prometheus_exporter.settings.yml, config/sync/workflows.workflow.editorial.yml, docroot/modules/custom/va_gov_content_types/src/Entity/DigitalForm.php, docroot/modules/custom/va_gov_content_types/va_gov_content_types.module, tests/phpunit/va_gov_content_types/functional/Entity/DigitalFormTest.php
Closes [#87711](https://github.com/department-of-veterans-affairs/va.gov-team/issues/87711)
Unit tests added for the Digital Form bundle class and the new fields attached to it.
Digital Form in the list of content types
Digital Form listed as an option in the "Add Content" page
The Create Digital Form page
What needs to be checked to prove this works? 
Digital Form creation, updating, and deletion
Creation, updating, and deletion of other content types
Only administrators should be able to create Digital Forms at this time.
1. Go to Manage > Content > Add content
2. Click "Digital Form"
3. Fill out the required fields and …
=> VATEAM-87711: Add Digital Form content type

config/sync/core.entity_form_display.paragraph.service_location.default.yml, config/sync/field.field.paragraph.service_location.field_additional_hours_info.yml
Relates to #18714 and #17754
Using the [entity relationship diagram](https://pr18878-bnpgayzcdwcden0klaetuacjlvr10not.ci.cms.va.gov/admin/reports/content-model/entity-diagram/paragraph/service_location?max_depth=1), I identified 4 different Drupal entities that currently use the Service Location paragraph type
I tested each of them on Tugboat:
- [VAMC Facility Health Service](https://pr18878-bnpgayzcdwcden0klaetuacjlvr10not.ci.cms.va.gov/node/add/health_care_local_health_service)
- [VAMC Facility Non-clinical Service](https://pr18878-bnpgayzcdwcden0klaetuacjlvr10not.ci.cms.va.gov/node/add/vha_facility_nonclinical_service)
- [Service Region](https://pr18878-bnpgayzcdwcden0klaetuacjlvr10not.ci.cms.va.gov/node/add/service_region)
- [VBA Facility …
=> VACMS-18714: Add character counter to Service Location "additional hours" field

config/sync/core.entity_form_display.node.vet_center.default.yml, config/sync/core.entity_view_display.node.vet_center.default.yml, config/sync/core.entity_view_display.node.vet_center.external_content.yml, config/sync/core.entity_view_display.node.vet_center.ief_table.yml, config/sync/core.entity_view_display.node.vet_center.teaser.yml, config/sync/field.field.node.vet_center.field_mission_explainer.yml, config/sync/field.storage.node.field_mission_explainer.yml
Added a Mission Explainer content block to the Vet center content type.
Relates to #18723
As a drupal admin:
> "Our services
> We offer these confidential services at our Vet Centers:
> 
> Counseling and a range of other services for individuals, families, and group sessions
> Alternative therapies and events may be offered such as art, equine, yoga, or fly fishing
> Connections to more support in VA and your community
> Note: You may be eligible for these services no matter your discharge status or eligibility for VA health care. And we won’t share anything about you or the services you receive at a Vet Center without your permission."
=> VACMS-18723 Exported and added configs to git for Mission Explainer

scripts/content/digital-forms.php
Adds VA Form 21-4140 to the Digital Form seed script created in #19025.
- Closes department-of-veterans-affairs/va.gov-team#90582
Ran the script in my local environment and verified the creation of a Digital Form with the correct info for VA Form 21-4140.
VA Form 21-4140 as generated by the script:
1. Open the command line and navigate to the `va.gov-cms` repo.
2. Start the CMS: `ddev start`
3. Enter the terminal for the web server: `ddev ssh`
4. Run the script: `drush scr scripts/content/digital-forms.php`
5. Go to Manage > Content
6. Click the title
7. Validate the following fields
=> VATEAM-90582: Add 21-4140 Digital Form to seed script

config/sync/core.entity_form_display.node.digital_form.default.yml, config/sync/core.entity_view_display.node.digital_form.default.yml, config/sync/core.entity_view_display.node.digital_form.external_content.yml, config/sync/core.entity_view_display.node.digital_form.teaser.yml, config/sync/field.field.node.digital_form.field_expiration_date.yml, config/sync/field.field.node.digital_form.field_respondent_burden.yml, config/sync/field.storage.node.field_expiration_date.yml, config/sync/field.storage.node.field_respondent_burden.yml, tests/phpunit/va_gov_content_types/functional/Entity/DigitalFormTest.php
Adds all fields necessary to render an accurate [OMB info component](https://design.va.gov/components/omb-info) on each form. Specifically, adds the following two fields:
- Expiration date (`string`, will be converted to expected pattern in `content-build`)
- Respondent Burden (`integer`, in minutes)
These two fields are grouped together with OMB Number to form an "OMB Info" field group.
- Closes department-of-veterans-affairs/va.gov-team#90732
Updated the Digital Form bundle class test with the new fields. Tested the form and view displays locally.
The "OMB info" field group in the form display:
The "OMB info" field group in the node display:
1. Go to Manage > Content > Add content > Digital Form
2. Verify all three of the above fields are required.
3. Enter data in …
=> VATEAM-90732: Add OMB info fields to Digital Form

config/sync/feature_toggle.features.yml
Re: Find Forms form detail pages
Create a feature toggle to use new markup in content-build in support of re-adding the PDF modal back.
Issue: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18855
=> VACMS-18855 Find Forms feature toggle for PDF modal

config/sync/core.entity_form_display.node.press_release.default.yml, config/sync/field.field.node.press_release.field_intro_text.yml, config/sync/node.type.press_release.yml
Relates to #17477
Manual testing of the News Release content type on Tugboat
1. [Login to tugboat](https://pr19126-ggwoomryhlndqjoziwsiksgsu0q8y2wl.ci.cms.va.gov/) as a Content Admin (e.g. david.pickett@va.gov)
1. Go to Content > Add Content > [News release](https://pr19126-ggwoomryhlndqjoziwsiksgsu0q8y2wl.ci.cms.va.gov/node/add/press_release)
=> VACMS-17477: Updated character counter on News Releases

composer.json, composer.lock
Closes #18996 
Drupal admin toolbar updated to 3.5.0 without error
=> VACMS-18996: Update drupal admin toolbar.

docroot/modules/custom/va_gov_user/src/Logger/Processor/VaGovUserCurrentUserProcessor.php, docroot/modules/custom/va_gov_user/va_gov_user.services.yml, docroot/sites/default/services/services.dev.yml, docroot/sites/default/services/services.monolog.yml, docroot/sites/default/services/services.prod.yml, docroot/sites/default/services/services.staging.yml
Closes #19175 
Tested locally
If this passes automated testing it should be good. 
=> VACMS-19175: new monolog current user processor

config/sync/core.entity_form_display.node.event.default.yml, config/sync/core.entity_form_display.node.news_story.default.yml, config/sync/core.entity_view_display.node.event.default.yml, config/sync/field.field.node.news_story.field_featured.yml
Relates to #18819
Manual in Tugboat
As a Content Admin (e.g. david.pickett@va.gov)
1. Log into the [review instance tugboat](https://pr19356-jjl6rcyzhtmwwpge7ydwtqa79rwksslh.ci.cms.va.gov)
2. Go to Content > Add Content > [Story](https://pr19356-jjl6rcyzhtmwwpge7ydwtqa79rwksslh.ci.cms.va.gov/node/add/news_story)
3.  Go to Content > Add Content > [Event](https://pr19356-jjl6rcyzhtmwwpge7ydwtqa79rwksslh.ci.cms.va.gov/node/add/event)
4. View (but don't edit) the following Stories
- [Five VA Bedford Veterans represent at National Veterans Golden Age …
=> VACMS-18819: Adjust Featured UI 

docroot/modules/custom/va_gov_batch/src/cbo_scripts/MigratePhoneFieldToParagraph.php, docroot/modules/custom/va_gov_vamc/src/EventSubscriber/VAMCEntityEventSubscriber.php
Fixes phpstan/reviewdog warnings.
Relates to #17854
Automated
=> VACMS-17854: Fix phpstan warnings.

.github/ISSUE_TEMPLATE/runbook-facility-url-change.md, .github/ISSUE_TEMPLATE/runbook-nca-facility-closed.md, .github/ISSUE_TEMPLATE/runbook-nca-facility-name-change.md, .github/ISSUE_TEMPLATE/runbook-nca-facility-new.md, .github/ISSUE_TEMPLATE/runbook-vamc-facility-closed.md, .github/ISSUE_TEMPLATE/runbook-vamc-facility-duplicate-or-section-change.md, .github/ISSUE_TEMPLATE/runbook-vamc-facility-name-change.md, .github/ISSUE_TEMPLATE/runbook-vamc-facility-new.md, .github/ISSUE_TEMPLATE/runbook-vamc-system-name-change.md, .github/ISSUE_TEMPLATE/runbook-vba-facility-closed.md, .github/ISSUE_TEMPLATE/runbook-vba-facility-name-change.md, .github/ISSUE_TEMPLATE/runbook-vba-facility-new.md, .github/ISSUE_TEMPLATE/runbook-vet-center-cap-to-outstation.md, .github/ISSUE_TEMPLATE/runbook-vet-center-closed.md, .github/ISSUE_TEMPLATE/runbook-vet-center-new.md, .github/ISSUE_TEMPLATE/runbook-vet-center-outstation-to-vet-center.md
Github projects automation relies on having the `sitewide` label on issues that should show up in our board. Adding to all Flagged Facilities runbooks that didn't have it already.
=> Add sitewide label to flagged facilities runbooks

composer.json, composer.lock, patches/3406627-duplicate-blocks-revisions-tabs.patch
Closes #19567 
Tested locally
1. Navigate to `/block/278/revisions`
=> VACMS-19567: remove duplicate block revisions tab

composer.lock, docroot/sites/default/default.settings.php, patches/2942404-contentinfo-landmark.patch, patches/3057267-maintenance-forced-logout-experimental.patch
Relates to #19773 
Local testing and content generation
Look at composer file to core-recommended and core-scaffold is up to 10.3.8
Spot check pages to make sure nothing is broken.
=> VACMS-19773: update drupal core to v1038

config/sync/field.field.node.nca_facility.field_operating_status_more_info.yml, config/sync/field.field.node.vba_facility.field_operating_status_more_info.yml, config/sync/field.field.node.vet_center.field_operating_status_more_info.yml, config/sync/field.field.node.vet_center_cap.field_operating_status_more_info.yml, config/sync/field.field.node.vet_center_outstation.field_operating_status_facility.yml, config/sync/field.field.node.vet_center_outstation.field_operating_status_more_info.yml, config/sync/field.storage.node.field_operating_status_facility.yml
Relates to #19805 
Manually
- Log in as an [admin](https://pr19881-d9qxbj3ygtxam1xgohoosfw3idwml7w9.ci.cms.va.gov/)
- Create a [Vet Center - Outstation](https://pr19881-d9qxbj3ygtxam1xgohoosfw3idwml7w9.ci.cms.va.gov/node/add/vet_center_outstation)
- Normal services and hours
- Limited services and hours
- Facility closed
- Temporary facility closure
- Temporary location
- Virtual care only
- Coming soon
- Facility notice
- Choose "Limited services and hours", "Facility closed", "Temporary facility closure", "Temporary location", "Virtual care only", "Coming soon", and "Facility notice" in succession.
- Edit the [Columbia VA Regional Benefit Office](https://pr19881-d9qxbj3ygtxam1xgohoosfw3idwml7w9.ci.cms.va.gov/node/4063/edit)
- Set the **Operating status** to "Temporary facility closure" …
=> VACMS-19805: Adds new statuses

docroot/modules/custom/va_gov_form_builder/src/Form/Base/FormBuilderNodeBase.php, tests/phpunit/va_gov_form_builder/unit/Form/Base/FormBuilderNodeBaseTest.php
Relates to https://github.com/department-of-veterans-affairs/va.gov-team/issues/95675
- Unit test added
- Manual testing done:
- Attempts to create a new Digital Form via Form Builder that has an OMB number that is too long.
1. Navigate to `/form-builder/start-conversion`.
2. Enter information for a new form:
- Enter an OMB number that is longer than 9 characters.
3. Confirm:
=> VAGOV-TEAM-95675: Updates validation flagging to consider nested paths

.github/ISSUE_TEMPLATE/taxonomy-add-term.yml
=> [DOCS] VACMS-19895 Update Taxonomy runbook based on Chaplain

composer.lock
Closes #20024 
Tested n test.prod.cms.va.gov. Login works as expected.
As long as automated testing passes it should be good. 
=> VACMS-20024: update simplesamlphp and saml2

config/sync/views.view.rich_text_field_audit.yml
Relates to #16461
Manually
- As a content admin, visit the [phone number audit view](https://pr20010-vryqfmpf0nwwsqoxh15swwdbnc5m0bco.ci.cms.va.gov/admin/content/audit/phone-numbers).
- Select "VAMC Facility" from the **Content type** filter.
- Click **Filter**
- Click **Download CSV**
=> VACMS-16461: Fixes phone export and adds new fields

composer.json, composer.lock, patches/3127628-simplesamlphp-auth-fix-redirection-issue.patch
Closes #20021 
Tested login on test.prod.cms.va.gov
=> VACMS-20021: patch simplesamlphp auth to fix login issue that leaves user anonymous

docroot/modules/custom/va_gov_form_builder/templates/page--va-gov-form-builder.html.twig, docroot/modules/custom/va_gov_form_builder/va_gov_form_builder.module, tests/phpunit/va_gov_form_builder/functional/templates/FormBuilderPageTemplateTest.php, tests/phpunit/va_gov_form_builder/unit/ModuleTest.php
- Adds a pagel-level Twig template for Form Builder pages.
- Applies this template to all Form Builder routes (all routes that begin with `va_gov_form_builder.`.
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/97904
- Unit tests added
- Ensure theme hook sets the appropriate `template` and `path` properties.
- Ensure theme-suggestions hook returns the appropriate theme suggestion.
- Ensure template includes expected elements (page wrapper, navbar).
- Ensure template does not include elements that should be removed relative to default theme (breadcrumbs).
- Manual testing done locally to confirm all expected routes have the template applied.
Here is a local screenshot. Other environments might lack the debugging information, but the other two highlighted pieces …
=> VAGOV-TEAM-97904: Adds Form Builder Page Template

docroot/modules/custom/va_gov_form_builder/css/va_gov_form_builder.css, docroot/modules/custom/va_gov_form_builder/src/Form/Base/FormBuilderBase.php, docroot/modules/custom/va_gov_form_builder/va_gov_form_builder.libraries.yml, tests/phpunit/va_gov_form_builder/unit/Form/Base/FormBuilderBaseTest.php
This PR implements the beginning of a Form Builder theme. It does a few things:
1. Defines a Form Builder library.
2. Creates a base Form Builder css file and connects it to the library.
3. Imports external VADS token css from UNPKG.
4. Attaches the two css files from the above two steps to all Form Builder pages.
Note that this PR does not do much to actually implement the design via css. It only sets things up to be able to do that in later work. For now, the only visible change (to prove this works) is to set the `font-family` at the page level. As seen in the below screenshots, the font was previously sans-serif and is now serif.
Relates to https://github.com/department-of-veterans-affairs/va.gov-team/issues/97909
- Unit test added to confirm css files are being attached to the form …
=> VAGOV-TEAM-97909: Form Builder Theme

docroot/themes/custom/vagovclaro/assets/js/anchor_links.js
Closes #19375 
Went to various pages within the CMS and navigated anchor links using the tab key. Verified that, on click, anchor link was defined and did not lose focus.
What needs to be checked to prove this works? Tab though and click anchor links
1. Navigate to the home page in the CMS
2. Click on the VA logo in the upper left corner
3. Tab and click on the "Skip to main content" link
4. Verify that the url is now appended by #main-content
5. Verify that tabbing further brings you into the main content section (VACO, NCA, etc)
=> VACMS-19375: Fix for undefined anchor links.

.github/CODEOWNERS
We added a custom module, but not a codeowner rule. Adding that now.
=> Add rule for owenrship of the Manila custom module

docroot/modules/custom/va_gov_form_builder/css/va_gov_form_builder.css, docroot/modules/custom/va_gov_form_builder/src/Controller/VaGovFormBuilderController.php, docroot/modules/custom/va_gov_form_builder/src/Form/Base/FormBuilderBase.php, docroot/modules/custom/va_gov_form_builder/templates/page--va-gov-form-builder.html.twig, docroot/modules/custom/va_gov_form_builder/va_gov_form_builder.libraries.yml, docroot/modules/custom/va_gov_form_builder/va_gov_form_builder.module, tests/phpunit/va_gov_form_builder/functional/Controller/VaGovFormBuilderControllerTest.php, tests/phpunit/va_gov_form_builder/functional/Form/IntroTest.php, tests/phpunit/va_gov_form_builder/functional/Form/NameAndDobTest.php, tests/phpunit/va_gov_form_builder/functional/Form/StartConversionTest.php, tests/phpunit/va_gov_form_builder/functional/templates/FormBuilderPageTemplateTest.php, tests/phpunit/va_gov_form_builder/unit/Form/Base/FormBuilderBaseTest.php, tests/phpunit/va_gov_form_builder/unit/LibrariesTest.php, tests/phpunit/va_gov_form_builder/unit/ModuleTest.php
This PR adds a navbar (three tabs) to the Form Builder page template. More importantly, it sets things up to be able to pass custom data from each form to the wrapping page template. In this case, we needed that to be able to pass the `activeTab` value to the page template. It might be used for additional values as we go.
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/97920
- Unit tests added.
- Manual tests done:
- Correct active tab on each page.
1. Visit `/form-builder/intro`
2. Proceed to '/form-builder/start-conversion`
3. Fill out form and proceed to next page (name-and-dob)
4. Visit some page outside Form Builder, like `node/add/digital_form`
=> VAGOV-TEAM-97920: Form Builder Navbar

docroot/modules/custom/va_gov_eca/src/Plugin/Action/CreateAdvancedQueueJob.php
The CreateAdvancedQueueJob is a custom ECA Action plugin that we wrote for providing a way to send any email notification via a queue. We followed practices in ECA's own Actions that allow the primary object, in this case a Drupal\advancedqueue\Job object, to be exported as a token and therefore usable by downstream Events, Conditions, or Actions. However, as of today, the job token is not being used anywhere, and thus we weren't seeing any problems with mail delivery.
The errors we were seeing were resulting from Job object not being in an expected format (a Drupal entity, Typed Data object, or scalar value). This PR solves that by creating the token as an associative array.
Relates to #19060
Tested by setting all ECA Models to run on every cron run (otherwise we could only test once a …
=> VACMS-19060: Ensure job token export does not throw an error

docroot/modules/custom/va_gov_form_builder/css/va_gov_form_builder.css, docroot/modules/custom/va_gov_form_builder/templates/page--va-gov-form-builder.html.twig, tests/phpunit/va_gov_form_builder/functional/templates/FormBuilderPageTemplateTest.php
Adds a sidebar with placeholder content to all Form Builder pages.
Relates to https://github.com/department-of-veterans-affairs/va.gov-team/issues/97922
- Unit test updated to ensure presence of sidebar.
- Manual tests to ensure sidebar is present.
1. Navigate to `/form-builder/intro`
2. Navigate to `/form-builder/start-conversion`
=> VAGOV-TEAM-97922: Adds sidebar placeholder

scripts/content/form-builder.php
This PR adds the creation of two test users to the pre-existing content-creation script. Notably, this PR changes the filename of the existing script from `digital-forms.php` to `form-builder.php`.  This was done to more accurately reflect the grouping of  user creation with digital-form creation. While the creation of digital form test nodes can technically be useful outside the context of Form Builder, the creation of test users is something separate. Since both are being used primarily for testing the Form Builder, the name change feels appropriate here, and, notably, better than creating two separate scripts that need to be run independently.
To execute the script, execute this command in the terminal: `drush scr scripts/content/form-builder.php`.
Closes …
=> VAGOV-TEAM-94247: Adds test-user creation to script.

config/sync/field.field.node.checklist.field_contact_information.yml, config/sync/field.field.node.faq_multiple_q_a.field_contact_information.yml, config/sync/field.field.node.media_list_images.field_contact_information.yml, config/sync/field.field.node.media_list_videos.field_contact_information.yml, config/sync/field.field.node.q_a.field_contact_information.yml, config/sync/field.field.node.step_by_step.field_contact_information.yml, config/sync/field.field.node.support_resources_detail_page.field_contact_information.yml, tests/cypress/integration/features/content_type/checklist.feature, tests/cypress/integration/features/content_type/support_resources_detail_page.feature, tests/cypress/integration/step_definitions/common/i_create_a_node.js
Removes the remove button on the contact information paragraph on several content types by making the 'contact information' field required.
Relates to #19616
Tested manually and via cypress
1. Visit the '[add Checklist](https://pr20222-jl1yo5qz9xvmvkqeaakbhf4sq9gt1aje.ci.cms.va.gov/node/add/checklist)' page
2. Visit the '[add FAQ page](https://pr20222-jl1yo5qz9xvmvkqeaakbhf4sq9gt1aje.ci.cms.va.gov/node/add/faq_multiple_q_a)' page
3. Visit the '[add Image List](https://pr20222-jl1yo5qz9xvmvkqeaakbhf4sq9gt1aje.ci.cms.va.gov/node/add/media_list_images)' page
4. Visit the '[add Video List](https://pr20222-jl1yo5qz9xvmvkqeaakbhf4sq9gt1aje.ci.cms.va.gov/node/add/media_list_videos)' page
5. Visit the '[add Reusable Q&A](https://pr20222-jl1yo5qz9xvmvkqeaakbhf4sq9gt1aje.ci.cms.va …
=> VACMS-19616: Contact info block has remove button not working

docroot/modules/custom/va_gov_form_builder/css/va_gov_form_builder.css, docroot/modules/custom/va_gov_form_builder/templates/page--va-gov-form-builder.html.twig, tests/phpunit/va_gov_form_builder/functional/templates/FormBuilderPageTemplateTest.php
This PR removes the sidebar placeholder put in recently, as it has been removed from updated designs.
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/100670
- Functional test updated.
- Manual testing to ensure sidebar is no longer present on Form Builder pages.
As a user with role `Form Builder user`:
1. Navigate to `/form-builder`.
=> VAGOV-TEAM-100670: Removes sidebar placeholder and two-column layout

config/sync/field.field.block_content.connect_with_us.field_external_link.yml
Relates to #19974
Manually
- As a content admin.
- Edit the [Connect with us VBA block](https://pr20301-0lpaofd5vk5kkfkhgdoh1fbkbvfx8fhn.ci.cms.va.gov/admin/content/block/324?destination=/admin/content/block)
=> VACMS-19974: Adds help text to general field

composer.json, composer.lock
This brings the content-build package in composer.json up-to-date.
A ticket is open to restore the automated process: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20308
=> Update Content Build package to 0.0.3666.

docroot/themes/custom/vagovclaro/assets/scss/components/_elements.scss
Relates to #20320 
Manually
- _Note: this is consistent with the fields that are highlighted by Clientside Validation_
=> VACMS-20320: adds CSS for better browser validation UX

config/sync/system.performance.yml
Editors logging in with their PIV cards have found that they are locked out of the CMS with an error relating to browser cookies. It has been determined that the routes requesting the tokens are getting cached when they shouldn't be. As a quick fix we are setting the global page cache time from one day to one hour. We are hoping that this keeps folks from getting locked out of the system waiting for the cache to expire.
Relates to #20339
Testing will need to be done in prod with monitoring of datadog and feedback from editors who were having issues with PIV login.
What needs to be checked to prove this works? 
- Once deployed navigate to `/admin/config/development/performance` and validate that the Browser and proxy cache maximum age is set to 1 hour.
What needs to be checked to prove it …
=> Set page cache from one day to one hour.

docroot/modules/custom/va_gov_build_trigger/README.md
- Relates to #19902
- Adds a readme to describe what the module is, how it works, and why it's important.
=> Add README for VaGovBuildTrigger Module

config/sync/views.view.va_forms.yml
=> VACMS-20358: Updates Forms audit for language

docroot/modules/custom/va_gov_manila/src/EventSubscriber/ManilaEventSubscriber.php
=> VACMS-19406: Excludes the Manila VAMC from getting auotomated path

config/sync/system.performance.yml
Editors logging in with their PIV cards have found that they are locked out of the CMS with an error relating to browser cookies. It has been determined that the routes requesting the tokens are getting cached when they shouldn't be. We previously set the global page cache time from one day to one hour. This helped a lot and didn't create a loss in observable site performance. There are still some editors experiencing this issue, a bunch after the weekend. This PR will completely remove global browser caching, which is not that necessary for an admin site like the CMS. We are hoping that this will eliminate the problem all together without causing a performance issue.
Relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20399
Manual set in prod right now and …
=> turned off browser cache

docroot/modules/custom/va_gov_form_builder/css/va_gov_form_builder.css, docroot/modules/custom/va_gov_form_builder/src/Controller/VaGovFormBuilderController.php, docroot/modules/custom/va_gov_form_builder/templates/components/breadcrumbs.html.twig, docroot/modules/custom/va_gov_form_builder/templates/page-content/page-content--va-gov-form-builder--home.html.twig, docroot/modules/custom/va_gov_form_builder/templates/page/page--va-gov-form-builder.html.twig, docroot/modules/custom/va_gov_form_builder/va_gov_form_builder.routing.yml, tests/phpunit/va_gov_form_builder/Traits/TestPageLoads.php, tests/phpunit/va_gov_form_builder/functional/Form/FormInfoTest.php, tests/phpunit/va_gov_form_builder/functional/content-pages/HomeTest.php, tests/phpunit/va_gov_form_builder/functional/content-pages/LayoutTest.php
- Adds a mechanism to define and render breadcrumbs on Form Builder pages.
- Defines those breadcrumbs for Form Info and Layout pages.
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/101602
- Functional tests updated to add test cases for breadcrumbs.
- Manual tests done on breadcrumb functionality.
As any user that can access Form Builder:
1. Navigate to `/form-builder/home`
2. Navigate to `/form-builder/form-info`
3. The rest of the validations require a Digital Form to exist. If needed, create one. Then locate the existing forms at the bottom of the Form Builder home …
=> VAGOV-TEAM-101602: Breadcrumbs

.github/ISSUE_TEMPLATE/runbook-vamc-facility-new.md
**ISSUE TEMPLATE change only.**
The example URL is confusing and not clearly an example. This can lead to confusion if we actually use that example to ask for canonical URL changes. Updated the example to use placeholder text / variables, to more clearly demonstrate that it's an example.
=> New VAMC Facility runbook: Replace URL example with placeholder content

config/sync/views.view.va_forms.yml
Relates to #20426
Manually.
VACO
NCA
VBA
VHA
OCTO
Test Audit View
Test VA Forms View for regressions
Test Changed Filename View for regressions
Test Changed Title View for regressions
Test New/Deleted Forms for regressions
=> VACMS-20426: Corrects forms audit 'Form Administration' allowed values

docroot/modules/custom/va_gov_form_builder/src/EntityWrapper/DigitalForm.php, docroot/modules/custom/va_gov_form_builder/src/Form/FormInfo.php, docroot/modules/custom/va_gov_form_builder/src/Service/DigitalFormsService.php, tests/phpunit/va_gov_form_builder/unit/EntityWrapper/DigitalFormTest.php, tests/phpunit/va_gov_form_builder/unit/Service/DigitalFormsServiceTest.php
- Implements functionality for adding steps of these types:
1. Your personal information
2. Address information
3. Contact information
- Implements the creation of default steps of each of the three types listed above.
- Creates default steps of the three types listed above upon initial form creation on the Form Info page. 
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/96557
- Unit tests added for the creation of each of the three step types.
- Manual tests creating a new form and confirming the existence of the three default steps.
The three steps are marked as "Complete" immediately upon form creation:
As a Form Builder user:
1. Create a new Digital Form at `/form-builder/form-info`.
1. On the "Layout" page:
1. Note the nid from the url and navigate to …
=> VAGOV-TEAM-96557: Add default steps to digital form

config/sync/core.entity_form_display.node.digital_form.default.yml, config/sync/core.entity_view_display.node.digital_form.default.yml, config/sync/core.entity_view_display.node.digital_form.external_content.yml, config/sync/core.entity_view_display.node.digital_form.teaser.yml, config/sync/field.field.node.digital_form.field_plain_language_title.yml, config/sync/field.storage.node.field_plain_language_title.yml, config/sync/user.role.form_builder_user.yml, tests/phpunit/va_gov_content_types/functional/Entity/DigitalFormTest.php
Closes [VAGOV-TEAM-101555](https://github.com/department-of-veterans-affairs/va.gov-team/issues/101555)
Adds plain-language title field to Digital Forms.
Verified that the new field was present when creating a Digital Form
- Create new `Digital Form` node
- Verify the plain language header field is present
=> VAGOV-TEAM-101555 add plain language title field to digital form content type

config/sync/menu_breadcrumb.settings.yml, config/sync/node.type.event.yml, config/sync/node.type.event_listing.yml, config/sync/node.type.health_care_local_facility.yml, config/sync/node.type.health_care_region_detail_page.yml, config/sync/node.type.health_care_region_page.yml, config/sync/node.type.health_services_listing.yml, config/sync/node.type.leadership_listing.yml, config/sync/node.type.locations_listing.yml, config/sync/node.type.news_story.yml, config/sync/node.type.person_profile.yml, config/sync/node.type.press_release.yml, config/sync/node.type.press_releases_listing.yml, config/sync/node.type.publication_listing.yml, config/sync/node.type.story_listing.yml, config/sync/node.type.vamc_operating_status_and_alerts.yml, config/sync/node.type.vamc_system_billing_insurance.yml, config/sync/node.type.vamc_system_medical_records_offi.yml, config/sync/node.type.vamc_system_policies_page.yml, config/sync/node.type.vamc_system_register_for_care.yml, config/sync/node.type.vamc_system_va_police.yml, config/sync/system.menu.va-manila-health-care.yml
Relates to #20606
Adds "VA Manila health care" menu and adds the menu to the necessary content types.
Manually in tugboat
As a QA Content Publisher
1. Log into the [Tugboat](https://pr20866-gxpfwogb0xkxlpqbbu0ktvnkeljcvw72.ci.cms.va.gov/)
2. Go to Content > Menus > All Menus > [VA Manila health care](https://pr20866-gxpfwogb0xkxlpqbbu0ktvnkeljcvw72.ci.cms.va.gov/admin/structure/menu/manage/va-manila-health-care)
3. Check that `<VA Manila health care>` appears in the Menu settings / Parent link drop down menu for each of these content types
=> VACMS-20606: Adds VA Manila health care menu

composer.json, composer.lock, config/sync/core.extension.yml, config/sync/openid_connect.settings.facebook.yml, config/sync/openid_connect.settings.generic.yml, config/sync/openid_connect.settings.github.yml, config/sync/openid_connect.settings.google.yml, config/sync/openid_connect.settings.linkedin.yml, config/sync/openid_connect.settings.okta.yml, config/sync/openid_connect.settings.yml
This PR adds the module openID connect, that we intend to use for Okta integration. It has been tested in a tugboat environment, but this PR simply adds and enables the module with no config. Config and setup will occur in follow up tickets. 
Closes #20699
This pull request adds support for the OpenID Connect module to the project. The most important changes include adding the OpenID Connect dependency in `composer.json`, updating the module configuration in `core.extension.yml`, and adding default settings for various OpenID Connect providers.
* [`composer.json`](diffhunk://#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R152): Added the `drupal/openid_connect` dependency.
* [`config/sync/core.extension.yml`](diffhunk://#diff-c74373ec0d30209248deac631a2a6db007924814c …
=> added openID connect module

.github/ISSUE_TEMPLATE/runbook-facility-url-change.md, .github/ISSUE_TEMPLATE/runbook-nca-facility-name-change.md, .github/ISSUE_TEMPLATE/runbook-vamc-facility-name-change.md, .github/ISSUE_TEMPLATE/runbook-vamc-system-name-change.md, .github/ISSUE_TEMPLATE/runbook-vba-facility-name-change.md, .github/ISSUE_TEMPLATE/runbook-vet-center-name-change.md
Relates to #20676 
We realized more runbook changes as a result of https://dsva.slack.com/archives/C02730UEZPS/p1740432213877859 LIghthouse removing their CSV as source of truth for Facility URLs. 
Updates include: 
* URL change ticket is no longer a blocker to any Facility name change processes. Drupal changes will drive URL changes in the UI for new visits, and the URL redirect is now only a correction for folks who may have the old URLs bookmarked and encounter a 404. 
* Updated steps for VBA name change to be more comprehensive now that some facilities are published with images, services, etc.
* Added verification steps to several runbooks, to ensure we're verifying our changes before notifying stakeholders.
=> Flagged facility updates: LH CSV and other process updates

composer.json, composer.lock
Updates content-build to 0.0.3710
This pull request includes a minor update to the `composer.json` file. The change updates the version of the `va-gov/content-build` dependency to a newer version.
* [`composer.json`](diffhunk://#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34L233-R233): Updated the `va-gov/content-build` dependency from version `^0.0.3708` to `^0.0.3710`.
=> updated content-build to 0.0.3710

tests/cypress/integration/features/content_type/facilities/manila.feature
Doesn't close #20981 but gets tests passing until launch.
Relates to #20981
Cypress tests pass.
=> VACMS-20981: Skipping the manila cypress tests until Manila revert launches.

composer.json, composer.lock
Update content-build to version 0.0.3714
Closes #20902.
Update content-build to version 0.0.3714 from 0.0.3710
Ran the command `ddev composer show 'va-gov/content-build'` to check the version
1. Do this
2. Then
- [x ] Manual Code Review Approved.
- [ x] `CMS Team`
=> VACMS-20902: Content-build-dependency_20250331

composer.json, composer.lock
Update content-build to version 0.0.3716
Closes #21062.
Update content-build to version 0.0.3714 from 0.0.3716
Ran the command `ddev composer show 'va-gov/content-build'` to check the version
1. Do this
2. Then
=> VACMS-21062: Updates content-build to latest version on packagist

tests/cypress/integration/features/content_type/campaign_landing_page/clp_connect_with_us.feature, tests/cypress/integration/features/content_type/facilities/vamc/health_care_local_health_service.feature
#21069 
This corrects a failing test step in the CLP 'Connect with us' tests.
This pull request includes a small change to the Cypress test file for the Campaign Landing Page feature. The change updates the expected text for one of the dropdown options in the "Connect with us" section.
* [`tests/cypress/integration/features/content_type/campaign_landing_page/clp_connect_with_us.feature`](diffhunk://#diff-8a0a7070716cf9f6b1582e70a9b87fb2f62c4765d3114c471738263f78a0b548L9-R9): Updated the expected text from "VACO" to "Veteran Affairs" for the dropdown option with selector `#edit-field-connect-with-us`.
Cypress tests must pass.
=> Correct test step in CLP tests 

composer.json, composer.lock, config/sync/core.entity_form_display.block_content.news_promo.default.yml, config/sync/core.extension.yml, config/sync/eca.eca.aging_content_expired_news_promo.yml, config/sync/eca.eca.aging_content_warn_news_promo.yml, config/sync/eca.eca.home_page_news_spotlight_block.yml, config/sync/eca.settings.yml, config/sync/entityqueue.entity_queue.home_page_news_spotlight.yml, config/sync/migrate_plus.migration.news_spotlight_blocks.yml, config/sync/views.view.news_spotlight_blocks.yml, docroot/modules/custom/va_gov_eca/src/Plugin/Action/ExecuteMigrationImport.php, docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.news_spotlight_blocks.yml, patches/3515195-add-migration_id-token-to-migrate-events.patch
Relates to #20923
This PR completes end-to-end automation for homepage news spotlights. It adds a new ECA workflow that automates placing News Spotlight blocks into the home page entityqueue/subqueue, which the FE already pulls from to create the news block on the homepage. No further actions are necessary to automate the process.
There are 4 "buckets" of workflows that run independently from each other, but work together to form the complete homepage news promo automation.
1. Drupal cron runs every ~15 minutes triggered by Jenkins
2. ECA Event: ECA cron event. At 12:15AM this event will trigger actions below (running the migrations)
1. ECA Action: Execute migration import of news_spotlight_images
2. ECA Action: Execute migration import of news_spotlight_media
3. ECA Action: Execute …
=> VACMS-20923: Homepage news spotlight block automation

docroot/modules/custom/va_gov_form_builder/src/Controller/VaGovFormBuilderController.php, docroot/modules/custom/va_gov_form_builder/src/EntityWrapper/DigitalForm.php, docroot/modules/custom/va_gov_form_builder/src/Traits/EntityReferenceRevisionsOperations.php, tests/phpunit/va_gov_form_builder/unit/Traits/EntityReferenceRevisionsOperationsTest.php
Relates to: department-of-veterans-affairs/va.gov-team#106493
This pull request introduces several changes to enhance the functionality and validation of digital forms in the `va_gov_form_builder` module. The most significant updates include adding a new trait for entity reference revisions operations, updating the logic for determining step status, and modifying the `DigitalForm` class to incorporate these changes.
* **Step Status Logic Update:**
- Updated the logic for determining the status of custom steps using the `getStepStatus` method in the `DigitalForm` class. This now includes recursive entity validation to check for any violations in the custom step paragraph or its descendant paragraphs. [[1]](diffhunk://#diff-9dffa0f8b39e9a7ba0a5c28ef2b99bd9a06ca95b1f77852efd1896d10e9b920cL450 …
=> VAGOV-TEAM-106493: Custom/additional Step Status

docroot/modules/custom/va_gov_form_builder/templates/page-content/step-layout.html.twig
Relates to #20738
This pull request includes changes to update the operating status of facilities from "Closed" to "Temporary facility closure" and introduces a new script to automate this process. The most important changes include the removal of the "closed" status option, the addition of a new script for updating facility statuses, and the inclusion of a new update hook to execute the script.
Changes to operating status options:
* [`config/sync/field.storage.node.field_operating_status_facility.yml`](diffhunk://#diff-48ea2fa5ddc78c4f206e14c5b305d6233439745d6d6c890da14144ad389fb5f5L20-L22): Removed the "closed" status option from the list of operating statuses.
New script for updating facility statuses:
* [`docroot/modules/custom/va_gov_batch/src/cbo_scripts/MakeClosedFacilitiesTemporari …
=> VACMS-20738: Removes closed from facility operating status.

composer.json, composer.lock
Closes to #21009
This pull request includes an update to the `composer.json` file. The change updates the version of the `va-gov/content-build` package from `^0.0.3716` to `^0.0.3727`.
* [`composer.json`](diffhunk://#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34L233-R233): Updated the `va-gov/content-build` package version from `^0.0.3716` to `^0.0.3727`
Pipeline builds successfully, tests this.
- verify Content-build is on latest
=> Updated content-build to v0.0.3727

composer.json, composer.lock
April 21 ddev composer updates
Relates to #[21175](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21175)
This pull request includes a minor version update to the `va-gov/content-build` dependency in the `composer.json` file. The version has been updated from `0.0.3730` to `0.0.3731`
NA
NA
NA
=> VACMS-21175: 21 April composer updates

docroot/modules/custom/va_gov_form_builder/css/repeatable-field-groups.css, docroot/modules/custom/va_gov_form_builder/src/Controller/VaGovFormBuilderController.php, docroot/modules/custom/va_gov_form_builder/src/Traits/RepeatableFieldGroup.php, docroot/modules/custom/va_gov_form_builder/va_gov_form_builder.libraries.yml
Relates to https://github.com/department-of-veterans-affairs/va.gov-team/issues/106494
Updates the $min parameter to be a startingIndex instead. Updates logic to use this value instead of always starting at 0. This should allow the edit page to define how many objects exist already and then add ajax items from there.
Also updated the form validation to not trigger on the ajax add button, only the actual form submit for the page.
Add this Trait to the `FormInfo.php` for testing:
```php
use Drupal\va_gov_form_builder\Traits\RepeatableFieldGroup;
class FormInfo extends FormBuilderFormBase {
use RepeatableFieldGroup;
```
Added this code block to `FormInfo.php` for testing:
```php
$field_definitions = [
'label' => ['#type' => 'textfield', '#title' => 'Label for radio item', '#required' => …
```
=> VAGOV-TEAM-106494 index iteration

.tugboat/config.yml, config/sync/simple_oauth.oauth2_scope.administrator.yml, config/sync/simple_oauth.oauth2_scope.admnistrator_users.yml, config/sync/simple_oauth.oauth2_scope.content_admin.yml, config/sync/simple_oauth.oauth2_scope.content_creator_benefits_hubs.yml, config/sync/simple_oauth.oauth2_scope.content_creator_vba.yml, config/sync/simple_oauth.oauth2_scope.content_creator_vet_center.yml, config/sync/simple_oauth.oauth2_scope.content_editor.yml, config/sync/simple_oauth.oauth2_scope.content_publisher.yml, config/sync/simple_oauth.oauth2_scope.content_reviewer.yml, config/sync/simple_oauth.oauth2_scope.next_js.yml, config/sync/simple_oauth.oauth2_scope.vamc_content_creator.yml
This PR adds a scope for each role that may need to use next preview. This is due to Drupal module updates for Next and simple_oauth. This combined with a change to the consumer entity on prod after this is merged will restore the preview for pages built with Next.
Also included is an enhancement for tugboat that will allow previews to work in PR tugboats and link the next & Drupal that are built with Tugboat.
Relates to #21229
This pull request introduces updates to the Tugboat configuration and adds several new OAuth2 scopes for improved role-based access control. The most significant changes include modifying the `.env` file for the Tugboat build preview server and defining new OAuth2 scopes for various user roles, which standardize the granularity configuration for Next.js roles.
* …
=> Next preview fix

docroot/modules/custom/va_gov_form_builder/css/form-info.css, docroot/modules/custom/va_gov_form_builder/src/Form/FormInfo.php, docroot/modules/custom/va_gov_form_builder/templates/form/form-info.html.twig, tests/phpunit/va_gov_form_builder/functional/Form/FormInfoTest.php
Relates to https://github.com/department-of-veterans-affairs/va.gov-team/issues/108810
Verified the field was present on the FormInfo step & that it prefilled properly if already saved on a digital form node via normal drupal node operations.
Visit the FormInfo page via the Form Builder UI for any form and note that the field is present (and auto-filled, if checking the employment questionnaire form)
=> VAGOV-TEAM-108810 add plain language title to form builder ui flow

docroot/themes/custom/vagovclaro/assets/scss/components/_process_list.scss
Just makes step style in kb articles higher contrast. 
1. Visit `/node/9421/edit`
2. Add a Process List component in the content. Make sure to add at least 3 steps. The content doesn't matter. Save as published.
3. Check the look of the numbers and the border connecting them. They should be dark blue. See screenshots below.
Before:
After:
=> Make step color in KB articles higher contrast.

docroot/modules/custom/va_gov_facilities/va_gov_facilities.module
There was a bug in the SQL queries to reduce the list of services for a given facility. One query was fetching all of the existing services and another was fetching the relevant services. The second query was relying on a value from the first query which could be empty. Fortunately the value in question (selected facility nid) was already being passed into the function.
Closes to #21301
This pull request includes a small but important change to the `function _va_gov_facilities_get_vamc_system_service_names` in the `va_gov_facilities.module` file. The change updates the query parameter to use the `selected_facility_id` instead of the `existing_facility_services` array, ensuring the correct facility ID is referenced in the query.
Tested locally
=> VACMS-21301: VAMC Facility Health Service bug for facilities with no existing services

READMES/testing.md, tests/cypress/integration/features/api/event.feature, tests/cypress/integration/features/api/event_listing.feature
This PR adds some simple JSON API tests to our cypress tests. Also the readme proposes a plan to expand upon these tests.
Relates to #21169
This pull request introduces documentation and test updates to ensure the functionality of JSON API endpoints for building page types with `next-build`. The key changes include adding a new section in the documentation for testing JSON APIs and creating Cypress tests for event and event listing endpoints.
* Added a new section in `READMES/testing.md` explaining how to test JSON API endpoints, including examples for basic and complex scenarios like event listing pages.
* Added a new Cypress test in `tests/cypress/integration/features/api/event.feature` to verify access to event nodes via the JSON API.
* Added a new Cypress test in …
=> initial tests for JSON API

.github/workflows/build-deploy-docs.yml
This just disables automatic run of the build docs workflow for the time being, since the version on `main` is not ready.
=> Disable workflow-on-push for build docs.

docroot/modules/custom/va_gov_form_builder/css/custom-single-question-response.css, docroot/modules/custom/va_gov_form_builder/templates/form/custom-single-question-checkbox-response.html.twig, docroot/modules/custom/va_gov_form_builder/templates/form/custom-single-question-radio-response.html.twig
Minor changes for radio and checkbox responses:
- Moves the 'required' field up next to the title
- Adds a maximum width to preview images (right sidebar) for consitency
- Remove guidance text
- Adjusts some styling due to removing guidance text
Relates to https://github.com/department-of-veterans-affairs/va.gov-team/issues/106477
Tested radio and checkboxes in both new and edit response pages.
=> VAGOV-TEAM-106482: Radio and checkbox improvements from walkthrough

composer.json, composer.lock
Closes #21274
This pull request updates the version constraint for the `va-gov/content-build` dependency in the `composer.json` file to allow for newer versions.
Dependency update:
* [`composer.json`](diffhunk://#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34L234-R234): Updated `va-gov/content-build` from a fixed version (`0.0.3740`) to a flexible version constraint (`^0.0.3743`), enabling compatibility with newer versions starting from `0.0.3743`.
=> VACMS-21274: update va-gov/content-build

docroot/modules/custom/va_gov_form_builder/va_gov_form_builder.links.menu.yml
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/109371
Verified that a link to Form Builder was under the Content menu.
Interestingly, `weight: 5` put it much higher on the list in my local environment. In tugboat, you can see the added `Form Builder` link above `Menus`
Log in, see `Form Builder` under the Content menu. Verify the link takes you to the Form Builder homepage.
=> VAGOV-TEAM-109371 add menu item for form builder

docroot/sites/default/settings.php, tests/phpunit/Security/AllowInsecureUploadsTest.php
Relates to #21096
This pull request focuses on improving security by disabling insecure file uploads and adding a corresponding test to ensure this configuration remains enforced.
* [`docroot/sites/default/settings.php`](diffhunk://#diff-b80b0a60af550f2090849fc9fd25fb09aa1022a91461c49e16fa1a2f0657ac54R306-R308): Added a configuration setting to disable insecure file uploads by setting `$config['system.file']['allow_insecure_uploads']` to `FALSE`.
* [`tests/phpunit/Security/AllowInsecureUploadsTest.php`](diffhunk://#diff-1dfb8b28a42ad880a3f5dcf6c9037f2783f9e1273cf08638ed3514d9d36d2721R1-R29): Introduced a new PHPUnit test class, `AllowInsecureUploadsTest`, to verify that the `allow_insecure_uploads` configuration is always set to `FALSE`. This ensures the security setting is not …
=> VACMS-21096: Adds a test for insecure_uploads and a runtime setting.

docroot/modules/custom/va_gov_form_builder/src/Entity/Paragraph/FormBuilderParagraphBase.php
Closes https://github.com/department-of-veterans-affairs/va.gov-team/issues/109413
Removes access checks so non-admin Form Builder users can see paragraph-action controls.
- Ensures the paragraph actions appear for both admins and non-admin users.
As a *non-admin* Form Builder user:
1. View form-layout page of a form with multiple steps, or step-layout page of a step with multiple pages:
=> VAGOV-TEAM-109413: Removes access checks on paragraph base class.

docroot/.htaccess
Relates to #21097
This change makes it so that any non-core .php file is returns a 403.
This pull request includes a minor adjustment to the `.htaccess` file to improve the accuracy of a rewrite condition.
* [`docroot/.htaccess`](diffhunk://#diff-97a20696a8f6a925104f5174167c8c6f73dd7606b1f7f263dea1f1d9e23969cbL171-R171): Updated the regular expression in a `RewriteCond` directive to use `^/core/` instead of `/core/` for more precise matching of PHP files in the `/core` directory.
Manual
Add the following lines:
```
<?php
phpinfo();
```
=> VACMS-21097: Adds root-restricted condition to .htaccess

tests/phpunit/Deploy/DeployServiceTest.php, tests/phpunit/Deploy/Plugins/HealthCheckTest.php, tests/phpunit/Logging/DatadogApmProcessorTest.php, tests/phpunit/va_gov_form_builder/functional/Form/IntroductionTest.php, tests/phpunit/va_gov_form_builder/functional/pages/AddressInfoTest.php, tests/phpunit/va_gov_form_builder/functional/pages/ContactInfoTest.php, tests/phpunit/va_gov_form_builder/functional/pages/HomeTest.php, tests/phpunit/va_gov_form_builder/functional/pages/IdentificationInfoTest.php, tests/phpunit/va_gov_form_builder/functional/pages/LayoutTest.php, tests/phpunit/va_gov_form_builder/functional/pages/NameAndDobTest.php, tests/phpunit/va_gov_form_builder/functional/pages/ReviewAndSignTest.php, tests/phpunit/va_gov_form_builder/functional/pages/ViewFormTest.php, tests/phpunit/va_gov_form_builder/unit/Traits/EntityReferenceRevisionsOperationsTest.php, tests/phpunit/va_gov_git/functional/Repository/RepositoryTest.php
This pull request refactors the namespace structure and file organization in the test suite to improve consistency and maintainability. It also includes minor updates to test metadata annotations.
* Updated namespaces across multiple test files to follow a consistent structure, such as changing `namespace test\phpunit\Deploy;` to `namespace Tests\Deploy;` in `DeployServiceTest.php` and similar updates in other files. [[1]](diffhunk://#diff-d0992daca20447a178c0f46fcdcc00127eded92a7b5e4ae67da8816b47c7f43eL3-R3) [[2]](diffhunk://#diff-526149aba1f3cfbe4b04d28069cc1c8089aae019c8fa9710204d794d8845ad6fL3-R3) [[3]](diffhunk://#diff-0be6a775930e05aadc27831faa7eb46f6eff43225e66e722b941d84dd77b0782L3-R3) [[4]](diffhunk://#diff-62fb4422c058366bdd70a93065d7088fe08034 …
=> bring phpunit test up to psr4 standard

composer.json, composer.lock
Closes #21484 
This pull request includes a minor update to the `composer.json` file. The change updates the version constraint for the `va-gov/content-build` package from `^0.0.3767` to `^0.0.3769`.
This should be good as long as automated testing passes. 
=> VACMS-21484: update content-build to v0.0.3769

config/sync/views.view.service_locations_audit.yml
Adds "Virtual support" to the Service locations audit and removes old fields from the CSV export.
Relates to #21474 
This pull request makes significant updates to the `config/sync/views.view.service_locations_audit.yml` file by introducing a new "Virtual Support" field and removing several outdated fields. These changes enhance the audit configuration for service locations by refining the structure and improving clarity.
* Added a new `field_virtual_support` to represent virtual support capabilities, including its configuration and display settings. [[1]](diffhunk://#diff-57df4e5b781227911732e9d5877c39b1a3beba98f3c06ccabad1177bf966197fR615-R676) [[2]](diffhunk://#diff-57df4e5b781227911732e9d5877c39b1a3beba98f3c06ccabad1177bf966197fL2276-R2158)
* Updated tags and dependencies to include …
=> VACMS-21474: Adds virtual support

tests/cypress/integration/features/api/person_profile.feature
Relates to #21323
This pull request introduces a new feature test for the API, specifically targeting the `person_profile` nodes. The test ensures that anonymous users can access these nodes via the JSON API and validates the response status code.
Testing additions:
* [`tests/cypress/integration/features/api/person_profile.feature`](diffhunk://#diff-185d8d88c7ffbd56d28cafa91374a681a25f3d6bb23054e04077b9af1f49ecd6R1-R5): Added a feature test to verify that anonymous users receive a status code of 200 when accessing `person_profile` nodes through the JSON API with specific filters and included fields.
Cypress
=> VACMS-21323: Cypress API test of person_profile (Staff profile)

tests/cypress/integration/features/api/news_story.feature
Adds a simple JSON API test for the news_story endpoint with the relevant includes
Relates to #21021 
This pull request adds new test scenarios to verify the functionality of the JSON API for `news_story` routes and nodes.
* [`tests/cypress/integration/features/api/news_story.feature`](diffhunk://#diff-1fb6d570ad166fede16792c6de0194620db18016a09a1e5a5bde9e7de7b017f5R1-R8): Added a scenario to test that an anonymous user can access `news_story` nodes with specific fields and relationships included, and receive a 200 status code.
Adds a test.
=> VACMS-21021: news_story JSON api test

composer.json, composer.lock
Relates to #[21591](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/21591). (or closes?)
This pull request includes a version update for the `va-gov/content-build` dependency in the `composer.json` file. The version constraint has been changed from `0.0.3774` to `^0.0.3777` to allow for greater flexibility in adopting newer patch versions.
=> VACMS-21591: Update content build version 26 June 

docroot/sites/default/settings.php
#21660 
This is in response to phpunit tests failing on Staging. See for example http://jenkins.vfs.va.gov/job/testing/job/cms-post-deploy-tests-staging/3296/consoleFull:
```
18:13:27    1) tests\phpunit\va_gov_git\functional\Repository\Settings\RepositorySettingsTest::testList
18:13:27    Drupal\va_gov_git\Exception\RepositoryPathNotSetException: Path not set for repository: next-build (va_gov_next_build_root)
18:13:27    
18:13:27    /var/www/cms/docroot/modules/custom/va_gov_git/src/Repository/Settings/RepositorySettings.php:62
18:13:27    /var/www/cms/docroot/modules/custom/va_gov_git/src/Repository/Settings/RepositorySettings.php:74
18:13:27    /var/www/cms/docroot/modules/custom/va_gov_git/src/Repository/Settings/RepositorySettings.php:76
18:13:27 …
```
=> Add default settings for Next Build git form.

docroot/modules/custom/va_gov_migrate/drush.services.yml, docroot/modules/custom/va_gov_migrate/src/Commands/Commands.php, docroot/modules/custom/va_gov_migrate/src/Service/VaGovMigrateService.php
Drush commands are now using service in va_gov_migrate
Relates to #21395
This pull request refactors the `va_gov_migrate` module to streamline service dependencies and improve the handling of migration-related logs. The most important changes include replacing multiple service dependencies with a single custom service and modifying the `cleanRevs` method to return structured data instead of logging messages directly.
* [`docroot/modules/custom/va_gov_migrate/drush.services.yml`](diffhunk://#diff-4cb3441df16425d519a585a554b5f908d33ef9eec87579a4d35e5e57f555ac9aL5-R5): Replaced multiple service dependencies with a single custom service, `@va_gov_migrate.va_gov_migrate_service`, simplifying the configuration of the `va_gov_migrate.commands` class.
* …
=> VACMS-21396: drush cleanup

docroot/modules/custom/va_gov_api/src/Controller/BannerAlertsController.php
Adds node_list cache tags to invalidate the cache for the path anytime a banner, promo_banner, or  full_width_banner_alert is updated, created, or deleted. Alternatively a custom cache tag could have been created for each cached path, and then invalidated once that value is used in the field of a banner. I felt like this simpler option was better since these don't get heavy use.
Closes to #21650.
This pull request makes updates to the `BannerAlertsController` class in the `va_gov_api` module to improve cache tagging for banner-related data and refactors the constructor for better readability.
* Updated cache tags for banner data collection methods to include specific tags for `node_list:banner`, `node_list:promo_banner`, and `node_list:full_width_banner_alert` to enhance cache management …
=> VACMS-21650: Banner API cache

composer.lock
updates simplesaml/saml2 to 4.18.1 from 4.16.14 for security.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-27773
Relates to #21690 
ci tests and manual testing on test.prod
=> VACMS-21690: simplesaml/sml2 security update

docroot/modules/custom/va_gov_backend/js/toolbar.es6.js, docroot/modules/custom/va_gov_backend/js/toolbar.js
Restores the production time information available on hover in Production.
Relates to #20364 
This pull request updates the JavaScript code in the `va_gov_backend` module to enhance functionality for displaying tooltips. The changes primarily involve expanding the scope of tooltips to include an additional element.
* [`docroot/modules/custom/va_gov_backend/js/toolbar.es6.js`](diffhunk://#diff-ca1c375605b7551e2fab6addf866828858b883943a684b6c523dfc33818ede96L11-R13): Modified the `Tippy` initialization to target both `#content-release-status-icon` and `#content-release-status-icon-prod`, allowing tooltips to be displayed for both elements. [[1]](diffhunk://#diff-ca1c375605b7551e2fab6addf866828858b883943a684b6c523dfc33818ede96L11-R13) …
=> VACMS-20364: Updates select for Tippy

docroot/modules/custom/va_gov_build_trigger/src/Plugin/VAGov/Environment/BRD.php
Closes #21733 
This pull request enhances the `BRD` environment plugin in the `va_gov_build_trigger` module to support triggering and monitoring builds for an additional repository (`next-build`) alongside the existing `content-build` repository. The changes include adding a new GitHub client, updating build trigger logic, and improving error handling for both repositories.
* Added a new protected property `nbGitHubClient` to the `BRD` class to interact with the `next-build` repository's GitHub API. Updated the constructor and dependency injection container to initialize this new client. (`[[1]](diffhunk://#diff-5d9813a56dfa01e1b80f602194be157badc68e9859487e5651f81fc95782cb14R40-R46)`, `[[2]](diffhunk://#diff-5d9813a56dfa01e1b80f602194be157badc68e9859487e5651f81fc95782cb14L49-R58)`, …
=> VACMS-21733: trigger content release for next build prod when certain actions are taken in drupal

.github/workflows/build-apache-container.yml
Relates to #21936 
This pull request updates the GitHub Actions workflow for building and publishing the Apache container image. The changes focus on improving the tagging logic for Docker images and optimizing the build process with caching and provenance settings.
**Build Tagging Improvements:**
* Refactored the logic for determining the next Docker tag: now checks if an existing tag is present and starts at `1.0.0` if none exists, otherwise increments the patch version of the latest tag. The new tag is set in the environment variable `NEW_TAG` for use in subsequent steps.
**Docker Build Process Optimization:**
* Updated the Docker build step to:
- Use the new `NEW_TAG` environment variable for tagging the image.
- Disable provenance metadata generation for the build.
- Add …
=> VACMS-21936: update gha for caching a cleaner tagging script

.github/workflows/build-drupal-container.yml, Dockerfile
Relates to #21936 
This pull request introduces a new GitHub Actions workflow for building and pushing the Drupal container to Amazon ECR, and updates the `Dockerfile` to use a specific base image tag. The workflow automates the build and deployment process, integrates with AWS for authentication, and improves image caching and tagging.
**CI/CD Workflow Automation:**
* Added `.github/workflows/build-drupal-container.yml` to automate building and pushing the Drupal Docker image to ECR on pushes to `main` or via manual dispatch. The workflow includes AWS authentication, Docker Buildx setup, image caching, and dynamic base image tagging.
**Dockerfile Update:**
* Changed the default `BASE_IMAGE_TAG` in `Dockerfile` from `latest` to `1.0.0` to ensure consistent and predictable base image usage …
=> VACMS-21936: added gha to build drupal container

.github/workflows/build-apache-container.yml, .github/workflows/build-drupal-container.yml, docker/apache/Dockerfile, scripts/compile-theme.sh, scripts/web-install.sh
Relates to #21936 
This pull request updates the logic for retrieving the most recent semantic version tag from the ECR repository in both the Apache and Drupal container build workflows. The new approach ensures that only tags following semantic versioning (e.g., `1.2.3`) are selected, improving reliability and consistency in tag selection.
**Improvements to ECR image tag selection:**
* Updated the logic in `.github/workflows/build-apache-container.yml` to iterate through image tags from newest to oldest and select the most recent tag that matches semantic versioning, defaulting to `1.0.0` if none are found.
* Applied the same semantic version tag selection logic to `.github/workflows/build-drupal-container.yml`, ensuring consistent behavior across both workflows.
What needs to be …
=> VACMS-21936: add semver check to cms-apache repo tagging for both builds

.github/workflows/build-drupal-container.yml, .github/workflows/update-manifest.yml
Relates to #21936
This pull request introduces a new workflow for updating infrastructure manifests and integrates automated deployment to the development environment after building and pushing the Drupal container. The key changes are the addition of a reusable workflow for manifest updates and the orchestration of deployment steps in the CI pipeline.
**CI/CD Pipeline Enhancements:**
* Added a new job `deploy-to-dev` to `.github/workflows/build-drupal-container.yml` that triggers deployment to the development environment using the new manifest update workflow.
**Infrastructure Manifest Update Workflow:**
* Created `.github/workflows/update-manifest.yml` to automate updating application manifests with new image tags, including permissions, input parameters, and steps for AWS …
=> VACMS-21936: new update manifest workflow

.github/workflows/build-drupal-container.yml
This wasn't picking up the PR when the content-build dependency was getting updated at night. This should fix it. 
This pull request updates the GitHub Actions workflow for building and pushing the Drupal container. The workflow is now triggered only when a pull request is closed and merged, instead of on every push to the main branch. This change helps prevent unnecessary builds and deployments.
**Workflow trigger changes:**
* Changed the workflow trigger from `push` on the `main` branch to `pull_request` events of type `closed`, ensuring the workflow only runs when a pull request is closed.
* Added a conditional check to the `build-and-push` job so it only runs if the pull request was actually merged (`github.event.pull_request.merged == true`).
What needs to be checked to prove this …
=> Fix the GHA trigger for building drupal container

config/sync/feature_toggle.features.yml, docroot/modules/custom/va_gov_login/src/Controller/VaGovLoginController.php, docroot/modules/custom/va_gov_login/va_gov_login.module, docroot/modules/custom/va_gov_login/va_gov_login.routing.yml, docroot/modules/custom/va_gov_login/va_gov_login.services.yml, docroot/sites/default/settings/settings.dev.php, docroot/sites/default/settings/settings.eks.php, docroot/sites/default/settings/settings.prod.php, docroot/sites/default/settings/settings.staging.php
Adds integration with EntraID to the va_gov_login custom module
Closes to #21845 
This pull request introduces Microsoft Entra ID (formerly Azure AD) as an alternative authentication method for PIV login, controlled by a new feature flag. It adds a new controller to handle the Entra ID OAuth flow, updates the login form to optionally use this flow, and configures environment-specific settings for the required Entra ID credentials. The implementation is gated by a feature toggle, ensuring backward compatibility with the existing SAML-based PIV login.
**Microsoft Entra ID integration for PIV login:**
* Added a new feature flag `feature_use_entraid_for_piv_login` to control whether Entra ID is used for PIV login (`config/sync/feature_toggle.features.yml`).
* Implemented …
=> VACMS-21845: entra va gov login

.github/workflows/build-drupal-container.yml, docker/apache/Dockerfile, docker/apache/docker-conf-files/prometheus.yml
Relates to #21854 
This pull request introduces Prometheus monitoring to the Drupal Apache Docker container and improves the CI workflow by preventing parallel builds. The main changes include installing and configuring Prometheus, exposing the necessary port, updating the container startup script, and adding a Prometheus configuration file.
**Prometheus Integration:**
* Added installation steps for Prometheus in the `docker/apache/Dockerfile`, including downloading, extracting, and cleaning up the Prometheus binary. Also, added a step to copy the Prometheus configuration file into the container.
* Added a new Prometheus configuration file `prometheus.yml` with scrape jobs for Prometheus itself, Apache, and PHP-FPM.
* Modified the container startup script to launch Prometheus alongside …
=> VACMS-21854: adding prometheus and queue container building

Dockerfile, docroot/sites/default/settings/settings.eks.php
Relates to #21855 
This pull request makes configuration changes to better support running Drupal behind a reverse proxy, specifically for EKS (Elastic Kubernetes Service) environments. The updates focus on improving proxy trust settings, handling HTTPS detection, and allowing a new frontend domain.
**EKS environment configuration improvements:**
* Added `^eks-dev.cms.va.gov
Relates to #21855 
to the list of trusted frontend domains in `settings.eks.php`, allowing requests from this domain.
* Enabled reverse proxy support by setting `$settings['reverse_proxy'] = TRUE` and specifying `127.0.0.1` as a trusted proxy address.
* Added logic to set the HTTP protocol to HTTPS when the `X-Forwarded-Proto` header is present, ensuring correct detection of secure requests behind a proxy. …
=> VACMS-21855: removing https redirect from application

tests/cypress/integration/features/api/vamc_police.feature, tests/cypress/integration/features/api/vamc_system.feature
Relates to #20443
This pull request adds new feature scenarios to the Cypress integration tests for API functionality. The main focus is on verifying that anonymous users can successfully access route translation and vamc_system nodes via the JSON API.
New API test scenarios:
* Added a scenario to ensure anonymous users receive a 200 status code when accessing route translation for a given `vamc_system` using the `/router/translate-path` endpoint.
* Added a scenario to verify anonymous users can access `vamc_system` nodes and receive a 200 status code via the same endpoint.
Cypress
=> VACMS-20443: Adds API cypress test for VAMC System

tests/cypress/integration/features/api/locations_listing.feature
Relates to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20461
This pull request adds new feature tests for the API endpoints related to `locations_listing`. The tests ensure that anonymous users can successfully access both the route translation and node listing endpoints, verifying correct API behavior.
API endpoint test coverage:
* Added a scenario to verify that an anonymous user receives a 200 status code when requesting route translation for a `locations_listing` path (`/router/translate-path`).
* Added a scenario to verify that an anonymous user receives a 200 status code when requesting a filtered and included list of `locations_listing` nodes via the JSON API (`/jsonapi/node/locations_listing`).
Cypress
=> VACMS-20461: Adds cypress test for locations listing

config/sync/user.role.admnistrator_users.yml, config/sync/user.role.content_admin.yml, config/sync/user.role.content_creator_benefits_hubs.yml, config/sync/user.role.content_creator_resources_and_support.yml, config/sync/user.role.content_creator_vba.yml, config/sync/user.role.content_creator_vet_center.yml, config/sync/user.role.content_editor.yml, config/sync/user.role.content_publisher.yml, config/sync/user.role.content_reviewer.yml, config/sync/user.role.form_builder_user.yml, config/sync/user.role.homepage_manager.yml, config/sync/user.role.office_content_creator.yml, config/sync/user.role.rates_editor.yml, config/sync/user.role.redirect_administrator.yml, config/sync/user.role.translation_manager.yml, config/sync/user.role.vamc_content_creator.yml, docroot/modules/custom/va_gov_workflow/js/modal.js, docroot/modules/custom/va_gov_workflow/js/restore-scroll.js, docroot/modules/custom/va_gov_workflow/src/EventSubscriber/EntityEventSubscriber.php, docroot/modules/custom/va_gov_workflow/src/Service/WorkflowContentControl.php, docroot/modules/custom/va_gov_workflow/va_gov_workflow.info.yml, docroot/modules/custom/va_gov_workflow/va_gov_workflow.install, docroot/modules/custom/va_gov_workflow/va_gov_workflow.libraries.yml, docroot/modules/custom/va_gov_workflow/va_gov_workflow.module, docroot/modules/custom/va_gov_workflow/va_gov_workflow.services.yml, docroot/themes/custom/vagovclaro/assets/scss/components/_elements.scss, tests/phpunit/Security/RolesPermissionsTest.php
Relates to #22068
The key changes involve the following:
- creating a modal screen and dialog that is triggered when a user tries to archive content that is referenced by other content
- allowing all editors to have access to the usage tab
This pull request introduces support for entity usage statistics across multiple user roles and integrates the entity usage service into the workflow event subscriber. The main goal is to allow various content-related roles to access entity usage data and to prepare the backend for future enhancements that may leverage usage statistics in workflows.
**Role Configuration Updates:**
* Added the `entity_usage` module as a dependency to all major content-related user roles, including administrator, content admin, content creator, editor, publisher, …
=> VACMS-22068: Adds modal for entities with usage

config/sync/field.storage.node.field_operating_status_facility.yml, docroot/modules/custom/va_gov_migrate/src/Commands/Commands.php
Relates to #20738. (or closes?)
This pull request makes a small change to the `field_operating_status_facility` field storage configuration by removing the "Facility closed" option from the list of possible values.
- Verified field is removed from content types and view.
1. For each facility content type (NCA Facility, VAMC Facility, VBA Facility, Vet Center, Vet Center - Community Access Point, Vet Center - Outstation)
2. Then
=> VACMS-20738: Remove "closed" operating status from Drupal

.github/pull_request_template.md
Added notice about locked main branch and pull request process.
Relates to #22376  (or closes?)
1. Do this
2. Then
=> Update pull request template with main branch notice

composer.lock
Makes the following patch updates:
| Module name | Version on main | Version in PR |
| ----------- | --------------- | ------------- |
| drupal/ga4_google_analytics        | 1.1.7        | 1.1.10   | 
| drupal/content_model_documentation | 1.0.34       | 1.0.36   | 
| drupal/devel_entity_updates        | 4.2.0        | 4.2.1    | 
| drupal/eca                         | 2.1.11       | 2.1.14   | 
| drupal/eca_cm                      | 1.0.10       | 1.0.11   | 
| drupal/menu_breadcrumb             | 2.0.0        | 2.0.1    | 
| drupal/monolog                     | 3.0.5        | 3.0.7    | 
Relates to #22221 
Automated (for regression)
N/A
=> VACMS-22221: Module updates (patches)
